# New ports collection makefile for:	flying
# Date created:				12 Jul 1996
# Whom:					searle
#
# $FreeBSD: ports/games/flying/Makefile,v 1.5 1999/08/25 06:03:23 obrien Exp $
#

PORTNAME=	flying
PORTVERSION=	6.20
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	games/arcade
EXTRACT_SUFX=	.tgz

MAINTAINER=	searle@longacre.demon.co.uk

USE_IMAKE=	yes
MAN1=		flying.1

.include <bsd.port.mk>
