# New ports collection makefile for:	ytalk
# Date created:		18 March 1995
# Whom:			dom@myrddin.demon.co.uk
#
# $FreeBSD: ports/net/ytalk/Makefile,v 1.10 1999/08/30 14:24:35 peter Exp $
#

PORTNAME=	ytalk
PORTVERSION=	3.1.1
CATEGORIES=	net
# This site is very slow, so we use sunsite instead.
#MASTER_SITES=	http://www.eleves.ens.fr:8080/home/espel/ytalk/
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR= system/network/chat

MAINTAINER=	dom@myrddin.demon.co.uk

MAN1=		ytalk.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
