# New ports collection makefile for:	fortunelock
# Date created:			25 April 2000
# Whom:				Daniel Harris <dannyboy@subdimension.com>
#
# $FreeBSD: ports/sysutils/fortunelock/Makefile,v 1.2 2000/07/19 15:41:21 dannyboy Exp $
#

PORTNAME=	fortunelock
PORTVERSION=	0.1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://cx.capsi.com/src/fortunelock/

MAINTAINER=	dannyboy@FreeBSD.org

USE_BZIP2=	yes

MAN1=		fortunelock.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
