# New ports collection makefile for:    ja-rubytk
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/rubytk/Makefile,v 1.7 2000/04/14 17:10:44 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	yasuf@bsdclub.org

TCL_VERSION?=	80
TK_VERSION?=	80
WITH_TCL_JP=	yes

MASTERDIR=	${.CURDIR}/../../x11-toolkits/rubytk

.include "${MASTERDIR}/Makefile"
