# New ports collection makefile for:    ja-rubytk
# Version required:     (depends on ${MASTERDIR})
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/rubytk/Makefile,v 1.4 1999/11/29 03:59:38 steve Exp $
#

PKGNAME=	ja-rubytk-${VERSION}
CATEGORIES=	japanese x11-toolkits

MAINTAINER=	yasuf@big.or.jp

TCL_VERSION?=	80
TK_VERSION?=	80
WITH_TCL_JP=	yes

MASTERDIR=	${.CURDIR}/../../x11-toolkits/rubytk

.include "${MASTERDIR}/Makefile"
