# New ports collection makefile for:	calife
# Date created:				13 Jun 2000
# Whom:					Thomas Quinot <thomas@cuivre.fr.eu.org>
#
# $FreeBSD: ports/security/calife/Makefile,v 1.1.1.1 2000/06/15 14:05:50 roberto Exp $
#

PORTNAME=	calife
PORTVERSION=	2.8.4b
CATEGORIES=	security
MASTER_SITES=	ftp://postfix.eu.org/pub/calife/

MAINTAINER=	thomas@cuivre.fr.eu.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	"--with-etcdir=$(PREFIX)/etc"

MAN1=		calife.1
MAN5=		calife.auth.5

.include <bsd.port.mk>
