# New ports collection makefile for:	avltree
# Date created:				13 January 2000
# Whom:					Bill Ross <bross@nas.nasa.gov>
#
# $FreeBSD: ports/devel/avltree/Makefile,v 1.1 2000/01/29 05:00:11 steve Exp $

PORTNAME=	avltree
PORTVERSION=	1.1
CATEGORIES=	devel
MASTER_SITES=	ftp://odin.compchem.ucsf.edu/pub/amber/

MAINTAINER=	bross@nas.nasa.gov

MAN3=		avltree.3
MANCOMPRESSED=	yes

.include <bsd.port.mk>
