# New ports collection makefile for:	avltree
# Date created:				13 January 2000
# Whom:					Bill Ross <bross@nas.nasa.gov>
#
# $FreeBSD: ports/devel/avltree/Makefile,v 1.2 2000/04/11 21:27:09 mharo Exp $

PORTNAME=	avltree
PORTVERSION=	1.1
CATEGORIES=	devel
MASTER_SITES=	ftp://odin.compchem.ucsf.edu/pub/amber/

MAINTAINER=	ports@FreeBSD.org

MAN3=		avltree.3
MANCOMPRESSED=	yes

.include <bsd.port.mk>
