# New ports collection makefile for:	Blackened IRC client
# Date created:		11 Jun 1999
# Whom:			Will Andrews <andrews@technologist.com>
#
# $FreeBSD: ports/irc/blackened/Makefile,v 1.10 2000/04/12 06:28:07 obrien Exp $
#

PORTNAME=	blackened
PORTVERSION=	1.7.1
CATEGORIES=	irc
MASTER_SITES=	ftp://ftp.blackened.com/pub/irc/blackened/

MAINTAINER=	toast@blackened.com

GNU_CONFIGURE=	yes
PLIST_SUB=	VERSION=${PORTVERSION}
MAKE_ENV=	prefix=${PREFIX}

.include <bsd.port.mk>
