# New ports collection makefile for:	Blackened IRC client
# Version required:	1.7.1
# Date created:		11 Jun 1999
# Whom:			Will Andrews <andrews@technologist.com>
#
# $FreeBSD: ports/irc/blackened/Makefile,v 1.8 2000/03/22 01:59:16 will Exp $
#

DISTNAME=	blackened-${VERSION}
CATEGORIES=	irc
MASTER_SITES=	ftp://ftp.blackened.com/pub/irc/blackened/

MAINTAINER=	toast@blackened.com

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${PKGNAME}
VERSION=	1.7.1
PLIST_SUB=	VERSION=${VERSION}
MAKE_ENV=	prefix=${PREFIX}

.include <bsd.port.mk>
