# New ports collection makefile for:	server of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/FreeWnn-server/Makefile,v 1.33 2000/09/12 17:08:29 taoka Exp $
#

PKGNAMESUFFIX=	-server

MASTERDIR=	${.CURDIR}/../FreeWnn-lib
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
