# New ports collection makefile for:	server of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/FreeWnn-server/Makefile,v 1.32 2000/08/11 02:56:25 asami Exp $
#

PKGNAMESUFFIX=	-server

MASTERDIR=	${.CURDIR}/../FreeWnn-lib
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
