# New ports collection makefile for:   XBalloon
# Date created:        3 March 1999
# Whom:                Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/x11/xballoon/Makefile,v 1.4 2000/08/03 09:28:47 asami Exp $
#

PORTNAME=	xballoon
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	http://wwwmiya.ee.kagu.sut.ac.jp/~sakai/

MAINTAINER=	sakai@miya.ee.kagu.sut.ac.jp

ALL_TARGET=	xballoon

USE_X_PREFIX=	yes
USE_XPM=	yes

MAN1=		xballoon.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
