# New ports collection makefile for:	exmh (Japanese)
# Version required:	2.0.2
# Date created:		15 Mar 1999
# Whom:		Takeshi WATANABE <watanabe@komadori.planet.sci.kobe-u.ac.jp>
#
# $FreeBSD: ports/japanese/exmh2/Makefile,v 1.3 1999/08/25 05:24:03 obrien Exp $
#

PKGNAME=	ja-${DISTNAME}
CATEGORIES=	japanese mail tk80

MAINTAINER=	ports@FreeBSD.org

JAPANESE_EXMH=	yes

MASTERDIR=	${.CURDIR}/../../mail/exmh2
COMMENT=	${.CURDIR}/pkg/COMMENT
DESCR=		${.CURDIR}/pkg/DESCR
WRKDIR=		${WRKDIRPREFIX}${.CURDIR}/work

.include	"${MASTERDIR}/Makefile"
