# New ports collection makefile for:	exmh (Japanese)
# Date created:		15 Mar 1999
# Whom:		Takeshi WATANABE <watanabe@komadori.planet.sci.kobe-u.ac.jp>
#
# $FreeBSD: ports/japanese/exmh2/Makefile,v 1.5 2000/04/11 14:13:38 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	ports@FreeBSD.org

JAPANESE_EXMH=	yes

MASTERDIR=	${.CURDIR}/../../mail/exmh2
COMMENT=	${.CURDIR}/pkg/COMMENT
DESCR=		${.CURDIR}/pkg/DESCR
WRKDIR=		${WRKDIRPREFIX}${.CURDIR}/work

.include	"${MASTERDIR}/Makefile"
