# New ports collection makefile for:	Action Server
# Date created:				Wed Apr 25 11:45:11 SAST 2001
# Whom:					markm@freebsd.org et al
#
# $FreeBSD: ports/games/hlserver-action/Makefile,v 1.3 2001/05/01 20:10:31 lioux Exp $
#

PORTNAME=	action
PORTVERSION=	0.4
MASTER_SITES=	ftp://ftp2.3ddownloads.com/90380/telefragged/ahl/ \
		ftp://ftp.3ddownloads.com/90380/telefragged/ahl/ \
		ftp://ftp.barrysworld.com/pub/games/halflife/mods/actionhl/official_patches/linux/ \
		ftp://ftp.wireplay.net/pub/downloads/fps/halflife/mods/action/linux/ \
		http://ftp1download.gamespy.com/fileplanet/fpnew/action/half-life/modifications/ahl/ \
		http://fileplanet.games-world.net/dl/ftp1.gamespy.com/fpnew/action/half-life/modifications/ahl/ \
		ftp://ftp.blackmesa.de/mods/ahl/
DISTNAME=	action
EXTRACT_SUFX=	.tgz

HALFLIFE_COUNTERSTRIKE_MASTER=	${.CURDIR}/../hlserver-cs

.include "${HALFLIFE_COUNTERSTRIKE_MASTER}/Makefile"
