# New ports collection makefile for: Mew (for xemacs)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs/Makefile,v 1.10 2000/05/08 13:13:16 shige Exp $
#

MAINTAINER=	kiri@FreeBSD.org

# This is a slave port.
MASTERDIR=	${.CURDIR}/../mew

# set emacs port
EMACS_PORT_NAME=xemacs

# use pkg-* files in ${.CURDIR}
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
