# New ports collection makefile for: Mew (for xemacs)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs/Makefile,v 1.7 2000/01/04 14:29:26 shige Exp $
#

EMACS_PORT_NAME=	xemacs

.include "${.CURDIR}/../mew/Makefile"
