# New ports collection makefile for: Mew (for xemacs)
# Version required:	1.93
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs/Makefile,v 1.5 1999/08/25 06:50:25 obrien Exp $
#

EMACS_PORT_NAME=	xemacs

MASTERDIR=		${.CURDIR}/../../mail/mew

.include "${MASTERDIR}/Makefile"
