# New ports collection makefile for:	MPEG-ID3v2Tag
# Date created:				Wed Jan  3 08:38:34 2001
# Whom:					will
#
# $FreeBSD: ports/audio/p5-MPEG-ID3v2Tag/Makefile,v 1.1 2001/01/03 23:32:22 will Exp $
#

PORTNAME=	MPEG-ID3v2Tag
PORTVERSION=	0.20
CATEGORIES=	audio perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	MPEG
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		MPEG::ID3v2Tag.3

.include <bsd.port.mk>
