# New ports collection makefile for:	pcre
# Date created:				08 July 1998
# Whom:					dom
#
# $FreeBSD: ports/devel/pcre/Makefile,v 1.5 2000/03/24 01:57:49 mharo Exp $
#

PORTNAME=	pcre
PORTVERSION=	3.1
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cus.cam.ac.uk/pub/software/programs/pcre/

MAINTAINER=	dom@myrddin.demon.co.uk

# Implies GNU_CONFIGURE.
USE_LIBTOOL=	yes

MAN3=		pcre.3 pcreposix.3
MAN1=		pgrep.1

.include <bsd.port.mk>
