# New ports collection makefile for:	pcre
# Date created:				08 July 1998
# Whom:					dom
#
# $FreeBSD: ports/devel/pcre/Makefile,v 1.7 2000/10/25 23:54:27 jeh Exp $
#

PORTNAME=	pcre
PORTVERSION=	3.4
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.cus.cam.ac.uk/pub/software/programs/pcre/

MAINTAINER=	dom@myrddin.demon.co.uk

USE_BZIP2=	yes
USE_LIBTOOL=	yes

MAN3=		pcre.3 pcreposix.3
MAN1=		pcregrep.1

.include <bsd.port.mk>
