# New ports collection makefile for:	pcre
# Version required:			3.1
# Date created:				08 July 1998
# Whom:					dom
#
# $FreeBSD: ports/devel/pcre/Makefile,v 1.4 1999/09/28 02:40:41 steve Exp $
#

DISTNAME=       pcre-3.1
CATEGORIES=     devel
MASTER_SITES=   ftp://ftp.cus.cam.ac.uk/pub/software/programs/pcre/

MAINTAINER=     dom@myrddin.demon.co.uk

# Implies GNU_CONFIGURE.
USE_LIBTOOL=	yes

MAN3=		pcre.3 pcreposix.3
MAN1=		pgrep.1

.include <bsd.port.mk>
