# New ports collection makefile for:	jvim3 for Canna
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna/Makefile,v 1.9 2000/04/11 14:14:11 knu Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
