# New ports collection makefile for:	jvim3 for Canna
# Version required:	3.0-1.7j
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna/Makefile,v 1.6 1999/08/25 05:24:40 obrien Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
