# New ports collection makefile for:	jvim3 for Canna
# Version required:	3.0-2.0j
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna/Makefile,v 1.7 1999/09/27 15:17:39 taoka Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
