# New ports collection makefile for:	asedit
# Date created:				28 Jul 1996
#
# Whom:	Andreas Kohout <shanee@augusta.de>
#
# $FreeBSD: ports/editors/asedit/Makefile,v 1.7 1999/08/25 05:43:25 obrien Exp $
#

PORTNAME=	asedit
PORTVERSION=	1.3.2
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	editors
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	shanee@augusta.de

REQUIRES_MOTIF=	yes
USE_IMAKE=	yes
XMKMF=		xmkmf

.include <bsd.port.mk>
