# New ports collection makefile for:	asedit
# Date created:				28 Jul 1996
#
# Whom:	Andreas Kohout <shanee@augusta.de>
#
# $FreeBSD: ports/editors/asedit/Makefile,v 1.9 2000/11/07 23:28:01 asami Exp $
#

PORTNAME=	asedit
PORTVERSION=	1.3.2
PORTREVISION=	1
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	editors
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	shanee@augusta.de

USE_MOTIF=	yes
USE_IMAKE=	yes
XMKMF=		xmkmf

MAN1=		asedit.1

.include <bsd.port.mk>
