#
# $FreeBSD: ports/palm/pilot_makedoc/files/Makefile,v 1.2 1999/08/30 14:33:02 peter Exp $
#

CXX?=	g++
CFLAGS?=-O2

pilot_makedoc:	makedoc7.cpp
		${CXX} ${CFLAGS} -o pilot_makedoc makedoc7.cpp

#
# EOF
