#
# $FreeBSD: ports/palm/pilot_makedoc/files/Makefile,v 1.3 2000/01/28 06:49:33 kris Exp $
#

CXX?=	g++
CXXFLAGS?=-O2

pilot_makedoc:	makedoc7.cpp
		${CXX} ${CXXFLAGS} -o pilot_makedoc makedoc7.cpp

#
# EOF
