# New ports collection makefile for:   ja-w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/w3m-ssl/Makefile,v 1.3 2000/02/06 22:24:34 kris Exp $
#

PKGNAMESUFFIX=	-ssl
CATEGORIES=	japanese www ipv6

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST.ja

JAPANESE=	Yes
USE_OPENSSL=	RSA

.include "${MASTERDIR}/Makefile"
