# New ports collection makefile for:   ja-w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/w3m-ssl/Makefile,v 1.7 2000/10/08 06:43:36 asami Exp $
#

PKGNAMESUFFIX=	-ssl
CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist.ja

JAPANESE=	Yes
USE_OPENSSL=	YES

.include "${MASTERDIR}/Makefile"
