# $FreeBSD: ports/x11-fonts/Makefile,v 1.11 2000/07/19 08:28:06 shige Exp $
#

    SUBDIR += XFree86-4-font100dpi
    SUBDIR += XFree86-4-font75dpi
    SUBDIR += XFree86-4-fontCyrillic
    SUBDIR += XFree86-4-fontDefaultBitmaps
    SUBDIR += XFree86-4-fontEncodings
    SUBDIR += XFree86-4-fontLatin2
    SUBDIR += XFree86-4-fontScalable
    SUBDIR += Xg
    SUBDIR += bitmap-fonts
    SUBDIR += etlfonts
    SUBDIR += freefonts
    SUBDIR += getbdf
    SUBDIR += intlfonts
    SUBDIR += mozilla-fonts
    SUBDIR += nexfontsel
    SUBDIR += nucleus
    SUBDIR += p5-type1inst
    SUBDIR += sharefonts
    SUBDIR += tkfont
    SUBDIR += ttmkfdir
    SUBDIR += xfed
    SUBDIR += xmbdfed

.include <bsd.port.subdir.mk>
