# $FreeBSD: ports/x11-fonts/Makefile,v 1.20 2001/05/11 15:58:01 vanilla Exp $
#

    SUBDIR += XFree86-4-font100dpi
    SUBDIR += XFree86-4-font75dpi
    SUBDIR += XFree86-4-fontCyrillic
    SUBDIR += XFree86-4-fontDefaultBitmaps
    SUBDIR += XFree86-4-fontEncodings
    SUBDIR += XFree86-4-fontScalable
    SUBDIR += Xg
    SUBDIR += bdfresize
    SUBDIR += bitmap-fonts
    SUBDIR += etlfonts
    SUBDIR += freefonts
    SUBDIR += geminifonts
    SUBDIR += getbdf
    SUBDIR += intlfonts
    SUBDIR += jmk-x11-fonts
    SUBDIR += mozilla-fonts
    SUBDIR += nexfontsel
    SUBDIR += nucleus
    SUBDIR += p5-Font-AFM
    SUBDIR += p5-type1inst
    SUBDIR += sharefonts
    SUBDIR += tkfont
    SUBDIR += ttmkfdir
    SUBDIR += urwfonts
    SUBDIR += webfonts
    SUBDIR += xfed
    SUBDIR += xmbdfed

.include <bsd.port.subdir.mk>
