# $FreeBSD: ports/x11-fonts/Makefile,v 1.6 1999/08/31 02:58:26 peter Exp $
#

    SUBDIR += Xg
    SUBDIR += bitmap-font
    SUBDIR += etlfonts
    SUBDIR += freefonts
    SUBDIR += getbdf
    SUBDIR += nexfontsel
    SUBDIR += p5-type1inst
    SUBDIR += sharefonts
    SUBDIR += tkfont
    SUBDIR += ttmkfdir
    SUBDIR += xfed
    SUBDIR += xmbdfed

.include <bsd.port.subdir.mk>
