# New ports collection makefile for:	p5-Net-XWhois
# Date created:				11 June 2001
# Whom:	      				Danny Howard <dannyman@tellme.com>
#
# $FreeBSD: ports/net/p5-Net-XWhois/Makefile,v 1.1 2001/07/06 17:36:08 ijliao Exp $
#

PORTNAME=	Net-XWhois
PORTVERSION=    0.82
CATEGORIES=	net perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Net
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@leeym.com

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Net::XWhois.3

.include <bsd.port.mk>
