# New ports collection makefile for:    bpatch
# Date created:         18 March 1996
# Whom:                 joerg
#
# $FreeBSD: ports/editors/bpatch/Makefile,v 1.7 1999/08/25 05:43:30 obrien Exp $
#

PORTNAME=	bpatch
PORTVERSION=	1.0
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org

MAN1=		bpatch.1
NO_WRKSUBDIR=   yes

.include <bsd.port.mk>
