# New ports collection makefile for:	ONEW for Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-wnn6/Makefile,v 1.6 2000/04/12 14:36:31 knu Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
