# New ports collection makefile for:	ONEW for Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-wnn6/Makefile,v 1.5 1999/08/25 05:26:07 obrien Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../onew-wnn4
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
