# New ports collection makefile for: Mew (for xemacs21-mule)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs21-mule/Makefile,v 1.8 2000/01/07 16:22:45 shige Exp $
#

EMACS_PORT_NAME=	xemacs21-mule

.include "${.CURDIR}/../mew/Makefile"
