# New ports collection makefile for: Mew (for xemacs21-mule)
# Version required:	1.94.1
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs21-mule/Makefile,v 1.5 2000/01/04 14:29:28 shige Exp $
#

EMACS_PORT_NAME=	xemacs21-mule

.include "${.CURDIR}/../mew/Makefile"
