# New ports collection makefile for:	jove
# Date created:		21 August 1994
# Whom:			jkh
#
# $FreeBSD: ports/editors/jove/Makefile,v 1.18 2000/04/14 00:25:35 mharo Exp $
#

PORTNAME=	jove
PORTVERSION=	4.16
CATEGORIES=	editors
MASTER_SITES=	ftp://relay.cs.toronto.edu/pub/moraes/jove/

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/jove
MAN1=		jove.1 teachjove.1 xjove.1 jovetool.1

.include <bsd.port.mk>
