#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-1.1/files/openoffice-wrapper,v 1.13 2004/07/31 03:29:15 maho Exp $

oopath=%%PREFIX%%/OpenOffice.org%%RELEASE_NR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
