# New ports collection Makefile for:	vrrpd
# Date created:		18 Feb 2001
# Whom:			Andy K <minosh@engineer.com>
#
# $FreeBSD: ports/net/vrrp/Makefile,v 1.1 2001/03/28 18:23:50 keichii Exp $
#

PORTNAME=	vrrpd
PORTVERSION=	0.1
CATEGORIES=	net

BROKEN=	"Do not build until MAINTAINER fixes licensing issues"

MASTER_SITES=	ftp://ftp.vrrp.net/pub/vrrpd/ \
		ftp://ftp.tecc.co.uk/pub/vrrpd/

MAINTAINER=	minosh@engineer.com

.include <bsd.port.mk>
