# New ports collection makefile for:    xmille
# Date created:         30 Dec 1994
# Whom:                 swallace
#
# $FreeBSD: ports/games/xmille/Makefile,v 1.13 2001/01/16 17:30:42 sobomax Exp $
#

PORTNAME=	xmille
PORTVERSION=	2.0
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}  \
		ftp://gatekeeper.dec.com/pub/X11-contrib/
MASTER_SITE_SUBDIR=	games
DISTFILES=	xmille.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
NO_WRKSUBDIR=	yes
MAN1=		xmille.1

.include <bsd.port.mk>
