# New ports collection makefile for:	Muggy for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/muggy/Makefile,v 1.3 2000/04/11 14:15:13 knu Exp $
#

LANGUAGE=	Japanese

CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../editors/muggy

.include	"${MASTERDIR}/Makefile"
