# New ports collection makefile for:	Muggy for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/muggy/Makefile,v 1.2 1999/08/25 05:25:33 obrien Exp $
#

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../editors/muggy

.include	"${MASTERDIR}/Makefile"
