# $FreeBSD: ports/shells/Makefile,v 1.26 2000/04/15 04:27:23 obrien Exp $
#

    SUBDIR += 44bsd-csh
    SUBDIR += bash1
    SUBDIR += bash2
    SUBDIR += es
    SUBDIR += esh
    SUBDIR += flash
    SUBDIR += ksh93
    SUBDIR += osh
    SUBDIR += pdksh
    SUBDIR += perlsh
    SUBDIR += rc
    SUBDIR += sash
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += zsh
    SUBDIR += zsh-devel

.include <bsd.port.subdir.mk>
