# $FreeBSD: ports/shells/Makefile,v 1.24 2000/01/08 18:31:01 wes Exp $
#

    SUBDIR += bash1
    SUBDIR += bash2
    SUBDIR += es
    SUBDIR += esh
    SUBDIR += flash
    SUBDIR += ksh93
    SUBDIR += pdksh
    SUBDIR += perlsh
    SUBDIR += rc
    SUBDIR += sash
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += zsh
    SUBDIR += zsh-devel

.include <bsd.port.subdir.mk>
