# $FreeBSD: ports/shells/Makefile,v 1.30 2001/03/01 15:57:05 clive Exp $
#

    SUBDIR += 44bsd-csh
    SUBDIR += bash1
    SUBDIR += bash2
    SUBDIR += es
    SUBDIR += esh
    SUBDIR += flash
    SUBDIR += ksh93
    SUBDIR += mudsh
    SUBDIR += osh
    SUBDIR += pash
    SUBDIR += pdksh
    SUBDIR += perlsh
    SUBDIR += rc
    SUBDIR += sash
    SUBDIR += scsh
    SUBDIR += tcsh
    SUBDIR += vshnu
    SUBDIR += wapsh
    SUBDIR += zsh
    SUBDIR += zsh-devel

.include <bsd.port.subdir.mk>
