#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.3 2003/03/05 23:24:05 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org-%%BUILD_NR%%/program/
program=`echo $0 | sed -e 's|.*-||'`

if [ ! $LANG ]; then
	export LANG=%%LANG%%
fi

if [ ! -e $HOME/OpenOffice.org1.1Beta/user/config/soffice.cfg ]; then
	touch $HOME/OpenOffice.org1.1Beta/user/config/soffice.cfg
fi

case $program in
$0)
	cd $oopath && ./soffice "$@"
	;;
	*)
	cd $oopath && exec $program "$@"
	;;
esac
