# New ports collection makefile for:	Mac-FileSpec-Unixish
# Date created:				Wed Jan  3 08:54:29 2001
# Whom:					will
#
# $FreeBSD: ports/devel/p5-Mac-FileSpec-Unixish/Makefile,v 1.1 2001/01/03 23:33:00 will Exp $
#

PORTNAME=	Mac-FileSpec-Unixish
PORTVERSION=	1.11
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Mac
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Mac::FileSpec::Unixish.3

.include <bsd.port.mk>
