# New ports collection makefile for:	fox-xunicode
# Date created:		24 February 2001
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/x11-toolkits/fox-xunicode/Makefile,v 1.1 2001/02/23 18:54:55 knu Exp $
#

MASTERDIR=	${.CURDIR}/../fox

MAINTAINER=	knu@FreeBSD.org

COMMENT=	${.CURDIR}/pkg-comment

BROKEN=		yes

WITH_XUNICODE=	yes

.include "${MASTERDIR}/Makefile"
