# New ports collection makefile for:	fox-xunicode
# Date created:		24 February 2001
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/x11-toolkits/fox-xunicode/Makefile,v 1.3 2001/02/24 20:23:18 knu Exp $
#

MASTERDIR=	${.CURDIR}/../fox

PORTVERSION=	0.99.167

MAINTAINER=	knu@FreeBSD.org

COMMENT=	${.CURDIR}/pkg-comment

WITH_XUNICODE=	yes

.include "${MASTERDIR}/Makefile"
