# New ports collection makefile for:	ja-tcsh NLS catalog (Rishu)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-rishu/Makefile,v 1.6 2000/04/12 14:37:59 knu Exp $
#

CATALOGNAME=	rishu

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

.include	"${MASTERDIR}/Makefile"
