# New ports collection makefile for:	ja-tcsh NLS catalog (Rishu)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-rishu/Makefile,v 1.5 1999/08/31 06:46:29 mharo Exp $
#

CATALOGNAME=	rishu

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
