# $FreeBSD: ports/emulators/vmware2/files/Makefile.vmmon,v 1.1 2000/03/29 21:23:05 knu Exp $

MAKE_SMP=	make -f Makefile.FreeBSD SMP=YES
MAKE_UP=	make -f Makefile.FreeBSD SMP=NO

all:	
	${MAKE_SMP} clean && ${MAKE_SMP}
	${MAKE_UP} clean && ${MAKE_UP}

install:	
	${MAKE_SMP} install
	${MAKE_UP} install
