# $FreeBSD: ports/emulators/vmware3/files/Makefile.vmmon,v 1.2 2001/02/25 10:16:25 knu Exp $

MAKE_SMP=	make -f Makefile.freebsd SMP=YES
MAKE_UP=	make -f Makefile.freebsd SMP=NO

all:	
	${MAKE_SMP} clean && ${MAKE_SMP}
	${MAKE_UP} clean && ${MAKE_UP}

install:	
	${MAKE_SMP} install
	${MAKE_UP} install
