#!/bin/sh
# $FreeBSD: ports/archivers/rpm5/pkg-install,v 1.3 2008/07/07 13:19:15 edwin Exp $

# The RPM database directory
RPM_DATABASE_DIR=/var/local/lib/rpm

# Provide instructions for initialising the RPM database.
if [ "$2" = "POST-INSTALL" ]; then
	if [ -d "${RPM_DATABASE_DIR}" ]; then
		echo ""
		echo "Old RPM database found. If you are upgrading RPM from a"
		echo "different version of Berkeley DB, you might need to rebuild"
		echo "with the command:"
		echo ""
		echo "	${PKG_PREFIX}/bin/rpm --rebuilddb"
		echo ""
	fi
fi
