# New ports collection makefile for:	p5-Class-Date
# Date Created:				28 June 2001
# Whom:					Pete Fritchman <petef@databits.net>
#
# $FreeBSD: ports/devel/p5-Class-Date/Makefile,v 1.2 2001/07/14 16:49:45 kevlo Exp $
#

PORTNAME=	Class-Date
PORTVERSION=	1.0.5
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Class
PKGNAMEPREFIX=	p5-

MAINTAINER=	petef@databits.net

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=	Class::Date.3

.include <bsd.port.mk>
