# New ports collection makefile for:	uwatch
# Date created:		3 November 1999
# Whom:			James Howard <howardjp@wam.umd.edu>
#
# $FreeBSD: ports/sysutils/uwatch/Makefile,v 1.2 2000/04/09 19:08:43 cpiazza Exp $
#

PORTNAME=	uwatch
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.wam.umd.edu/pub/howardjp/software/uwatch/ \
		http://www.wam.umd.edu/~howardjp/software/uwatch/ \
		ftp://dragon.ham.muohio.edu/pub/howardjp/software/uwatch/

MAINTAINER=	howardjp@wam.umd.edu

MAN1=		uwatch.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
