# New ports collection makefile for:	xwipower
# Date created:         05 July 2000
# Whom:			sumikawa
#
# $FreeBSD: ports/sysutils/xwipower/Makefile,v 1.2 2000/12/31 21:17:44 sumikawa Exp $
#

PORTNAME=	xwipower
PORTVERSION=	20000623
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://iplab.aist-nara.ac.jp/member/masafu-o/xwipower/
EXTRACT_SUFX=	.tgz

MAINTAINER=	sumikawa@FreeBSD.org

WRKSRC=		${WRKDIR}/xwipower
USE_IMAKE=	yes

.include <bsd.port.mk>
