# New ports collection makefile for:	xdemineur
# Date created:		13 Feb 1998
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xdemineur/Makefile,v 1.8 2000/08/03 09:24:04 asami Exp $
#

PORTNAME=	xdemineur
PORTVERSION=	2.1.1
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB} \
		ftp://ftp.babafou.eu.org/pub/babafou/
MASTER_SITE_SUBDIR=	games

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		xdemineur.1

.include <bsd.port.mk>
