# New ports collection makefile for:    xdemineur
# Version required:     2.1.1
# Date created:         13 Feb 1998
# Whom:                 Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xdemineur/Makefile,v 1.5 1999/08/25 06:05:04 obrien Exp $
#

DISTNAME=       xdemineur-2.1.1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.babafou.eu.org/pub/babafou/

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		xdemineur.1

.include <bsd.port.mk>
