# New ports collection makefile for:    xdemineur
# Date created:         13 Feb 1998
# Whom:                 Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xdemineur/Makefile,v 1.7 2000/04/14 12:27:15 asami Exp $
#

PORTNAME=       xdemineur
PORTVERSION=	2.1.1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.babafou.eu.org/pub/babafou/

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		xdemineur.1

.include <bsd.port.mk>
