# New ports collection makefile for:  xw
# Date created:                       26 January 20001
# Whom:                               Daniel Hemmerich <dan@BSDpro.com>
#
# $FreeBSD: ports/sysutils/xw/Makefile,v 1.3 2001/03/12 19:18:57 sf Exp $
#

PORTNAME=	xw
PORTVERSION=	0.1.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.BSDpro.com/pub/xw/ \
		ftp://ftp.databits.net/pub/xw/

MAINTAINER=	dan@BSDpro.com

GTK_CONFIG=${X11BASE}/bin/gtk12-config

USE_GTK=	yes
USE_IMLIB=	yes
USE_X_PREFIX=	yes

.include <bsd.port.mk>
