# New ports collection makefile for:	fxhtml
# Date created:		21 August 1994
# Whom:			Trefor S. <trefor@flevel.co.uk>
#
# $FreeBSD: ports/www/fxhtml/Makefile,v 1.5 2000/02/05 10:22:14 dirk Exp $
#

PORTNAME=	fxhtml
PORTVERSION= 	1.6.7
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.flevel.co.uk/pub/fxhtml/
DISTNAME=	${PORTNAME}-freebsd-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

pre-install:
	${MKDIR} ${PREFIX}/www/cgi-bin ${PREFIX}/www/data

.include <bsd.port.mk>
