# New ports collection makefile for:	fxhtml
# Date created:		21 August 1994
# Whom:			Trefor S. <trefor@flevel.co.uk>
#
# $FreeBSD: ports/www/fxhtml/Makefile,v 1.6 2000/04/10 00:05:11 cpiazza Exp $
#

PORTNAME=	fxhtml
PORTVERSION=	1.6.7
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.flevel.co.uk/pub/fxhtml/
DISTNAME=	${PORTNAME}-freebsd-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

pre-install:
	${MKDIR} ${PREFIX}/www/cgi-bin ${PREFIX}/www/data

.include <bsd.port.mk>
