# New ports collection makefile for:   fxhtml
# Version required:     1.6.7
# Date created:         21 August 1994
# Whom:                 Trefor S. <trefor@flevel.co.uk>
#
# $FreeBSD: ports/www/fxhtml/Makefile,v 1.3 1999/08/31 02:42:49 peter Exp $
#
 
DISTNAME=       fxhtml-freebsd-1.6.7
PKGNAME=	fxhtml-1.6.7
CATEGORIES=     www
MASTER_SITES=   ftp://ftp.flevel.co.uk/pub/fxhtml/
 
pre-install:
	${MKDIR} ${PREFIX}/www/cgi-bin ${PREFIX}/www/data

.include <bsd.port.mk>
