# Ports collection makefile for:	cdict
# Version required:			1.0
# Date created:                         Thu Oct 14, 1999
# Whom:                                 Peng HaiJie   (phj@cn.FreeBSD.org)
#                                       (phj@transfar.com)
#
# $FreeBSD: ports/chinese/cdict/Makefile,v 1.3 2000/01/03 15:30:32 foxfair Exp $
#

DISTNAME=	zh-cdict-1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://ftp.cn.FreeBSD.org/pub/ported/

MAINTAINER=	phj@cn.FreeBSD.org

REQUIRES_MOTIF=	yes

GNU_CONFIGURE=	yes
USE_XLIB=	yes

MANCOMPRESSED=	yes
MAN1=		cdict.1

.include <bsd.port.mk>
