# New ports collection makefile for:	esound
# Date created:		19 July 1998
# Whom:			Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/audio/esound/Makefile,v 1.19 2000/04/08 21:23:27 mharo Exp $
#

PORTNAME=	esound
PORTVERSION=	0.2.18
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/esound

MAINTAINER=	vanilla@FreeBSD.org

LIB_DEPENDS=	audiofile.0:${PORTSDIR}/audio/libaudiofile

USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes

.include <bsd.port.mk>
