# New ports collection makefile for:	esound
# Version required:	0.2.8
# Date created:		19 July 1998
# Whom:			Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/audio/esound/Makefile,v 1.12 1999/08/25 04:35:27 obrien Exp $
#

DISTNAME=	esound-0.2.8
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	gnome-1.0/sources

MAINTAINER=	vanilla@FreeBSD.org

LIB_DEPENDS=	audiofile.0:${PORTSDIR}/audio/libaudiofile

USE_LIBTOOL=	yes

.include <bsd.port.mk>
