# ex:ts=8
# Ports collection makefile for:	g-wrap
# Date created:		Jun 29, 2000
# Whom:			Matthew Condell (mcondell@alum.mit.edu)
#
# $FreeBSD: ports/devel/g-wrap/Makefile,v 1.8 2001/01/22 19:33:59 ade Exp $
#

PORTNAME=	g-wrap
PORTVERSION=	0.9.12
CATEGORIES=	devel
MASTER_SITES=	http://www.gnucash.org/pub/g-wrap/source/

MAINTAINER=	gnome@FreeBSD.org

LIB_DEPENDS=	guile.9:${PORTSDIR}/lang/guile

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
