# New ports collection makefile for:	nslint
# Date created:		27 October 1997
# Whom:			dglo@ssec.wisc.edu
#
# $FreeBSD: ports/net/nslint/Makefile,v 1.12 2001/04/21 22:16:59 roam Exp $
#

PORTNAME=	nslint
PORTVERSION=	2.0.2
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.ee.lbl.gov/

MAINTAINER=	petef@FreeBSD.org

GNU_CONFIGURE=	yes
ALL_TARGET=	nslint
INSTALL_TARGET=	install install-man
MAN8=		nslint.8

.include <bsd.port.mk>
