# New ports collection makefile for:	beav
# Date created:		01 July 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/editors/beav/Makefile,v 1.15 1999/08/31 06:42:51 mharo Exp $
#

PORTNAME=	beav
PORTVERSION=	1.40.13
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.debian.org/debian/dists/stable/main/source/editors/
DISTNAME=	${PORTNAME}_1.40-13

MAINTAINER=	jseger@FreeBSD.org

MAN1=		beav.1
WRKSRC=		${WRKDIR}/beav-1.40

.include <bsd.port.mk>
