# New ports collection makefile for:    ja-rubytk
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/ruby14-tcltklib/Makefile,v 1.8 2000/04/25 07:01:59 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	yasuf@bsdclub.org

TCL_VERSION?=	80
TK_VERSION?=	80
WITH_TCLTK_JP=	yes

MASTERDIR=	${.CURDIR}/../../lang/ruby14-tcltklib

.include "${MASTERDIR}/Makefile"
