# New ports collection makefile for:   wmCalClock
# Date created:        16 March 1999
# Whom:                Kris Kennaway <kris@FreeBSD.org>
#
# $FreeBSD: ports/x11-clocks/wmcalclock/Makefile,v 1.10 2000/08/12 07:51:55 kevlo Exp $
#

PORTNAME=	wmCalClock
PORTVERSION=	1.25
CATEGORIES=	x11-clocks windowmaker
MASTER_SITES=	http://nis-www.lanl.gov/~mgh/WindowMaker/

MAINTAINER=	kris@FreeBSD.org

WRKSRC=		${WRKDIR}/${DISTNAME}/Src

USE_X_PREFIX=	yes
USE_XPM=	yes
ALL_TARGET=	clean all

MAN1=		wmCalClock.1

.include <bsd.port.mk>
