# New ports collection makefile for:    gnowavcut
# Date created:                         19 May 2001
# Whom:                                 Steve Coltrin <spcoltri@omcl.org>
#
# $FreeBSD: ports/audio/gnowavcut/Makefile,v 1.1 2001/05/21 19:47:44 alex Exp $
#

PORTNAME=	gnowavcut
PORTVERSION=	0.0.7
CATEGORIES=	audio gnome
MASTER_SITES=	http://gnowavcut.good-day.net/src/

MAINTAINER=	spcoltri@omcl.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
USE_GNOME=	yes

.include <bsd.port.mk>
