#!/bin/sh
#
# $FreeBSD: ports/shells/bash/pkg-install,v 1.6 2007/08/04 11:41:18 gabor Exp $
#

BASHC="$(echo ${PKG_PREFIX-/usr/local}/bin/bashc | /usr/bin/sed -e 's|//|/|g')"
SHELLS="/etc/shells"

case $2 in
POST-INSTALL)
  if [ -d "${SHELLS%/*}" ] && ! grep -qs "^$BASHC\$" "$SHELLS"; then
    if [ `id -u` -eq 0 ]; then
      echo "$BASHC" >> "$SHELLS"
    else
      echo "Not root, please add $BASHC to $SHELLS manually"
    fi
  fi
  ;;
esac
