# New ports collection makefile for: bkpupsd
# Date created:             26 May 1995
# Whom:                     Yoshifumi Watanabe <mwatts@edu1.tokyo-med.ac.jp>
#
# $FreeBSD: ports/sysutils/bkpupsd/Makefile,v 1.3 2000/04/09 19:07:15 cpiazza Exp $
#

PORTNAME=	bkpupsd
PORTVERSION=	1.0a
CATEGORIES=	sysutils
MASTER_SITES=	ftp://edu1.tokyo-med.ac.jp/pub/contrib/bkpupsd/

MAINTAINER=	mwatts@edu1.tokyo-med.ac.jp

MAN8=		bkpupsd.8

.include <bsd.port.mk>
