# New ports collection makefile for:	nscache
# Date created:		04 March 2000
# Whom:			Kris Kennaway <kris@FreeBSD.org>
#
# $FreeBSD: ports/www/nscache/Makefile,v 1.1 2000/03/05 10:13:43 kris Exp $
#

PORTNAME=	nscache
PORTVERSION= 	0.2p2
CATEGORIES=	www
MASTER_SITES=	http://www.idata.sk/~ondrej/sw/
DISTNAME=	nscache-0.2pl2
EXTRACT_SUFX=	.tgz

MAINTAINER=	kris@FreeBSD.org

LIB_DEPENDS=	gtk12.2:${PORTSDIR}/x11-toolkits/gtk12

USE_AUTOCONF=	yes

.include <bsd.port.mk>
