# New ports collection makefile for:	jvim for Canna
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna/Makefile,v 1.5 2000/04/11 14:14:04 knu Exp $
#

PKGNAMESUFFIX=	-canna
CANNA=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
