# New ports collection makefile for:	jvim for Canna
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna/Makefile,v 1.4 1999/08/25 05:24:34 obrien Exp $
#

PKGNAMESUFFIX=	-canna
CANNA=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
