#!/bin/sh
#
# $FreeBSD: ports/devel/pear-PEAR/pkg-install,v 1.3 2004/12/21 22:14:02 edwin Exp $
#
# Register the package $1 in the port registry

PREFIX=${PKG_PREFIX:=%%PREFIX%%}
PEAR=${PREFIX}/bin/pear
PEAR2=${PREFIX}/bin/pear2
PKGREGDIR=${PREFIX}/share/pear/packages/$1

if [ -f "${PEAR2}" ]; then
	PEAR_INSTALLER=${PEAR2}
else
	PEAR_INSTALLER=${PEAR}
fi

[ "x$1" = "x" ] && exit 1
if [ "x$2" = "xPOST-INSTALL" ]; then
	${PEAR_INSTALLER} install -r -n -f ${PKGREGDIR}/package.xml
fi
