# New ports collection makefile for:    manck
# Date created:         10 September 1995
# Whom:                 joerg
#
# $FreeBSD: ports/sysutils/manck/Makefile,v 1.12 1999/09/19 10:30:45 wosch Exp $
#

PORTNAME=	manck
PORTVERSION= 	1.2
CATEGORIES=	sysutils
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		manck.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
