# New ports collection makefile for:    manck
# Version required:     1.0
# Date created:         10 September 1995
# Whom:                 joerg
#
# $FreeBSD: ports/sysutils/manck/Makefile,v 1.11 1999/08/31 01:59:51 peter Exp $
#

DISTNAME=       manck-1.2
CATEGORIES=	sysutils
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		manck.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
