# New ports collection makefile for:	zh-joe
# Date created:			3 July 1999
# Whom:				Shen Chuan-Hsing <statue@mail.elife.idv.tw>
#
# $FreeBSD: ports/chinese/joe/Makefile,v 1.3 2001/03/17 03:12:28 clive Exp $
#

MASTERDIR=	${.CURDIR}/../../editors/joe

PATCH_SITES=	http://freebsd.sinica.edu.tw/~statue/
PATCHFILES=	zh-joe-2.8_3-patch
PATCH_DIST_STRIP=	-p1

MAINTAINER=	statue@freebsd.sinica.edu.tw

MD5_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
