# New ports collection makefile for: pips for EPSON PM-770C
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips770/Makefile,v 1.2 2000/10/08 10:21:16 asami Exp $
#

MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		770

do-install:     # empty

.include "${MASTERDIR}/Makefile"
