# New ports collection makefile for:	xwrits
# Version required:	2.10
# Date created:		02 January 2000
# Whom:			Matt Braithwaite <mab@red-bean.com>
#
# $FreeBSD: ports/deskutils/xwrits/Makefile,v 1.1.1.1 2000/01/04 18:01:20 jedgar Exp $
#

DISTNAME=	xwrits-2.10
CATEGORIES=	deskutils
MASTER_SITES=	http://www.pdos.lcs.mit.edu/~eddietwo/xwrits/

MAINTAINER=	mab@red-bean.com

GNU_CONFIGURE=	yes

USE_X_PREFIX=	yes

MAN1=		xwrits.1

.include <bsd.port.mk>
