# New ports collection makefile for:	xwrits
# Date created:		02 January 2000
# Whom:			Matt Braithwaite <mab@red-bean.com>
#
# $FreeBSD: ports/deskutils/xwrits/Makefile,v 1.3 2000/04/08 22:04:14 mharo Exp $
#

PORTNAME=	xwrits
PORTVERSION=	2.11
CATEGORIES=	deskutils
MASTER_SITES=	http://www.pdos.lcs.mit.edu/~eddietwo/xwrits/

MAINTAINER=	mab@red-bean.com

GNU_CONFIGURE=	yes

USE_X_PREFIX=	yes

MAN1=		xwrits.1

.include <bsd.port.mk>
