# New ports collection makefile for:	Death Match Classic Mod
# Date created:				Fri Jun  8 02:33:32 EDT 2001
# Whom:					pat@databits.net
#
# $FreeBSD: ports/games/hlserver-dmc/Makefile,v 1.1 2001/06/09 19:52:59 lioux Exp $
#

PORTNAME=	dmc
PORTVERSION=	1.0
MASTER_SITES=	http://games.velocity.net/files/Halflife/ \
		ftp://ftp.bluesnews.com/half-life/dmc/ \
		http://www.smidge.com/data/files/17/ \
		http://www.planetmirror.com/pub/bluesnews/half-life/dmc/
DISTNAME=	${PORTNAME}_v1_i386

HALFLIFE_COUNTERSTRIKE_MASTER=	${.CURDIR}/../hlserver-cs

.include "${HALFLIFE_COUNTERSTRIKE_MASTER}/Makefile"
