# New ports collection makefile for:	vlock
# Date created:		08 Oct 2000
# Whom:			George Reid <services@nevernet.net>
#
# $FreeBSD: ports/security/vlock/Makefile,v 1.1 2000/10/22 15:36:24 trevor Exp $
#

PORTNAME=		vlock
PORTVERSION=		1.3
CATEGORIES=		security
MASTER_SITES=		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	utils/console

MAINTAINER=		greid@ukug.uk.freebsd.org

MAN1=			vlock.1

.include <bsd.port.mk>
