# New ports collection makefile for:	p5-Unix-Syslog
# Date created:				November 19th 2000
# Whom:					Blaz Zupan <blaz@amis.net>
#
# $FreeBSD: ports/sysutils/p5-Unix-Syslog/Makefile,v 1.3 2001/03/01 06:39:05 vanilla Exp $
#

PORTNAME=	Unix-Syslog
PORTVERSION=	0.95
CATEGORIES=	sysutils perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Unix
PKGNAMEPREFIX=	p5-
DISTNAME=	Syslog-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Unix::Syslog.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
