# Ports collection makefile for:	tocps
# Date created:		Thu Oct 14, 1999
# Whom:			Peng HaiJie <phj@transfar.com>
#
# $FreeBSD: ports/chinese/tocps/Makefile,v 1.2 2000/03/19 01:58:47 foxfair Exp $
#

PORTNAME=	tocps
PORTVERSION=	1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://ftp.cn.FreeBSD.org/pub/ported/
DISTNAME=	${PKGNAME}

MAINTAINER=	phj@cn.FreeBSD.org

MANCOMPRESSED=	yes
MAN1=		tocps.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
