# Ports collection makefile for:	tocps
# Version required:	1.0
# Date created:		Thu Oct 14, 1999
# Whom:			Peng HaiJie <phj@transfar.com>
#
# $FreeBSD: ports/chinese/tocps/Makefile,v 1.1.1.1 1999/11/26 20:38:31 steve Exp $
#

DISTNAME=	zh-tocps-1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://ftp.cn.FreeBSD.org/pub/ported/

MAINTAINER=	phj@cn.FreeBSD.org

MANCOMPRESSED=	yes
MAN1=		tocps.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
