# New ports collection makefile for:	lwm
# Date created:		17 March 1998
# Whom:			J Han <hjh@photino.com>
#
# $FreeBSD: ports/x11-wm/lwm/Makefile,v 1.10 2001/02/05 21:05:41 olgeni Exp $
#

PORTNAME=	lwm
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.boognish.org.uk/enh/lwm/
DISTNAME=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}
USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
