# New ports collection makefile for:	kinput2-canna
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna/Makefile,v 1.10 1999/08/25 05:24:54 obrien Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../kinput2-wnn4/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
