# New ports collection makefile for:	kinput2-canna
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna/Makefile,v 1.12 2000/09/08 04:34:25 taoka Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
