# New ports collection makefile for:	kinput2-canna
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna/Makefile,v 1.11 2000/04/11 14:14:23 knu Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
