# New ports collection makefile for: pips for EPSON PM-900C
# Date created:        2000.12.09
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips900/Makefile,v 1.1 2000/12/11 02:08:22 taoka Exp $
#

PORTVERSION=	1.3
MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		900

do-install:     # empty

.include "${MASTERDIR}/Makefile"
