# New ports collection makefile for:    patch
# Date created:         21 Jan 1998
# Whom:                 ache
#
# $FreeBSD: ports/devel/patch/Makefile,v 1.6 2001/01/11 00:56:18 trevor Exp $
#

PORTNAME=	patch
PORTVERSION=	2.5
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	patch

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--program-prefix=g

MAN1=		gpatch.1

.include <bsd.port.mk>
