# New ports collection makefile for: pgp4pine
# Date created:		29 February 2000
# Whom:			Holger Lamm <holger@flatline.de>
#
# $FreeBSD: ports/mail/pgp4pine/Makefile,v 1.2 2000/02/29 08:07:12 kris Exp $
#

PORTNAME=	pgp4pine
PORTVERSION= 	1.74
CATEGORIES=	mail
MASTER_SITES=	http://pgp4pine.flatline.de/
EXTRACT_SUFX=	.tgz

MAINTAINER=	holger@flatline.de

MAN1=		pgp4pine.1
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
