# New ports collection makefile for: pgp4pine
# Date created:		29 February 2000
# Whom:			Holger Lamm <holger@flatline.de>
#
# $FreeBSD: ports/mail/pgp4pine/Makefile,v 1.4 2000/09/18 13:51:41 jedgar Exp $
#

PORTNAME=	pgp4pine
PORTVERSION=	1.76
CATEGORIES=	mail
MASTER_SITES=	http://pgp4pine.flatline.de/

MAINTAINER=	holger@flatline.de

MAN1=		pgp4pine.1
GNU_CONFIGURE=	yes
CONFIGURE_ARGS= --with-docdir=${PREFIX}/share/doc

.include <bsd.port.mk>
