# ex:ts=8
# New ports collection makefile for:   mahjong
# Date created:                Jan 31, 2001
# Whom:                        Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/games/mahjong/Makefile,v 1.5 2001/05/19 05:46:19 ijliao Exp $
#

PORTNAME=	mahjong
PORTVERSION=	1.2
CATEGORIES=	games net
MASTER_SITES=	http://www.stevens-bradfield.com/MahJong/Source/
DISTNAME=	mj-${PORTVERSION}-src

MAINTAINER=	ports@FreeBSD.org

USE_GTK=	yes

USE_GMAKE=	yes

INSTALL_TARGET=	install install.man

MAN1=		xmj.1 mj-player.1 mj-server.1

.include <bsd.port.mk>
