# New ports collection makefile for:   w3m-image
# Date Created:                22 July 2001
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-img/Makefile,v 1.1 2001/07/21 18:21:56 sf Exp $
#

PKGNAMESUFFIX=	-img

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

INLINE_IMAGE=	yes

.include "${MASTERDIR}/Makefile"
