# New ports collection makefile for:	netscape
# Version required:     3.04 (gold)
# Date created:		21 August 1995
# Whom:			asami
#
# $FreeBSD: ports/www/netscape3-gold/Makefile,v 1.4 1999/08/31 02:43:02 peter Exp $
#

DISTNAME=	netscape-gold-3.04
MASTER_SITES=	ftp://archive:oldies@archive.netscape.com/archive/navigator/3.04/shipping/english/unix/bsdi11/navigator_gold_complete/

DIST_SUBDIR=	gold
COMMENT=	${.CURDIR}/pkg/COMMENT
MASTERDIR=	${.CURDIR}/../netscape3
NO_LATEST_LINK=	yes

.include "${MASTERDIR}/Makefile"
