# New ports collection makefile for:	netscape
# Date created:		21 August 1995
# Whom:			asami
#
# $FreeBSD: ports/www/netscape3-gold/Makefile,v 1.7 2000/10/08 10:23:11 asami Exp $
#

PORTNAME=	netscape-gold
PORTVERSION=	3.04
MASTER_SITES=	ftp://archive:oldies@archive.netscape.com/archive/navigator/3.04/shipping/english/unix/bsdi11/navigator_gold_complete/

DIST_SUBDIR=	gold
COMMENT=	${.CURDIR}/pkg-comment
MASTERDIR=	${.CURDIR}/../netscape3
NO_LATEST_LINK=	yes

.include "${MASTERDIR}/Makefile"
