# New ports collection makefile for: X Japanese man documents for XFree86 3.x.x
# Date created:		8 Aug 2001
# Whom:			SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/xjman-3/Makefile,v 1.14 2001/08/06 14:07:47 sada Exp $
#

PORTVERSION=	0.5

MAINTAINER=	sada@FreeBSD.org

MASTERDIR=	${.CURDIR}/../xjman
WRKSRC=		${WRKDIR}/man/ja_JP.eucJP

.include "${MASTERDIR}/Makefile"
