# New ports collection makefile for:    lv
# Version required:     4.49.2
# Date created:         Fri Nov  6 09:06:33 PST 1998
# Whom:                 sumikawa@kame.net
#
# $FreeBSD: ports/misc/lv/Makefile,v 1.7 1999/08/25 07:22:05 obrien Exp $
#

DISTNAME=	lv4492
PKGNAME=	lv-4.49.2
CATEGORIES=	misc
MASTER_SITES=	http://www.ff.iij4u.or.jp/~nrt/freeware/

MAINTAINER=	sumikawa@kame.net

WRKSRC=		${WRKDIR}/${DISTNAME}/src
GNU_CONFIGURE=	yes

MAN1=		lv.1

.include <bsd.port.mk>
