# New ports collection makefile for:    lv
# Date created:         Fri Nov  6 09:06:33 PST 1998
# Whom:                 sumikawa@FreeBSD.org
#
# $FreeBSD: ports/misc/lv/Makefile,v 1.10 2000/04/14 08:46:12 asami Exp $
#

PORTNAME=	lv
PORTVERSION=	4.49.4
CATEGORIES=	misc
MASTER_SITES=	http://www.ff.iij4u.or.jp/~nrt/freeware/
DISTNAME=	lv4494

MAINTAINER=	sumikawa@FreeBSD.org

WRKSRC=		${WRKDIR}/${DISTNAME}/src
GNU_CONFIGURE=	yes

MAN1=		lv.1

.include <bsd.port.mk>
