# New ports collection makefile for:    xcdplayer
# Date created:         30 Sep 1994
# Whom:                 swallace
#
# $FreeBSD: ports/audio/xcdplayer/Makefile,v 1.10 1999/08/25 04:36:22 obrien Exp $
#

PORTNAME=	xcdplayer
PORTVERSION=	2.2
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.x.org/R5contrib/ \
		ftp://ftp.cdrom.com/pub/X11/R5contrib/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	swallace@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xcdplayer.1

.include <bsd.port.mk>
