# New ports collection makefile for:	CipherSaber
# Date created:				Wed Jan  3 16:03:49 2001
# Whom:					will
#
# $FreeBSD: ports/security/p5-Crypt-CipherSaber/Makefile,v 1.2 2001/03/01 06:37:13 vanilla Exp $
#

PORTNAME=	CipherSaber
PORTVERSION=	0.60
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Crypt
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Crypt::CipherSaber.3

.include <bsd.port.mk>
