# New ports collection makefile for:	RealTimeBattle
# Date created:				30 June 2000
# Whom:				Dishanker Rajakulendren <draj@oceanfree.net>
#
# $FreeBSD: ports/games/rtb/Makefile,v 1.1 2000/06/30 22:44:00 will Exp $
#

PORTNAME=	RealTimeBattle
PORTVERSION=	1.0.4
CATEGORIES=	games
MASTER_SITES=	http://www.lysator.liu.se/realtimebattle/Download/

MAINTAINER=	draj@oceanfree.net

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
CONFIGURE_ARGS=	--enable-debug

.include <bsd.port.mk>
