# New ports collection makefile for:	RealTimeBattle
# Date created:				30 June 2000
# Whom:				Dishanker Rajakulendren <draj@oceanfree.net>
#
# $FreeBSD: ports/games/rtb/Makefile,v 1.2 2000/10/05 06:36:15 reg Exp $
#

PORTNAME=	RealTimeBattle
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://www.lysator.liu.se/realtimebattle/Download/

MAINTAINER=	draj@oceanfree.net

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
CONFIGURE_ARGS=	--enable-debug

.include <bsd.port.mk>
