# New ports collection makefile for:	word2x
# Version required:	0.003
# Date created:		10 June 1998
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/textproc/word2x/Makefile,v 1.8 2000/01/29 22:46:04 reg Exp $

DISTNAME=	word2x
PKGNAME=	word2x-0.003
CATEGORIES=	textproc
MASTER_SITES=	ftp://ftp.gu.net/pub/unix/viewers/ \
		ftp://ftp.afti.nsu.ru/pub/source/utils/word2x/ \
		http://people.FreeBSD.org/~billf/

MAINTAINER=	billf@FreeBSD.org

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=	word2x.1

.include <bsd.port.mk>
