# New ports collection makefile for:	word2x
# Date created:		10 June 1998
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/textproc/word2x/Makefile,v 1.10 2000/03/11 01:47:05 billf Exp $
#

PORTNAME=	word2x
PORTVERSION=	0.005
CATEGORIES=	textproc
MASTER_SITES=	http://word2x.alcom.co.uk/download/

MAINTAINER=	billf@FreeBSD.org

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=	word2x.1

.include <bsd.port.mk>
