# New ports collection makefile for:	worker
# Date created:				14 March 2001
# Whom:					Simon Dick <simond@irrelevant.org>
#
# $FreeBSD: ports/x11-fm/worker/Makefile,v 1.1 2001/03/31 02:58:11 will Exp $
#

PORTNAME=	worker
PORTVERSION=	2.2.0
CATEGORIES=	x11-fm
MASTER_SITES=	http://www.boomerangsworld.de/worker/downloads/ \
		http://www.informatik.uni-halle.de/~hoffmanr/worker/downloads/

MAINTAINER=	simond@irrelevant.org

GNU_CONFIGURE=	yes
USE_XLIB=	yes

MAN1=		worker.1

.include <bsd.port.mk>
