#!/bin/sh
# $FreeBSD: ports/japanese/alias-fonts/pkg-deinstall,v 1.4 2011/08/15 07:03:55 tota Exp $

dir="${PKG_PREFIX}/lib/X11/fonts/local";
to="$dir/fonts.alias";
from="$to.orig";

if ! mv $to $from; then
  echo "Couldn't rename $to."
  exit 1
fi

IFS="
"

while read line; do
  trimmed=${line# *}
  case $trimmed in
    -alias-*) ;;
    *) echo $line;;
  esac
done < $from > $to

rm $from
