#!/bin/sh
# $FreeBSD: ports/japanese/alias-fonts/pkg-deinstall,v 1.3 2002/04/09 09:05:22 sada Exp $

dir="${PKG_PREFIX}/lib/X11/fonts/local";
to="$dir/fonts.alias";
from="$to.orig";

if ! mv $to $from; then
  echo "Couldn't rename $to."
  exit 1
fi

IFS="
"

while read line; do
  trimmed=${line# *}
  case $trimmed in
    !*|"") echo $line;;
    -alias-*) echo $line;;
    *) ;;
  esac
done < $from > $to

rm $from
