# New ports collection makefile for:	p5-Parse-RecDescent
# Date created:				July 9th 1999
# Whom:	      				Jerry Hicks <wghicks@bellsouth.net>
#
# $FreeBSD: ports/devel/p5-Parse-RecDescent/Makefile,v 1.9 2001/03/01 06:38:28 vanilla Exp $
#

PORTNAME=	Parse-RecDescent
PORTVERSION=	1.80
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Parse
PKGNAMEPREFIX=	p5-

MAINTAINER=	gehicks@cisco.com

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Parse::RecDescent.3 Text::Balanced.3

.include <bsd.port.mk>
