# New ports collection makefile for:	Geo-METAR
# Date created:				Mon Jan  1 01:42:56 2001
# Whom:					will
#
# $FreeBSD: ports/astro/p5-Geo-METAR/Makefile,v 1.1 2001/01/01 06:53:32 will Exp $
#

PORTNAME=	Geo-METAR
PORTVERSION=	1.14
CATEGORIES=	astro
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Geo
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

USE_PERL5=	yes
PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Geo::METAR.3

.include <bsd.port.mk>
