# New ports collection makefile for:	acroread-chsfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chsfont/Makefile,v 1.6 2000/04/13 08:27:51 asami Exp $
#

DISTNAME=	chsfont
CATEGORIES=	chinese

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
