# New ports collection makefile for: br-ispell
# Date created:         5 February 1999
# Whom:                 Joao Carlos Mendes Luis <jonny@jonny.eng.br>
#
# $FreeBSD: ports/textproc/br-ispell/Makefile,v 1.4 1999/11/14 01:57:11 steve Exp $
#

PORTNAME=	br-ispell
PORTVERSION= 	2.4
CATEGORIES=	textproc
MASTER_SITES=	ftp://ftp.ime.usp.br/pub/ueda/br.ispell/
DISTNAME=	br.ispell-2.4

MAINTAINER=	jonny@jonny.eng.br

BUILD_DEPENDS=	buildhash:${PORTSDIR}/textproc/ispell

MAN1=		conjugue.1

.include <bsd.port.mk>
