# New ports collection makefile for:	p5-NetAddr-IP
# Date created:				12 July 2000
# Whom:					Christopher N. Harrell <cnh@ivmg.net>
#
# $FreeBSD: ports/net/p5-NetAddr-IP/Makefile,v 1.3 2001/03/01 06:38:26 vanilla Exp $
#

PORTNAME=	NetAddr-IP
PORTVERSION=	2.00
CATEGORIES=	net perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	NetAddr
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		NetAddr::IP.3

.include <bsd.port.mk>
