# New ports collection makefile for:   XShodou
# Date created:        11 January 1999
# Whom:                Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/japanese/xshodou/Makefile,v 1.2 1999/08/25 05:27:59 obrien Exp $
#

PORTNAME=	xshodou
PORTVERSION=	1.11
CATEGORIES=	japanese tk80
MASTER_SITES=	http://wwwmiya.ee.kagu.sut.ac.jp/~sakai/

MAINTAINER=	sakai@miya.ee.kagu.sut.ac.jp

RUN_DEPENDS=    wish8.0:${PORTSDIR}/x11-toolkits/tk80

USE_X_PREFIX=	yes
MAN1=		xshodou.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
