# New ports collection makefile for: Mew (for xemacs20)
# Version required:	1.93
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs20/Makefile,v 1.3 1999/08/25 06:50:28 obrien Exp $
#

EMACS_PORT_NAME=	xemacs20

MASTERDIR=		${.CURDIR}/../../mail/mew

.include "${MASTERDIR}/Makefile"
