# New ports collection makefile for: Mew (for xemacs20)
# Version required:	1.94.1
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs20/Makefile,v 1.4 1999/09/09 08:06:22 taoka Exp $
#

EMACS_PORT_NAME=	xemacs20

.include "${.CURDIR}/../mew/Makefile"
