# New ports collection makefile for:	xphoon
# Version required:	18sep91 (in R5 contrib)
# Date created:		14 February 1995
# Whom:			asami
#
# $FreeBSD: ports/astro/xphoon/Makefile,v 1.13 2000/03/22 01:58:53 will Exp $
#

DISTNAME=	xphoon
PKGNAME=	xphoon-91.9.18
CATEGORIES=	astro x11
MASTER_SITES=	ftp://ftp.x.org/R5contrib/ \
		ftp://ftp.freesoftware.com/pub/X11/R5contrib/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	will@FreeBSD.org

USE_IMAKE=	yes

MAN1=		xphoon.1

.include <bsd.port.mk>
