# $FreeBSD: ports/japanese/libjconv/files/Makefile.prog,v 1.1 2001/01/16 18:27:26 knu Exp $

PREFIX?=	/usr/local
LOCALBASE?=	/usr/local

PROG=		jconv
SRCS=		jconv.c
CFLAGS+=        -I${LOCALBASE}/include
LDADD=          -L${.CURDIR} -ljconv
NOMAN=          YES
BINDIR=         ${PREFIX}/bin

.include <bsd.prog.mk>
