# New ports collection makefile for:	emacs-lisp-intro
# Date created:		18 November 1997
# Whom:			Don Croyle <croyle@gelemna.ft-wayne.in.us>
#
# $FreeBSD: ports/lang/emacs-lisp-intro/Makefile,v 1.5 1999/08/25 06:34:27 obrien Exp $
#

PORTNAME=	emacs-lisp-intro
PORTVERSION=	1.05
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	emacs

MAINTAINER=	croyle@gelemna.ft-wayne.in.us

.include <bsd.port.mk>
