# New ports collection makefile for:	emacs-lisp-intro
# Date created:		18 November 1997
# Whom:			Don Croyle <croyle@gelemna.org>
#
# $FreeBSD: ports/lang/emacs-lisp-intro/Makefile,v 1.6 2000/04/12 06:18:16 obrien Exp $
#

PORTNAME=	emacs-lisp-intro
PORTVERSION=	1.05
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	emacs

MAINTAINER=	croyle@gelemna.org

.include <bsd.port.mk>
