# New ports collection makefile for:    obliterate
# Date created:         17 Nov 1999
# Whom:                 Wes Peters <wes@FreeBSD.ORG>
#
# $FreeBSD: ports/sysutils/obliterate/Makefile,v 1.5 2000/04/22 10:12:54 mharo Exp $
#

PORTNAME=	obliterate
PORTVERSION=	0.4
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.bsdconspiracy.net/pub/softweyr/

MAINTAINER=	wes@softweyr.com

.include <bsd.port.mk>
