# New ports collection makefile for:    obliterate
# Version required:     0.4
# Date created:         17 Nov 1999
# Whom:                 Wes Peters <wes@FreeBSD.ORG>
#
# $FreeBSD: ports/sysutils/obliterate/Makefile,v 1.2 1999/11/24 01:19:50 wes Exp $
#

DISTNAME=	obliterate-0.4
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.xmission.com/pub/users/s/softweyr/pub/

MAINTAINER=	wes@softweyr.com

.include <bsd.port.mk>
