# New ports collection makefile for:    obliterate
# Date created:         17 Nov 1999
# Whom:                 Wes Peters <wes@FreeBSD.ORG>
#
# $FreeBSD: ports/sysutils/obliterate/Makefile,v 1.3 1999/12/10 07:38:55 wes Exp $
#

PORTNAME=	obliterate
PORTVERSION= 	0.4
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.xmission.com/pub/users/s/softweyr/pub/

MAINTAINER=	wes@softweyr.com

.include <bsd.port.mk>
