# New ports collection makefile for:	xbmbrowser
# Date created:		06 September 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/graphics/xbmbrowser/Makefile,v 1.7 1999/08/25 06:15:16 obrien Exp $
#

PORTNAME=	xbmbrowser
PORTVERSION=	5.1
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	tg@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		xbmbrowser.1

USE_GMAKE=	yes

.include <bsd.port.mk>

