# New ports collection makefile for: gd
# Date created:				19 Aug 1998
# Whom:					ichiro@ichiro.org
#
# $FreeBSD: ports/japanese/gd/Makefile,v 1.14 2001/02/06 13:21:53 olgeni Exp $
#

CATEGORIES=	japanese

MAINTAINER=	ichiro@ichiro.org

MASTERDIR=	${.CURDIR}/../../graphics/gd

MAKE_ARGS=	-DJISX0208

.include "${MASTERDIR}/Makefile"
