# New ports collection makefile for:	sh-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sh-rtems-gcc/Makefile,v 1.1 2000/07/10 04:32:30 steve Exp $
#

PORTNAME=	gcc

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sh-rtems
.include "${.CURDIR}/../i386-rtems-gcc/Makefile"
