# New ports collection makefile for:	sh-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sh-rtems-gcc/Makefile,v 1.2 2000/10/02 03:10:22 jeh Exp $
#

PORTNAME=	gcc

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sh-rtems
BROKEN=		"Generates an internal compiler error.  Under investigation."
.include "${.CURDIR}/../i386-rtems-gcc/Makefile"
