# New ports collection makefile for:	xtimer
# Date created:		19 May 2000
# Whom:			candy@kgc.co.jp
#
# $FreeBSD: ports/x11-clocks/xtimer/Makefile,v 1.9 2000/05/19 07:41:03 cpiazza Exp $
#

PORTNAME=	xtimer
PORTVERSION=	0.8089
CATEGORIES=	x11-clocks
MASTER_SITES=	http://hp.vector.co.jp/authors/VA004959/xtimer/
DISTNAME=	${PORTNAME}-8089

MAINTAINER=	candy@kgc.co.jp

USE_IMAKE=	yes
MAN1=		xtimer.1

.include <bsd.port.mk>
