# New ports collection makefile for:	ted
# Date Created:		18 Sep 1997
# Whom:			Vanilla I. Shu <vanilla@MinJe.com.TW>
#
# $FreeBSD: ports/chinese/ted/Makefile,v 1.24 2000/04/02 04:43:10 vanilla Exp $
#

PORTNAME=		ted
PORTVERSION=		4.4d
CATEGORIES=		chinese editors
MASTER_SITES=		ftp://freebsd.ntu.edu.tw/freebsd/ntu/moon/X/ted/
DISTFILES=		ted4.4d.tgz

MAINTAINER=		vanilla@FreeBSD.org

RUN_DEPENDS=		${X11BASE}/bin/xcin:${PORTSDIR}/chinese/xcin

USE_X_PREFIX=		yes
WRKSRC=			${WRKDIR}/ted

.include <bsd.port.mk>
