# New ports collection makefile for: bjfilter850
# Date created:		2001.02.11
# Whom:                 taoka@FreeBSD.org
#
# $FreeBSD: ports/print/bjfilter850/Makefile,v 1.1 2001/03/01 05:46:51 taoka Exp $
#

PORTNAME=	bjfilter${PRTYPE}${SUFIX_PRTYPE}
MASTERDIR=	${.CURDIR}/../bjfiltercom

SLAVE_PORT=	yes
PRTYPE?=	850
SUFIX_PRTYPE?=	

.include "${MASTERDIR}/Makefile"

