# ex:ts=8
# New ports collection makefile for:	sunclock
# Date created:		15 September 1996
# Whom:			torstenb
#
# $FreeBSD: ports/astro/sunclock/Makefile,v 1.12 2001/04/02 14:10:59 ijliao Exp $
#

PORTNAME=	sunclock
PORTVERSION=	3.38
CATEGORIES=	astro x11-clocks
MASTER_SITES=	ftp://ftp.ac-grenoble.fr/ge/geosciences/
EXTRACT_SUFX=	.tgz

MAINTAINER=	torstenb@FreeBSD.org

LIB_DEPENDS=	jpeg.9:${PORTSDIR}/graphics/jpeg

USE_IMAKE=	YES

MAN1=		sunclock.1

.include <bsd.port.mk>
