# New ports collection makefile for:	tvision
# Date created:				16 February 1997
# Whom:					Sandro Sigala
#
# $FreeBSD: ports/devel/tvision/Makefile,v 1.12 2000/01/29 22:46:00 reg Exp $
#

PORTNAME=	tvision
PORTVERSION=	0.7
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	devel/lang/c++

MAINTAINER=	ssigala@globalnet.it

USE_LIBTOOL=	yes

.include <bsd.port.mk>
