# New ports collection makefile for:	tvision
# Date created:				16 February 1997
# Whom:					Sandro Sigala
#
# $FreeBSD: ports/devel/tvision/Makefile,v 1.13 2000/04/14 05:44:37 asami Exp $
#

PORTNAME=	tvision
PORTVERSION=	0.7
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	devel/lang/c++

MAINTAINER=	ssigala@globalnet.it

USE_LIBTOOL=	yes
INSTALL_SHLIBS=	yes

.include <bsd.port.mk>
