# New ports collection makefile for: se-ispell
# Date created:         4 November 1999
# Whom:                 Kent Boortz <kent@erix.ericsson.se>
#
# $FreeBSD: ports/textproc/se-ispell/Makefile,v 1.1 1999/12/27 02:01:41 steve Exp $
#

PORTNAME=	se-ispell
PORTVERSION= 	1.2.1
CATEGORIES=	textproc
MASTER_SITES=	http://www.sslug.dk/locale/ispell/iswedish/
DISTNAME=	iswedish-1.2.1

MAINTAINER=	kent@erix.ericsson.se

BUILD_DEPENDS=	buildhash:${PORTSDIR}/textproc/ispell

.include <bsd.port.mk>
