# New ports collection makefile for:	cgiparse
# Date created:				30 March 1997
# Whom:					jmg
#
# $FreeBSD: ports/www/cgiparse/Makefile,v 1.7 1999/08/31 06:51:38 mharo Exp $
#

PORTNAME=	cgiparse
PORTVERSION= 	0.8e
CATEGORIES=	devel
MASTER_SITES=	http://resnet.uoregon.edu/~gurney_j/	\
		http://d182-89.uoregon.edu/~jmg/

MAINTAINER=	jmg@FreeBSD.org

.include <bsd.port.mk>
