# New ports collection makefile for:	cgiparse
# Date created:				30 March 1997
# Whom:					jmg
#
# $FreeBSD: ports/www/cgiparse/Makefile,v 1.11 2000/06/16 18:14:38 jmg Exp $
#

PORTNAME=	cgiparse
PORTVERSION= 	0.9a
CATEGORIES=	devel www
MASTER_SITES=	http://resnet.uoregon.edu/~gurney_j/jmpc/dist/	\
		http://www.funkthat.com/~jmg/

MAINTAINER=	jmg@FreeBSD.org

LIB_DEPENDS=	mime.1:${PORTSDIR}/devel/mime:install

.include <bsd.port.mk>
