# New ports collection makefile for:	photopc-1.6
# Date created:		11 October 1997
# Whom:			Douglas Carmichael <dcarmich@mcs.com>
#
# $FreeBSD: ports/graphics/photopc/Makefile,v 1.3 2000/04/14 10:46:59 asami Exp $
#

PORTNAME=	photopc
PORTVERSION=	3.04
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.average.org/pub/photopc/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=	photopc.1 epinfo.1

.include <bsd.port.mk>
