# New ports collection makefile for:	photopc-1.6
# Date created:		11 October 1997
# Whom:			Douglas Carmichael <dcarmich@mcs.com>
#
# $FreeBSD: ports/graphics/photopc/Makefile,v 1.2 1999/08/25 06:14:37 obrien Exp $
#

PORTNAME=	photopc
PORTVERSION=	1.6
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.average.org/pub/photopc/

MAINTAINER=	dcarmich@mcs.com

MAN1=	photopc.1 epinfo.1

.include <bsd.port.mk>
