# New ports collection makefile for:    hLaTeXp pkfonts 600dpi
# Date created:                 Jun 29 2000
# Whom:                         CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/hlatexp-pkfonts1200/Makefile,v 1.2 2000/10/08 10:21:44 asami Exp $
#

MASTERDIR=      ${.CURDIR}/../hlatexp-pkfonts300
FILESDIR=	${.CURDIR}/files
PKGDIR=		${.CURDIR}
MD5_FILE=	${.CURDIR}/distinfo

# pkfonts dpi
RESOLUTION=	1200

NO_CDROM=	"Package is too big"

.include        "${MASTERDIR}/Makefile"
