# New ports collection makefile for:	Ruby-slang (slanglib)
# Date created:		23 Aug 2000
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/ruby-slang/Makefile,v 1.1 2000/08/23 04:35:50 knu Exp $
#

MASTERDIR=	${.CURDIR}/../../devel/ruby-slang

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

COMMENT=	${.CURDIR}/pkg-comment

WITH_JAPANESE=	yes

.include "${MASTERDIR}/Makefile"
