#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-2.0-devel/files/openoffice-wrapper,v 1.13 2004/06/13 23:57:01 maho Exp $

oopath=%%PREFIX%%/%%INSTALLATION_BASEDIR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
