# New ports collection makefile for:   gtl
# Version required:    0.3.2
# Date created:        05 October 1999
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/misc/gtl/Makefile,v 1.1 1999/10/06 05:32:09 nakai Exp $
#

DISTNAME=	GTL-0.3.2
PKGNAME=	gtl-0.3.2
CATEGORIES=	misc
MASTER_SITES=	http://infosun.fmi.uni-passau.de/GTL/archive/

MAINTAINER=	nakai@FreeBSD.org

GNU_CONFIGURE=	yes
USE_NEWGCC=	yes

.include <bsd.port.mk>
