# New ports collection makefile for:   gtl
# Date created:        05 October 1999
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/misc/gtl/Makefile,v 1.2 2000/01/12 05:54:52 nakai Exp $
#

PORTNAME=	gtl
PORTVERSION=	0.3.2
CATEGORIES=	misc
MASTER_SITES=	http://infosun.fmi.uni-passau.de/GTL/archive/
DISTNAME=	GTL-${PORTVERSION}

MAINTAINER=	nakai@FreeBSD.org

GNU_CONFIGURE=	yes
USE_NEWGCC=	yes

.include <bsd.port.mk>
