# New ports collection makefile for:    xtacy
# Date created:         25 July 1996
# Whom:                 matt@bdd.net
#
# $FreeBSD: ports/x11/xtacy/Makefile,v 1.9 2000/04/15 12:57:39 imura Exp $
#

PORTNAME=	xtacy
PORTVERSION=	1.14
CATEGORIES=	x11
MASTER_SITES=	http://www.ultranet.com/~jjohnson/ \
		${MASTER_SITE_SUNSITE}
DISTNAME=	${PORTNAME}114

MAINTAINER=	matt@bdd.net

USE_IMAKE=	yes
MAN1=		xtacy.1

WRKSRC=		${WRKDIR}/Xtacy

.include <bsd.port.mk>
