# ex:ts=8
# New ports collection makefile for:	ebnf2yacc
# Date created:			Jul 3, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/devel/ebnf2yacc/Makefile,v 1.1 2001/07/02 17:33:46 ijliao Exp $
#

PORTNAME=	ebnf2yacc
PORTVERSION=	0.1.1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
