# New ports collection makefile for:   grap
# Date created:        4 February 2000
# Whom:                faber@lunabase.org
#
# $FreeBSD: ports/textproc/grap/Makefile,v 1.11 2001/02/05 16:34:39 olgeni Exp $
#

PORTNAME=	grap
PORTVERSION=	1.20
CATEGORIES=	textproc graphics
MASTER_SITES=	http://www.lunabase.org/~faber/Vault/software/grap/

MAINTAINER=	faber@lunabase.org

GNU_CONFIGURE=	yes

MAN1=		grap.1

.include <bsd.port.mk>
