# New ports collection makefile for:	snobol
# Date created:		Fri Sep  1 00:05:55 MDT 2000
# Whom:			Wes Peters <wes@softweyr.com>
#
# $FreeBSD: ports/lang/snobol/Makefile,v 1.1 2000/09/01 06:52:03 wes Exp $

PORTNAME=	snobol
PORTVERSION=	0.99.4
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.snobol4.com/

MAINTAINER=	wes@FreeBSD.org

MAN1= snobol4.1

.include <bsd.port.mk>
