# New ports collection makefile for:	wmitime
# Date created:		14 March 1999
# Whom:			Jim Mock <jim@FreeBSD.org>
#
# $FreeBSD: ports/x11-clocks/wmitime/Makefile,v 1.8 2000/08/12 07:43:11 kevlo Exp $
#

PORTNAME=	wmitime
PORTVERSION=	0.3
CATEGORIES=	x11-clocks windowmaker afterstep
MASTER_SITES=	http://www.neotokyo.org/illusion/downloads/

MAINTAINER=	jim@FreeBSD.org

WRKSRC=		${WRKDIR}/wmitime/wmitime

USE_X_PREFIX=	yes
USE_XPM=	yes

.include <bsd.port.mk>
