# New ports collection makefile for:	jvim3 for Canna and FreeWnn
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna+freewnn/Makefile,v 1.9 2000/04/11 14:14:12 knu Exp $
#

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
