# New ports collection makefile for:	jvim3 for Canna and Wnn4
# Version required:	3.0-1.7j
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna+wnn4/Makefile,v 1.6 1999/08/25 05:24:41 obrien Exp $
#

CANNA=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
