# New ports collection makefile for:	jvim3 for Canna and FreeWnn
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna+freewnn/Makefile,v 1.10 2000/09/08 04:34:36 taoka Exp $
#

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
