# New ports collection makefile for: xmail
# Date created:		15 July 1997
# Whom:			Stephen Roznowski <sjr1@flash.net>
#
# $FreeBSD: ports/mail/xmail/Makefile,v 1.10 2000/12/21 06:28:17 will Exp $
#

PORTNAME=	xmail
PORTVERSION=	1.6
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		xmail.1

.include <bsd.port.mk>
