# New ports collection makefile for:    freeze
# Date created:         20 Jul 1996
# Whom:                 lukin@okbmei.msk.su
#
# $FreeBSD: ports/archivers/freeze/Makefile,v 1.8 2001/01/16 17:30:00 sobomax Exp $
#

PORTNAME=	freeze
PORTVERSION=	2.5
PORTREVISION=	1
CATEGORIES=	archivers
MASTER_SITES=	ftp://ftp.freesoftware.com/pub/unixfreeware/archive/ \
		ftp://ftp.warwick.ac.uk/pub/compression/

MAINTAINER=	lukin@okbmei.msk.su

GNU_CONFIGURE=	yes
ALL_TARGET=	prog
MAN1=		freeze.1 melt.1 unfreeze.1 fcat.1 statist.1

.include <bsd.port.mk>
