# New ports collection makefile for:    freeze
# Date created:         20 Jul 1996
# Whom:                 lukin@okbmei.msk.su
#
# $FreeBSD: ports/archivers/freeze/Makefile,v 1.5 1999/08/25 04:25:05 obrien Exp $
#

PORTNAME=       freeze
PORTVERSION=	2.5
CATEGORIES=	archivers
MASTER_SITES=	ftp://ftp.cdrom.com/pub/unixfreeware/archive/ \
		ftp://ftp.warwick.ac.uk/pub/compression/

MAINTAINER=     lukin@okbmei.msk.su

GNU_CONFIGURE=	yes
ALL_TARGET=	prog
MAN1=		freeze.1 melt.1 unfreeze.1 fcat.1 statist.1

.include <bsd.port.mk>
