# $FreeBSD: ports/mbone/Makefile,v 1.14 2000/05/01 13:45:21 jseger Exp $
#
    SUBDIR += wbd

    SUBDIR += imm
    SUBDIR += nte
    SUBDIR += rat
    SUBDIR += rqm
    SUBDIR += rtpmon
    SUBDIR += rtptools
    SUBDIR += rqm
    SUBDIR += sdr
    SUBDIR += speak_freely
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb

.include <bsd.port.subdir.mk>
