# $FreeBSD: ports/mbone/Makefile,v 1.17 2001/06/07 02:21:29 kiri Exp $
#

    SUBDIR += imm
    SUBDIR += nte
    SUBDIR += rat
    SUBDIR += rat30
    SUBDIR += relate
    SUBDIR += rqm
    SUBDIR += rtpmon
    SUBDIR += rtptools
    SUBDIR += sdr
    SUBDIR += speak_freely
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb
    SUBDIR += wbd

.include <bsd.port.subdir.mk>
