# $FreeBSD: ports/mbone/Makefile,v 1.15 2001/05/11 19:31:03 assar Exp $
#
    SUBDIR += wbd

    SUBDIR += imm
    SUBDIR += nte
    SUBDIR += rat
    SUBDIR += rat30
    SUBDIR += rqm
    SUBDIR += rtpmon
    SUBDIR += rtptools
    SUBDIR += rqm
    SUBDIR += sdr
    SUBDIR += speak_freely
    SUBDIR += vat
    SUBDIR += vic
    SUBDIR += wb

.include <bsd.port.subdir.mk>
