# New ports collection makefile for: zh Big5/GB-ized Netcape
# Date created:		23 Oct 2000
# Whom:			Jing-Tang Keith Jang <keith@FreeBSD.org>
#
# $FreeBSD: ports/chinese/netscape47-navigator/Makefile,v 1.1 2000/11/02 03:45:04 foxfair Exp $
#

BROWSER=	navigator

MASTERDIR=	${.CURDIR}/../netscape47-communicator
.include	"${.CURDIR}/../netscape47-communicator/Makefile"
