# New ports collection makefile for:	navi2ch for xemacs21-mule
# Date created:		13 May 2001
# Whom:			FUJISHIMA Satsuki <sf@FreeBSD.org>
#
# $FreeBSD: ports/japanese/navi2ch-xemacs21-mule/Makefile,v 1.4 2001/06/02 22:03:10 sf Exp $
#

MASTERDIR=	${.CURDIR}/../navi2ch-emacs20

EMACS_PORT_NAME=	xemacs21-mule

RUN_DEPENDS=		${X11BASE}/lib/X11/fonts/local/monak12.pcf.gz:${PORTSDIR}/japanese/monafonts

.include <${MASTERDIR}/Makefile>
