# New ports collection makefile for:	hexcalc
# Version required:	1.11 (taken from sccsid in hexcalc.c)
# Date created:		5 December 1994
# Whom:			asami
#
# $FreeBSD: ports/math/hexcalc/Makefile,v 1.10 1999/08/25 07:10:41 obrien Exp $
#

DISTNAME=	hexcalc
PKGNAME=	hexcalc-1.11
CATEGORIES=	math
MASTER_SITES=	ftp://aixpdslib.seas.ucla.edu/pub/hexcalc/RISC/3.2/src/
EXTRACT_SUFX=	..tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		hexcalc.1

.include <bsd.port.mk>
