# New ports collection makefile for:	hexcalc
# Date created:		5 December 1994
# Whom:			asami
#
# $FreeBSD: ports/math/hexcalc/Makefile,v 1.12 2000/04/14 07:20:11 asami Exp $
#

PORTNAME=	hexcalc
PORTVERSION=	1.11
CATEGORIES=	math
MASTER_SITES=	ftp://aixpdslib.seas.ucla.edu/pub/hexcalc/RISC/3.2/src/
DISTNAME=	${PORTNAME}
EXTRACT_SUFX=	..tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		hexcalc.1

.include <bsd.port.mk>
