# New ports collection makefile for:	p5-PDF-Create
# Date created:				20 January 2001
# Whom:					petef@databits.net
#
# $FreeBSD: ports/textproc/p5-PDF-Create/Makefile,v 1.1 2001/03/10 20:51:44 will Exp $
#

PORTNAME=	PDF-Create
PORTVERSION= 	0.01
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File/FTASSIN
PKGNAMEPREFIX=	p5-

MAINTAINER=     petef@FreeBSD.org

PERL_CONFIGURE=	yes
MAN3=		PDF::Create.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
