# New ports collection makefile for:   kproject
# Date created:        23 May 1998
# Whom:                Hans Petter Bieker <hanspb@persbraten.vgs.no>
#
# $FreeBSD: ports/deskutils/kproject/Makefile,v 1.14 2001/04/03 08:13:59 will Exp $
#

PORTNAME=	kproject
PORTVERSION=	0.1
CATEGORIES=	deskutils kde
MASTER_SITES=	$(MASTER_SITE_KDE)
MASTER_SITE_SUBDIR= unstable/apps/office
EXTRACT_SUFX=	.tgz

USE_LIBTOOL=	yes
USE_KDELIBS_VER=1
WRKSRC=		${WRKDIR}/kproject

.include <bsd.port.mk>
