# New ports collection makefile for:	Wanderlust (for xemacs-mule)
# Date created:		7 Apr 1999
# Whom: 		MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/mail/wanderlust-xemacs21-mule/Makefile,v 1.6 2000/02/18 23:17:19 taoka Exp $
#

MAINTAINER=	nobutaka@nobutaka.com

MASTERDIR=	${.CURDIR}/../../mail/wanderlust-emacs

EMACS_NAME=		xemacs
EMACS_PORT=		xemacs21-mule
EMACS_VER=		21.1.9
MULE_VER=		21.1.9
EMACS_LIBDIR=		lib/xemacs
EMACS_PACKAGESDIR=	lib/xemacs/site-packages
MANIFEST=		MANIFEST.wl

HAVE_COMMON_PORT=	yes

IS_SLAVE=		yes

.include <${MASTERDIR}/Makefile>
