# New ports collection makefile for:	Wanderlust (for xemacs21-mule)
# Date created:		7 Apr 1999
# Whom: 		MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/mail/wanderlust-xemacs21-mule/Makefile,v 1.8 2000/04/19 06:52:38 knu Exp $
#

MAINTAINER=	nobutaka@nobutaka.com

MASTERDIR=	${.CURDIR}/../../mail/wanderlust-emacs

EMACS_PORT_NAME=	xemacs21-mule
EMACS_PACKAGESDIR=	lib/xemacs/site-packages
MANIFEST=		MANIFEST.wl

IS_SLAVE=		yes

.include <${MASTERDIR}/Makefile>
