# New ports collection makefile for:	Authen-Ticket
# Date created:				Mon Jan  1 03:55:39 2001
# Whom:					will
#
# $FreeBSD: ports/security/p5-Authen-Ticket/Makefile,v 1.1 2001/01/01 09:02:18 will Exp $
#

PORTNAME=	Authen-Ticket
PORTVERSION=	0.02
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Authen
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
