# New ports collection makefile for:	mule with Canna and FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+freewnn/Makefile,v 1.8 2000/04/14 16:47:42 knu Exp $
#

PKGNAMESUFFIX=	-canna+freewnn
CATEGORIES=	japanese

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
