# New ports collection makefile for:	mule 2.3@19.34 with Canna and Wnn4
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+wnn4/Makefile,v 1.7 2000/04/11 14:15:19 knu Exp $
#

PKGNAMESUFFIX=	-canna+wnn4
CATEGORIES=	japanese

CANNA=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
