# New ports collection makefile for:	mule with Canna and FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+freewnn/Makefile,v 1.9 2000/09/08 04:34:40 taoka Exp $
#

PKGNAMESUFFIX=	-canna+freewnn
CATEGORIES=	japanese

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
