# New ports collection makefile for:	newsfish
# Version required:	1.1
# Date created:		17 January 1999
# Whom:			asaddi@philosophysw.com
#
# $FreeBSD: ports/news/newsfish/Makefile,v 1.3 1999/08/30 14:31:43 peter Exp $
#

DISTNAME=	newsfish-1.1
CATEGORIES=	news
MASTER_SITES=	http://www.philosophysw.com/download/

MAINTAINER=	asaddi@philosophysw.com

MAN1=		newsfish.1

.include <bsd.port.mk>
