# New ports collection makefile for:	newsfish
# Date created:		17 January 1999
# Whom:			asaddi@philosophysw.com
#
# $FreeBSD: ports/news/newsfish/Makefile,v 1.8 2001/05/27 15:23:17 kevlo Exp $
#

PORTNAME=	newsfish
PORTVERSION=	1.2.5
CATEGORIES=	news
MASTER_SITES=	http://download.sourceforge.net/newsfish/ \
		ftp://ftp.philosophysw.com/pub/software/

MAINTAINER=	asaddi@philosophysw.com

USE_AUTOMAKE=	yes
USE_GMAKE=	yes

MAN1=		newsfish.1

.include <bsd.port.mk>
