# New ports collection makefile for:	newsfish
# Date created:		17 January 1999
# Whom:			asaddi@philosophysw.com
#
# $FreeBSD: ports/news/newsfish/Makefile,v 1.5 2000/01/31 23:37:55 jedgar Exp $
#

PORTNAME=	newsfish
PORTVERSION=	1.2
CATEGORIES=	news
MASTER_SITES=	http://www.philosophysw.com/download/

MAINTAINER=	asaddi@philosophysw.com

MAN1=		newsfish.1

.include <bsd.port.mk>
