# New ports collection makefile for:	choparp
# Date created:		7 October 1997
# Whom:			itojun@itojun.org
#
# $FreeBSD: ports/net/choparp/Makefile,v 1.4 2000/04/09 18:10:24 cpiazza Exp $
#

PORTNAME=	choparp
PORTVERSION=	971007
CATEGORIES=	net
MASTER_SITES=	http://delegate.uec.ac.jp:8081/club/mma/~tree/soft/choparp/

MAINTAINER=	ports@freebsd.org

MAN8=		choparp.8
MANCOMPRESSED=	maybe

WRKSRC=		${WRKDIR}/choparp

.include <bsd.port.mk>
