# New ports collection makefile for:	mule 2.3@19.34 with sj3 and Wnn4
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-sj3+wnn4/Makefile,v 1.7 2000/04/11 14:15:22 knu Exp $
#

PKGNAMESUFFIX=	-sj3+wnn4
CATEGORIES=	japanese

SJ3=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
