# New ports collection makefile for:	mule with sj3 and FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-freewnn+sj3/Makefile,v 1.9 2000/09/08 04:34:47 taoka Exp $
#

PKGNAMESUFFIX=	-freewnn+sj3
CATEGORIES=	japanese

SJ3=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
