# New ports collection makefile for:	sic
# Date created:		04 Apr 1998
# Whom:			sec@42.org
#
# $FreeBSD: ports/irc/sic/Makefile,v 1.6 2000/04/12 06:28:27 obrien Exp $
#

PORTNAME=	sic
PORTVERSION=	0.22a
CATEGORIES=	irc
MASTER_SITES=	ftp://ftp.funet.fi/pub/unix/irc/sic/
EXTRACT_SUFX=	.tgz

MAINTAINER=	sec@42.org

GNU_CONFIGURE=	yes

MAN1=		sic.1
MAN5=		sic-alias.5 sic-server.5

.include <bsd.port.mk>
