# New ports collection makefile for:	dejagnu
# Date created:		12 October 1996
# Whom:			markm
#
# $FreeBSD: ports/misc/dejagnu/Makefile,v 1.14 2001/03/31 23:15:06 obrien Exp $
#

PORTNAME=	dejagnu
PORTVERSION=	1.4.1
CATEGORIES=	misc tcl83 tk83
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	dejagnu

MAINTAINER=	ports@FreeBSD.org

RUN_DEPENDS=	expect:${PORTSDIR}/lang/expect

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
