# New ports collection makefile for:	xdu
# Date created:		9 February 1995
# Whom:			asami
#
# $FreeBSD: ports/sysutils/xdu/Makefile,v 1.13 2000/04/22 10:13:55 mharo Exp $
#

PORTNAME=	xdu
PORTVERSION=	3.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://sd.wareonearth.com/~phil/xdu/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_IMAKE=	yes
MAN1=		xdu.1

.include <bsd.port.mk>
