# New ports collection makefile for:	xdu
# Date created:		9 February 1995
# Whom:			asami
#
# $FreeBSD: ports/sysutils/xdu/Makefile,v 1.12 2000/04/09 19:09:00 cpiazza Exp $
#

PORTNAME=	xdu
PORTVERSION=	3.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.arl.mil/pub/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_IMAKE=	yes
MAN1=		xdu.1

.include <bsd.port.mk>
