# New ports collection makefile for:	xdu
# Version required:	R6 contrib tape
# Date created:		9 February 1995
# Whom:			asami
#
# $FreeBSD: ports/sysutils/xdu/Makefile,v 1.10 1999/08/31 02:00:29 peter Exp $
#

DISTNAME=	xdu-3.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.arl.mil/pub/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_IMAKE=	yes
MAN1=		xdu.1

.include <bsd.port.mk>
