# New ports collection makefile for:   jpilot (japanized)
# Date created:        Tue Aug 31 23:23:00 JST 1999
# Whom:                sumikawa
#
# $FreeBSD: ports/japanese/jpilot/Makefile,v 1.6 2000/03/05 14:00:28 sumikawa Exp $
#

MASTERDIR=	${.CURDIR}/../../palm/jpilot
COMMENT=	${.CURDIR}/pkg/COMMENT

CATEGORIES=	japanese

MAINTAINER=	sumikawa@FreeBSD.org

CONFIGURE_ARGS=	--with-japanese

.include "${MASTERDIR}/Makefile"
