# New ports collection makefile for:   jpilot (japanized)
# Version required:    0.98
# Date created:        Tue Aug 31 23:23:00 JST 1999
# Whom:                sumikawa
#
# $FreeBSD: ports/japanese/jpilot/Makefile,v 1.5 1999/12/25 15:58:45 sumikawa Exp $
#

MASTERDIR=	${.CURDIR}/../../palm/jpilot
COMMENT=	${.CURDIR}/pkg/COMMENT

PKGNAME=	ja-jpilot-0.98
CATEGORIES=	japanese

MAINTAINER=	sumikawa@FreeBSD.org

CONFIGURE_ARGS=	--with-japanese

.include "${MASTERDIR}/Makefile"
