# New ports collection makefile for:   jpilot (japanized)
# Version required:    0.96
# Date created:        Tue Aug 31 23:23:00 JST 1999
# Whom:                sumikawa
#
# $FreeBSD: ports/japanese/jpilot/Makefile,v 1.3 1999/09/10 17:35:46 sumikawa Exp $
#

MASTERDIR=	${.CURDIR}/../../palm/jpilot
COMMENT=	${.CURDIR}/pkg/COMMENT

PKGNAME=	ja-jpilot-0.96
CATEGORIES=	japanese

MAINTAINER=	sumikawa@kame.net

CONFIGURE_ARGS=	--with-japanese

.include "${MASTERDIR}/Makefile"
