# New ports collection makefile for:	mailcrypt
# Date created:        29 May 1998
# Whom:                Murray Stokely <murray@cdrom.com>
#
# $FreeBSD: ports/mail/mailcrypt/Makefile,v 1.8 2001/01/25 15:29:44 murray Exp $
#

PORTNAME=	mailcrypt
PORTVERSION=	3.5.5
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=    apps/crypto

MAINTAINER=	murray@FreeBSD.org

BUILD_DEPENDS=	emacs:${PORTSDIR}/editors/emacs20

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
