# New ports collection makefile for:	mailcrypt
# Date created:        29 May 1998
# Whom:                Murray Stokely <murray@cdrom.com>
#
# $FreeBSD: ports/mail/mailcrypt/Makefile,v 1.5 1999/12/23 18:00:24 steve Exp $
#

PORTNAME=	mailcrypt
PORTVERSION= 	3.5.5
CATEGORIES=	mail
MASTER_SITES=	http://www.nb.net/~lbudney/linux/software/mailcrypt/

MAINTAINER=	murray@cdrom.com

BUILD_DEPENDS=	emacs:${PORTSDIR}/editors/emacs20

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
