# New ports collection makefile for:    xblackjack
# Version required:     2.2
# Date created:         8/16/1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/games/xblackjack/Makefile,v 1.8 1999/08/25 06:04:46 obrien Exp $
#

DISTNAME=	xblackjack-2.2
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	erich@FreeBSD.org

REQUIRES_MOTIF=	yes
USE_IMAKE=	yes
MAN1=		xblackjack.1

.include <bsd.port.mk>
