# New ports collection makefile for:    xblackjack
# Date created:         8/16/1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/games/xblackjack/Makefile,v 1.10 2000/04/14 12:27:01 asami Exp $
#

PORTNAME=	xblackjack
PORTVERSION=	2.2
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

REQUIRES_MOTIF=	yes
USE_IMAKE=	yes
MAN1=		xblackjack.1

.include <bsd.port.mk>
