# New ports collection makefile for:	xbatt
# Date created:		2 May 1995
# Whom:			Nobuhiro Yasutomi <nobu@psrc.isac.co.jp>
#
# $FreeBSD: ports/sysutils/xbatt/Makefile,v 1.10 2000/04/09 19:08:57 cpiazza Exp $
#

PORTNAME=	xbatt
PORTVERSION=	1.2.1
CATEGORIES=	sysutils
MASTER_SITES=	http://www.clave.gr.jp/~eto/xbatt/

MAINTAINER=	nobu@psrc.isac.co.jp

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

ONLY_FOR_ARCHS=	i386

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
