# New ports collection makefile for:	wmavgload
# Date created:		20 July 1998
# Whom:			Vladimir Kushnir <kushn@mail.kar.net>
#
# $FreeBSD: ports/sysutils/wmavgload/Makefile,v 1.9 2000/08/03 09:26:27 asami Exp $
#

PORTNAME=	wmavgload
PORTVERSION=	0.7.0
CATEGORIES=	sysutils windowmaker
MASTER_SITES=	${MASTER_SITE_WINDOWMAKER}
MASTER_SITE_SUBDIR=	contrib/srcs/utils

MAINTAINER=	anders@fix.no

USE_IMAKE=	yes
USE_XPM=	yes
NO_INSTALL_MANPAGES=	yes
ALL_TARGET=	wmavgload

.include <bsd.port.mk>
