# New ports collection makefile for:    wmavgload
# Date created:         20 July 1998
# Whom:                 Vladimir Kushnir <kushn@mail.kar.net>
#
# $FreeBSD: ports/sysutils/wmavgload/Makefile,v 1.5 1999/08/31 02:00:21 peter Exp $
#

PORTNAME=	wmavgload
PORTVERSION= 	0.7.0
CATEGORIES=	sysutils windowmaker
MASTER_SITES=	ftp://ftp.windowmaker.org/pub/contrib/srcs/utils/

MAINTAINER=	kushn@mail.kar.net

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=      	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
