# New ports collection makefile for:	wmavgload
# Date created:		20 July 1998
# Whom:			Vladimir Kushnir <kushn@mail.kar.net>
#
# $FreeBSD: ports/sysutils/wmavgload/Makefile,v 1.8 2000/06/23 13:50:15 sobomax Exp $
#

PORTNAME=	wmavgload
PORTVERSION=	0.7.0
CATEGORIES=	sysutils windowmaker
MASTER_SITES=	${MASTER_SITE_WINDOWMAKER}
MASTER_SITE_SUBDIR=	contrib/srcs/utils

MAINTAINER=	kushn@mail.kar.net

USE_IMAKE=	yes
USE_XPM=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
