# New ports collection makefile for:    icqlib
# Date created:                         16 March 1999
# Whom:                                 Pavel Andreev
#
# $FreeBSD: ports/net/icqlib/Makefile,v 1.8 2000/06/16 21:51:45 asami Exp $
#

PORTNAME=	icqlib
PORTVERSION=	0.1.3
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	lioux@uol.com.br

INSTALLS_SHLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
