# New ports collection makefile for:    icqlib
# Version required:                     0.1.3
# Date created:                         16 March 1999
# Whom:                                 Pavel Andreev
#
# $FreeBSD: ports/net/icqlib/Makefile,v 1.3 1999/08/30 14:22:59 peter Exp $
#

DISTNAME=	icqlib-0.1.3
CATEGORIES=	net
MASTER_SITES=	http://download.sourceforge.net/icqlib/

MAINTAINER=	paxvel@iname.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
