# New ports collection makefile for:    tkhfs
# Date created:         17 November 1994
# Whom:                 jmz
#
# $FreeBSD: ports/emulators/tkhfs/Makefile,v 1.19 1999/09/08 00:17:04 jmz Exp $
#

PORTNAME=	tkhfs
PORTVERSION=	1.27
CATEGORIES=	emulators tk82
MASTER_SITES=	ftp://ftp.obs-besancon.fr/pub/outgoing/
DISTNAME=	${PORTNAME}

MAINTAINER=	jmz@FreeBSD.org

RUN_DEPENDS=	hfs:${PORTSDIR}/emulators/hfs \
		wish8.2:${PORTSDIR}/x11-toolkits/tk82

.include <bsd.port.mk>
