# New ports collection makefile for:    tkhfs
# Date created:         17 November 1994
# Whom:                 jmz
#
# $FreeBSD: ports/emulators/tkhfs/Makefile,v 1.21 2000/06/11 17:30:28 jmz Exp $
#

PORTNAME=	tkhfs
PORTVERSION=	1.27
CATEGORIES=	emulators tk82
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	jmz
DISTNAME=	${PORTNAME}

MAINTAINER=	jmz@FreeBSD.org

RUN_DEPENDS=	hfs:${PORTSDIR}/emulators/hfs \
		wish8.2:${PORTSDIR}/x11-toolkits/tk82

.include <bsd.port.mk>
