# New ports collection makefile for:    p5-Proc-Simple
# Date created:				June 26th 1997
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Proc-Simple/Makefile,v 1.11 2000/11/15 10:51:02 demon Exp $
#

PORTNAME=	Proc-Simple
PORTVERSION=	1.16
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Proc
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Proc::Simple.3

.include <bsd.port.mk>
