# New ports collection makefile for:	mule with sj3 and Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-sj3+wnn6/Makefile,v 1.9 2000/04/14 16:47:46 knu Exp $
#

PKGNAMESUFFIX=	-sj3+wnn6
CATEGORIES=	japanese

SJ3=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
