# New ports collection makefile for:	mule 2.3@19.34 with sj3 and Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-sj3+wnn6/Makefile,v 1.7 1999/08/25 05:25:42 obrien Exp $
#

PKGNAMESUFFIX=	-sj3+wnn6
CATEGORIES=	japanese editors

SJ3=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
