# New ports collection makefile for:	ruby_static-devel
# Date created:			3 June 2001
# Whom:				Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/lang/ruby_static-devel/Makefile,v 1.1 2001/06/04 14:57:03 knu Exp $
#

MASTERDIR=      ${.CURDIR}/../ruby_static

RUBY_VER=	1.7

HAVE_FNMATCH=	yes

.include "${MASTERDIR}/Makefile"
