# New ports collection makefile for:	xmbdfed
# Date created:		June 20, 1997
# Whom:			jfieber
#
# $FreeBSD: ports/x11-fonts/xmbdfed/Makefile,v 1.20 2000/11/07 23:28:18 asami Exp $
#

PORTNAME=	xmbdfed
PORTVERSION=	4.4
CATEGORIES=	x11-fonts
MASTER_SITES=	ftp://crl.nmsu.edu/CLR/multiling/General/

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
USE_FREETYPE=	yes
USE_MOTIF=	yes

MAN1=		xmbdfed.1

.include <bsd.port.mk>
