# $FreeBSD: ports/deskutils/Makefile,v 1.24 2000/05/01 03:07:41 steve Exp $
#

    SUBDIR += abacus
    SUBDIR += bulb
    SUBDIR += cal
    SUBDIR += cbb
    SUBDIR += gaddr
    SUBDIR += genius
    SUBDIR += gnofin
    SUBDIR += gnomepim
    SUBDIR += gnucash
    SUBDIR += gtimer
    SUBDIR += gvid
    SUBDIR += ical
    SUBDIR += korganizer
    SUBDIR += korganizer11-i18n
    SUBDIR += kproject
    SUBDIR += moneydance
    SUBDIR += offix-trash
    SUBDIR += plan
    SUBDIR += sliderule
    SUBDIR += teapot
    SUBDIR += wmpinboard
    SUBDIR += wpeople
    SUBDIR += xinvest
    SUBDIR += xmaddressbook
    SUBDIR += xmdiary
    SUBDIR += xopps
    SUBDIR += xpostit
    SUBDIR += xpostitPlus
    SUBDIR += xrolo
    SUBDIR += xwrits
    SUBDIR += yank
    SUBDIR += zorro

.include <bsd.port.subdir.mk>
