# $FreeBSD: ports/deskutils/Makefile,v 1.43 2001/03/30 21:09:37 olgeni Exp $
#

    SUBDIR += abacus
    SUBDIR += aspostit
    SUBDIR += bigyear
    SUBDIR += bitnotes
    SUBDIR += bulb
    SUBDIR += cal
    SUBDIR += cbb
    SUBDIR += gaddr
    SUBDIR += gcal
    SUBDIR += genius
    SUBDIR += gnofin
    SUBDIR += gnomepim
    SUBDIR += gnucash
    SUBDIR += gtimer
    SUBDIR += ical
    SUBDIR += ithought
    SUBDIR += kdepim
    SUBDIR += korganizer
    SUBDIR += kproject
    SUBDIR += loserjabber
    SUBDIR += moneydance
    SUBDIR += notebook
    SUBDIR += offix-trash
    SUBDIR += phpgroupware
    SUBDIR += phpgw_inventory
    SUBDIR += phpgw_projects
    SUBDIR += plan
    SUBDIR += sliderule
    SUBDIR += teapot
    SUBDIR += wmpinboard
    SUBDIR += xcalendar
    SUBDIR += xinvest
    SUBDIR += xmaddressbook
    SUBDIR += xmdiary
    SUBDIR += xopps
    SUBDIR += xpostit
    SUBDIR += xpostitPlus
    SUBDIR += xrolo
    SUBDIR += xwrits
    SUBDIR += yank
    SUBDIR += zorro

.include <bsd.port.subdir.mk>
