# New ports collection makefile for:  movemail
# Version required:    1.0
# Date created:        1997/09/09
# Whom:                wosch
#
# $FreeBSD: ports/mail/movemail/Makefile,v 1.4 1999/08/31 06:47:30 mharo Exp $
#

DISTNAME=      movemail-1.0
CATEGORIES=    mail
MASTER_SITES=  http://www.de.freebsd.org/~wosch/src/

MAINTAINER=    wosch@FreeBSD.org

MAN1=		movemail.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
