# New ports collection makefile for:  movemail
# Date created:        1997/09/09
# Whom:                wosch
#
# $FreeBSD: ports/mail/movemail/Makefile,v 1.5 1999/09/19 10:30:44 wosch Exp $
#

PORTNAME=	movemail
PORTVERSION= 	1.0
CATEGORIES=    mail
MASTER_SITES=  http://www.de.freebsd.org/~wosch/src/

MAINTAINER=    wosch@FreeBSD.org

MAN1=		movemail.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
