# New ports collection makefile for:  movemail
# Date created:        1997/09/09
# Whom:                wosch
#
# $FreeBSD: ports/mail/movemail/Makefile,v 1.6 2000/04/13 20:00:11 cpiazza Exp $
#

PORTNAME=	movemail
PORTVERSION=	1.0
CATEGORIES=	mail
MASTER_SITES=	http://www.de.freebsd.org/~wosch/src/

MAINTAINER=	wosch@FreeBSD.org

MAN1=		movemail.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
