# New ports collection makefile for:   bottlerocket
# Date created:        15 July 1999
# Whom:                Mike Smith <msmith@freebsd.org>
#
# $FreeBSD: ports/misc/bottlerocket/Makefile,v 1.3 1999/12/28 20:27:22 billf Exp $
#

PORTNAME=	bottlerocket
PORTVERSION=	0.04c
CATEGORIES=	misc
MASTER_SITES=	http://mlug.missouri.edu/~tymm/

MAINTAINER=	msmith@freebsd.org

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
ALL_TARGET=	br

.include <bsd.port.mk>
