# New ports collection makefile for: elftoaout
# Date created:         3 Jul 1998
# Whom:                 kchowksey@hss.hns.com
#
# $FreeBSD: ports/devel/elftoaout/Makefile,v 1.3 2000/04/11 21:27:49 mharo Exp $
#

PORTNAME=	elftoaout
PORTVERSION=	2.0
CATEGORIES=	devel
MASTER_SITES=   ftp://sunsite.mff.cuni.cz/OS/Linux/Sparc/local/ultra/
EXTRACT_SUFX=	.tgz

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/elftoaout ${PREFIX}/bin

.include <bsd.port.mk>
