# New ports collection makefile for:	joe
# Date created:		01 Jul 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/editors/joe/Makefile,v 1.7 2000/03/22 01:59:05 will Exp $
#

PORTNAME=	joe
PORTVERSION=	2.8
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.std.com/src/editors/
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	will@FreeBSD.org

WRKSRC=		${WRKDIR}/joe
ALL_TARGET=	joe
MAN1=		joe.1

.include <bsd.port.mk>
