# New ports collection makefile for:	python-doc-postscript-a4
# Date created:		02 June 1999
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/lang/python-doc-postscript-a4/Makefile,v 1.3 1999/09/10 18:58:20 peter Exp $
#

DOCFORMAT=	postscript-a4
MASTERDIR=	${.CURDIR}/../python-doc-html

.include "${MASTERDIR}/Makefile"
