# New ports collection makefile for: cd-console
# Date created:		Sun Nov 28 19:55:19 EST 1999
# Whom:			jdunn@aquezada.com
#
# $FreeBSD: ports/audio/cd-console/Makefile,v 1.2 2000/04/08 21:23:20 mharo Exp $
#

PORTNAME=	cd-console
PORTVERSION=	2.3
CATEGORIES=	audio
MASTER_SITES=	http://www.cs.helsinki.fi/~salerma/cd-console/ \
		ftp://ftp.aquezada.com/pub/distrib/cd-console/

MAINTAINER=	jdunn@aquezada.com

.include <bsd.port.mk>
