# New ports collection makefile for:	pscal
# Date created:			Apr 16, 2001
# Whom:				Mark Pulford <mark@kyne.com.au>
#
# $FreeBSD: ports/print/pscal/Makefile,v 1.1 2001/04/16 14:06:13 ijliao Exp $
#

PORTNAME=	pscal
PORTVERSION=	1.13
CATEGORIES=	print
MASTER_SITES=	http://www.panix.com/~mbh/pscal/

MAINTAINER=	markp@FreeBSD.org

NO_BUILD=	yes

do-install:
	${INSTALL_SCRIPT} ${WRKSRC}/pscal ${PREFIX}/bin

.include <bsd.port.mk>
