# New ports collection makefile for:	hunt
# Date created:				2001-02-20
# Whom:					bdluevel@heitec.net
#
# $FreeBSD: ports/games/44bsd-hunt/Makefile,v 1.1 2001/03/25 06:37:19 will Exp $

PORTNAME=	hunt
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.heitec.net/pub/distfiles/

MAINTAINER=	bdluevel@heitec.net

MAN6=	hunt.6 huntd.6

.include <bsd.port.mk>
