# New ports collection makefile for:	webalizer2
# Date created:		02.Jun 1998
# Whom:			dirk.meyer@dinoex.sub.org
#
# $FreeBSD: ports/german/webalizer2/Makefile,v 1.23 2001/03/21 19:38:24 dinoex Exp $

PKGNAMEPREFIX?=	de-
MASTERDIR?=	${.CURDIR}/../../www/webalizer
CATEGORIES=	german
WEBALIZER_LANG=	german

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
