# New ports collection makefile for:   xdvik + jp-patch
# Date created:        15 Jun 1998
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/xdvik-vflib-pk600/Makefile,v 1.13 2000/04/13 08:33:41 knu Exp $
#

RUN_DEPENDS=	${LOCALBASE}/share/texmf/fonts/pk/${MF_MODE}/pk${BDPI}:${PORTSDIR}/japanese/ptex-pkfonts${BDPI}

FONTTYPE=	pkfont
USEPK_MODE=	ljfour
BDPI=		600
SHRINK=		8
MASTERDIR=	${.CURDIR}/../xdvik-vflib

.include	"${MASTERDIR}/Makefile"
