# New ports collection makefile for:	php3
# Date created:		Mon Feb 26 12:20:25 CET 2001
# Whom:			Dirk Froemberg <dirk@FreeBSD.org>
#
# $FreeBSD: ports/lang/php3/Makefile,v 1.1 2001/03/04 18:32:15 dirk Exp $
#

PORTNAME=	php3
CATEGORIES=	lang

MASTERDIR=	${.CURDIR}/../../www/mod_php3
COMMENT=	${PKGDIR}/pkg-comment.standalone
PKGMESSAGE=	mustnotexist
PLIST=		${PKGDIR}/pkg-plist.standalone

STANDALONE=	yes

.include "${MASTERDIR}/Makefile"
