# New ports collection makefile for:	gnome-vnc
# Date created:			Sun Jul 18 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/net/gnome-vnc/Makefile,v 1.3 2000/04/09 18:11:27 cpiazza Exp $
#

PORTNAME=	gnome-vnc
PORTVERSION=	0.1
CATEGORIES= 	net gnome
MASTER_SITES=	ftp://ftp.daa.com.au/pub/james/gnome/

MAINTAINER=	domi@saargate.de

LIB_DEPENDS=	gnome.4:${PORTSDIR}/x11/gnomelibs

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
