# New ports collection makefile for:	gnome-vnc
# Date created:			Sun Jul 18 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/net/gnome-vnc/Makefile,v 1.5 2001/02/05 15:50:39 olgeni Exp $
#

PORTNAME=	gnome-vnc
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	net gnome
MASTER_SITES=	ftp://ftp.daa.com.au/pub/james/gnome/

MAINTAINER=	domi@saargate.de

USE_GNOMELIBS=	yes
USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
