# New ports collection makefile for:	xcopilot
# Date created:			July 17 1997
# Whom:				Nick Sayer <nsayer@quack.kfu.com>
#
# $FreeBSD: ports/palm/xcopilot/Makefile,v 1.13 2000/11/16 17:45:43 nsayer Exp $
#

PORTNAME=	xcopilot
PORTVERSION=	0.6.6
CATEGORIES=	palm emulators
MASTER_SITES=	http://xcopilot.cuspy.com/build/

MAINTAINER=	ports@freebsd.org

USE_X_PREFIX=	yes
USE_XPM=	yes
USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		xcopilot.1

.include <bsd.port.mk>
