# New ports collection makefile for:	roottail
# Date created:			30 September 1999
# Whom:				Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/sysutils/roottail/Makefile,v 1.6 2000/11/15 00:11:18 jedgar Exp $
#

PORTNAME=	roottail
PORTVERSION=	0.0.10
CATEGORIES=	sysutils
MASTER_SITES=	http://www.goof.com/pcg/marc/data/ \
		ftp://ftp.goof.com/pub/pcg/marc/
DISTNAME=	root-tail-${PORTVERSION}

MAINTAINER=	jedgar@FreeBSD.org

MAN1=		root-tail.1
USE_IMAKE=	yes
MANCOMPRESSED=	no

.include <bsd.port.mk>
