# New ports collection makefile for:	p5-Config-IniFiles
# Date created:				October 21st 1996
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Config-IniFiles/Makefile,v 1.17 2000/12/03 18:15:39 will Exp $
#

PORTNAME=	Config-IniFiles
PORTVERSION=	2.13
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Config
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeremy@external.org

USE_PERL5=	YES
PERL_CONFIGURE=	YES

MAN3=		Config::IniFiles.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
