# New ports collection makefile for:	sh-rtems-gdb
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sh-rtems-gdb/Makefile,v 1.1 2000/07/10 04:32:30 steve Exp $
#

PORTNAME=	gdb

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sh-rtems
CONFIGURE_ARGS=	--verbose --enable-sim
.include "${.CURDIR}/../i386-rtems-gdb/Makefile"
