# New ports collection makefile for:	jvim3 for Wnn4
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-wnn4/Makefile,v 1.8 2000/02/07 16:40:35 taoka Exp $
#

WNN4=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
