# New ports collection makefile for:	jvim3 for FreeWnn
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-freewnn/Makefile,v 1.9 2000/04/11 14:14:15 knu Exp $
#

FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
