# New ports collection makefile for: ja-tcsh NLS catalog (Koshiki Yukari)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-koshiki/Makefile,v 1.9 2000/04/12 14:37:53 knu Exp $
#

CATALOGNAME=	koshiki

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

.include	"${MASTERDIR}/Makefile"
