# New ports collection makefile for:	p5-File-CounterFile
# Date created:				Jan 28 2000
# Whom:					Wei-chun Chao
#
# $FreeBSD: ports/misc/p5-File-CounterFile/Makefile,v 1.1 2000/06/30 01:05:40 will Exp $
#

PORTNAME=	File-CounterFile
PORTVERSION=	0.12
CATEGORIES=	misc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=	p5-

MAINTAINER=	wchao@isi.edu

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		File::CounterFile.3

.include <bsd.port.mk>
