#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.7 2003/04/16 06:51:35 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org-%%BUILD_NR%%/program/
program=`echo $0 | sed -e 's|.*-||'`

if [ ! $LANG ]; then
	export LANG=%%LANG%%
fi

if [ -e $HOME/OpenOffice.org1.1/setup.log ]; then
	if [ ! -e $HOME/OpenOffice.org1.1/user/config/soffice.cfg ]; then
		touch $HOME/OpenOffice.org1.1/user/config/soffice.cfg
	fi
fi

case $program in
$0)
	cd $oopath && ./soffice "$@"
	;;
	*)
	cd $oopath && exec ./$program "$@"
	;;
esac
