# New ports collection makefile for:    p5-Term-ReadKey
# Date created:				June 26th 1997
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Term-ReadKey/Makefile,v 1.13 2000/11/13 12:43:36 demon Exp $
#

PORTNAME=	Term-ReadKey
PORTVERSION=	2.14
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Term
PKGNAMEPREFIX=	p5-
DISTNAME=	TermReadKey-${PORTVERSION}

MAINTAINER=	demon@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Term::ReadKey.3

.include <bsd.port.mk>
