#!/bin/sh
#
# Run vmware
#
# $FreeBSD: ports/emulators/vmware2/files/vmware,v 1.3 2000/04/25 14:23:37 knu Exp $

if [ ! -e @@LINUX_DIR@@/proc/cpuinfo ]; then
    echo "************************************************************"
    echo "It seems Linux procfs is not mounted on @@LINUX_DIR@@/proc."
    echo "VMware does not work without Linux procfs mounted."
    echo
    echo "For details, see linprocfs(5) manpage."
    echo "************************************************************"
    exit 1
fi

LANG=C
PATH=/bin:$PATH

if [ _$TMPDIR = _ ]; then 
    TMPDIR=/var/tmp
    echo Setting TMPDIR="$TMPDIR".
    export TMPDIR
fi

exec @@PREFIX@@/lib/vmware/bin/vmware "$@"
