# New ports collection makefile for:	libspigot.a
# Date Created:		Fri Sep 15 10:04:46 CDT 1995
# Whom:			james@cs.uwm.edu
#
# $FreeBSD: ports/graphics/spigot/Makefile,v 1.11 2000/06/22 19:15:31 fenner Exp $
#

PORTNAME=	spigot
PORTVERSION=	1.7
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	fenner
DISTFILES=	spigot.1.7.tar.gz

MAINTAINER=	james@cs.uwm.edu

# binary package
NO_BUILD=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
