# New ports collection makefile for:   radiusclient
# Date created:        Wed Nov  4 08:48:08 EST 1998
# Whom:                maurice
#
# $FreeBSD: ports/net/radiusclient/Makefile,v 1.10 2000/06/16 08:18:39 sobomax Exp $
#

PORTNAME=	radiusclient
PORTVERSION=	0.3.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.hamburg.cityline.net/pub/radiusclient/ \
		ftp://ftp.ecrc.net/pub/netsw/Network/IP/Management/RADIUS/

MAINTAINER=	maurice@serc.rmit.edu.au

USE_GMAKE=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
