#!/bin/sh
#
#	$FreeBSD: ports/security/amavisd/pkg-install,v 1.1 2002/05/15 13:19:02 ijliao Exp $
#

PKG_PREFIX=${PKG_PREFIX:=/usr/local}
BATCH=${BATCH:=no}

USER=$1
GROUP=$2

if /usr/sbin/pw groupshow "${GROUP}" 2>/dev/null; then
    echo "You already have a group \"${GROUP}\", so I will use it."
else
    if /usr/sbin/pw groupadd ${GROUP} -h -g 110 -
    then
	echo "Added group \"${GROUP}\"."
    else
	echo "Adding group \"${GROUP}\" failed..."
	echo "Please create it, and try again."
	exit 1
    fi
fi

if /usr/sbin/pw user show "${USER}" 2>/dev/null; then
    echo "You already have a user \"${USER}\", so I will use it."
else
    if /usr/sbin/pw useradd ${USER} -g ${GROUP} -h - \
       -d /var/amavis \
       -s /bin/sh \
       -c "Scanning Virus Account" \
       -u 110
    then
	echo "Added user \"${USER}\"."
    else
	echo "Adding user \"${USER}\" failed..."
	echo "Please create it, and try again."
	exit 1
    fi
fi
