# New ports collection makefile for: pips for EPSON PM-670C
# Date created:        2000.12.09
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips670/Makefile,v 1.1 2000/12/11 02:07:20 taoka Exp $
#

PORTVERSION=	1.3
MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		670

do-install:     # empty

.include "${MASTERDIR}/Makefile"
