# New ports collection makefile for:	sigrot
# Date created:		4 Mar 1998
# Whom:			Marijn Meijles <marijn@stack.nl>
#
# $FreeBSD: ports/mail/sigrot/Makefile,v 1.3 2000/04/13 20:00:47 cpiazza Exp $
#

PORTNAME=	sigrot
PORTVERSION=	1.0
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/mail/misc
DISTNAME=	${PORTNAME}_v${PORTVERSION}

MAINTAINER=	marijn@stack.nl

MAN1=		sigrot.1

.include <bsd.port.mk>
