# New ports collection makefile for:	libffi
# Date created:			14, June, 1998
# Whom:				Horance Chou <horance@freedom.ie.cycu.edu.tw>
#
# $FreeBSD: ports/devel/libffi/Makefile,v 1.13 2000/06/16 08:47:16 sobomax Exp $
#

PORTNAME=	libffi
PORTVERSION=	1.20
CATEGORIES=	devel
MASTER_SITES=	ftp://sourceware.cygnus.com/pub/libffi/

MAINTAINER=	horance@freedom.ie.cycu.edu.tw

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
CONFIGURE_TARGET=	# empty

.include <bsd.port.mk>
