# New ports collection makefile for:	textproc/p5-Text-Format
# Date created:				30 December 2000
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-Text-Format/Makefile,v 1.1 2000/12/31 05:34:30 will Exp $
#

PORTNAME=	Text-Format
PORTVERSION=	0.52
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Text
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3=		Text::Format.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
