# New ports collection makefile for:	astro/p5-Astro-Sunrise
# Date created:				25 April 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/astro/p5-Astro-Sunrise/Makefile,v 1.1 2001/04/28 15:03:42 joe Exp $
#

PORTNAME=	Astro-Sunrise
PORTVERSION=	0.04
CATEGORIES=	astro perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Astro
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Astro::Sunrise.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
