# New ports collection makefile for:	biabam
# Date created:		03 January 2001
# Whom:			George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/mail/biabam/Makefile,v 1.1 2001/02/27 06:05:36 steve Exp $
#

PORTNAME=		biabam
PORTVERSION=		0.9.2
CATEGORIES=		mail
MASTER_SITES=		http://mmj.dk/biabam/

MAINTAINER=		greid@FreeBSD.org

NO_BUILD=		yes

do-install:
	${INSTALL_SCRIPT} ${WRKSRC}/biabam ${PREFIX}/bin

.include <bsd.port.mk>
