# New ports collection makefile for:	gtkstep
# Date Created:				7 nov 98
# Whom:				 	Gilad Rom
#
# $FreeBSD: ports/x11-toolkits/gtkstep/Makefile,v 1.16 2000/10/05 06:42:46 reg Exp $
#

PORTNAME=	gtkstep
PORTVERSION= 	2.2
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://ulli.linuxave.net/gtkstep/

MAINTAINER=	sobomax@FreeBSD.org

USE_BZIP2=	yes
USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
