# New ports collection makefile for:		elisp-manual
# Date created:		18 November 1997
# Whom:			Don Croyle <croyle@gelemna.org>
#
# $FreeBSD: ports/lang/elisp-manual/Makefile,v 1.6 2000/04/12 06:18:12 obrien Exp $
#

PORTNAME=	elisp-manual
PORTVERSION=	20-2.5
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	emacs

MAINTAINER=	croyle@gelemna.org

GNU_CONFIGURE=	yes

ALL_TARGET=	elisp

.include <bsd.port.mk>
