# New ports collection makefile for:	p5-Font-AFM
# Date created:				25 April 2001
# Whom:					Pete Fritchman <petef@databits.net>
#
# $FreeBSD: ports/x11-fonts/p5-Font-AFM/Makefile,v 1.1 2001/05/11 15:58:04 vanilla Exp $
#

PORTNAME=	Font-AFM
PORTVERSION=	1.18
CATEGORIES=	x11-fonts perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Font
PKGNAMEPREFIX=	p5-

MAINTAINER=	petef@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Font::AFM.3

.include <bsd.port.mk>
