# New ports collection makefile for:	psgml for xemacs-mule
# Date created:		26 May 1999
# Whom:			kuriyama
#
# $FreeBSD: ports/editors/psgml-xemacs21-mule/Makefile,v 1.13 2000/07/12 15:57:14 shige Exp $
#

MAINTAINER=	kuriyama@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../psgml-emacs

# emacs port setup
EMACS_PORT_NAME=	xemacs21-mule

# pkg-* files in ${.CURDIR} are used
PKGDIR=		${.CURDIR}

.include <${MASTERDIR}/Makefile>
