# New ports collection makefile for:   cpp2html
# Date created:        24 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/devel/cpp2html/Makefile,v 1.1 2001/01/28 20:04:27 dannyboy Exp $
#

PORTNAME=	cpp2html
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=		${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=		greid@ukug.uk.freebsd.org

GNU_CONFIGURE=		yes

.include <bsd.port.mk>
