# New ports collection makefile for:	powerpc-rtems-chill
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/powerpc-rtems-chill/Makefile,v 1.1 2000/07/10 04:32:25 steve Exp $
#

PORTNAME=	chill

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	powerpc-rtems
.include "${.CURDIR}/../i386-rtems-chill/Makefile"
