# New ports collection makefile for:    xbattbar
# Date created:		Fri Feb 18 10:05:12 JST 2000
# Whom:                 sumikawa
#
# $FreeBSD: ports/sysutils/xbattbar/Makefile,v 1.6 2000/12/26 06:59:19 sumikawa Exp $
#

PORTNAME=	xbattbar
PORTVERSION=	1.4.1
CATEGORIES=	sysutils
MASTER_SITES=	http://infonet.aist-nara.ac.jp/member/suguru/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	sumikawa@FreeBSD.org

USE_IMAKE=	yes
USE_X_PREFIX=	yes
WRKSRC=		${WRKDIR}/xbattbar-${PORTVERSION}
MAN1=		xbattbar.1

.include <bsd.port.mk>
