# New ports collection makefile for:    xbattbar
# Date created:		Fri Feb 18 10:05:12 JST 2000
# Whom:                 sumikawa
#
# $FreeBSD: ports/sysutils/xbattbar/Makefile,v 1.2 2000/04/09 19:08:58 cpiazza Exp $
#

PORTNAME=	xbattbar
PORTVERSION= 	1.3
CATEGORIES=	sysutils
MASTER_SITES=	http://infonet.aist-nara.ac.jp/member/suguru/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	sumikawa@FreeBSD.org

USE_IMAKE=      yes
USE_X11_PREFIX=	yes
WRKSRC=		${WRKDIR}/xbattbar
MAN1=		xbattbar.1

.include <bsd.port.mk>
