# New ports collection makefile for:	xmms-tfmx
# Date created:			21 May 2000
# Whom:				Anders Nordby <anders@fix.no>
#
# $FreeBSD: ports/audio/xmms-tfmx/Makefile,v 1.3 2000/12/04 14:40:34 kevlo Exp $
#

PORTNAME=	xmms-tfmx
PORTVERSION=	0.3
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.nuug.no/pub/anders/distfiles/ \
		http://www.freenix.no/~anders/

MAINTAINER=	anders@fix.no

LIB_DEPENDS=	xmms.1:${PORTSDIR}/audio/xmms

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
