# New ports collection makefile for:	xmms-tfmx
# Date created:			21 May 2000
# Whom:				Anders Nordby <anders@fix.no>
#
# $FreeBSD: ports/audio/xmms-tfmx/Makefile,v 1.2 2000/10/05 06:35:59 reg Exp $
#

PORTNAME=	xmms-tfmx
PORTVERSION=	0.3
CATEGORIES=	audio
MASTER_SITES=	http://fatal.telia.nu/hosted/ \
		http://www.freenix.no/~anders/ \
		ftp://totem.fix.no/pub/mirrors/misc/

MAINTAINER=	anders@fix.no

LIB_DEPENDS=	xmms.1:${PORTSDIR}/audio/xmms

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
