# New ports collection makefile for:	e3
# Date created:		Tue 5 Dec 2000
# Whom:			joseph@randomnetworks.com
#
# $FreeBSD: ports/editors/e3/Makefile,v 1.2 2001/01/04 09:38:34 nbm Exp $
#

PORTNAME=	e3
PORTVERSION=	1.61
CATEGORIES=	editors
MASTER_SITES=	http://www.sax.de/~adlibit/

MAINTAINER=	joseph@randomnetworks.com

BUILD_DEPENDS=	nasm:${PORTSDIR}/devel/nasm

USE_GMAKE=	yes
MAKE_ARGS=	OS=FREEBSD
ONLY_FOR_ARCH=	i386

MAN1=		e3.1

.include <bsd.port.mk>
