# New ports collection makefile for:	e3
# Date created:		Tue 5 Dec 2000
# Whom:			joseph@randomnetworks.com
#
# $FreeBSD: ports/editors/e3/Makefile,v 1.3 2001/06/14 05:24:16 dwcjr Exp $
#

PORTNAME=	e3
PORTVERSION=	1.7
CATEGORIES=	editors
MASTER_SITES=	http://www.sax.de/~adlibit/

MAINTAINER=	joseph@randomnetworks.com

BUILD_DEPENDS=	nasm:${PORTSDIR}/devel/nasm

USE_GMAKE=	yes
MAKE_ARGS=	OS=FREEBSD
ONLY_FOR_ARCH=	i386

MAN1=		e3.1

.include <bsd.port.mk>
