# $FreeBSD: ports/mail/spamprobe/files/Makefile,v 1.1 2002/09/05 19:40:10 mdodd Exp $
#
PREFIX?=	/usr/local
BINDIR=		${PREFIX}/bin
NOMAN=
PROG_CXX=	spamprobe-export_0.6
CXXFLAGS=	-Wall -DUSE_DBM
SRCS=		File.cc export0_6.cc

.include <bsd.prog.mk>
