# New ports collection makefile for:	oidentd
# Date created:		29 Mar 2000
# Whom:			trevor@jpj.net
#
# $FreeBSD: ports/security/oidentd/Makefile,v 1.3 2000/04/09 18:30:05 cpiazza Exp $
#

PORTNAME=	oidentd
PORTVERSION=	1.6.4
CATEGORIES=	security
MASTER_SITES=	ftp://ftp.sourceforge.net/pub/sourceforge/ojnk/ \
		http://www.numb.org/~odin/stuff/

MAINTAINER=	trevor@jpj.net

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
MAN8=		oidentd.8

.include <bsd.port.mk>
