# New ports collection makefile for:	oidentd
# Date created:		29 Mar 2000
# Whom:			trevor@jpj.net
#
# $FreeBSD: ports/security/oidentd/Makefile,v 1.4 2000/05/21 12:32:02 knu Exp $
#

PORTNAME=	oidentd
PORTVERSION=	1.6.4
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE} \
		http://www.numb.org/~odin/stuff/
MASTER_SITE_SUBDIR=	ojnk

MAINTAINER=	trevor@jpj.net

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
MAN8=		oidentd.8

.include <bsd.port.mk>
