#! /bin/sh
#
# $FreeBSD: ports/security/sudo/pkg-install,v 1.8 2011/04/11 19:43:39 wxs Exp $

PATH=/bin:/usr/bin:/usr/sbin

case $2 in

PRE-INSTALL)
  install -d -o 0 -g 0 -m 0750 ${PKG_PREFIX}/etc/sudoers.d
  ;;

esac
