# New ports collection makefile for:   pppload
# Version required:    1.0
# Date created:        30 January 1998
# Whom:                Sean Cole <scole@aracnet.com>
#
# $FreeBSD: ports/net/pppload/Makefile,v 1.11 1999/08/30 14:23:51 peter Exp $
#

DISTNAME=	pppload-1.0
CATEGORIES=	net sysutils
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=		system/network/serial/ppp

MAINTAINER=	ports@FreeBSD.org

USE_QT=		yes
USE_GMAKE=	yes

MAN1=		pppload.1

.include <bsd.port.mk>
