# New ports collection makefile for:	rmsg
# Version required:	1.64
# Date created:		9 October 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/net/rmsg/Makefile,v 1.8 1999/08/30 14:24:02 peter Exp $
#

DISTNAME=	rmsg-1.64
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.funet.fi/pub/unix/tcpip/ \
		ftp://proton.elka.pw.edu.pl/pub/unix/network/

MAINTAINER=	torstenb@FreeBSD.org

WRKSRC=		${WRKDIR}/rmsg
MAN1=		rmsg.1
MAN8=		rmsgd.8

.include <bsd.port.mk>
