# New ports collection makefile for:	rmsg
# Date created:		9 October 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/net/rmsg/Makefile,v 1.10 2000/04/09 18:13:24 cpiazza Exp $
#

PORTNAME=	rmsg
PORTVERSION=	1.64
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.funet.fi/pub/unix/tcpip/ \
		ftp://proton.elka.pw.edu.pl/pub/unix/network/

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/rmsg
MAN1=		rmsg.1
MAN8=		rmsgd.8

.include <bsd.port.mk>
