# New ports collection makefile for:	xonix
# Date created:		3 May 1995
# Whom:			joerg
#
# $FreeBSD: ports/games/xonix/Makefile,v 1.10 2000/04/14 12:27:54 asami Exp $
#

PORTNAME=	xonix
PORTVERSION=	1.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org

USE_IMAKE=      yes
USE_XPM=	yes
MAN1=		xonix.1

.include <bsd.port.mk>
