# New ports collection makefile for:	xonix
# Date created:		3 May 1995
# Whom:			joerg
#
# $FreeBSD: ports/games/xonix/Makefile,v 1.9 2000/02/19 19:38:01 joerg Exp $
#

PORTNAME=	xonix
PORTVERSION=	1.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=      yes
MAN1=		xonix.1

.include <bsd.port.mk>
