# New ports collection makefile for:	m68k-rtems-binutils
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/m68k-rtems-binutils/Makefile,v 1.1 2000/07/10 04:32:19 steve Exp $
#

PORTNAME=	binutils

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	m68k-rtems
.include "${.CURDIR}/../i386-rtems-binutils/Makefile"
