# New ports collection makefile for:	p5-CGI-Minimal
# Date created:				26th December 2000
# Whom:	      				Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-CGI-Minimal/Makefile,v 1.2 2001/02/05 15:33:39 olgeni Exp $
#

PORTNAME=	CGI-Minimal
PORTVERSION=	1.06
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	CGI
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		CGI::Minimal.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
