# New ports collection makefile for: comconsole
# Date created:		27 Dec 1998
# Whom:			SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/comconsole/Makefile,v 1.4 2000/04/09 19:07:20 cpiazza Exp $
#

PORTNAME=	comconsole
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	#
DISTFILES=

MAINTAINER=	sada@FreeBSD.org

NO_BUILD=	yes
NO_WRKSUBDIR=	yes

do-install:
	@${SH} ${PKGINSTALL} ${PKGNAME} POST-INSTALL

.include <bsd.port.mk>
