# New ports collection makefile for:	recode
# Date created:		14 Jul 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/converters/recode/Makefile,v 1.8 1999/12/29 08:12:57 steve Exp $
#

PORTNAME=	recode
PORTVERSION=	3.5
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	recode

MAINTAINER=	torstenb@FreeBSD.org

USE_LIBTOOL=	yes

MAN1=		recode.1

.include <bsd.port.mk>
