# New ports collection makefile for:	recode
# Version required:	3.4
# Date created:		14 Jul 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/converters/recode/Makefile,v 1.6 1999/08/25 05:16:28 obrien Exp $
#

DISTNAME=	recode-3.4
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	recode

MAINTAINER=	torstenb@FreeBSD.org

GNU_CONFIGURE=	YES

.include <bsd.port.mk>
