# Ports collection makefile for:  muuz
# Date created:			  21 March 2000
# Whom:				  kline@thought.org
#
# $FreeBSD: ports/misc/muuz/Makefile,v 1.2 2000/05/30 08:12:12 knu Exp $
#

PORTNAME=       muuz
PORTVERSION=    0.27.2
CATEGORIES=     misc
MASTER_SITES=	ftp://toxic.magnesium.net/pub/FreeBSD/muuz/

MAINTAINER=	kline@thought.org

LIB_DEPENDS=	Xaw3d.${XAWVER}:${PORTSDIR}/x11-toolkits/Xaw3d

USE_IMAKE=	yes
MAN1=		muuz.1

.include <bsd.port.mk>
