# Ports collection makefile for:  muuz
# Date created:			  21 March 2000
# Whom:				  kline@thought.org
#
# $FreeBSD: ports/misc/muuz/Makefile,v 1.3 2000/09/05 18:34:51 asami Exp $
#

PORTNAME=	muuz
PORTVERSION=	0.27.2
CATEGORIES=	misc
MASTER_SITES=	ftp://toxic.magnesium.net/pub/FreeBSD/muuz/

MAINTAINER=	kline@thought.org

LIB_DEPENDS=	Xaw3d.${XAWVER}:${PORTSDIR}/x11-toolkits/Xaw3d

USE_IMAKE=	yes
MAN1=		muuz.1

.include <bsd.port.mk>
