# New ports collection makefile for:    txt2pdbdoc
# Date created:         Mon Jan 8 2001
# Whom:                 keichii@iteration.net
#
# $FreeBSD: ports/palm/txt2pdbdoc/Makefile,v 1.2 2001/02/18 05:22:02 kris Exp $
#

PORTNAME=	txt2pdbdoc
PORTVERSION=	1.3
CATEGORIES=	palm converters
MASTER_SITES=	http://homepage.mac.com/pauljlucas/software/

MAINTAINER=	keichii@iteration.net

PREFIX=		${LOCALBASE}/

USE_GMAKE=	yes

MAN1=		txt2pdbdoc.1 pdbtxt2html.1 html2pdbtxt.1
MAN4=		pdb.4 doc.4

.include <bsd.port.mk>
