# New ports collection makefile for:	hypermail
# Date created:				23 Dec 1997
# Whom:					mjhsieh
#
# $FreeBSD: ports/www/hypermail/Makefile,v 1.5 1999/12/23 15:38:31 steve Exp $
#

PORTNAME=	hypermail
PORTVERSION=	2b28
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.landfield.com/hypermail/ \
		ftp://ftp.faqs.org/hypermail/

MAINTAINER=	veers@disturbed.net

HAS_CONFIGURE=  yes

MAN1=		hypermail.1
MAN4=           hmrc.4

.include <bsd.port.mk>
