# New ports collection makefile for:   Migemo (for xemacs21-mule)
# Date Created:			24 Mar 2001
# Whom:				MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/migemo-xemacs21-mule/Makefile,v 1.1 2001/04/11 04:54:06 knu Exp $
#

MASTERDIR=      ${.CURDIR}/../../japanese/migemo-emacs20
PKGDIR=         ${.CURDIR}
PLIST=          ${MASTERDIR}/pkg-plist
PKGMESSAGE=     ${MASTERDIR}/pkg-message

EMACS_PORT_NAME=	xemacs21-mule

.include <${MASTERDIR}/Makefile>
