# New ports collection makefile for:    xmandel
# Date created:         		18 October 1996
# Whom:                 		andreas@marvin.robin.de
#
# $FreeBSD: ports/graphics/xmandel/Makefile,v 1.5 2000/04/14 10:47:51 asami Exp $
#

PORTNAME=	xmandel
PORTVERSION=	1.0
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.cray.com/src/graphics/xmandel/
EXTRACT_SUFX=	.shar
# The README says the location is ftp.cray.com:/usr/ftp/src/graphics/xmandel,
# but this has changed apparently.
DISTNAME=	${PORTNAME}

EXTRACT_CMD=	sh
EXTRACT_BEFORE_ARGS=	# empty
EXTRACT_AFTER_ARGS=	# empty
USE_IMAKE=	yes
NO_WRKSUBDIR=	yes
MAN1=		xmandel.1

MAINTAINER=	andreas@marvin.robin.de

.include <bsd.port.mk>
