# New ports collection makefile for:	kcfonts
# Date Created:				5 Dec 1997
# Whom:					Ming-I Hseh <PA@FreeBSD.Ntu.edu.TW>
#
# $FreeBSD: ports/chinese/kcfonts/Makefile,v 1.9 2000/04/13 08:28:05 asami Exp $
#

PORTNAME=	kcfonts
PORTVERSION=	1.05
CATEGORIES=	chinese x11-fonts
MASTER_SITES=	ftp://freebsd.ntu.edu.tw/freebsd/taiwan/

MAINTAINER=	PA@FreeBSD.ee.Ntu.edu.TW

USE_X_PREFIX=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
