# New ports collection makefile for:	opendx-samples
# Version required:	4.0
# Date created:		06 Oct 1999
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/graphics/opendx-samples/Makefile,v 1.1.1.1 1999/10/06 09:05:28 tg Exp $
#

DISTNAME=	dxsamples-4.0
PKGNAME=	opendx-samples-4.0
CATEGORIES=	graphics math
MASTER_SITES=	http://opendx.npaci.edu/source/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
