# New ports collection makefile for:	Wizard Wars Server
# Date created:				Fri May	4 17:43:25 BRT 2001
# Whom:		Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
#
# $FreeBSD: ports/games/hlserver-wizwars/Makefile,v 1.1 2001/05/04 20:59:13 lioux Exp $
#

PORTNAME=	wizardwars
PORTVERSION=	2.8.0
MASTER_SITES=	http://pm.gamesmania.de/gamesmania/planet-mods/mods/hl/wizardwars/ \
		http://194.195.228.180/exp/hl/mod/wizardwars/ \
		ftp://ftp.gigabell.net/pub/exp/hl/mod/wizardwars/ \
		http://ftp2.extreme-players.de/exp/hl/mod/wizardwars/
DISTNAME=	wizwars_b2_8

MAINTAINER=	lioux@FreeBSD.org

WRKSRC=		${WRKDIR}/wizwars

HALFLIFE_COUNTERSTRIKE_MASTER=	${.CURDIR}/../hlserver-cs

.include "${HALFLIFE_COUNTERSTRIKE_MASTER}/Makefile"
