# New ports collection makefile for:    mpeg_stat
# Date created:         Thu Aug  1 21:52:06 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/graphics/mpeg_stat/Makefile,v 1.7 2000/04/14 10:46:44 asami Exp $
#

PORTNAME=	mpeg_stat
PORTVERSION=	2.2b
CATEGORIES=	graphics
MASTER_SITES=	ftp://mm-ftp.CS.Berkeley.EDU/pub/multimedia/mpeg/stat/
DISTNAME=	${PKGNAME}-src

MAINTAINER=	ports@FreeBSD.org

MAN1=		mpeg_stat.1
MANCOMPRESSED=	yes

WRKSRC=		${WRKDIR}/mpeg_stat

.include <bsd.port.mk>
