# New ports collection makefile for:	tosha
# Date created:		01 Jan 1999
# Whom:			Oliver Fromme <oliver.fromme@heim3.tu-clausthal.de>
#
# $FreeBSD: ports/audio/tosha/Makefile,v 1.6 2001/02/18 00:35:43 kris Exp $
#

PORTNAME=	tosha
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	markp

MAINTAINER=	ports@FreeBSD.org

MAN1=		pcmfade.1 pcmplay.1 tosha.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
