# New ports collection makefile for:	mnews-gnspool
# Date created:			23 Sep 1996
# Whom:				Masafumi NAKANE <max@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mnews-gnspool/Makefile,v 1.5 1999/12/26 14:58:48 sada Exp $
#

PKGNAMESUFFIX=	-gnspool

RUN_DEPENDS=	gnspool:${PORTSDIR}/japanese/gn-gnspool

MASTERDIR=	${.CURDIR}/../mnews
COMMENT=	${.CURDIR}/pkg/COMMENT

GNSPOOL=	1

.include "${MASTERDIR}/Makefile"
