# New ports collection makefile for:	mnews-gnspool
# Version required:		1.21
# Date created:			23 Sep 1996
# Whom:				Masafumi NAKANE <max@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mnews-gnspool/Makefile,v 1.3 1999/08/25 05:25:31 obrien Exp $
#

PKGNAME=	ja-mnews-gnspool-1.21

RUN_DEPENDS=	gnspool:${PORTSDIR}/japanese/gn-gnspool

MASTERDIR=	${.CURDIR}/../mnews
COMMENT=	${.CURDIR}/pkg/COMMENT

GNSPOOL=	1

.include "${MASTERDIR}/Makefile"
