# New ports collection makefile for:	mnews-gnspool
# Date created:			23 Sep 1996
# Whom:				Masafumi NAKANE <max@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mnews-gnspool/Makefile,v 1.6 2000/04/11 14:15:09 knu Exp $
#

PKGNAMESUFFIX=	-gnspool

RUN_DEPENDS=	gnspool:${PORTSDIR}/japanese/gn-gnspool

MASTERDIR=	${.CURDIR}/../mnews
COMMENT=	${.CURDIR}/pkg-comment

GNSPOOL=	1

.include "${MASTERDIR}/Makefile"
