# New ports collection makefile for:    MIT-Scheme
# Version required:     7.3
# Date created:         Mar 26 1995
# Whom:                 jmacd@FreeBSD.org
#
# $FreeBSD: ports/lang/mit-scheme/Makefile,v 1.13 1999/08/25 06:34:55 obrien Exp $
#

DISTNAME=       mit-scheme
PKGNAME=	mit-scheme-7.3
CATEGORIES=	lang
MASTER_SITES=   ${MASTER_SITE_LOCAL}
DISTFILES=	scheme-microcode+dist-7.3-freebsd.tgz

MAINTAINER= 	jmacd@FreeBSD.org

BROKEN_ELF=	yes

USE_XLIB=	yes

.include <bsd.port.mk>
