# New ports collection makefile for:	acroread-chtfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chtfont/Makefile,v 1.7 2000/04/14 16:55:50 knu Exp $
#

CATEGORIES=	chinese
DISTNAME=	chtfont

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
