# New ports collection makefile for:	acroread-chtfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chtfont/Makefile,v 1.6 2000/04/13 08:27:52 asami Exp $
#

DISTNAME=	chtfont
CATEGORIES=	chinese

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
