# New ports collection makefile for:	acroread-chtfont
# Version required:	1999.7.20
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chtfont/Makefile,v 1.4 1999/08/25 04:57:38 obrien Exp $
#

DISTNAME=	chtfont
CATEGORIES=	chinese linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
