# ex:ts=8
# Ports collection makefile for:  xosview
# Date created:			  19 Nov 1997
# Whom:				  Brian Handy <handy@physics.montana.edu>
#
# $FreeBSD: ports/sysutils/xosview/Makefile,v 1.24 2000/04/22 10:14:01 mharo Exp $
#

PORTNAME=	xosview
PORTVERSION=	1.7.3
CATEGORIES=	sysutils
MASTER_SITES=	http://lore.ece.utexas.edu/~bgrayson/xosview/ \
		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/status/xstatus

MAINTAINER=	obrien@FreeBSD.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
MAN1=		xosview.1

.include <bsd.port.mk>
