# New ports collection makefile for:   pr
# Date created:        27 March 2001
# Whom:                Anton Voronin <anton@urc.ac.ru>
#
# $FreeBSD: ports/comms/pr/Makefile,v 1.1 2001/03/31 01:36:29 will Exp $
#

PORTNAME=	pr
PORTVERSION=	1.1
CATEGORIES=	comms net
MASTER_SITES=	http://rnoc.urc.ac.ru/~anton/projects/files/
DISTNAME=	pr-${PORTVERSION}

MAINTAINER=	anton@urc.ac.ru

WRKSRC=		${WRKDIR}/pr

NO_BUILD=	YES

.include <bsd.port.mk>
