# New ports collection makefile for:    kbanner
# Date created:		Fri Feb 26 15:07:10 PST 1999
# Whom:			sumikawa
#
# $FreeBSD: ports/japanese/kbanner/Makefile,v 1.4 2000/04/11 14:14:21 knu Exp $
#

PORTNAME=	kbanner
PORTVERSION=	2.1
PORTREVISION=	1
CATEGORIES=	japanese
MASTER_SITES=	ftp://ftp.lab.kdd.co.jp/Usenet/fj.sources/1993/oct/
EXTRACT_SUFX=	.tar.Z
DISTNAME=	${PORTNAME}${PORTVERSION:R}

MAINTAINER=	sumikawa@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}${PORTVERSION}
ALL_TARGET=	kbanner
MAN1=		kbanner.1

.include <bsd.port.mk>
