# New ports collection makefile for:	xmbibtex
# Version required:			1.5
# Date created:				06 Nov 1997
# Whom:					Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/print/xmbibtex/Makefile,v 1.7 1999/08/31 01:45:28 peter Exp $
#

DISTNAME=	xmbibtex-1.5
CATEGORIES=	print databases
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/tex

MAINTAINER=	ports@FreeBSD.org

REQUIRES_MOTIF=	yes
WRKSRC=		${WRKDIR}/${DISTNAME}/src
USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
