# New ports collection makefile for:	xmbibtex
# Date created:				06 Nov 1997
# Whom:					Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/print/xmbibtex/Makefile,v 1.11 2000/11/07 23:28:15 asami Exp $
#

PORTNAME=	xmbibtex
PORTVERSION=	1.5
CATEGORIES=	print databases
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/tex

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/${DISTNAME}/src

USE_MOTIF=	yes
USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
