#!/bin/sh
# $FreeBSD: ports/print/texinfo/pkg-install,v 1.1 2005/05/30 23:23:28 lioux Exp $

[ $# != 2 ] && exit 1
PKGNAME=$1
ACTION=$2

PATH="${PKG_PREFIX}/bin:${LOCALBASE}/bin:/usr/bin:${PATH}"

SETENV=env
TEXHASH=texhash
TRUE=true

case "$ACTION" in

POST-INSTALL|DEINSTALL)
	${SETENV} PATH="${PATH}" ${TEXHASH} 2>/dev/null || ${TRUE}
	;;

PRE-INSTALL|POST-DEINSTALL)
	;;

*)
	exit 1
	;;
esac

exit
