# New ports collection makefile for:	piewm
# Date created:		24 November 1994
# Whom:			asami
#
# $FreeBSD: ports/x11-wm/piewm/Makefile,v 1.21 2000/04/10 19:50:08 cpiazza Exp $
#

PORTNAME=	piewm
PORTVERSION= 	1.03
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://ftp.crynwr.com/piewm/

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		piewm.1

.include <bsd.port.mk>
