# New ports collection makefile for:	piewm
# Version required:	1.02
# Date created:		24 November 1994
# Whom:			asami
#
# $FreeBSD: ports/x11-wm/piewm/Makefile,v 1.18 1999/08/31 06:53:14 mharo Exp $
#

DISTNAME=	piewm-1.02
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://ftp.crynwr.com/piewm/

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		piewm.1

.include <bsd.port.mk>
