# New ports collection makefile for:	llnlxftp
# Date created:				9 November 1997
# Whom: Dima Ruban <dima@FreeBSD.org>
#
# $FreeBSD: ports/ftp/llnlxftp/Makefile,v 1.7 2000/04/12 05:31:14 mharo Exp $
#

PORTNAME=	llnlxftp
PORTVERSION=	2.1
CATEGORIES=	ftp
MASTER_SITES=	ftp://ftp.llnl.gov/pub/ia/llnlxftp/
DISTNAME=	latest_xftp
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	dima@FreeBSD.org

WRKSRC=		${WRKDIR}/llnlxftp2.1/sources
REQUIRES_MOTIF=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
