# New ports collection makefile for:	llnlxftp
# Date created:				9 November 1997
# Whom: Dima Ruban <dima@FreeBSD.org>
#
# $FreeBSD: ports/ftp/llnlxftp/Makefile,v 1.9 2000/11/07 23:28:04 asami Exp $
#

PORTNAME=	llnlxftp
PORTVERSION=	2.1
PORTREVISION=	1
CATEGORIES=	ftp
MASTER_SITES=	ftp://ftp.llnl.gov/pub/ia/llnlxftp/
DISTNAME=	latest_xftp
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	dima@FreeBSD.org

WRKSRC=		${WRKDIR}/llnlxftp2.1/sources
USE_MOTIF=	yes
USE_IMAKE=	yes

MAN1=		xftp.1

.include <bsd.port.mk>
