# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		25 Jun 2000
# Whom:			cjh@FreeBSD.org
#
# $FreeBSD: ports/korean/linux-netscape47-navigator/Makefile,v 1.1.1.1 2000/06/25 13:15:41 cjh Exp $
#

BROWSER_NAME=	navigator

.include	"${.CURDIR}/../linux-netscape47-communicator/Makefile"
