# New ports collection makefile for:	libPropList
# Date Created:				6 December 1998
# Whom:					Glenn Johnson
#
# $FreeBSD: ports/devel/libPropList/Makefile,v 1.11 2000/05/25 19:39:39 will Exp $
#

PORTNAME=	libproplist
PORTVERSION=	0.10.1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_WINDOWMAKER}
MASTER_SITE_SUBDIR=	libs
DISTNAME=	libPropList-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
