# New ports collection makefile for:	libPropList
# Version required:			0.10.0
# Date Created:				6 December 1998
# Whom:					Glenn Johnson
#
# $FreeBSD: ports/devel/libPropList/Makefile,v 1.7 1999/10/06 07:05:22 tg Exp $
#

DISTNAME=	libPropList-0.10.0
PKGNAME=	libproplist-0.10.0
CATEGORIES=	devel gnome
MASTER_SITES=	${MASTER_SITE_WINDOWMAKER}
MASTER_SITE_SUBDIR=	libs

MAINTAINER=    gljohns@bellsouth.net

USE_LIBTOOL=	yes

.include <bsd.port.mk>
