# New ports collection makefile for:	umatrix
# Date created:				1 May 1997
# Whom:					Sandro Sigala <ssigala@globalnet.it>
#
# $FreeBSD: ports/math/umatrix/Makefile,v 1.2 1999/08/25 07:16:25 obrien Exp $
#

PORTNAME=	umatrix
PORTVERSION=	1.1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ssigala@globalnet.it

GNU_CONFIGURE=	yes
MAN1=		umatrix.1

.include <bsd.port.mk>
