# New ports collection makefile for:	umatrix
# Date created:				1 May 1997
# Whom:					Sandro Sigala <ssigala@globalnet.it>
#
# $FreeBSD: ports/math/umatrix/Makefile,v 1.3 2000/04/14 07:20:45 asami Exp $
#

PORTNAME=	umatrix
PORTVERSION=	1.1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS

MAINTAINER=	ssigala@globalnet.it

GNU_CONFIGURE=	yes
MAN1=		umatrix.1

.include <bsd.port.mk>
