# New ports collection makefile for:	mule with sj3
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-sj3/Makefile,v 1.15 2000/09/08 04:34:48 taoka Exp $
#

PKGNAMESUFFIX=	-sj3
CATEGORIES=	japanese

SJ3=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
