# New ports collection makefile for:	echoping
# Version required:	2.2.0
# Date created:		13 April 1997
# Whom:			peter
#
# $FreeBSD: ports/net/echoping/Makefile,v 1.4 1999/08/30 14:22:39 peter Exp $
#

DISTNAME=	echoping-2.2.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

MAINTAINER=	peter@FreeBSD.org

MAN1=		echoping.1

.include <bsd.port.mk>
