# New ports collection makefile for:	echoping
# Date created:		13 April 1997
# Whom:			peter
#
# $FreeBSD: ports/net/echoping/Makefile,v 1.6 2000/04/09 18:11:08 cpiazza Exp $
#

PORTNAME=	echoping
PORTVERSION=	3.0.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--enable-icp

MAN1=		echoping.1

.include <bsd.port.mk>
