# New ports collection makefile for:	echoping
# Date created:		13 April 1997
# Whom:			peter
#
# $FreeBSD: ports/net/echoping/Makefile,v 1.8 2001/02/14 16:41:59 sumikawa Exp $
#

PORTNAME=	echoping
PORTVERSION=	4.1.0
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--enable-icp --enable-smtp --with-ssl

MAN1=		echoping.1

.include <bsd.port.mk>
