# New ports collection makefile for:	orville-write
# Date created:		4 December 1999
# Whom:			James Howard <howardj@wam.umd.edu>
#
# $FreeBSD: ports/misc/orville-write/Makefile,v 1.3 2000/04/14 08:46:21 asami Exp $
#

PORTNAME=	orville-write
PORTVERSION=	2.53
CATEGORIES=	misc
MASTER_SITES=	http://www.wwnet.net/~janc/software/

MAINTAINER=	howardjp@wam.umd.edu

MAN1=	amin.1 helpers.1 huh.1 mesg.1 write.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
