# New ports collection makefile for:   wsoundPrefs
# Version required:    1.0.2
# Date created:        12 December 1998
# Whom:                gljohns@bellsouth.net
#
# $FreeBSD: ports/audio/wsoundprefs/Makefile,v 1.5 1999/08/25 04:36:20 obrien Exp $
#

DISTNAME=	WSoundPrefs-1.0.2
CATEGORIES=	audio windowmaker
MASTER_SITES=	ftp://shadowmere.student.utwente.nl/pub/WindowMaker/

MAINTAINER=	ports@FreeBSD.org	

BUILD_DEPENDS=	wmaker:${PORTSDIR}/x11-wm/windowmaker \
		wmsound:${PORTSDIR}/audio/wmsound

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
