# New ports collection makefile for:	wsoundPrefs
# Date created:		12 December 1998
# Whom:			gljohns@bellsouth.net
#
# $FreeBSD: ports/audio/wsoundprefs/Makefile,v 1.8 2000/04/08 21:24:47 mharo Exp $
#

PORTNAME=	wsoundprefs
PORTVERSION=	1.0.2
CATEGORIES=	audio windowmaker
MASTER_SITES=	ftp://shadowmere.student.utwente.nl/pub/WindowMaker/
DISTNAME=	WSoundPrefs-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

BUILD_DEPENDS=	wmaker:${PORTSDIR}/x11-wm/windowmaker \
		wmsound:${PORTSDIR}/audio/wmsound

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
