# New ports collection makefile for:   normalize
# Date created:        31 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/audio/normalize/Makefile,v 1.1 2001/02/03 18:16:34 dannyboy Exp $
#

PORTNAME=	normalize
PORTVERSION=	0.4
CATEGORIES=	audio
MASTER_SITES=	http://www.cs.columbia.edu/~cvaill/normalize/

MAINTAINER=	greid@ukug.uk.freebsd.org

LIB_DEPENDS=	intl.1:${PORTSDIR}/devel/gettext \
		gnugetopt.1:${PORTSDIR}/devel/libgnugetopt

GNU_CONFIGURE=	yes

MAN1=		normalize.1

.include <bsd.port.mk>
