# New ports collection makefile for:	muse
# Date created:				27 December 1999
# Whom:					freebsd@spatula.net
#
# $FreeBSD: ports/sysutils/muse/Makefile,v 1.1.1.1 1999/12/28 02:45:45 jedgar Exp $
#

PORTNAME=	muse
PORTVERSION= 	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://www.spatula.net/muse/

MAINTAINER=	freebsd@spatula.net

MAN1=		muse.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
