# New ports collection makefile for:	qbrew
# Date created:				22 September 2000
# Whom:					David Johnson <david@usermode.org>
#
# $FreeBSD: ports/misc/qbrew/Makefile,v 1.1 2001/04/07 06:46:38 will Exp $
#

PORTNAME=	qbrew
PORTVERSION=	0.2.0
CATEGORIES=	misc
MASTER_SITES=	http://www.usermode.org/code/

MAINTAINER=	david@usermode.org

USE_QT_VER=	2
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
