# New ports collection makefile for:    engdic-0.2
# Version required:     0.2
# Date created:         3 Jun 1999
# Whom:                 Oh Junseon <hollywar@mail.holywar.net>
#
# $FreeBSD: ports/korean/engdic/Makefile,v 1.3 1999/09/06 05:10:31 taoka Exp $
#

DISTNAME=	engdic-0.2
PKGNAME=	ko-engdic-0.2
CATEGORIES=	korean deskutils
MASTER_SITES=	ftp://ftp.holywar.net/pub/engdic/ \
		ftp://ftp.kr.freebsd.org/pub/FreeBSD-kr/distfiles/

MAINTAINER=	hollywar@mail.holywar.net

ALL_TARGET=	clean all

.include <bsd.port.mk>
