# New ports collection makefile for:	acs
# Date created:		01 January 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/cad/acs/Makefile,v 1.12 1999/11/16 10:40:03 tg Exp $
#

PORTNAME=	acs
PORTVERSION=	0.25
CATEGORIES=	cad
MASTER_SITES=	http://www.geda.seul.org/dist/ \
		http://www.geda.coelacanth.com/dist/ \
		ftp://ftp.geda.seul.org/pub/geda/dist/

MAINTAINER=	tg@FreeBSD.org

USE_NEWGCC=	yes
MAKE_ENV=	CCC="${CXX}"

.include <bsd.port.mk>
