# New ports collection makefile for:	acs
# Version required:	0.25
# Date created:		01 January 1995
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/cad/acs/Makefile,v 1.11 1999/08/25 04:52:27 obrien Exp $
#

DISTNAME=	acs-0.25
CATEGORIES=	cad
MASTER_SITES=	http://www.geda.seul.org/dist/ \
		http://www.geda.coelacanth.com/dist/ \
		ftp://ftp.geda.seul.org/pub/geda/dist/

MAINTAINER=	tg@FreeBSD.org

USE_NEWGCC=	yes
MAKE_ENV=	CCC="${CXX}"

.include <bsd.port.mk>
