# $FreeBSD: ports/news/Makefile,v 1.60 2000/11/03 15:03:24 taoka Exp $
#

    SUBDIR += atp
    SUBDIR += aub
    SUBDIR += bgrab
    SUBDIR += c-nocem
    SUBDIR += cnews
    SUBDIR += dejasearch
    SUBDIR += diablo
    SUBDIR += dnews
    SUBDIR += fidogate
    SUBDIR += glitter
    SUBDIR += grn
    SUBDIR += gup
    SUBDIR += ifmail
    SUBDIR += inn
    SUBDIR += inn-stable
    SUBDIR += knews
    SUBDIR += krn
    SUBDIR += leafnode
    SUBDIR += leafnode+
    SUBDIR += newsfetch
    SUBDIR += newsfish
    SUBDIR += nn
    SUBDIR += nntp
    SUBDIR += nntpbtr
    SUBDIR += nntpcache
    SUBDIR += p5-Gateway
    SUBDIR += p5-NNTPClient
    SUBDIR += p5-News-Article
    SUBDIR += p5-News-Newsrc
    SUBDIR += pan
    SUBDIR += pgpmoose
    SUBDIR += PicMonger
    SUBDIR += plor
    SUBDIR += rkive
    SUBDIR += slnr
    SUBDIR += slrn
    SUBDIR += slurp
    SUBDIR += suck
    SUBDIR += t-gnus-emacs20
    SUBDIR += t-gnus-mule
    SUBDIR += t-gnus-xemacs21-mule
    SUBDIR += tin
    SUBDIR += trn
    SUBDIR += trn4
    SUBDIR += ubh
    SUBDIR += unpost
    SUBDIR += xmitbin
    SUBDIR += xvnews

.include <bsd.port.subdir.mk>
