# New ports collection makefile for:	p5-Locale-Maketext
# Date created:			March 13, 2000
# Whom:				Frank Mayhar <frank@exit.com>
#
# $FreeBSD: ports/devel/p5-Locale-Maketext/Makefile,v 1.1 2000/05/01 02:48:54 steve Exp $
#

PORTNAME=	Locale-Maketext
PORTVERSION=	0.17
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Locale
PKGNAMEPREFIX=	p5-

MAINTAINER=	frank@exit.com

PERL_CONFIGURE=	YES

MAN3=		Locale::Maketext.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
