# New ports collection makefile for:	xinfocom
# Version required:			1.8m
# Date created:				7 May 1998
# Whom:					Matthew Hunt <mph@FreeBSD.org>
#
# $FreeBSD: ports/games/xinfocom/Makefile,v 1.3 1999/08/25 06:05:19 obrien Exp $
#

DISTNAME=		unix8m
PKGNAME=		xinfocom-1.8m
CATEGORIES=		games
MASTER_SITES=   	http://people.FreeBSD.org/~mph/distfiles/
EXTRACT_SUFX=		.tgz

MAINTAINER=		mph@freebsd.org

WRKSRC=			${WRKDIR}/xinfocom

USE_IMAKE=		yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
