# New ports collection makefile for:	xinfocom
# Date created:				7 May 1998
# Whom:					Matthew Hunt <mph@FreeBSD.org>
#
# $FreeBSD: ports/games/xinfocom/Makefile,v 1.5 2000/04/14 12:27:28 asami Exp $
#

PORTNAME=		xinfocom
PORTVERSION=		1.8m
CATEGORIES=		games
MASTER_SITES=   	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	mph
DISTFILES=		unix8m.tgz

MAINTAINER=		mph@freebsd.org

WRKSRC=			${WRKDIR}/xinfocom

USE_IMAKE=		yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
