# New ports collection makefile for:	xinfocom
# Date created:				7 May 1998
# Whom:					Matthew Hunt <mph@FreeBSD.org>
#
# $FreeBSD: ports/games/xinfocom/Makefile,v 1.6 2000/06/14 05:44:52 mph Exp $
#

PORTNAME=		xinfocom
PORTVERSION=		1.8m
CATEGORIES=		games
MASTER_SITES=   	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	mph
DISTFILES=		unix8m.tgz

MAINTAINER=		mph@freebsd.org

WRKSRC=			${WRKDIR}/xinfocom

USE_IMAKE=		yes

.include <bsd.port.mk>
