# New ports collection makefile for:	m68k-rtems-g77
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/m68k-rtems-g77/Makefile,v 1.1 2000/07/10 04:32:20 steve Exp $
#

PORTNAME=	g77

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	m68k-rtems
.include "${.CURDIR}/../i386-rtems-g77/Makefile"
