# New ports collection makefile for:	symlinks
# Date created:		Sa  27 Mai 2000 00:21:44 CEST
# Whom:			Andreas Klemm <andreas@klemm.gtn.com>
#
# $FreeBSD: ports/sysutils/symlinks/Makefile,v 1.2 2001/03/27 05:19:54 andreas Exp $
#

PORTNAME=		symlinks
PORTVERSION=		1.2
CATEGORIES=		sysutils
MASTER_SITES=		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	utils/file

MAINTAINER=		andreas_and_joe@tao.org.uk

MAN8=			symlinks.8

.include <bsd.port.mk>
