# New ports collection makefile for:	acroread-jpnfont
# Version required:	1999.7.20
# Date created:		99/06/16
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/acroread-jpnfont/Makefile,v 1.3 1999/08/25 05:23:30 obrien Exp $
#

DISTNAME=	jpnfont
CATEGORIES=	japanese linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
