# New ports collection makefile for:	tvtwm
# Date created:		5th December 1994
# Whom:			gpalmer
#
# $FreeBSD: ports/x11-wm/tvtwm/Makefile,v 1.17 1999/08/31 06:53:15 mharo Exp $
#

PORTNAME=	tvtwm
PORTVERSION= 	pl11
CATEGORIES=	x11-wm
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	window_managers
DISTNAME=	${PORTNAME}.${PORTVERSION}

MAINTAINER=	gpalmer@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

WRKSRC=		${WRKDIR}/tvtwm
USE_IMAKE=	yes
MAN1=		tvtwm.1

.include <bsd.port.mk>
