# New ports collection makefile for:	tvtwm
# Date created:		5th December 1994
# Whom:			gpalmer
#
# $FreeBSD: ports/x11-wm/tvtwm/Makefile,v 1.19 2000/08/03 09:28:16 asami Exp $
#

PORTNAME=	tvtwm
PORTVERSION=	pl11
CATEGORIES=	x11-wm
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	window_managers
DISTNAME=	${PORTNAME}.${PORTVERSION}

MAINTAINER=	gpalmer@FreeBSD.org

WRKSRC=		${WRKDIR}/tvtwm
USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		tvtwm.1

.include <bsd.port.mk>
