#!/bin/sh
#
# $FreeBSD: ports/security/portaudit/pkg-install,v 1.1 2004/02/25 09:46:26 eik Exp $
#

case $2 in
POST-INSTALL)
  if [ ! -f "%%DATABASEDIR%%/auditfile.tbz" ]; then
    echo
    echo "===>  To check your installed ports for known vulnerabilities now do:"
    echo
    echo "      %%PREFIX%%/bin/portaudit -F -a"
    echo
  fi
  ;;
esac
