# New ports collection makefile for:	ftpfind
# Date created:		Feb 21 1998
# Whom:			Tomokazu ISHII <t-ishii@tryplanet.com>
#
# $FreeBSD: ports/ftp/ftpfind/Makefile,v 1.5 1999/08/25 05:55:06 obrien Exp $
#

PORTNAME=	ftpfind
PORTVERSION=	0.996
CATEGORIES=	ftp
MASTER_SITES=	http://hp.vector.co.jp/authors/VA013366/ \
		http://www.tryplanet.com/t-ishii/programs/ftpfind/

MAINTAINER=	t-ishii@tryplanet.com

.include <bsd.port.mk>
