# New ports collection makefile for:	xskat
# Date created:		27 Apr 1996
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xskat/Makefile,v 1.13 1999/10/12 06:38:18 tg Exp $
#

PORTNAME=	xskat
PORTVERSION=	3.2
CATEGORIES=	games
MASTER_SITES=	http://www.gulu.net/xskat/

MAINTAINER=	tg@FreeBSD.org

WRKSRC=		${WRKDIR}/xskat
USE_IMAKE=	yes
MAN1=		xskat.1

.include <bsd.port.mk>
