# New ports collection makefile for:	xskat
# Date created:		27 Apr 1996
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xskat/Makefile,v 1.17 2000/11/08 13:09:23 tg Exp $
#

PORTNAME=	xskat
PORTVERSION=	3.4
CATEGORIES=	games
MASTER_SITES=	http://www.gulu.net/xskat/

MAINTAINER=	tg@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xskat.1 xskat-de.1

.include <bsd.port.mk>
