# New ports collection makefile for:	xskat
# Date created:		27 Apr 1996
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/games/xskat/Makefile,v 1.16 2000/05/04 09:32:06 tg Exp $
#

PORTNAME=	xskat
PORTVERSION=	3.4
CATEGORIES=	games
MASTER_SITES=	http://www.gulu.net/xskat/

MAINTAINER=	tg@FreeBSD.org

USE_IMAKE=	yes
MANN=		xskat.n xskat-de.n
MANCOMPRESSED=	no

.include <bsd.port.mk>
