# New ports collection makefile for:	xlifegame
# Date created:		11 January 2000
# Whom:			HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xlifegame/Makefile,v 1.3 2000/04/14 12:27:37 asami Exp $
#

PORTNAME=	xlifegame
PORTVERSION=	1.11
CATEGORIES=	games
MASTER_SITES=	http://puma.cis.ibaraki.ac.jp/pub/X11/ \
		http://nadja.cis.ibaraki.ac.jp/pub/X11/

MAINTAINER=	th@cis.ibaraki.ac.jp

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
