# New ports collection makefile for:	xlifegame
# Date created:		11 January 2000
# Whom:			HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xlifegame/Makefile,v 1.7 2001/07/14 05:53:14 knu Exp $
#

PORTNAME=	xlifegame
PORTVERSION=	1.13
CATEGORIES=	games
MASTER_SITES=	http://puma.cis.ibaraki.ac.jp/pub/X11/

MAINTAINER=	hym@cocoa.freemail.ne.jp

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
