# New ports collection makefile for:	xlifegame
# Version required:	1.1
# Date created:		11 January 2000
# Whom:			HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xlifegame/Makefile,v 1.1 2000/01/29 05:06:00 steve Exp $
#

DISTNAME=	xlifegame-1.1
CATEGORIES=	games
MASTER_SITES=	http://puma.cis.ibaraki.ac.jp/~th/pub/X11/ \
		http://nadja.cis.ibaraki.ac.jp/pub/X11/

MAINTAINER=	th@cis.ibaraki.ac.jp

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
