# Date created:		29 December 2002
# Whom:			"Bjoern A. Zeeb" (bzeeb+freebsdports@zabbadoz.net)
#
# $FreeBSD: ports/textproc/xerces-c2/Makefile.alpha,v 1.1 2003/01/12 02:03:09 naddy Exp $
#

# set bitsToBuild to 64
CONFIGURE_ARGS+=	-b 64
SAMPLES_CONFIG_ARGS+=	-b 64

