# ex:ts=8
# New ports collection makefile for:	hexcurse
# Date created:			Jun 3, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/editors/hexcurse/Makefile,v 1.2 2001/07/05 18:45:11 ijliao Exp $
#

PORTNAME=	hexcurse
PORTVERSION=	1.21
CATEGORIES=	editors
MASTER_SITES=	http://jewfish.net/downloads/

MAINTAINER=	ijliao@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=	hexcurse.1

.include <bsd.port.mk>
