# New ports collection makefile for:	powerpc-rtems-objc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/powerpc-rtems-objc/Makefile,v 1.1 2000/07/10 04:32:29 steve Exp $
#

PORTNAME=	objc

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	powerpc-rtems
.include "${.CURDIR}/../i386-rtems-objc/Makefile"
