#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.5 2003/03/29 07:47:10 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org-%%BUILD_NR%%/program/
program=`echo $0 | sed -e 's|.*-||'`

if [ ! $LANG ]; then
	export LANG=%%LANG%%
fi

if [ -e $HOME/OpenOffice.org644/setup.log ]; then
	if [ ! -e $HOME/OpenOffice.org644/user/config/soffice.cfg ]; then
		touch $HOME/OpenOffice.org644/user/config/soffice.cfg
	fi
fi

case $program in
$0)
	cd $oopath && ./soffice "$@"
	;;
	*)
	cd $oopath && exec $program "$@"
	;;
esac
