# New ports collection makefile for:	php4
# Date created:		20 February, 2001
# Whom:			Alastair D'Silva <deece@newmillennium.net.au>
#
# $FreeBSD: ports/lang/php4/Makefile,v 1.3 2001/06/24 22:37:25 dirk Exp $
#

PORTNAME=	php4
PORTREVISION=	1
CATEGORIES=	lang

MASTERDIR=	${.CURDIR}/../../www/mod_php4
COMMENT=	${PKGDIR}/pkg-comment.standalone
PKGMESSAGE=	mustnotexist
PLIST=		${PKGDIR}/pkg-plist.standalone

STANDALONE=	yes

.include "${MASTERDIR}/Makefile"
