# New ports collection makefile for:    urwfonts
# Date created:         Sat Aug 12 15:02:03 CEST 2000
# Whom:                 olgeni@uli.it
#
# $FreeBSD: ports/x11-fonts/urwfonts/Makefile,v 1.4 2001/01/24 12:43:14 olgeni Exp $
#

PORTNAME=	urwfonts
PORTVERSION=	1.0
CATEGORIES=	x11-fonts
MASTER_SITES=	http://www.gimp.org/
DISTNAME=	urw-fonts

MAINTAINER=	olgeni@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_X_PREFIX=	yes

post-install:
	@${CAT} ${DESCR}

.include <bsd.port.mk>
