# New ports collection makefile for:	ppptraf
# Date created:		9 February 2000
# Whom:			diskiller@cnbinc.com
#
# $FreeBSD: ports/net/ppptraf/Makefile,v 1.1.1.1 2000/02/29 04:00:55 dburr Exp $
#

PORTNAME=	ppptraf
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.borg-cube.com/users/diskiller/distfiles/

MAINTAINER=	diskiller@cnbinc.com

#MAN1=		ppptraf.1

.include <bsd.port.mk>
