# New ports collection makefile for:	ppptraf
# Date created:		9 February 2000
# Whom:			diskiller@cnbinc.com
#
# $FreeBSD: ports/net/ppptraf/Makefile,v 1.2 2000/04/09 18:13:10 cpiazza Exp $
#

PORTNAME=	ppptraf
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.borg-cube.com/users/diskiller/distfiles/ \
		http://people.FreeBSD.org/~dburr/distfiles/

MAINTAINER=	diskiller@cnbinc.com

#MAN1=		ppptraf.1

.include <bsd.port.mk>
