# New ports collection makefile for:    eiffel
# Date created:         Thu Sep 14 11:10:01 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/lang/eiffel/Makefile,v 1.6 1999/08/31 06:46:44 mharo Exp $
#

PORTNAME=	eiffel
PORTVERSION=	13a
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.cm.cf.ac.uk/pub/Eiffel/SIG/Eiffel-S-1.3/BSD/
DISTNAME=	eiffels13a
EXTRACT_SUFX=	.freebsd.tar.gz

MAINTAINER=	erich@FreeBSD.org

WRKSRC=		${WRKDIR}/eiffel

.include <bsd.port.mk>
