# New ports collection makefile for:    eiffel
# Version required:     1.3
# Date created:         Thu Sep 14 11:10:01 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/lang/eiffel/Makefile,v 1.5 1999/08/25 06:34:23 obrien Exp $
#

DISTNAME=	eiffels13a
PKGNAME=	eiffel-13a
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.cm.cf.ac.uk/pub/Eiffel/SIG/Eiffel-S-1.3/BSD/
EXTRACT_SUFX=	.freebsd.tar.gz

MAINTAINER=	erich@FreeBSD.org

WRKSRC=		${WRKDIR}/eiffel

.include <bsd.port.mk>
