# New ports collection makefile for:	screen
# Date created:         25 Nov 1994
# Whom:                 ache
#
# $FreeBSD: ports/misc/screen/Makefile,v 1.32 2001/01/16 17:31:43 sobomax Exp $
#

PORTNAME=	screen
PORTVERSION=    3.9.9
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.uni-erlangen.de/pub/utilities/screen/ \
		${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	screen

MAINTAINER=	ache@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		screen.1

.include <bsd.port.mk>
