# New ports collection makefile for:	enscript (letterdj)
# Date created:			24 Jul, 1997
# Whom:				kline
#
# $FreeBSD: ports/print/enscript-letterdj/Makefile,v 1.2 1999/08/31 01:44:44 peter Exp $
#

PAPERSIZE=	letterdj
MASTERDIR=	${.CURDIR}/../enscript-letter

.include "${MASTERDIR}/Makefile"
