# New ports collection makefile for:	XEmacs with Wnn6
# Version required:	21.1.6
# Date created:		25 January 1998
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-wnn6/Makefile,v 1.6 1999/09/09 14:25:35 taoka Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../../japanese/xemacs
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
