# New ports collection makefile for:	XEmacs with Wnn6
# Date created:		25 January 1998
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-wnn6/Makefile,v 1.12 2000/07/13 09:52:59 taoka Exp $
#

COMMENT=		${.CURDIR}/pkg-comment

XEMACS_MAJOR_VER=	21
WNN6=			yes

.include	"${.CURDIR}/../xemacs${XEMACS_MAJOR_VER}-canna/Makefile"
