# $FreeBSD: ports/ukrainian/Makefile,v 1.4 2001/04/17 11:12:49 sobomax Exp $
#

    SUBDIR += gd
    SUBDIR += monacofonts
    SUBDIR += pine.language
    SUBDIR += webalizer

.include <bsd.port.subdir.mk>
