# New ports collection makefile for:	xneko
# Date created:		22 December 1995
# Whom:			markm
#
# $FreeBSD: ports/games/xneko/Makefile,v 1.12 2000/04/14 12:27:50 asami Exp $
#

PORTNAME=	xneko
PORTVERSION=	4.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.freesoftware.com/pub/4.4BSD-Lite/4.4BSD-Lite/usr/src/games/
DISTNAME=	${PORTNAME}

MAINTAINER=	markm@FreeBSD.org

MAN6=		xneko.6
MANCOMPRESSED=	maybe

USE_X_PREFIX=	yes
IGNOREFILES=	${DISTFILES}
WRKSRC=		${WRKDIR}/pub/bsd-sources/4.4BSD-Lite/usr/src/games/xneko

.include <bsd.port.mk>
