# New ports collection makefile for:	gtkyahoo
# Date created:			18 August 1999
# Whom:				dannyman@dannyland.org
#
# $FreeBSD: ports/net/gtkyahoo/Makefile,v 1.5 2001/05/16 08:38:10 jkoshy Exp $
#

PORTNAME=	gtkyahoo
PORTVERSION=	0.17
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	gtkyahoo

MAINTAINER=	anders@codefactory.se

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_BISON=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
