# New ports collection makefile for:    xtic
# Date created:         22 June 1995
# Whom:                 asami
#
# $FreeBSD: ports/games/xtic/Makefile,v 1.7 1999/08/31 06:44:52 mharo Exp $
#

PORTNAME=	xtic
PORTVERSION=	1.12
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=      yes
MAN1=		xtic.1

.include <bsd.port.mk>
