# New ports collection makefile for:	mule with Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-wnn6/Makefile,v 1.39 2000/09/08 04:34:50 taoka Exp $
#

PKGNAMESUFFIX=	-wnn6
CATEGORIES=	japanese

WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
