# New ports collection makefile for:	mule 2.3@19.34 with Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-wnn6/Makefile,v 1.36 1999/08/25 05:25:44 obrien Exp $
#

PKGNAMESUFFIX=	-wnn6
CATEGORIES=	japanese editors

WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
