# New ports collection makefile for:	buffy
# Date Created:				13 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/buffy/Makefile,v 1.4 2001/02/05 16:48:46 olgeni Exp $
#

PORTNAME=	buffy
PORTVERSION=	0.2
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://reality.sgi.com/offer/src/buffy/

MAINTAINER=	sobomax@FreeBSD.org

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
