# New ports collection makefile for:	p5-HTML-Table
# Date created:			Di  13 Mär 2001 19:37:25 CET
# Whom:				Andreas Klemm <andreas@klemm.gtn.com>
#
# $FreeBSD: ports/www/p5-HTML-Table/Makefile,v 1.3 2001/08/13 12:39:35 kevlo Exp $
#

PORTNAME=	HTML-Table
PORTVERSION=	1.11
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	HTML
PKGNAMEPREFIX=	p5-

MAINTAINER=	petef@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		HTML::Table.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
