# ex:ts=8
# New ports collection makefile for:	chemtool
# Date created:			Mar 31, 2001
# Whom:				Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/science/chemtool/Makefile,v 1.1 2001/03/30 19:22:59 ijliao Exp $

PORTNAME=	chemtool
PORTVERSION=	1.3.1
CATEGORIES=	science
MASTER_SITES=	http://www.uni-ulm.de/~s_tvolk/chemtool/src/

MAINTAINER=	ports@FreeBSD.org

RUN_DEPENDS=	transfig:${PORTSDIR}/print/transfig

USE_GTK=	yes

MAN1=	chemtool.1

.include <bsd.port.mk>
