# New ports collection makefile for:   t1utils
# Date created:        2 September 1999
# Whom:                mwm
#
# $FreeBSD: ports/print/t1utils/Makefile,v 1.5 2000/04/09 17:41:18 cpiazza Exp $
#

PORTNAME=	t1utils
PORTVERSION=	1.14
CATEGORIES=	print
MASTER_SITES=	http://www.lcdf.org/~eddietwo/type/

MAINTAINER=	mwm@phone.net

MAN1=		t1ascii.1 t1binary.1 t1asm.1 t1disasm.1 t1unmac.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
