# New ports collection makefile for:	xanim
# Date created:         Sat Nov 5 11:43:03 PST 1994
# Whom:                 Rod Taylor
#
# $FreeBSD: ports/graphics/gxanim/Makefile,v 1.4 2000/09/07 23:05:27 fenner Exp $
#

PORTNAME=	gxanim
PORTVERSION=	0.50
CATEGORIES=	graphics
MASTER_SITES=		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	fenner

MAINTAINER=	rbt@zort.on.ca

RUN_DEPENDS=	xanim:${PORTSDIR}/graphics/xanim

USE_BZIP2=	yes
USE_XLIB=	yes
USE_GTK=	yes

.include <bsd.port.mk>
