# New ports collection makefile for:	rpc2
# Date created:				Wed Mar 22 19:06:45 EST 2000
# Whom:					jaharkes
#
# $FreeBSD: ports/devel/rpc2/Makefile,v 1.5 2000/10/05 22:42:09 shafeeq Exp $
#

PORTNAME=	rpc2
PORTVERSION=	1.9
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.coda.cs.cmu.edu/pub/rpc2/src/

MAINTAINER=	coda@cs.cmu.edu

LIB_DEPENDS=	lwp.2:${PORTSDIR}/devel/lwp

USE_GMAKE=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
