# New ports collection makefile for:	JDE's DeepForest for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/deepforest/Makefile,v 1.2 1999/08/25 05:23:40 obrien Exp $
#

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../archivers/deepforest

.include	"${MASTERDIR}/Makefile"
