# New ports collection makefile for:	i960-rtems-gdb
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/i960-rtems-gdb/Makefile,v 1.1 2000/07/10 04:32:19 steve Exp $
#

PORTNAME=	gdb

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	i960-rtems
.include "${.CURDIR}/../i386-rtems-gdb/Makefile"
