# New ports collection makefile for:	textproc/p5- Text-Wrapper
# Date created:				30 December 2000
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-Text-Wrapper/Makefile,v 1.2 2001/03/01 06:39:01 vanilla Exp $
#

PORTNAME=	Text-Wrapper
PORTVERSION=	1.000
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Text
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Text::Wrapper.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
