# New ports collection makefile for:    S-Lang library
# Date created:         11 July 1996
# Whom:                 ache
#
# $FreeBSD: ports/devel/libslang/Makefile,v 1.20 2000/06/16 08:47:52 sobomax Exp $
#

PORTNAME=	libslang
PORTVERSION=	1.4.0
CATEGORIES=	devel
MASTER_SITES=	ftp://space.mit.edu/pub/davis/slang/v1.4/
DISTNAME=	slang-${PORTVERSION}

MAINTAINER=	xaa+ports@timewasters.nl

USE_BZIP2=	yes
GNU_CONFIGURE=	yes
INSTALLS_SHLIB=	yes
#WRKSRC=		${WRKDIR}/slang

ALL_TARGET=	all elf
INSTALL_TARGET=	install install-elf

.include <bsd.port.mk>
