# New ports collection makefile for: YaTeX
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-xemacs/Makefile,v 1.12 2000/04/09 17:50:57 cpiazza Exp $
#

PKGNAMESUFFIX=	-xemacs

XEMACS=		yes

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg/COMMENT

.include	"${MASTERDIR}/Makefile"
