# New ports collection makefile for: YaTeX
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-xemacs/Makefile,v 1.11 2000/04/09 17:41:39 cpiazza Exp $
#

PORTNAME=	yatex-xemacs
PORTVERSION=	1.67

XEMACS=		yes

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg/COMMENT

.include	"${MASTERDIR}/Makefile"
