# New ports collection makefile for:    splitmpg
# Date created:         Wed Jul 31 21:59:42 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/graphics/splitmpg/Makefile,v 1.6 2000/04/14 10:47:25 asami Exp $
#

PORTNAME=	splitmpg
PORTVERSION=	1.0
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.ecel.uwa.edu.au/users/michael/
DISTFILES=	${PORTNAME}.tgz

MAINTAINER=	ports@FreeBSD.org

MAN1=		splitmpeg.1
MANCOMPRESSED=	yes

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
