# New ports collection makefile for:    xmorph
# Date created:         Thu Aug  1 09:10:22 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/graphics/xmorph/Makefile,v 1.12 2000/04/23 22:59:40 kris Exp $
#

PORTNAME=	xmorph
PORTVERSION=	2000.04.28
CATEGORIES=	graphics
MASTER_SITES=	http://www.colorado-research.com/~gourlay/software/Graphics/Xmorph/pub/
DISTNAME=	${PORTNAME}-2000apr28

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
INSTALLS_SHLIB=	yes

MAN1=		xmorph.1

.include <bsd.port.mk>
