# New ports collection makefile for:    xwit
# Date created:         15 June 1998
# Whom:                 Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/x11/xwit/Makefile,v 1.8 2000/06/16 11:48:20 tg Exp $
#

PORTNAME=	xwit
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	tg

MAINTAINER=	tg@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xwit.1

.include <bsd.port.mk>
