# New ports collection makefile for:    xwit
# Version required:     1.0
# Date created:         15 June 1998
# Whom:                 Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/x11/xwit/Makefile,v 1.3 1999/08/31 02:51:22 peter Exp $
#

DISTNAME=       xwit-1.0
CATEGORIES=	x11
MASTER_SITES=   http://www.freebsd.org/~tg/

MAINTAINER=     tg@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xwit.1

.include <bsd.port.mk>
