# New ports collection makefile for:	XEmacs with Canna and Wnn4
# Version required:	21.1.6
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-canna+wnn4/Makefile,v 1.3 1999/08/25 05:27:53 obrien Exp $
#

CANNA=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../../japanese/xemacs
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
