# New ports collection makefile for:	XEmacs with Canna and Wnn4
# Version required:	21.1
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-canna+wnn4/Makefile,v 1.6 2000/01/06 01:46:31 shige Exp $
#

XEMACS_MAJOR_VER=	21
CANNA=			yes
WNN4=			yes

.include	"${.CURDIR}/../xemacs${XEMACS_MAJOR_VER}-canna/Makefile"
