# New ports collection makefile for:    lincity
# Version required:	1.04
# Date created:         13 Feb 1997
# Whom:                 Julian Assange
#
# $FreeBSD: ports/games/lincity/Makefile,v 1.5 1999/08/25 06:03:57 obrien Exp $
#

DISTNAME=       lincity-1.11
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.demon.co.uk/pub/unix/linux/games/

MAINTAINER=	proff@iq.org

USE_XLIB=	yes
ALL_TARGET=	freebsd
MAN6=		lincity.6
MANCOMPRESSED=	no

.include <bsd.port.mk>
