# New ports collection makefile for:    lincity
# Version required:	1.04
# Date created:         13 Feb 1997
# Whom:                 Julian Assange
#
# $FreeBSD: ports/games/lincity/Makefile,v 1.6 1999/09/27 16:54:27 cpiazza Exp $
#

DISTNAME=       lincity-1.11
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.demon.co.uk/pub/unix/linux/games/

MAINTAINER=	ports@FreeBSD.org

USE_XLIB=	yes
ALL_TARGET=	freebsd
MAN6=		lincity.6
MANCOMPRESSED=	no

.include <bsd.port.mk>
