# New ports collection makefile for:	SJXA
# Date created:		10 Aug 1996
# Whom:			Hidekazu Kuroki <hidekazu@cs.titech.ac.jp>
#
# $FreeBSD: ports/japanese/sjxa/Makefile,v 1.5 1999/08/25 05:26:53 obrien Exp $
#

PORTNAME=	sjxa
PORTVERSION=	1.5.11
CATEGORIES=	japanese x11
MASTER_SITES=	ftp://ftp.sony.co.jp/pub/unsupported/src/ \
		ftp://ftp.cs.titech.ac.jp/pub/japanese/sj3/

MAINTAINER=	hidekazu@cs.titech.ac.jp

RUN_DEPENDS=	sj3serv:${PORTSDIR}/japanese/sj3

USE_IMAKE=	yes

.include <bsd.port.mk>
