# New ports collection makefile for:	sparc-rtems-binutils
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sparc-rtems-binutils/Makefile,v 1.1 2000/07/10 04:32:31 steve Exp $
#

PORTNAME=	binutils

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sparc-rtems
.include "${.CURDIR}/../i386-rtems-binutils/Makefile"
