# New ports collection makefile for:  	bbmail
# Date created:		May 3 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/mail/bbmail/Makefile,v 1.11 2000/06/18 01:42:14 cpiazza Exp $
#

PORTNAME=	bbmail
PORTVERSION=	0.6.8
CATEGORIES=	mail
MASTER_SITES=	http://bbtools.thelinuxcommunity.org/sources/

MAINTAINER=	patseal@hyperhost.net

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
