# New ports collection makefile for:  	bbmail
# Version required:   	0.6.2
# Date created:		May 3 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/mail/bbmail/Makefile,v 1.8 1999/09/10 22:42:12 cpiazza Exp $
#

DISTNAME=	bbmail-0.6.2
CATEGORIES=	mail
MASTER_SITES=	http://bbtools.windsofstorm.net/sources/ \
		ftp://stokes.tte.ele.tue.nl/pub/bbmail/

MAINTAINER=	cpiazza@FreeBSD.org

GNU_CONFIGURE=	yes	
USE_XLIB=	yes	

.include <bsd.port.mk>
