# New ports collection makefile for:	ja-tcsh NLS catalog (Miyakonjo)
# Version required:	6.08.05
# Date created:		6 January 1999
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-miyakonjo/Makefile,v 1.4 1999/08/25 05:27:21 obrien Exp $
#

DISTNAME=	tcsh-6.08.05.add2
PKGNAME=	ja-tcsh-nls-miyakonjo-6.08.05
CATEGORIES=	japanese shells
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST
NLSSRC=		${DISTNAME}/nls/ja.miyakonjo

.include	"${MASTERDIR}/Makefile"
