# New ports collection makefile for:	ja-tcsh NLS catalog (Miyakonjo)
# Date created:		6 January 1999
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-miyakonjo/Makefile,v 1.5 1999/08/31 06:46:27 mharo Exp $
#

CATALOGNAME=	miyakonjo

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
