# New ports collection makefile for:	p5-Devel-DProf
# Date created:				June 15th 1997
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Devel-DProf/Makefile,v 1.13 2000/10/23 21:02:46 will Exp $
#

PORTNAME=	DProf
PORTVERSION=	19990108
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Devel
PKGNAMEPREFIX=	p5-Devel-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MAN1PREFIX=	${PREFIX}
MAN1=		dprofpp.1
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Devel::DProf.3

.include <bsd.port.mk>
