# ex:ts=8
# Ports collection makefile for:  vim-lite
# Date created:			  Fri Jun 25, 1999
# Whom:				  David O'Brien (obrien@NUXI.com)
#
# $FreeBSD: ports/editors/vim-lite/Makefile,v 1.10 2000/03/22 00:28:05 obrien Exp $
#

PORTNAME=	vim-lite

LITE=		yes

MASTERDIR=	${.CURDIR}/../vim5

.include "${MASTERDIR}/Makefile"
