# ex:ts=8
# Ports collection makefile for:  vim-lite
# Date created:			  Fri Jun 25, 1999
# Whom:				  David O'Brien (obrien@NUXI.com)
#
# $FreeBSD: ports/editors/vim-lite/Makefile,v 1.8 2000/02/13 03:24:39 obrien Exp $
#

PKGNAME=	vim-lite-${PKGVER}

LITE=		yes

MASTERDIR=	${.CURDIR}/../vim5

.include "${MASTERDIR}/Makefile"
