# ex:ts=8
# Ports collection makefile for:  vim-lite
# Version required:     	  5.3
# Date created:			  Fri Jun 25, 1999
# Whom:				  David O'Brien (obrien@NUXI.com)
#
# $FreeBSD: ports/editors/vim-lite/Makefile,v 1.5 1999/08/25 05:44:35 obrien Exp $
#

PKGNAME=	vim-lite-5.3

LITE=		yes

MASTERDIR=	${.CURDIR}/../vim5

.include "${MASTERDIR}/Makefile"
