# New ports collection makefile for:	apg
# Date created:		1 September 2000
# Whom:			roam@FreeBSD.org
#
# $FreeBSD: ports/security/apg/Makefile,v 1.1 2001/01/20 00:13:14 roam Exp $
#

PORTNAME=	apg
PORTVERSION=	1.1.61b
CATEGORIES=	security
MASTER_SITES=	http://www.adel.nursat.kz/apg/download/

MAINTAINER=	roam@FreeBSD.org

USE_GMAKE=	yes

MAN1=		apg.1
MAN8=		apgd.8

.include <bsd.port.mk>
