# New ports collection makefile for:	wmcdplay
# Date created:		7 December 1998
# Whom:			Chia-liang Kao <clkao@CirX.ORG>
#
# $FreeBSD: ports/audio/wmcdplay/Makefile,v 1.8 2000/08/03 09:22:29 asami Exp $
#

PORTNAME=	wmcdplay
PORTVERSION=	1.0b1
CATEGORIES=	audio windowmaker
MASTER_SITES=	http://www.geocities.com/SiliconValley/Vista/2471/files/
DISTNAME=	wmcdplay-1.0-beta1
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/wmcdplay

USE_IMAKE=	yes
USE_XPM=	yes

.include <bsd.port.mk>
