# New ports collection makefile for:	wmcdplay
# Date created:		7 December 1998
# Whom:			Chia-liang Kao <clkao@CirX.ORG>
#
# $FreeBSD: ports/audio/wmcdplay/Makefile,v 1.6 1999/08/25 04:36:17 obrien Exp $
#

PORTNAME=	wmcdplay
PORTVERSION=	1.0b1
CATEGORIES=	audio windowmaker
MASTER_SITES=	http://www.geocities.com/SiliconValley/Vista/2471/files/
DISTNAME=	wmcdplay-1.0-beta1
EXTRACT_SUFX=	.tgz

MAINTAINER=	clkao@CirX.ORG

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

WRKSRC=		${WRKDIR}/wmcdplay

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
