# New ports collection makefile for:	wmcdplay
# Date created:		7 December 1998
# Whom:			Chia-liang Kao <clkao@CirX.ORG>
#
# $FreeBSD: ports/audio/wmcdplay/Makefile,v 1.7 2000/04/08 21:24:42 mharo Exp $
#

PORTNAME=	wmcdplay
PORTVERSION=	1.0b1
CATEGORIES=	audio windowmaker
MASTER_SITES=	http://www.geocities.com/SiliconValley/Vista/2471/files/
DISTNAME=	wmcdplay-1.0-beta1
EXTRACT_SUFX=	.tgz

MAINTAINER=	clkao@CirX.ORG

WRKSRC=		${WRKDIR}/wmcdplay

USE_IMAKE=	yes
USE_XPM=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
