# New ports collection makefile for:	TiMidity++
# Version required:	1.3.10
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/japanese/timidity++-slang/Makefile,v 1.1.1.1 1999/10/12 17:42:23 flathill Exp $
#

INTERFACE=	slang
JAPANESE=	yes

MASTERDIR=	${.CURDIR}/../../audio/timidity++-emacs

.include "${MASTERDIR}/Makefile"
