# New ports collection makefile for:	Xtuner
# Date created:		19 December 96
# Whom:			Lars Koeller <Lars.Koeller@Uni-Bielefeld.DE>
#
# $FreeBSD: ports/audio/xtuner/Makefile,v 1.11 2000/08/03 09:22:35 asami Exp $
#

PORTNAME=	xtuner
PORTVERSION=	2.1
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.uni-bielefeld.de/pub/systems/FreeBSD/lkoeller/
DISTNAME=	Xtuner-${PORTVERSION}

MAINTAINER=	Lars.Koeller@Uni-Bielefeld.DE

LIB_DEPENDS=	xforms.0:${PORTSDIR}/x11-toolkits/xforms

USE_IMAKE=	YES
USE_XPM=	YES

.include <bsd.port.mk>
