# New ports collection makefile for:	libmorph
# Date Created:				14 September 2000
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/graphics/libmorph/Makefile,v 1.1 2000/09/14 08:18:49 sobomax Exp $
#

PORTNAME=	libmorph
PORTVERSION=	0.1.2
CATEGORIES=	graphics
MASTER_SITES=	http://wine.sexcity.pl/morpheus/meat/

MAINTAINER=	sobomax@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
