# New ports collection makefile for:	telnet8
# Date created:		13 Feb 1999
# Whom:			Ching-Hong Wu <woju@freebsd.ntu.edu.tw>
#
# $FreeBSD: ports/chinese/telnet/Makefile,v 1.3 2000/04/13 08:28:16 asami Exp $
#

PORTNAME=	telnet
PORTVERSION=	1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://bsd.sinica.edu.tw/pub/FreeBSD/taiwan/users/woju/source/
DISTNAME=	telnet8-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	woju@freebsd.ntu.edu.tw

.include <bsd.port.mk>
