# New ports collection makefile for:	telnet8
# Date created:		13 Feb 1999
# Whom:			Ching-Hong Wu <woju@freebsd.ntu.edu.tw>
#
# $FreeBSD: ports/chinese/telnet/Makefile,v 1.2 1999/08/25 04:58:01 obrien Exp $
#

PORTNAME=	telnet
PORTVERSION=	1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://freebsd.ntu.edu.tw/freebsd/woju/source/ \
		ftp://bsd.sinica.edu.tw/pub/FreeBSD/taiwan/users/woju/source/
DISTNAME=	telnet8-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	woju@freebsd.ntu.edu.tw

.include <bsd.port.mk>
