#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-2.0-devel/files/openoffice-wrapper,v 1.14 2005/01/10 12:28:19 maho Exp $

oopath=%%PREFIX%%/%%INSTALLATION_BASEDIR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%m%%MILESTONE%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
