#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.11 2003/09/17 04:06:28 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org%%FRELEASE_NR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
