# New ports collection makefile for:	tgif2tex for Japanese
# Date created:		12 Mar 1998
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/tgif2tex/Makefile,v 1.4 2000/04/12 14:38:03 knu Exp $
#

CATEGORIES=	japanese

RUN_DEPENDS=	nkf:${PORTSDIR}/japanese/nkf

MASTERDIR=	${.CURDIR}/../../print/tgif2tex
PKGDIR=		${.CURDIR}/pkg
PORTSDOCDIR=	${PREFIX}/share/doc/ja-tgif2tex
DOCSRC=		Makefile \
		how-to-use.tex \
		sample1.obj \
		sample2.obj

.include "${MASTERDIR}/Makefile"
