# New ports collection makefile for:    xmfract
# Date created:         Thu Aug  1 09:10:22 CDT 1996
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/graphics/xmfract/Makefile,v 1.6 1999/08/25 06:15:27 obrien Exp $
#

PORTNAME=	xmfract
PORTVERSION=	1.4
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	erich@FreeBSD.org

REQUIRES_MOTIF=	yes
USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
