# New ports collection makefile for:    xlisp-stat
# Date created:         Tue Aug 15 17:57:48 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/math/xlispstat/Makefile,v 1.9 1999/12/23 23:50:12 steve Exp $
#

PORTNAME=	xlispstat
PORTVERSION=	3.52.9
CATEGORIES=	math lang
MASTER_SITES=	ftp://ftp.stat.umn.edu/pub/xlispstat/current/   \
		http://lib.stat.cmu.edu/xlispstat/Src/current/  \
		ftp://ftp.stat.unipg.it/pub/stat/xlispstat/current/     \
		ftp://srsuna.shlrc.mq.edu.au/pub/xlispstat/current/     \
		ftp://statlab.uni-heidelberg.de/pub/mirrors/umn/xlispstat/current
DISTNAME=	xlispstat-3-52-9

MAINTAINER=	erich@FreeBSD.org

USE_XLIB=	yes
HAS_CONFIGURE=	yes
ALL_TARGET=

.include <bsd.port.mk>
