# $FreeBSD: ports/biology/Makefile,v 1.12 1999/08/25 04:47:53 obrien Exp $
#

    SUBDIR += babel
    SUBDIR += deft
    SUBDIR += gperiodic
    SUBDIR += hmmer
    SUBDIR += kinemage
    SUBDIR += molden
    SUBDIR += mopac
    SUBDIR += ortep3
    SUBDIR += platon
    SUBDIR += povchem
    SUBDIR += psi88
    SUBDIR += rasmol
    SUBDIR += seaview
    SUBDIR += tinker
    SUBDIR += xmolwt

.include <bsd.port.subdir.mk>
