# $FreeBSD: ports/biology/Makefile,v 1.13 1999/09/06 20:09:12 taoka Exp $
#

    SUBDIR += babel
    SUBDIR += chemeq
    SUBDIR += clustalw
    SUBDIR += deft
    SUBDIR += gperiodic
    SUBDIR += hmmer
    SUBDIR += kinemage
    SUBDIR += molden
    SUBDIR += mopac
    SUBDIR += ortep3
    SUBDIR += paml
    SUBDIR += phylip
    SUBDIR += platon
    SUBDIR += povchem
    SUBDIR += psi88
    SUBDIR += rasmol
    SUBDIR += seaview
    SUBDIR += tinker
    SUBDIR += xmolwt

.include <bsd.port.subdir.mk>
