# $FreeBSD: ports/biology/Makefile,v 1.16 2000/07/27 14:32:50 nbm Exp $
#

    SUBDIR += babel
    SUBDIR += chemeq
    SUBDIR += clustalw
    SUBDIR += deft
    SUBDIR += gperiodic
    SUBDIR += hmmer
    SUBDIR += kinemage
    SUBDIR += molden
    SUBDIR += mopac
    SUBDIR += ortep3
    SUBDIR += p5-AcePerl
    SUBDIR += paml
    SUBDIR += phylip
    SUBDIR += platon
    SUBDIR += povchem
    SUBDIR += psi88
    SUBDIR += rasmol
    SUBDIR += seaview
    SUBDIR += sim4
    SUBDIR += tinker
    SUBDIR += xdrawchem
    SUBDIR += xmolwt

.include <bsd.port.subdir.mk>
