# New ports collection makefile for:	fltk-xunicode
# Date created:		25 Aug 2000
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/x11-toolkits/fltk-xunicode/Makefile,v 1.1 2000/08/25 18:24:49 knu Exp $
#

MASTERDIR=	${.CURDIR}/../fltk

MAINTAINER=	knu@FreeBSD.org

COMMENT=	${.CURDIR}/pkg-comment

WITH_XUNICODE=	yes

.include "${MASTERDIR}/Makefile"
