# New ports collection makefile for:    p5-Authen-PAM
# Date created:				Mon Oct  4 1999
# Whom:	      				Matt Behrens <matt@zigg.com>
#
# $FreeBSD: ports/security/p5-Authen-PAM/Makefile,v 1.4 2000/06/17 02:36:45 will Exp $
#

PORTNAME=	Authen-PAM
PORTVERSION=	0.09
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Authen
PKGNAMEPREFIX=	p5-

MAINTAINER=	matt@zigg.com

PERL_CONFIGURE=	yes

MAN3=		Authen::PAM.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
