# New ports collection makefile for:	yabasic
# Date created:		11 Nov 1999
# Whom:			Frank Gruender
#
# $FreeBSD: ports/lang/yabasic/Makefile,v 1.9 2001/01/20 09:38:53 clive Exp $
#

PORTNAME=	yabasic
PORTVERSION=	2.681
CATEGORIES=	lang
MASTER_SITES=	http://www.yabasic.de/download/

MAINTAINER=	elwood@mc5sys.in-berlin.de

BROKEN=		"Patches fail to apply; needs to be updated to new version"

USE_BISON=	yes
USE_XLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
