# New ports collection makefile for:	yabasic
# Date created:		11 Nov 1999
# Whom:			Frank Gruender
#
# $FreeBSD: ports/lang/yabasic/Makefile,v 1.7 2000/09/22 02:19:24 kris Exp $
#

PORTNAME=	yabasic
PORTVERSION=	2.64
CATEGORIES=	lang
MASTER_SITES=	http://www.yabasic.de/download/
DISTFILES=	yab.tar.Z

MAINTAINER=	elwood@mc5sys.in-berlin.de

USE_BISON=	yes
USE_XLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
