# New ports collection makefile for:	yabasic
# Date created:		11 Nov 1999
# Whom:			Frank Gruender
#
# $FreeBSD: ports/lang/yabasic/Makefile,v 1.8 2000/09/25 12:21:27 asami Exp $
#

PORTNAME=	yabasic
PORTVERSION=	2.66
CATEGORIES=	lang
MASTER_SITES=	http://www.yabasic.de/download/
DISTFILES=	yab.tar.Z

MAINTAINER=	elwood@mc5sys.in-berlin.de

USE_BISON=	yes
USE_XLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
