# New ports collection makefile for:	mpd
# Date created:				26 Jun 2000
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/suckblow/Makefile,v 1.1 2000/06/28 00:31:45 archie Exp $
#

PORTNAME=	suckblow
PORTVERSION=	1.1
CATEGORIES=	net misc
MASTER_SITES=	http://people.FreeBSD.org/~archie/distfiles/

MAINTAINER=	archie@freebsd.org

MAN1=		suck.1
MLINKS=		suck.1 blow.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
