# New ports collection makefile for:    xmj
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xmj/Makefile,v 1.13 2001/01/16 17:30:43 sobomax Exp $
#

PORTNAME=	xmj
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://forte.mathematik.uni-bremen.de/pub/comp/X11/
DISTNAME=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
