# New ports collection makefile for:    xmj
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xmj/Makefile,v 1.10 2000/04/14 12:27:46 asami Exp $
#

PORTNAME=	xmj
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://forte.mathematik.uni-bremen.de/pub/comp/X11/
DISTNAME=       ${PORTNAME}

MAINTAINER=	swallace@FreeBSD.org

USE_IMAKE=	yes
NO_INSTALL_MANPAGES= yes

.include <bsd.port.mk>
