# New ports collection makefile for:    xmj
# Date created:         2 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xmj/Makefile,v 1.12 2001/01/09 19:36:17 sf Exp $
#

PORTNAME=	xmj
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://forte.mathematik.uni-bremen.de/pub/comp/X11/
DISTNAME=	${PORTNAME}

MAINTAINER=	swallace@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
