# New ports collection makefile for:	sysutils/p5-Stat-lsMode
# Date created:				25 April 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/sysutils/p5-Stat-lsMode/Makefile,v 1.1 2001/04/28 14:21:39 joe Exp $
#

PORTNAME=	Stat-lsMode
PORTVERSION=	0.50
CATEGORIES=	sysutils perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Stat
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Stat::lsMode.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
