# New ports collection makefile for:    xkeycaps
# Date created:         12 February 1995
# Whom:                 jmz
#
# $FreeBSD: ports/x11/xkeycaps/Makefile,v 1.14 2000/06/13 13:28:19 jmz Exp $
#

PORTNAME=	xkeycaps
PORTVERSION=	2.46
CATEGORIES=	x11
MASTER_SITES=	http://www.jwz.org/xkeycaps/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xkeycaps.1

.include <bsd.port.mk>
