# New ports collection makefile for:    xkeycaps
# Date created:         12 February 1995
# Whom:                 jmz
#
# $FreeBSD: ports/x11/xkeycaps/Makefile,v 1.12 1999/09/27 19:55:54 jmz Exp $
#

PORTNAME=	xkeycaps
PORTVERSION= 	2.45
CATEGORIES=	x11
MASTER_SITES=	http://www.jwz.org/xkeycaps/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xkeycaps.1

.include <bsd.port.mk>
