# New ports collection makefile for:    xkeycaps
# Date created:         12 February 1995
# Whom:                 jmz
#
# $FreeBSD: ports/x11/xkeycaps/Makefile,v 1.15 2001/02/05 16:18:32 olgeni Exp $
#

PORTNAME=	xkeycaps
PORTVERSION=	2.46
PORTREVISION=	1
CATEGORIES=	x11
MASTER_SITES=	http://www.jwz.org/xkeycaps/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xkeycaps.1

.include <bsd.port.mk>
