# New ports collection makefile for:	ja-tcsh NLS catalog (Merril)
# Date created:		6 January 1999
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-merril/Makefile,v 1.6 2000/04/12 14:37:54 knu Exp $
#

CATALOGNAME=	merril

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

.include	"${MASTERDIR}/Makefile"
