# $FreeBSD: ports/devel/linuxthreads/files/Makefile.libgcc_r,v 1.3 2000/11/06 19:43:33 jasone Exp $

PREFIX?=	${DESTDIR}/usr/local
LIBDIR=		${PREFIX:S,^${DESTDIR},,}/lib

CFLAGS+=-D_PTHREADS -I../
CFLAGS+=-I../sysdeps/i386 -I../sysdeps/pthread -I../sysdeps/unix/sysv/linux
CXXFLAGS=	${CXXINCLUDES} ${CFLAGS}

installincludes:

.include "Makefile.inc"

#
# Override various things that are set in the main Makefile.
#

.undef SUBDIR
