# $FreeBSD: ports/devel/linuxthreads/files/Makefile.libgcc_r,v 1.4 2002/06/08 18:27:19 tegge Exp $

PREFIX?=	${DESTDIR}/usr/local
LIBDIR=		${PREFIX:S,^${DESTDIR},,}/lib

CFLAGS+=-D_PTHREADS -I../
CFLAGS+=-I../sysdeps/i386 -I../sysdeps/pthread -I../sysdeps/unix/sysv/linux
CXXFLAGS=	${CXXINCLUDES} ${CFLAGS:C/-std=[a-z:0-9]+//}

installincludes:

.include "Makefile.inc"

#
# Override various things that are set in the main Makefile.
#

.undef SUBDIR
