# $FreeBSD: ports/devel/linuxthreads/files/Makefile.libgcc_r,v 1.1 1999/12/02 02:14:14 julian Exp $

DESTDIR=/usr/local/
LIBDIR= lib/

CFLAGS+=-D_PTHREADS -I../

.include "/usr/src/gnu/lib/libgcc/Makefile"

#
# Override various things that are set in the main Makefile.
#

GCCDIR:=$(GCCDIR:T:S/^/\/usr\/src\/contrib\/&/)

LIB=	lgcc_r

.PATH: ${GCCDIR}/cp ${GCCDIR}
