# New ports collection makefile for:	iconv
# Date created:				21 September 1999
# Whom:			Konstantin Chuguev <Konstantin.Chuguev@dante.org.uk>
#
# $FreeBSD: ports/converters/iconv/Makefile,v 1.5 2000/09/12 10:06:46 sobomax Exp $
#

PORTNAME=	iconv
PORTVERSION=	1.1
CATEGORIES=	converters
MASTER_SITES=	http://www.dante.net/staff/konstantin/FreeBSD/iconv/

MAINTAINER=	Konstantin.Chuguev@dante.org.uk

USE_PERL5=	yes
INSTALLS_SHLIB=	yes

MANCOMPRESSED=	yes
MAN1=		iconv.1
MAN3=		iconv.3 iconv_open.3 iconv_close.3

.include <bsd.port.mk>
