# New ports collection makefile for:	iconv
# Date created:		21 Sep 1999
# Whom:			joy@urc.ac.ru
#
# $FreeBSD: ports/converters/iconv/Makefile,v 1.1.1.1 1999/11/01 03:30:58 steve Exp $
#

PORTNAME=	iconv
PORTVERSION=	0.2
CATEGORIES=	converters
MASTER_SITES=	ftp://ftp.urc.ac.ru/pub/OS/FreeBSD/converters/

MAINTAINER=	joy@urc.ac.ru

MAN1=		iconv.1
MAN3=		iconv.3 iconv_close.3 iconv_open.3
MANCOMPRESSED=	yes

.include <bsd.port.mk>
