# New ports collection makefile for:	cflow
# Date created:		28 Sept 1995
# Whom:			dchapes@zeus.leitch.com
#
# $FreeBSD: ports/devel/cflow/Makefile,v 1.7 2000/04/11 21:27:20 mharo Exp $
#

PORTNAME=	cflow
PORTVERSION=	2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	devel/lang/c

MAINTAINER=	dchapes@zeus.leitch.com

USE_GMAKE=	yes
MAN1=		cflow.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
