# New ports collection makefile for:	cflow
# Date created:		28 Sept 1995
# Whom:			dchapes@zeus.leitch.com
#
# $FreeBSD: ports/devel/cflow/Makefile,v 1.8 2000/06/07 22:07:05 asami Exp $
#

PORTNAME=	cflow
PORTVERSION=	2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	devel/lang/c

MAINTAINER=	bsdport@ddm.wox.org

USE_GMAKE=	yes
MAN1=		cflow.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
