# New ports collection makefile for:	cflow
# Date created:		28 Sept 1995
# Whom:			dchapes@zeus.leitch.com
#
# $FreeBSD: ports/devel/cflow/Makefile,v 1.6 1999/08/25 05:47:31 obrien Exp $
#

PORTNAME=	cflow
PORTVERSION=	2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	devel/lang/c

MAINTAINER=	dchapes@zeus.leitch.com

USE_GMAKE=	yes

.include <bsd.port.mk>
