#!/bin/sh
#
# Wrapper for the real fetchmailconf.  Checks whether Python is installed,
# and runs the real fetchmailconf or alerts the user, as appropriate.
#
# $FreeBSD: ports/mail/fetchmail/files/fetchmailconf,v 1.2 1999/08/30 12:06:24 peter Exp $

PREFIX=@PREFIX@

if [ -e $PREFIX/bin/python ]; then
	exec $PREFIX/libexec/fetchmailconf.bin
else
	cat <<EOF
The fetchmailconf program requires Python with Tkinter , which does not
appear to be installed on this system.  Python/Tkinter can be found in
the FreeBSD Ports Collection under x11/py-tkinter.
EOF
	exit 1
fi
