# New ports collection makefile for: socket
# Date created:         14 August 1996
# Whom:                 wosch
#
# $FreeBSD: ports/sysutils/socket/Makefile,v 1.9 1999/09/19 10:30:45 wosch Exp $
#

PORTNAME=	socket
PORTVERSION= 	1.1
CATEGORIES=	sysutils net
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		socket.1

.include <bsd.port.mk>
