# New ports collection makefile for: socket
# Version required:     1.1
# Date created:         14 August 1996
# Whom:                 wosch
#
# $FreeBSD: ports/sysutils/socket/Makefile,v 1.8 1999/08/31 02:00:05 peter Exp $
#

DISTNAME=       socket-1.1
CATEGORIES=	sysutils net
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		socket.1

.include <bsd.port.mk>
