# New ports collection makefile for: bgrot
# Date created:			12 January 1999
# Whom:				Matthew Fuller <fullermd@futuresouth.com>
#
# $FreeBSD: ports/x11/bgrot/Makefile,v 1.3 1999/08/31 02:50:09 peter Exp $
#

PORTNAME=	bgrot
PORTVERSION= 	1.20
CATEGORIES=	x11
MASTER_SITES=	http://www.futuresouth.com/~fullermd/bgrot/ \
		http://www.over-yonder.net/~fullermd/bgrot/

MAINTAINER=	fullermd@futuresouth.com

RUN_DEPENDS=	xv:${PORTSDIR}/graphics/xv

USE_PERL5=	yes

MAN1=		bgrot.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
