# New ports collection makefile for: bgrot
# Date created:			12 January 1999
# Whom:				Matthew Fuller <fullermd@futuresouth.com>
#
# $FreeBSD: ports/x11/bgrot/Makefile,v 1.5 2000/06/27 12:23:15 alex Exp $
#

PORTNAME=	bgrot
PORTVERSION=	1.30
CATEGORIES=	x11
MASTER_SITES=	http://www.over-yonder.net/~fullermd/projects/bgrot/ \
		http://www.futuresouth.com/~fullermd/bgrot/

MAINTAINER=	fullermd@over-yonder.net

RUN_DEPENDS=	xv:${PORTSDIR}/graphics/xv

USE_PERL5=	yes

MAN1=		bgrot.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
