# New ports collection makefile for:	p5-Net-Netmask
# Date created:				Jan 28 2000
# Whom:					Wei-chun Chao
#
# $FreeBSD: ports/net/p5-Net-Netmask/Makefile,v 1.1 2000/06/30 01:12:14 will Exp $
#

PORTNAME=	Net-Netmask
PORTVERSION=	1.8
CATEGORIES=	net perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Net
PKGNAMEPREFIX=	p5-

MAINTAINER=	wchao@isi.edu

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Net::Netmask.3

.include <bsd.port.mk>
