# New ports collection makefile for:   gnet
# Date created:        16 February 2000
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/net/gnet/Makefile,v 1.10 2000/10/05 06:22:58 reg Exp $
#

PORTNAME=	gnet
PORTVERSION=	1.0.4
CATEGORIES=	net
MASTER_SITES=	http://www.eecs.umich.edu/~dhelder/misc/gnet/src/

MAINTAINER=	nakai@FreeBSD.org

USE_GLIB=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
