# New ports collection makefile for:   gnet
# Date created:        16 February 2000
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/net/gnet/Makefile,v 1.9 2000/06/16 21:51:47 asami Exp $
#

PORTNAME=	gnet
PORTVERSION=	1.0.3
CATEGORIES=	net
MASTER_SITES=	http://www.eecs.umich.edu/~dhelder/misc/gnet/src/

MAINTAINER=	nakai@FreeBSD.org

USE_GLIB=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
