# New ports collection makefile for:	xchat-ja
# Date created:		30 Sep 2000
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/xchat/Makefile,v 1.9 2001/09/03 16:59:59 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

CONFIGURE_ARGS=	--enable-japanese-conv

MASTERDIR=	${.CURDIR}/../../x11/gnomecore

.include "${MASTERDIR}/Makefile"
