# New ports collection makefile for:	xchat-ja
# Date created:		30 Sep 2000
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/xchat/Makefile,v 1.10 2001/09/04 19:41:58 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

CONFIGURE_ARGS=	--enable-japanese-conv

MASTERDIR=	${.CURDIR}/../../irc/xchat

.include "${MASTERDIR}/Makefile"
