# New ports collection makefile for:	everybuddy
# Date created:			1 Mar 2000
# Whom:				Jim Mock <jim@FreeBSD.org>
#
# $FreeBSD: ports/net/everybuddy/Makefile,v 1.9 2001/01/21 09:02:41 jim Exp $
#

PORTNAME=	everybuddy
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	http://www.everybuddy.com/files/

MAINTAINER=	jim@FreeBSD.org

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GTK=	yes
GNU_CONFIGURE=	yes

MAN1=		everybuddy.1

.include <bsd.port.mk>
