# New ports collection makefile for:	everybuddy
# Date created:			1 Mar 2000
# Whom:				Jim Mock <jim@FreeBSD.org>
#
# $FreeBSD: ports/net/everybuddy/Makefile,v 1.5 2000/10/03 17:06:17 jim Exp $
#

PORTNAME=	everybuddy
PORTVERSION=	0.1.4.2
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	http://www.everybuddy.com/files/
DISTNAME=	${PORTNAME}-${PORTVERSION:S/.2/-2/}

MAINTAINER=	jim@FreeBSD.org

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GNOME=	yes
GNU_CONFIGURE=	yes

MAN1=		everybuddy.1

.include <bsd.port.mk>
