# New ports collection makefile for:	messarge
# Date created:				2000 May 29
# Whom:					@BABOLO <.@babolo.ru>
#
# $FreeBSD: ports/russian/messarge/Makefile,v 1.2 2000/06/09 23:01:00 will Exp $
#

PORTNAME=	messarge
PORTVERSION=	1.19
CATEGORIES=	russian mail www
MASTER_SITES=	ftp://ftp.kiarchive.ru/pub/unix/mail/ \
		http://www.links.ru/soft/messarge/

MAINTAINER=	.@babolo.ru

MAN1=		messarge.1 mesraw.1 mesdbc.1 mesarc.1 mestun.1
MANLANG=	ru_RU.KOI8-R
MANCOMPRESSED=	yes

.include <bsd.port.mk>
