# New ports collection makefile for:	Apache::AddHostPath
# Date created:				04 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/www/p5-Apache-AddHostPath/Makefile,v 1.1 2001/01/03 23:21:23 will Exp $
#

PORTNAME=	Apache-AddHostPath
PORTVERSION=	0.02
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Apache
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Apache::AddHostPath.3

.include <bsd.port.mk>
