# New ports collection makefile for:    xcept
# Date created:         Sep 1, 1996
# Whom:                 joerg
#
# $FreeBSD: ports/comms/xcept/Makefile,v 1.11 2000/04/08 23:22:43 mharo Exp $
#

PORTNAME=	xcept
PORTVERSION=	2.1.2
CATEGORIES=	comms
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS

MAINTAINER=	joerg@FreeBSD.org

USE_XLIB=	yes
MAN1=		xcept.1
MAN8=		ceptd.8
MANCOMPRESSED=	maybe

WRKSRC=		${WRKDIR}/XCept-${PORTVERSION}

.include <bsd.port.mk>
