# New ports collection makefile for:    xcept
# Version required:     2.1.2
# Date created:         Sep 1, 1996
# Whom:                 joerg
#
# $FreeBSD: ports/comms/xcept/Makefile,v 1.9 1999/08/25 05:12:40 obrien Exp $
#

DISTNAME=       xcept-2.1.2
CATEGORIES=	comms
MASTER_SITES=   ${MASTER_SITE_LOCAL}

MAINTAINER=     joerg@FreeBSD.org

USE_XLIB=	yes
MAN1=		xcept.1
MAN8=		ceptd.8
MANCOMPRESSED=	maybe

WRKSRC=		${WRKDIR}/XCept-2.1.2

.include <bsd.port.mk>
