# New ports collection makefile for: linux-netscape47-navigator
# Date created:			Tue Mar  7 22:59:55 CET 2000
# Whom:				Dirk Froemberg <dirk@FreeBSD.org>
# Based on work by:		girgen@partitur.se
#
# $FreeBSD: ports/www/linux-netscape47-navigator/Makefile,v 1.22 2000/04/10 00:05:45 cpiazza Exp $
#

BROWSER_NAME=	navigator

.include "../linux-netscape47-communicator/Makefile"
