# New ports collection makefile for:	acpicatools
# Date created:		25 Jun 2001
# Whom:			Mitsuru IWASAKI <iwasaki@FreeBSD.org>
#
# $FreeBSD: ports/devel/acpicatools/Makefile,v 1.2 2001/08/29 18:09:47 iwasaki Exp $
#

PORTNAME=	acpicatools
PORTVERSION=	20010920.0
CATEGORIES=	devel
MASTER_SITES=	http://people.FreeBSD.org/~iwasaki/acpi/ \
		http://developer.intel.com/technology/iapc/acpi/downloads/ \
		${MASTER_SITE_PORTS_JP}
DISTFILES=	${DISTNAME}${EXTRACT_SUFX} \
		acpica-unix-20010920.tar.gz
WRKSRC=		${WRKDIR}

MAINTAINER=	iwasaki@FreeBSD.org

.include <bsd.port.mk>
