# New ports collection makefile for:	acpicatools
# Date created:		25 Jun 2001
# Whom:			Mitsuru IWASAKI <iwasaki@FreeBSD.org>
#
# $FreeBSD: ports/devel/acpicatools/Makefile,v 1.1 2001/06/25 15:37:17 iwasaki Exp $
#

PORTNAME=	acpicatools
PORTVERSION=	20010816.0
CATEGORIES=	devel
MASTER_SITES=	http://people.FreeBSD.org/~iwasaki/acpi/ \
		ftp://download.intel.com/technology/iapc/acpi/downloads/ \
		${MASTER_SITE_PORTS_JP}
DISTFILES=	${DISTNAME}${EXTRACT_SUFX} \
		acpica-unix-20010816.tar.gz
WRKSRC=		${WRKDIR}

MAINTAINER=	iwasaki@FreeBSD.org

.include <bsd.port.mk>
