# New ports collection makefile for:	oroborus
# Date created:				19 April 2001
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-wm/oroborus/Makefile,v 1.4 2001/06/08 08:24:42 sobomax Exp $
#

PORTNAME=	oroborus
PORTVERSION=	1.14.0
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.kensden.pwp.blueyonder.co.uk/Oroborus/files/
#DISTNAME=	${PORTNAME}-src-v${PORTVERSION}

MAINTAINER=	olgeni@FreeBSD.org

USE_XPM=	yes
USE_X_PREFIX=	yes
USE_GMAKE=	yes
MAKE_ENV=	MKDIR="${MKDIR}"

.include <bsd.port.mk>
