# New ports collection makefile for:	xd
# Date created:		17 October 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/misc/xd/Makefile,v 1.3 1999/08/25 07:23:08 obrien Exp $
#

PORTNAME=	xd
PORTVERSION=	2.3
CATEGORIES=	misc
MASTER_SITES=	http://spock.vector.co.jp/authors/VA004959/xd/
DISTNAME=	xd-8087

MAINTAINER=	kiri@kiri.toba-cmt.ac.jp

MAN1=		xd.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
