#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.1 2002/10/18 22:41:29 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org-643/program/
program=`echo $0 | sed -e 's|.*-||'`

case $program in
$0)
	exec $oopath/soffice "$@"
	;;
	*)
	exec $oopath/$program "$@"
	;;
esac
