# New ports collection makefile for: speak
# Version required:	1.2
# Date created:		18 January 2000
# Whom:			freebsd@spatula.net
#
# $FreeBSD: ports/games/speak/Makefile,v 1.1.1.1 2000/01/24 03:32:48 jedgar Exp $
#

DISTNAME=	speak-1.2
CATEGORIES=	games
MASTER_SITES=	http://www.spatula.net/software/speak/

MAINTAINER=	freebsd@spatula.net

.include <bsd.port.mk>
