# New ports collection makefile for: speak
# Date created:		18 January 2000
# Whom:			freebsd@spatula.net
#
# $FreeBSD: ports/games/speak/Makefile,v 1.2 2000/02/15 19:19:47 billf Exp $
#

PORTNAME=	speak
PORTVERSION=	1.2
CATEGORIES=	games
MASTER_SITES=	http://www.spatula.net/software/speak/

MAINTAINER=	freebsd@spatula.net

.include <bsd.port.mk>
