# New ports collection makefile for:	Q3 Mod: OSP Tourney DM/CA/CTF
# Date created:				Mon Jun  4 16:20:32 EDT 2001
# Whom:					pat@databits.net
#
# $FreeBSD: ports/games/q3server-osp/Makefile,v 1.1 2001/07/22 02:24:06 lioux Exp $
#

PORTNAME=	osp
PORTVERSION=	0.99v2
MASTER_SITES=	http://www.orangesmoothie.org/downloads/beta/
DISTNAME=	${PORTNAME}-quake3-${PORTVERSION}

Q3_MOD_MASTER=	${.CURDIR}/../q3server-ra3

.include "${Q3_MOD_MASTER}/Makefile"
