# $FreeBSD: ports/french/Makefile,v 1.4 2001/04/13 09:22:08 demon Exp $
#

    SUBDIR += ispell
    SUBDIR += kde2-i18n
    SUBDIR += php_doc
    SUBDIR += staroffice52

.include <bsd.port.subdir.mk>
