# New ports collection makefile for:	gtkglarea
# Date created:		1 August 1999
# Whom:			Michael Sardo <jaeger16@yahoo.com>
#
# $FreeBSD: ports/x11-toolkits/gtkglarea/Makefile,v 1.10 2000/10/05 06:42:45 reg Exp $
#

PORTNAME=	gtkglarea
PORTVERSION=	1.2.2
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://www.student.oulu.fi/~jlof/gtkglarea/download/

MAINTAINER=	jaeger16@yahoo.com

USE_MESA=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
CONFIGURE_ARGS=	--with-lib-GL

.include <bsd.port.mk>
