# New ports collection makefile for:    gperf
# Date created:         19.04.1999
# Whom:                 dirk.meyer@dinoex.sub.org
#
# $FreeBSD: ports/devel/gperf/Makefile,v 1.4 2000/04/11 21:28:10 mharo Exp $
#

PORTNAME=	gperf
PORTVERSION=	2.7.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gperf

MAINTAINER=	dirk.meyer@dinoex.sub.org

GNU_CONFIGURE=	yes
MAN1=		gperf.1

.include <bsd.port.mk>
