# New ports collection makefile for:    unix-connect
# Version required:     2.7
# Date created:         19.04.1999
# Whom:                 dirk.meyer@dinoex.sub.org
#
# $FreeBSD: ports/devel/gperf/Makefile,v 1.1 1999/12/29 09:09:36 steve Exp $
#

DISTNAME=	gperf-2.7
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gperf

MAINTAINER=	dirk.meyer@dinoex.sub.org

GNU_CONFIGURE=	yes
MAN1=		gperf.1

.include <bsd.port.mk>
