# New ports collection makefile for:	xml-i18n-tools
# Date created:				19th January 2001
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/textproc/xml-i18n-tools/Makefile,v 1.5 2001/05/04 21:39:45 ade Exp $
#

PORTNAME=	xml-i18n-tools
PORTVERSION=	0.8.1
CATEGORIES=	textproc gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/${PORTNAME}

MAINTAINER=	gnome@FreeBSD.org

USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
