# New ports collection makefile for:	logo
# Date created:		22 October 1994
# Whom:			jkh
#
# $FreeBSD: ports/lang/logo/Makefile,v 1.16 1999/08/31 06:46:48 mharo Exp $
#

PORTNAME=	ucblogo
PORTVERSION=	4.6
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU} \
		ftp://anarres.cs.berkeley.edu/pub/ucblogo/
MASTER_SITE_SUBDIR=	ucblogo

MAINTAINER=	jmacd@FreeBSD.org

USE_XLIB=	yes
MAKEFILE=	makefile
HAS_CONFIGURE=	yes

.include <bsd.port.mk>
