# New ports collection makefile for:	gtkbe
# Date Created:				6 July 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/gtkbe/Makefile,v 1.5 2000/10/05 06:42:44 reg Exp $
#

PORTNAME=	gtkbe
PORTVERSION=	200007091019
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	GTK-Be-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/GTKBeEngine

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
