# New ports collection makefile for:	xcut
# Date created:			23 September 1999
# Whom:				Cy Schubert <Cy.Schubert@uumail.gov.bc.ca>
#
# $FreeBSD: ports/x11/xcut/Makefile,v 1.1.1.1 1999/11/01 03:18:28 steve Exp $
#

PORTNAME=	xcut
PORTVERSION= 	0.2
CATEGORIES=	x11
MASTER_SITES=	http://acsys.anu.edu.au/~tpot/xcut/

MAINTAINER=	Cy.Schubert@uumail.gov.bc.ca

USE_IMAKE=	YES
MAN1=		xcut.1

.include <bsd.port.mk>
