# New ports collection makefile for:    viewfax
# Date created:         16 sept 1995
# Whom:                 jmz
#
# $FreeBSD: ports/comms/viewfax/Makefile,v 1.13 2000/02/02 22:37:39 mharo Exp $
#

PORTNAME=	viewfax
PORTVERSION=	2.3
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.leo.org/pub/comp/os/unix/networking/mgetty/

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes

MAN1=		viewfax.1

.include <bsd.port.mk>
