# New ports collection makefile for:    viewfax
# Version required:     2.3
# Date created:         16 sept 1995
# Whom:                 jmz
#
# $FreeBSD: ports/comms/viewfax/Makefile,v 1.12 1999/08/25 05:12:40 obrien Exp $
#

DISTNAME=       viewfax-2.3
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.leo.org/pub/comp/os/unix/networking/mgetty/

MAINTAINER=	jmz@FreeBSD.org

USE_IMAKE=	yes

MAN1=		viewfax.1

.include <bsd.port.mk>
