# New ports collection makefile for:	nucleus
# Date created:				Sat Aug 12 15:02:03 CEST 2000
# Whom:					olgeni@uli.it
#
# $FreeBSD: ports/x11-fonts/nucleus/Makefile,v 1.1 2000/09/16 04:23:50 will Exp $
#

PORTNAME=	nucleus
PORTVERSION= 	0.77
CATEGORIES=	x11-fonts
MASTER_SITES=	http://dreamer.nitro.dk/linux/lfp/

MAINTAINER=	olgeni@uli.it

NO_WRKSUBDIR=	yes
USE_X_PREFIX=	yes

post-install:
	@${CAT} ${DESCR}

.include <bsd.port.mk>
