# New ports collection makefile for:	libao
# Date created:				18 October 2000
# Whom:					t.vanklaveren@student.utwente.nl
#
# $FreeBSD: ports/audio/libao/Makefile,v 1.3 2000/11/16 13:06:27 asami Exp $
#

PORTNAME=	libao
PORTVERSION=	0.6.0
CATEGORIES=	audio
MASTER_SITES=	http://home.student.utwente.nl/t.vanklaveren/distfiles/ \
		http://www.vorbis.com/files/beta4/unix/

MAINTAINER=	t.vanklaveren@student.utwente.nl

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_LIBTOOL=	yes
USE_AUTOMAKE=	yes

INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
