# New ports collection makefile for: Netscape browser with Japanese resources
# Date created:		13 Mar 1998
# Whom:			sada
#
# $FreeBSD: ports/japanese/netscape47-communicator/Makefile,v 1.20 2000/07/19 14:32:36 sada Exp $
#

DISTNAME=	communicator-ja-euc-v474-export.generic-generic-generic

MASTERDIR=	${.CURDIR}/../netscape4-communicator
SUBMASTERDIR=	${.CURDIR}/../netscape${BROWSER_VER}-communicator
FILESDIR=	${SUBMASTERDIR}/files
PATCHDIR=	${SUBMASTERDIR}/patches
PKGDIR=		${SUBMASTERDIR}/pkg

BROWSER_VER=	47
BROWSER_VERSION=	4.74
NETHELP=	nethelp-v47

.include "${MASTERDIR}/Makefile"
