# New ports collection makefile for:	libol
# Date created:				22 April 2000
# Whom:					Vince Valenti <vince@blue-box.net>
#
# $FreeBSD: ports/devel/libol/Makefile,v 1.3 2000/06/16 21:49:55 asami Exp $
#

PORTNAME=	libol
PORTVERSION=	0.2.17
CATEGORIES=	devel
MASTER_SITES=	http://www.balabit.hu/downloads/libol/0.2/

MAINTAINER=	vince@blue-box.net

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
