# New ports collection makefile for:	libol
# Date created:				22 April 2000
# Whom:					Vince Valenti <vince@blue-box.net>
#
# $FreeBSD: ports/devel/libol/Makefile,v 1.6 2000/10/03 15:23:42 kevlo Exp $
#

PORTNAME=	libol
PORTVERSION=	0.2.21
CATEGORIES=	devel
MASTER_SITES=	http://www.balabit.hu/downloads/libol/0.2/

MAINTAINER=	vince@blue-box.net

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
