# $FreeBSD: ports/x11-fm/Makefile,v 1.19 2000/11/26 04:52:09 dougb Exp $
#

    SUBDIR += asfiles
    SUBDIR += binder
    SUBDIR += dfm
    SUBDIR += endeavour
    SUBDIR += ezfm
    SUBDIR += filerunner
    SUBDIR += fsv
    SUBDIR += gnomemc
    SUBDIR += jafm
    SUBDIR += mfm
    SUBDIR += nautilus
    SUBDIR += offix-files
    SUBDIR += rox-base
    SUBDIR += rox-filer
    SUBDIR += systemg
    SUBDIR += tkdesk
    SUBDIR += vide
    SUBDIR += workplace
    SUBDIR += x-files
    SUBDIR += xcruise
    SUBDIR += xdiskusage
    SUBDIR += xfm
    SUBDIR += xnc

.include <bsd.port.subdir.mk>
