# $FreeBSD: ports/x11-fm/Makefile,v 1.9 1999/10/07 21:05:17 cpiazza Exp $
#

    SUBDIR += asfiles
    SUBDIR += binder
    SUBDIR += dfm
    SUBDIR += endeavour
    SUBDIR += explorer
    SUBDIR += ezfm
    SUBDIR += filerunner
    SUBDIR += gnomemc
    SUBDIR += jafm
    SUBDIR += offix-files
    SUBDIR += q3dmenu
    SUBDIR += tkdesk
    SUBDIR += workplace
    SUBDIR += x-files
    SUBDIR += xcruise
    SUBDIR += xfm
    SUBDIR += xnc

.include <bsd.port.subdir.mk>
