# $FreeBSD: ports/x11-fm/Makefile,v 1.14 2000/06/05 13:51:04 sobomax Exp $
#

    SUBDIR += asfiles
    SUBDIR += binder
    SUBDIR += dfm
    SUBDIR += endeavour
    SUBDIR += ezfm
    SUBDIR += filerunner
    SUBDIR += fsv
    SUBDIR += gnomemc
    SUBDIR += jafm
    SUBDIR += mfm
    SUBDIR += offix-files
    SUBDIR += tkdesk
    SUBDIR += vide
    SUBDIR += workplace
    SUBDIR += x-files
    SUBDIR += xcruise
    SUBDIR += xfm
    SUBDIR += xnc

.include <bsd.port.subdir.mk>
