# New ports collection makefile for:   exctags
# Version required:    3.2.2
# Date created:        4 June 1996
# Whom:                jkoshy
#
# $FreeBSD: ports/devel/ctags/Makefile,v 1.4 1999/08/25 05:47:43 obrien Exp $
#

DISTNAME=	ctags-3.2.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}\
		http://fly.hiwaay.net/~darren/archives/ \
		http://www.freebsd.org/~jkoshy/PORTS/

MAINTAINER=	jkoshy@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--enable-macro-patterns

MAN1=		ctags.1
MLINKS=		ctags.1 etags.1

.include <bsd.port.mk>
