# New ports collection makefile for:	psgml for mule
# Date created:		23 January 1999
# Whom:			shige
#
# $FreeBSD: ports/editors/psgml-mule/Makefile,v 1.7 2000/07/12 15:57:08 shige Exp $
#

MAINTAINER=	shige@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../editors/psgml-emacs

# emacs port setup
EMACS_PORT_NAME=	mule

# pkg-* files in ${.CURDIR} are used
PKGDIR=		${.CURDIR}

.include <${MASTERDIR}/Makefile>
