# New ports collection makefile for:	psgml for mule
# Date created:		23 January 1999
# Whom:			shige
#
# $FreeBSD: ports/editors/psgml-mule/Makefile,v 1.6 2000/04/14 06:20:36 asami Exp $
#

MAINTAINER=	shige@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../editors/psgml-emacs

# emacs port setup
EMACS_PORT_NAME=	mule

# pkg/* files are used in ${.CURDIR}
PKGDIR=		${.CURDIR}/pkg

.include <${MASTERDIR}/Makefile>
