# New ports collection makefile for:	JDE's SeizeDesktop for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/seizedesktop/Makefile,v 1.2 1999/08/25 05:26:51 obrien Exp $
#

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../misc/seizedesktop

.include	"${MASTERDIR}/Makefile"
