# New ports collection makefile for:	JDE's SeizeDesktop for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/seizedesktop/Makefile,v 1.3 2000/04/12 14:37:34 knu Exp $
#

CATEGORIES=	japanese

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../misc/seizedesktop

.include	"${MASTERDIR}/Makefile"
