# New ports collection makefile for:	rand
# Version required:		1.5
# Date created:			Mon Jul 26 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/textproc/rand/Makefile,v 1.2 1999/08/31 02:09:42 peter Exp $
#

DISTNAME=	rand-1.5
CATEGORIES=	textproc
MASTER_SITES=	http://math.smsu.edu/~br0ke/files/

MAINTAINER=	domi@saargate.de

WRKSRC=		${WRKDIR}/rand

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/rand ${PREFIX}/bin

.include <bsd.port.mk>
