# New ports collection makefile for:   diacanvas
# Date created:        04 February 2000
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/graphics/diacanvas/Makefile,v 1.5 2000/06/16 21:51:05 asami Exp $
#

PORTNAME=	diacanvas
PORTVERSION=	0.40.1
CATEGORIES=	graphics gnome
MASTER_SITES=	http://www.linuxstart.com/~arjan/diacanvas/download/

MAINTAINER=	nakai@FreeBSD.org

USE_X_PREFIX=	yes
USE_GNOME=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
