# New ports collection makefile for:	ja-w3m
# Date Created:			8 Oct 1999
# Whom:				SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/w3m/Makefile,v 1.3 2000/01/18 12:34:27 sumikawa Exp $
#

CATEGORIES=	japanese www ipv6

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST.ja

JAPANESE=	Yes

.include "${MASTERDIR}/Makefile"
