# New ports collection makefile for:	ja-w3m
# Date Created:			8 Oct 1999
# Whom:				SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/w3m/Makefile,v 1.7 2000/10/08 10:21:31 asami Exp $
#

CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

JAPANESE=	Yes

.include "${MASTERDIR}/Makefile"
