# New ports collection makefile for:	ja-w3m
# Date Created:			8 Oct 1999
# Whom:				SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/w3m/Makefile,v 1.5 2000/04/14 17:24:53 knu Exp $
#

CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg-plist.ja

JAPANESE=	Yes

.include "${MASTERDIR}/Makefile"
