# New ports collection makefile for:	xenophilia
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/xenophilia/Makefile,v 1.3 2000/07/07 19:59:21 steve Exp $
#

PORTNAME=	xenophilia
PORTVERSION= 	0.4
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://www.obsession.se/johan/gtk/
DISTNAME=	Xenophilia-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

USE_X_PREFIX=	yes
USE_GTK=	yes
ALL_TARGET=	# empty

.include <bsd.port.mk>
