# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.7
# Date created:		29 Dec 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape47-navigator/Makefile,v 1.11 1999/10/11 18:35:12 sada Exp $
#

BROWSER=	navigator

.include	"${.CURDIR}/../netscape47-communicator/Makefile"
