# New ports collection makefile for: Netscape browser with Japanese resources
# Date created:		29 Dec 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape47-navigator/Makefile,v 1.13 2000/04/11 14:15:43 knu Exp $
#

BROWSER_NAME=	navigator

.include	"${.CURDIR}/../netscape47-communicator/Makefile"
