# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.6
# Date created:		29 Dec 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape46-navigator/Makefile,v 1.8 1999/08/25 05:25:53 obrien Exp $
#

MAINTAINER=	sada@FreeBSD.org

FILESDIR=	${BASEDIR}/files

BASEDIR=	${.CURDIR}/../netscape46-communicator
BROWSER=	navigator

.include	"${BASEDIR}/Makefile"
