# New ports collection makefile for:	gimp-manual-1.0.0 (PS)
# Date created:		5 June 1998
# Whom:			Brett Taylor
#
# $FreeBSD: ports/graphics/gimp-manual-ps/Makefile,v 1.2 1999/08/25 06:14:04 obrien Exp $
#

DOCFORMAT=	PS
MASTERDIR=	${.CURDIR}/../gimp-manual-html

.include "${MASTERDIR}/Makefile"
