# New ports collection makefile for:	xmms
# Date created:			3 July 1999
# Whom:				Espen Skoglund <esk@ira.uka.de>
#
# $FreeBSD: ports/chinese/xmms/Makefile,v 1.3 2000/10/07 23:35:00 asami Exp $
#

MASTERDIR=	${.CURDIR}/../../audio/xmms

PATCH_SITES=	${MASTER_SITE_LOCAL}
PATCH_SITE_SUBDIR=	sobomax

EXTRA_PATCHES=	${.CURDIR}/files/extra-patch-xmms-1.2.x-xfont

MAINTAINER=	clive@CirX.ORG

#RUN_DEPENDS=	${X11BASE}/lib/X11/fonts/TrueType/bsmi00lp.ttf:${PORTSDIR}/chinese/arphicttf

.include "${MASTERDIR}/Makefile"
