# New ports collection makefile for:	nail
# Date created:		20 October 2000
# Whom:			Kris Kennaway <kris@FreeBSD.org>
#
# $FreeBSD: ports/mail/nail/Makefile,v 1.2 2001/01/14 08:02:08 kris Exp $
#

PORTNAME=	nail
PORTVERSION=	9.25
CATEGORIES=	mail
MASTER_SITES=	http://omnibus.ruf.uni-freiburg.de/~gritter/archive/nail/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		nail.1

.include <bsd.port.mk>
