# New ports collection makefile for:	whowatch
# Date created:		12 June 2000
# Whom:			Daniel Harris <dannyboy@subdimension.com>
#
# $FreeBSD: ports/sysutils/whowatch/Makefile,v 1.1.1.1 2000/06/21 15:50:50 sobomax Exp $
#

PORTNAME=	whowatch
PORTVERSION=	1.4
CATEGORIES=	sysutils
MASTER_SITES=	http://wizard.ae.krakow.pl/~mike/download/

MAINTAINER=	dannyboy@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=		whowatch.1

.include <bsd.port.mk>
