#! /bin/sh

# $FreeBSD: ports/audio/teamspeak_server/pkg-install,v 1.1 2003/10/08 07:53:26 edwin Exp $

PATH=/bin:/usr/sbin
TSHOME=${PKG_PREFIX}/lib/teamspeak_server

USER=teamspeak
GROUP=${USER}

case $2 in
POST-INSTALL)
	chown -R ${USER}:${GROUP} ${TSHOME}
	chmod -R u+w,o-rx ${TSHOME}
	;;
esac
