# New ports collection makefile for:	nurbs++
# Date created:				14 May 2000
# Whom:					R Joseph Wright <rjoseph@mammalia.org>
#
# $FreeBSD: ports/graphics/nurbs++/Makefile,v 1.1 2000/06/09 22:51:49 will Exp $
#

PORTNAME=	nurbs++
PORTVERSION=	3.0.10
CATEGORIES=	graphics
MASTER_SITES=	http://yukon.genie.uottawa.ca/~lavoie/software/nurbs/

MAINTAINER= 	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
