# New ports collection makefile for:	XMangekyou
# Date created:		30 October 1998
# Whom:			Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/x11/xmangekyou/Makefile,v 1.4 2000/04/13 19:10:46 cpiazza Exp $
#

PORTNAME=	xmangekyou
PORTVERSION=	2.0
CATEGORIES=	x11
MASTER_SITES=	http://wwwmiya.ee.kagu.sut.ac.jp/~sakai/

MAINTAINER=	sakai@miya.ee.kagu.sut.ac.jp

ALL_TARGET=	xmangekyou

USE_X_PREFIX=	yes
USE_XPM=	yes

MAN1=		xmangekyou.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
