# New ports collection makefile for:	XMangekyou
# Date created:		30 October 1998
# Whom:			Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/x11/xmangekyou/Makefile,v 1.5 2000/08/03 09:28:53 asami Exp $
#

PORTNAME=	xmangekyou
PORTVERSION=	2.0.1
CATEGORIES=	x11
MASTER_SITES=	http://www.seki.ee.kagu.sut.ac.jp/~sakai/myfreesoft/

MAINTAINER=	sakai@seki.ee.kagu.sut.ac.jp

ALL_TARGET=	xmangekyou

USE_X_PREFIX=	yes
USE_XPM=	yes

MAN1=		xmangekyou.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
