# Ports collection Makefile for:	powershell
# Date created:				6 May 2000
# Whom:					Scott A. Moberly <smoberly@xavier.dyndns.org>
#
# $FreeBSD: ports/x11/powershell/Makefile,v 1.2 2000/06/14 13:21:19 sobomax Exp $
#

PORTNAME=	powershell
PORTVERSION=	0.8
CATEGORIES=	x11 gnome
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	smoberly@xavier.dyndns.org

ALL_TARGET=	powershell

USE_X_PREFIX=	yes
USE_GNOME=	yes
USE_AUTOCONF=	yes

.include <bsd.port.mk>
