# New ports collection makefile for:	gpart
# Date created:		29 Sep 1999
# Whom:			Andrew Stevenson <andrew@ugh.net.au>
#
# $FreeBSD: ports/sysutils/gpart/Makefile,v 1.3 2000/04/09 19:07:42 cpiazza Exp $
#

PORTNAME=	gpart
PORTVERSION=	0.1f
CATEGORIES=	sysutils
MASTER_SITES=	http://www.stud.uni-hannover.de/user/76201/gpart/ \
		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/filesystems

MAINTAINER=	andrew@ugh.net.au

USE_GMAKE=	yes
MAN8=		gpart.8

.include <bsd.port.mk>
