# New ports collection makefile for:	gpart
# Version required:	0.1f
# Date created:		29 Sep 1999
# Whom:			Andrew Stevenson <andrew@ugh.net.au>
#
# $FreeBSD: ports/sysutils/gpart/Makefile,v 1.1.1.1 1999/11/01 03:05:53 steve Exp $
#

DISTNAME=	gpart-0.1f
CATEGORIES=	sysutils
MASTER_SITES=	http://www.stud.uni-hannover.de/user/76201/gpart/ \
		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/filesystems

MAINTAINER=	andrew@ugh.net.au

USE_GMAKE=	yes
MAN8=		gpart.8

.include <bsd.port.mk>
