# New ports collection makefile for:	WhistlerK
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/whistlerk/Makefile,v 1.1 2000/10/26 16:15:48 sobomax Exp $
#

PORTNAME=	WhistlerK
PORTVERSION=	200010142358
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	${PORTNAME}-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/gtk-theme-WhistlerK

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
