# New ports collection makefile for:	gtk-Mac2-theme
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/gtk-Mac2-theme/Makefile,v 1.2 2000/09/20 18:18:22 sobomax Exp $
#

PORTNAME=	gtk-Mac2-theme
PORTVERSION= 	200003050858
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	Mac2-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
