# New ports collection makefile for:	math/p5-Statistics-ChiSquare
# Date created:				01 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/math/p5-Statistics-ChiSquare/Makefile,v 1.1 2001/01/03 09:35:25 nbm Exp $
#

PORTNAME=	Statistics-ChiSquare
PORTVERSION=	0.2
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

WRKSRC=		${WRKDIR}/Statistics/ChiSquare

MAN3=		Statistics::ChiSquare.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
