# ex:ts=8
# New ports collection makefile for:	stan
# Date created:			May 1, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/misc/stan/Makefile,v 1.1 2001/05/01 17:31:38 ijliao Exp $
#

PORTNAME=	stan
PORTVERSION=	0.3
CATEGORIES=	misc
MASTER_SITES=	http://www.r0q.cx/stan/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=	stan.1

.include <bsd.port.mk>
