# New ports collection makefile for:	xdl
# Date created:         17 July 1995
# Whom:                 asami
#
# $FreeBSD: ports/graphics/xdl/Makefile,v 1.10 2000/04/14 10:47:44 asami Exp $
#

PORTNAME=	xdl
PORTVERSION=	2.1
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
MAN1=		xdl.1

.include <bsd.port.mk>
