# New ports collection makefile for:	xdl
# Date created:         17 July 1995
# Whom:                 asami
#
# $FreeBSD: ports/graphics/xdl/Makefile,v 1.9 1999/08/31 06:45:16 mharo Exp $
#

PORTNAME=	xdl
PORTVERSION=	2.1
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
MAN1=		xdl.1

.include <bsd.port.mk>
