# New ports collection makefile for:	xdl
# Version required:     2.1
# Date created:         17 July 1995
# Whom:                 asami
#
# $FreeBSD: ports/graphics/xdl/Makefile,v 1.8 1999/08/25 06:15:19 obrien Exp $
#

DISTNAME=	xdl-2.1
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
MAN1=		xdl.1

.include <bsd.port.mk>
