# New ports collection makefile for:   pg
# Date created:        3 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/misc/pg/Makefile,v 1.1 2001/01/04 10:58:56 nbm Exp $
#

PORTNAME=	pg
PORTVERSION=	010103
CATEGORIES=	misc
MASTER_SITES=	http://omnibus.ruf.uni-freiburg.de/~gritter/archive/

MAINTAINER=	greid@ukug.uk.freebsd.org

MAKEFILE=	makefile

MAN1=		pg.1

.include <bsd.port.mk>
