# New ports collection makefile for:   kworldwatch
# Date created:        12 July 1998
# Whom:                Marc G. Fournier <scrappy@freebsd.org>
#
# $FreeBSD: ports/x11/kworldwatch/Makefile,v 1.20 2001/04/03 08:14:43 will Exp $
#

PORTNAME=	kworldwatch
PORTVERSION=	0.6
CATEGORIES=	x11 kde
MASTER_SITES=	$(MASTER_SITE_KDE)
MASTER_SITE_SUBDIR=	Attic/old/1.1.2/apps/utils
EXTRACT_SUFX=	.tgz

MAINTAINER=	scrappy@freebsd.org

USE_KDELIBS_VER=1
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
