#!/bin/sh
# $FreeBSD: ports/mail/sympa/pkg-deinstall,v 1.1 2003/12/09 09:07:36 demon Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=simpa

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete Sympa user permanently, use 'pw userdel ${USER}'"
fi

exit 0
