#!/bin/sh
# $FreeBSD: ports/mail/sympa/pkg-deinstall,v 1.2 2003/12/22 08:52:11 demon Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
	exit 0
fi

USER=sympa
GROUP=${USER}

if pw groupshow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete the 'sympa' group permanently, use 'pw groupdel ${USER}'"
fi

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete the 'sympa' user permanently, use 'pw userdel ${USER}'"
fi

exit 0
