# New ports collection makefile for:	libshout
# Date created:				06 Jun 2000
# Whom:					zach@pabst.bendnet.com
#
# $FreeBSD: ports/audio/libshout/Makefile,v 1.2 2000/06/16 08:47:49 sobomax Exp $
#

PORTNAME=	libshout
PORTVERSION=	1.0.3
CATEGORIES=	audio net
MASTER_SITES=	http://developer.icecast.org/libshout/releases/

MAINTAINER=	zach@pabst.bendnet.com

GNU_CONFIGURE=	yes
INSTALLS_SHLIB=	yes
PLIST_SUB+=	PORTVERSION=${PORTVERSION}

.include <bsd.port.mk>
