# New ports collection makefile for: netscape (navigator only)
# Date created:		20 Sept 1998
# Whom:			brett@peloton.physics.montana.edu
#
# $FreeBSD: ports/www/netscape47-navigator/Makefile,v 1.51 2000/08/19 21:49:40 sada Exp $
#

BROWSER=	navigator
INFILE_HEAD=	'Navigator,4.76.0.20001006'

.include "${.CURDIR}/../netscape47-communicator/Makefile"
