# New ports collection makefile for: netscape (navigator only)
# Date created:		20 Sept 1998
# Whom:			brett@peloton.physics.montana.edu
#
# $FreeBSD: ports/www/netscape47-navigator/Makefile,v 1.50 2000/07/25 15:16:45 sada Exp $
#

BROWSER=	navigator
INFILE_HEAD=	'Navigator,4.75.0.20000814'

.include "${.CURDIR}/../netscape47-communicator/Makefile"
