# New ports collection makefile for: netscape (navigator only)
# Version required:	4.6*
# Date created:		20 Sept 1998
# Whom:			brett@peloton.physics.montana.edu
#
# $FreeBSD: ports/www/netscape46-navigator/Makefile,v 1.39 1999/08/31 02:43:05 peter Exp $
#

MASTER_SITES=	ftp://ftp.netscape.com/pub/communicator/english/4.61/unix/unsupported/freebsd/navigator_standalone/
DISTFILES=	navigator-v461-export.x86-unknown-freebsd.tar.gz

MAINTAINER?=	sada@FreeBSD.org

BROWSER=	navigator
INFILE_HEAD=	'Navigator,4.61.0.99147'

.include "${.CURDIR}/../netscape46-communicator/Makefile"
