#
# Directories for pcnfsd(8)
# $FreeBSD: ports/net/pcnfsd/files/Makefile.inc,v 1.2 1999/08/30 14:23:47 peter Exp $
#
BINDIR=	${PREFIX}/libexec
MANDIR=	${PREFIX}/man/man
PRDIR=	${DESTDIR}/var/spool/pcnfs
