# New ports collection makefile for:    spider
# Date created:         2 Oct 1995
# Whom:                 se
#
# $FreeBSD: ports/games/spider/Makefile,v 1.9 2000/01/22 03:27:10 jedgar Exp $
#

PORTNAME=	spider
PORTVERSION=	1.1
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	games/solitaires
DISTNAME=	${PORTNAME}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
INSTALL_TARGET=	install install.doc
MAN1=		spider.1

.include <bsd.port.mk>
