# New ports collection makefile for:	xed
# Date created:		28 Jul 1996
# Whom:			shanee
#
# $FreeBSD: ports/editors/xed/Makefile,v 1.11 1999/08/25 05:44:51 obrien Exp $
#

PORTNAME=	xed
PORTVERSION=	1.3
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	editors
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	shanee@augusta.de

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		xed.1

.include <bsd.port.mk>
