# New ports collection makefile for:   klyx
# Date created:        23 May 1998
# Whom:                Hans Petter Bieker <hanspb@persbraten.vgs.no>
#
# $FreeBSD: ports/print/klyx/Makefile,v 1.16 2001/04/03 08:14:25 will Exp $
#

PORTNAME=	klyx
PORTVERSION=	0.10.0
CATEGORIES=	print kde
MASTER_SITES=	${MASTER_SITE_KDE}
MASTER_SITE_SUBDIR= unstable/apps/office

MAINTAINER=	tom@FreeBSD.org

USE_KDELIBS_VER=1
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
CONFIGURE_ENV=	INSTALL_SCRIPT="${INSTALL_SCRIPT}"

.include <bsd.port.mk>
