# New ports collection makefile for:	p5-Error
# Date created:		24-May-2000
# Whom:	      		Peter van Heusden <pvh@egenetics.com>
#
# $FreeBSD: ports/lang/p5-Error/Makefile,v 1.1.1.1 2000/06/22 11:07:21 nbm Exp $
#

PORTNAME=	Error
PORTVERSION=	0.13
CATEGORIES=	lang perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=Error
PKGNAMEPREFIX=	p5-

MAINTAINER=	pvh@egenetics.com

PERL_CONFIGURE=	YES

MAN3=		Error.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
