# New ports collection makefile for:	bvi
# Version required:			1.2.0
# Date created:				05 November 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/editors/bvi/Makefile,v 1.1.1.1 1999/11/26 20:06:33 steve Exp $
#

DISTNAME=	bvi-1.2.0
CATEGORIES=	editors
MASTER_SITES=	http://bvi.linuxbox.com/download/
EXTRACT_SUFX=	.src.tar.gz

MAINTAINER=	jedgar@fxp.org

GNU_CONFIGURE=	yes

MAN1=		bvi.1
MLINKS=		bvi.1 bview.1

.include <bsd.port.mk>
