# New ports collection makefile for:	File-Binary
# Date created:				Mon Jan  1 11:48:35 2001
# Whom:					will
#
# $FreeBSD: ports/devel/p5-File-Binary/Makefile,v 1.1 2001/01/03 23:49:29 will Exp $
#

PORTNAME=	File-Binary
PORTVERSION=	0.3
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		File::Binary.3

.include <bsd.port.mk>
