# New ports collection makefile for:	hnb
# Date created:				Fri Jul  6 05:37:14 EDT 2001
# Whom:					Patrick Li <pat@databits.net>
#
# $FreeBSD: ports/editors/hnb/Makefile,v 1.1 2001/07/06 16:19:07 kevlo Exp $
#

PORTNAME=	hnb
PORTVERSION=	1.8.0
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	pat@databits.net

GNU_CONFIGURE=	yes

MAN1=		hnb.1

.include <bsd.port.mk>
