# New ports collection makefile for: ja-jlatex209
# Date created:		4 Nov 1996
# Whom:			Mita Yoshio <mita@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/jtex209-ntt/Makefile,v 1.6 2000/04/11 14:14:03 knu Exp $
#

BATCH_TEX=	NTT

MANUAL_PACKAGE_BUILD=	incompatible with other versions of jtex-*

MASTERDIR=	${.CURDIR}/../jtex209-both/
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
