# ex:ts=8
# New ports collection makefile for:	bonk
# Date created:			Jun 1, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/audio/bonk/Makefile,v 1.1 2001/06/01 18:19:06 ijliao Exp $
#

PORTNAME=	bonk
PORTVERSION=	0.5
CATEGORIES=	audio
MASTER_SITES=	http://yoyo.cc.monash.edu.au/~pfh/bonk/

MAINTAINER=	ports@FreeBSD.org

.include <bsd.port.mk>
