# New ports collection makefile for:	devel/p5-Devel-Modlist
# Date created:				25 April 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/devel/p5-Devel-Modlist/Makefile,v 1.1 2001/04/26 18:01:53 joe Exp $
#

PORTNAME=	Devel-Modlist
PORTVERSION=	0.4
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Devel
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Devel::Modlist.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
