# ports collection makefile for:   mikmod304
# Date created:        16 November 1998
# Whom:                yoshiaki Uchikawa
#
# $FreeBSD: ports/audio/mikmod/Makefile,v 1.14 1999/08/25 04:35:49 obrien Exp $
#

PORTNAME=	mikmod
PORTVERSION=	3.1.6
CATEGORIES=	audio
MASTER_SITES=	http://www.multimania.com/miodrag/mikmod/mikmod/ \
				http://mikmod.darkorb.net/mikmod/

MAINTAINER=	yoshiaki@kt.rim.or.jp

LIB_DEPENDS=	mikmod.2:${PORTSDIR}/audio/libmikmod

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		mikmod.1

.include <bsd.port.mk>
