# New ports collection makefile for:	kinput2-wnn6
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-wnn6/Makefile,v 1.6 2000/04/11 14:14:33 knu Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
