# $FreeBSD: ports/devel/oniguruma/files/BSDmakefile,v 1.3 2003/03/13 02:31:42 knu Exp $

LIB=		onig
SHLIB_MAJOR?=	0
SHLIB_MINOR?=	0
CFLAGS+=	-DHAVE_CONFIG_H -DNOT_RUBY
SRCS=		regerror.o regcomp.o regexec.o reggnu.o \
		regposix.o regposerr.o regparse.o
INCS=		onigposix.h \
		oniguruma.h
NOMAN=		YES
LIBDIR=		${LOCALBASE}/lib
INCSDIR=	${LOCALBASE}/include/onig
INCDIR=		${INCSDIR}		# for pre-bsd.incs.mk API

beforeinstall:
	mkdir -p ${INCSDIR}

.include <bsd.lib.mk>
