# New ports collection makefile for:	DockApp Library
# Date created:		17 July 1999
# Whom:			Jim Mock <jim@FreeBSD.org>
#
# $FreeBSD: ports/x11-wm/libdockapp/Makefile,v 1.8 2000/04/28 19:25:29 jim Exp $
#

PORTNAME=	libdockapp
PORTVERSION= 	0.4.0
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://shadowmere.student.utwente.nl/pub/WindowMaker/ \
		http://people.FreeBSD.org/~jim/distfiles/

MAINTAINER=	jim@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_BZIP2=	yes
USE_X_PREFIX=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
