# New ports collection makefile for:    a2dev
# Date created:         		1 July 1998
# Whom:                 		Archie L. Cobbs <archie@whistle.com>
#
# $FreeBSD: ports/devel/a2dev/Makefile,v 1.3 1999/08/25 05:47:19 obrien Exp $
#

PORTNAME=		a2dev
PORTVERSION=		1.2
CATEGORIES=		devel
MASTER_SITES=		ftp://ftp.whistle.com/pub/archie/a2dev/
EXTRACT_SUFX=		.tgz

MAINTAINER=		archie@whistle.com

USE_GMAKE=		defined
PATCH_STRIP=		-p1
MAN1=			a2asm.1 a2link.1 a2load.1 a2objx.1

.include <bsd.port.mk>
