# New ports collection makefile for:    a2dev
# Date created:         		1 July 1998
# Whom:                 		Archie L. Cobbs <archie@whistle.com>
#
# $FreeBSD: ports/devel/a2dev/Makefile,v 1.5 2000/05/11 03:28:47 archie Exp $
#

PORTNAME=		a2dev
PORTVERSION=		1.2
CATEGORIES=		devel
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	archie
EXTRACT_SUFX=		.tgz

MAINTAINER=		archie@whistle.com

USE_GMAKE=		defined
PATCH_STRIP=		-p1
MAN1=			a2asm.1 a2link.1 a2load.1 a2objx.1

.include <bsd.port.mk>
