# New ports collection makefile for:	kinput2-canna+sj3
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna+sj3/Makefile,v 1.9 2000/04/11 14:14:24 knu Exp $
#

CANNA=		yes
SJ3=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
