#!/bin/sh
#
# $FreeBSD: ports/www/horde2/pkg-deinstall,v 1.4 2003/01/30 09:28:41 dirk Exp $
#
# Try to restore httpd.conf when deinstalling Horde

if [ x$2 != xDEINSTALL ]; then
    exit
fi

if [ -f ${PKG_PREFIX}/etc/apache/httpd.conf.beforeHorde ] ; then
	echo "Restoring httpd.conf..."
	cp ${PKG_PREFIX}/etc/apache/httpd.conf ${PKG_PREFIX}/etc/apache/httpd.conf.deinstHorde
	sed -i.tmp -e "s:Include ${PKG_PREFIX}/etc/horde:# Include ${PKG_PREFIX}/etc/horde:g" \
		${PKG_PREFIX}/etc/apache/httpd.conf
	rm ${PKG_PREFIX}/etc/apache/httpd.conf.tmp
fi

# Backup Horde config files, if needed.

if [ -z "${PACKAGE_BUILDING}" ]; then
  for cf in `ls ${PKG_PREFIX}/www/horde/config/*php`; do
    diff -bBqw $cf $cf.dist >/dev/null 2>&1
    case $? in
      0)  # original config file, will be deleted by pkg-plist
          ;;
      1)  # config file has been updated, must be backuped
          cp -p $cf $cf.previous
          echo "===> Backing-up..."
          echo "--->   $cf has been saved ***"
          echo "--->      as $cf.previous ***"
          ;;
      *)  # not found?
          ;;
    esac
  done
fi
