# New ports collection makefile for:	mpd
# Date created:				25 Feb 1999
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/mpd/Makefile,v 1.14 1999/08/30 14:23:16 peter Exp $
#

PORTNAME=	mpd
PORTVERSION=	2.0.b2
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.whistle.com/pub/archie/mpd/

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	${FILESDIR}/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
