# New ports collection makefile for:	mpd
# Date created:				25 Feb 1999
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/mpd/Makefile,v 1.16 2000/04/15 08:57:33 asami Exp $
#

PORTNAME=	mpd
PORTVERSION=	2.0.b2
CATEGORIES=	net
MASTER_SITES=	http://people.FreeBSD.org/~archie/distfiles/
DISTNAME=	mpd-2.0b2

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	${FILESDIR}/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
