# New ports collection makefile for:	texi2html
# Date created:				5 Nov 1997
# Whom:					Ian Vaudrey <i.vaudrey@bigfoot.com>
#
# $FreeBSD: ports/textproc/texi2html/Makefile,v 1.7 2000/04/15 10:03:23 asami Exp $
#

PORTNAME=	texi2html
PORTVERSION= 	1.64
CATEGORIES=	textproc
MASTER_SITES=	http://www.mathematik.uni-kl.de/~obachman/Texi2html/Distrib/

MAINTAINER=	roam@orbitel.bg

USE_AUTOMAKE=	yes
USE_AUTOCONF=	yes
GNU_CONFIGURE=	yes

MAN1=		texi2html.1

.include <bsd.port.mk>
