# New ports collection makefile for:	libghttp
# Version required:			1.0.5
# Date Created:				24 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/www/libghttp/Makefile,v 1.13 2000/01/01 05:32:52 vanilla Exp $
#

DISTNAME=	libghttp-1.0.5
CATEGORIES=	www gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/libghttp

MAINTAINER=	vanilla@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
