# New ports collection makefile for:	libghttp
# Version required:			1.0.4
# Date Created:				24 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/www/libghttp/Makefile,v 1.11 1999/08/31 02:42:54 peter Exp $
#

DISTNAME=	libghttp-1.0.4
CATEGORIES=	www gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	sources/libghttp

MAINTAINER=	vanilla@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
