# New ports collection makefile for:	libghttp
# Date Created:				24 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/www/libghttp/Makefile,v 1.22 2001/02/05 15:33:26 olgeni Exp $
#

PORTNAME=	libghttp
PORTVERSION=	1.0.9
CATEGORIES=	www gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/libghttp

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
