# New ports collection makefile for:    skill
# Date created:         20 Oct 1998
# Whom:                 Joao Carlos Mendes Luis <jonny@jonny.eng.br>
#
# $FreeBSD: ports/sysutils/skill/Makefile,v 1.12 2000/09/25 12:21:39 asami Exp $
#

PORTNAME=	skill
PORTVERSION=	4.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://fast.cs.utah.edu/pub/skill/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jonny@jonny.eng.br

MAN1=		skill.1
MLINKS=		skill.1 snice.1

.include <bsd.port.mk>
