# New ports collection makefile for:    libXg
# Date created:         Sun Aug 13 12:36:14 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/x11-fonts/Xg/Makefile,v 1.9 2000/04/10 00:44:32 cpiazza Exp $
#

PORTNAME=	libXgFonts
PORTVERSION= 	1.0
CATEGORIES=	x11-fonts plan9
MASTER_SITES=	ftp://ftp.ecf.toronto.edu/pub/plan9/matty/
DISTNAME=	libXg.utf.fonts

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_X_PREFIX=	yes

.include <bsd.port.mk>
