# New ports collection makefile for:    libXg
# Date created:         Sun Aug 13 12:36:14 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/x11-fonts/Xg/Makefile,v 1.10 2000/04/23 22:59:51 kris Exp $
#

PORTNAME=	libXgFonts
PORTVERSION=	1.0
CATEGORIES=	x11-fonts plan9
MASTER_SITES=	ftp://ftp.cs.usyd.edu.au/matty/unicode/
DISTNAME=	libXg.utf.fonts

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
USE_X_PREFIX=	yes

.include <bsd.port.mk>
