#!/bin/sh
#
# $FreeBSD: ports/databases/grass-i18n/pkg-deinstall,v 1.1 2003/12/09 01:46:09 linimon Exp $
#
# remove lockfile so that deinstallation can complete

if [ x$2 != xDEINSTALL ]; then
    exit
fi

echo "Removing lockfiles, if any ..."
rm -rf ${PKG_PREFIX}/grass5/locks/*
