# $FreeBSD: ports/ftp/Makefile,v 1.2 1999/08/25 05:54:58 obrien Exp $
#

    SUBDIR += IglooFTP
    SUBDIR += cftp
    SUBDIR += curl
    SUBDIR += downloader
    SUBDIR += ftpfind
    SUBDIR += ftpmirror
    SUBDIR += ftpsearch
    SUBDIR += ftptool
    SUBDIR += gftp
    SUBDIR += greed
    SUBDIR += gtm
    SUBDIR += jmirror
    SUBDIR += lftp
    SUBDIR += llnlxdir
    SUBDIR += llnlxftp
    SUBDIR += mirror
    SUBDIR += moxftp
    SUBDIR += ncftp
    SUBDIR += ncftp2
    SUBDIR += ncftp3
    SUBDIR += omi
    SUBDIR += pavuk
    SUBDIR += proftpd
    SUBDIR += spegla
    SUBDIR += wget
    SUBDIR += wu-ftpd
    SUBDIR += wxftp
    SUBDIR += yafc
    SUBDIR += yale-tftpd

.include <bsd.port.subdir.mk>
