# $FreeBSD: ports/ftp/Makefile,v 1.16 2001/02/05 19:05:28 ijliao Exp $
#

    SUBDIR += IglooFTP
    SUBDIR += axyftp
    SUBDIR += caitoo
    SUBDIR += cftp
    SUBDIR += curl
    SUBDIR += downloader
    SUBDIR += ftpcopy
    SUBDIR += ftpfind
    SUBDIR += ftplocate
    SUBDIR += ftpmirror
    SUBDIR += ftpq
    SUBDIR += ftpsearch
    SUBDIR += ftptool
    SUBDIR += gftp
    SUBDIR += greed
    SUBDIR += gtm
    SUBDIR += hsftp
    SUBDIR += jmirror
    SUBDIR += junglemonkey
    SUBDIR += kmago
    SUBDIR += lftp
    SUBDIR += llnlxdir
    SUBDIR += llnlxftp
    SUBDIR += mirror
    SUBDIR += moxftp
    SUBDIR += ncftp
    SUBDIR += ncftp2
    SUBDIR += ncftp3
    SUBDIR += omi
    SUBDIR += pavuk
    SUBDIR += proftpd
    SUBDIR += puf
    SUBDIR += sftp
    SUBDIR += spegla
    SUBDIR += vsftpd
    SUBDIR += wget
    SUBDIR += wu-ftpd
    SUBDIR += xrmftp
    SUBDIR += yafc
    SUBDIR += yale-tftpd

.include <bsd.port.subdir.mk>
