# New ports collection makefile for:	jvim for Canna and Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna+wnn6/Makefile,v 1.5 2000/04/11 14:14:06 knu Exp $
#

PKGNAMESUFFIX=	-canna+wnn6
CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
