# New ports collection makefile for:    p5-I18N-Charset
# Date created:			26 December 1999
# Whom:	      			Dmitry Sivachenko <dima@Chg.RU>
#
# $FreeBSD: ports/misc/p5-I18N-Charset/Makefile,v 1.6 2001/03/13 10:34:14 demon Exp $
#

PORTNAME=	I18N-Charset
PORTVERSION=	1.08
CATEGORIES=	misc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	I18N
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		I18N::Charset.3

.include <bsd.port.mk>
