# New ports collection makefile for:	XEmacs with Canna and Wnn6
# Version required:	21.1.6
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-canna+wnn6/Makefile,v 1.6 1999/09/09 14:25:32 taoka Exp $
#

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../../japanese/xemacs
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
