# New ports collection makefile for:	XEmacs with Canna and Wnn6
# Version required:	21.1.8
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-canna+wnn6/Makefile,v 1.7 1999/09/10 21:04:23 taoka Exp $
#

CANNA=		yes
WNN6=		yes

.include	"${.CURDIR}/../xemacs-canna/Makefile"
