# New ports collection makefile for:	libtool
# Date created:		6 May 1998
# Whom:			Motoyuki Kasahara <m-kasahr@sra.co.jp>
#
# $FreeBSD: ports/devel/libtool/Makefile,v 1.11 2000/04/11 21:28:49 mharo Exp $
#

PORTNAME=	libtool
PORTVERSION=	1.3.4
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	libtool

MAINTAINER=	reg@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--disable-ltdl-install
CONFIGURE_ENV=	PREFIX=${PREFIX}

.include <bsd.port.mk>
