# New ports collection makefile for:	p5-Date-Manip
# Date created:				April 28th 1996
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Date-Manip/Makefile,v 1.17 2000/12/20 10:10:04 roam Exp $
#

PORTNAME=	Date-Manip
PORTVERSION=	5.39
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Date
PKGNAMEPREFIX=	p5-
DISTNAME=	DateManip-${PORTVERSION}

MAINTAINER=	kapr@crosswinds.net

PERL_CONFIGURE=	YES

MAN3=		Date::Manip.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
