# New ports collection makefile for:	mule 2.3@19.34 with Wnn4
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/mule-wnn4/Makefile,v 1.6 1999/08/30 12:09:02 peter Exp $
#

PKGNAMESUFFIX=	-wnn4
CATEGORIES=	korean editors
KWNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
