# New ports collection makefile for:	mule 2.3@19.34 with Wnn4
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/mule-wnn4/Makefile,v 1.7 2000/04/13 09:17:01 asami Exp $
#

PKGNAMESUFFIX=	-wnn4
CATEGORIES=	korean
KWNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
