# New ports collection makefile for:	mule with FreeWnn
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/mule-freewnn/Makefile,v 1.9 2000/09/08 04:34:18 taoka Exp $
#

CATEGORIES=	korean
PKGNAMESUFFIX=	-freewnn

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

KFREEWNN=	yes

.include	"${MASTERDIR}/Makefile"
