# New ports collection makefile for:	speyes
# Date created:				03 November 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/games/speyes/Makefile,v 1.4 2000/08/03 09:23:51 asami Exp $
#

PORTNAME=	speyes
PORTVERSION=	1.2.0
CATEGORIES=	games
MASTER_SITES=	http://www.halcyon.com/amalmin/speyes/

MAINTAINER=	jedgar@fxp.org

USE_IMAKE=	yes
USE_XPM=	yes

.include <bsd.port.mk>
