# $FreeBSD: ports/palm/Makefile,v 1.13 2000/02/22 20:28:59 dirk Exp $
#

    SUBDIR += coldsync
    SUBDIR += gnomepilot
    SUBDIR += gnomepilot-conduits
    SUBDIR += imgvtopgm
    SUBDIR += isilo
    SUBDIR += jpilot
    SUBDIR += kpilot
    SUBDIR += malsync
    SUBDIR += pilot-link
    SUBDIR += pilot_makedoc
    SUBDIR += syncal
    SUBDIR += xcopilot

.include <bsd.port.subdir.mk>
