# $FreeBSD: ports/palm/Makefile,v 1.4 1999/08/30 14:32:59 peter Exp $
#

    SUBDIR += imgvtopgm
    SUBDIR += kpilot
    SUBDIR += pilot-link
    SUBDIR += pilot_makedoc
    SUBDIR += prc-tools
    SUBDIR += syncal
    SUBDIR += xcopilot

.include <bsd.port.subdir.mk>
