# $FreeBSD: ports/palm/Makefile,v 1.7 1999/11/26 18:45:00 steve Exp $
#

    SUBDIR += imgvtopgm
    SUBDIR += isilo
    SUBDIR += jpilot
    SUBDIR += kpilot
    SUBDIR += pilot-link
    SUBDIR += pilot_makedoc
    SUBDIR += syncal
    SUBDIR += xcopilot

.include <bsd.port.subdir.mk>
