# New ports collection makefile for:	gmessage
# Date created:			Sun Jul 18 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/x11/gmessage/Makefile,v 1.5 2001/02/05 16:18:00 olgeni Exp $
#

PORTNAME=	gmessage
PORTVERSION=	0.2
CATEGORIES=	x11
MASTER_SITES=	http://www.brettnacher.org/users/dominik/FreeBSD/

MAINTAINER=	domi@saargate.de

USE_X_PREFIX=	yes
USE_GTK=	yes

.include <bsd.port.mk>
