# New ports collection makefile for:	gmessage
# Date created:			Sun Jul 18 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/x11/gmessage/Makefile,v 1.1.1.1 1999/09/09 02:22:48 taoka Exp $
#

PORTNAME=	gmessage
PORTVERSION= 	0.2
CATEGORIES=	x11
MASTER_SITES=	http://www.math.uni-goettingen.de/dadler/gmessage/

MAINTAINER=	domi@saargate.de

LIB_DEPENDS=	gtk12.2:${PORTSDIR}/x11-toolkits/gtk12

USE_X_PREFIX=	yes

.include <bsd.port.mk>
