# New ports collection makefile for:	gmessage
# Date created:			Sun Jul 18 1999
# Whom:				domi@saargate.de
#
# $FreeBSD: ports/x11/gmessage/Makefile,v 1.4 2000/10/05 06:42:30 reg Exp $
#

PORTNAME=	gmessage
PORTVERSION=	0.2
CATEGORIES=	x11
MASTER_SITES=	http://www.math.uni-goettingen.de/dadler/gmessage/

MAINTAINER=	domi@saargate.de

USE_X_PREFIX=	yes
USE_GTK=	yes

.include <bsd.port.mk>
