#
# $FreeBSD: ports/devel/bugzilla/Makefile.common,v 1.2 2011/06/11 04:25:06 tota Exp $
#

DIST_SUBDIR=	${PORTNAME}

CONFLICTS=	bugzilla-3.*

PORTSCOUT=	limitw:1,even

WWWDIR=	${PREFIX}/www/bugzilla

NO_BUILD=	yes

