# New ports collection makefile for:	Wanderlust (for emacs20)
# Date created:		7 Apr 1999
# Whom: 		MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/mail/wanderlust-emacs20/Makefile,v 1.5 2000/03/10 21:31:15 asami Exp $
#

MAINTAINER=	nobutaka@nobutaka.com

MASTERDIR=	${.CURDIR}/../../mail/wanderlust-emacs

EMACS_NAME=	emacs
EMACS_PORT=	emacs20
EMACS_VER=	20.6
EMACS_LIBDIR=	share/emacs

IS_SLAVE=	yes

.include <${MASTERDIR}/Makefile>
