# New ports collection makefile for:    ja-rubytk
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/rubytk/Makefile,v 1.5 1999/12/24 04:33:46 steve Exp $
#

CATEGORIES=	japanese x11-toolkits

MAINTAINER=	yasuf@big.or.jp

TCL_VERSION?=	80
TK_VERSION?=	80
WITH_TCL_JP=	yes

MASTERDIR=	${.CURDIR}/../../x11-toolkits/rubytk

.include "${MASTERDIR}/Makefile"
