# New ports collection makefile for:    ja-ruby-tcltklib
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/ruby-tcltklib/Makefile,v 1.9 2000/09/07 00:03:28 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

TCL_VERSION?=	80
TK_VERSION?=	80
WITH_TCLTK_JP=	yes

MASTERDIR=	${.CURDIR}/../../lang/ruby-tcltklib

.include "${MASTERDIR}/Makefile"
