# Ports collection makefile for:	fooseti
# Date created:				28 June 2001
# Whom:					Pete Fritchman <petef@databits.net>
#
# $FreeBSD: ports/astro/fooseti/Makefile,v 1.1 2001/07/07 14:27:05 ijliao Exp $
#

PORTNAME=	fooseti
PORTVERSION=	0.6.5
CATEGORIES=	astro
MASTER_SITES=	http://www-personal.engin.umich.edu/~agorski/fooseti/

MAINTAINER=	petef@FreeBSD.org

LIB_DEPENDS=	intl.1:${PORTSDIR}/devel/gettext

GNU_CONFIGURE=	yes
USE_GTK=	yes

.include <bsd.port.mk>
