# New ports collection makefile for:	XEmacs for Japanese with Canna
# Version required:	21.1.6
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-canna/Makefile,v 1.4 1999/09/09 14:25:31 taoka Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../../japanese/xemacs
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
