# New ports collection makefile for:	XEmacs for Japanese with Canna
# Version required:	20.4
# Date created:		5 Dec 1997
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-canna/Makefile,v 1.3 1999/08/25 05:27:52 obrien Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../../japanese/xemacs
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
