# New ports collection makefile for:	TiMidity++
# Version required:	1.3.10
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/audio/timidity++-tcltk/Makefile,v 1.1.1.1 1999/10/13 06:50:07 flathill Exp $
#

INTERFACE=	tcltk

MASTERDIR=	${.CURDIR}/../../audio/timidity++-emacs

.include "${MASTERDIR}/Makefile"
