# ex:ts=8
# New ports collection makefile for:	mdcrack
# Date created:			Apr 19, 2001
# Whom:				Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/security/mdcrack/Makefile,v 1.1 2001/04/19 17:30:00 ijliao Exp $
#

PORTNAME=	mdcrack
PORTVERSION=	1.0
CATEGORIES=	security
MASTER_SITES=	http://mdcrack.multimania.com/

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes
ALL_TARGET=	# empth

.include <bsd.port.mk>
