# ex:ts=8
# New ports collection makefile for:	mdcrack
# Date created:			Apr 19, 2001
# Whom:				Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/security/mdcrack/Makefile,v 1.2 2001/07/16 04:31:24 ijliao Exp $
#

PORTNAME=	mdcrack
PORTVERSION=	1.1
CATEGORIES=	security
MASTER_SITES=	http://mdcrack.multimania.com/

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}
ALL_TARGET=	# empth

.include <bsd.port.mk>
