# New ports collection makefile for:   ladder
# Date created:        18 Feb 1998
# Whom:                Stefan Zehl <sec@42.org>
#
# $FreeBSD: ports/games/ladder/Makefile,v 1.3 1999/08/25 06:03:53 obrien Exp $
#

PORTNAME=	ladder
PORTVERSION=	1.00
CATEGORIES=	games
MASTER_SITES=	http://www.srv.net/~kth/ \
		ftp://ftp.42.org/pub/unix/games/
DISTFILES=	ladder.tar

MAINTAINER=	sec@42.org

RESTRICTED=	"possible copyright problems ?"

NO_WRKSUBDIR=	true
EXTRACT_CMD=		${TAR}
EXTRACT_BEFORE_ARGS=	-xf
EXTRACT_AFTER_ARGS=	# empty

.include <bsd.port.mk>
