# New ports collection makefile for:	popper
# Version required:	2.2
# Date created:		1 April 1995
# Whom:			pst
#
# $Id: Makefile,v 1.9 1995/05/27 07:58:40 asami Exp $
#

DISTNAME=	qpop2.2
PKGNAME=	qpop-2.2
CATEGORIES+=	mail
MASTER_SITES=	ftp://ftp.qualcomm.com/quest/unix/servers/popper/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	pst@freebsd.org

WRKSRC=		${WRKDIR}/qpopper2.2

.include <bsd.port.mk>
