# New ports collection makefile for:	XEmacs with Wnn4
# Date created:		25 January 1998
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-wnn4/Makefile,v 1.9 2000/04/13 08:33:57 knu Exp $
#

COMMENT=		${.CURDIR}/pkg/COMMENT

XEMACS_MAJOR_VER=	21
WNN4=			yes

.include	"${.CURDIR}/../xemacs${XEMACS_MAJOR_VER}-canna/Makefile"
