# New ports collection makefile for:	XEmacs with Wnn4
# Version required:	21.1.8
# Date created:		25 January 1998
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-wnn4/Makefile,v 1.5 1999/09/10 21:04:23 taoka Exp $
#

WNN4=		yes

.include	"${.CURDIR}/../xemacs-canna/Makefile"
