# New ports collection makefile for:	XEmacs with FreeWnn
# Date created:		25 January 1998
# Whom:			KIRIYAMA Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-freewnn/Makefile,v 1.10 2000/07/13 09:52:59 taoka Exp $
#

COMMENT=		${.CURDIR}/pkg/COMMENT

XEMACS_MAJOR_VER=	21
FREEWNN=		yes

.include	"${.CURDIR}/../xemacs${XEMACS_MAJOR_VER}-canna/Makefile"
