# New ports collection makefile for:	pxtools
# Date created:				27 November 1999
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
#
# $FreeBSD: ports/databases/pxtools/Makefile,v 1.5 2000/07/16 13:15:17 jedgar Exp $
#

PORTNAME=	pxtools
PORTVERSION=	0.0.13
CATEGORIES=	databases
MASTER_SITES=	http://www.kneschke.de/projekte/pxtools/download/

MAINTAINER=	jedgar@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
