# New ports collection makefile for:	pxtools
# Date created:				27 November 1999
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
#
# $FreeBSD: ports/databases/pxtools/Makefile,v 1.4 2000/04/16 12:42:45 jedgar Exp $
#

PORTNAME=	pxtools
PORTVERSION=	0.0.11
CATEGORIES=	databases
MASTER_SITES=	http://www.kneschke.de/projekte/pxtools/download/

MAINTAINER=	jedgar@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
