# New ports collection makefile for:	pxtools
# Version required:			0.0.5
# Date created:				27 November 1999
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
#
# $FreeBSD: ports/databases/pxtools/Makefile,v 1.1.1.1 1999/12/22 23:21:07 jedgar Exp $
#

DISTNAME=	pxtools-0.0.5
CATEGORIES=	databases
MASTER_SITES=	http://www.kneschke.de/projekte/pxtools/download/

MAINTAINER=	jedgar@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
