# New ports collection makefile for:    scheme48
# Version required:     0.46
# Date created:         25 Aug 1997
# Whom:                 jmacd
#
# $FreeBSD: ports/lang/scheme48/Makefile,v 1.11 1999/08/25 06:35:21 obrien Exp $
#

DISTNAME=	scheme48-0.46
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp-swiss.ai.mit.edu/pub/s48/
EXTRACT_SUFX=	.tgz

MAINTAINER= 	jmacd@FreeBSD.org

GNU_CONFIGURE=  yes
CONFIGURE_ARGS= --prefix=${PREFIX}
ALL_TARGET = 	enough
#NO_WRKSUBDIR=	yes
STRIP=
MAN1=		scheme48.1

.include <bsd.port.mk>
