# New ports collection makefile for:    scheme48
# Date created:         25 Aug 1997
# Whom:                 jmacd
#
# $FreeBSD: ports/lang/scheme48/Makefile,v 1.13 1999/12/24 18:39:35 mharo Exp $
#

PORTNAME=	scheme48
PORTVERSION=	0.46
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp-swiss.ai.mit.edu/pub/s48/
EXTRACT_SUFX=	.tgz

MAINTAINER= 	jmacd@FreeBSD.org

GNU_CONFIGURE=  yes
ALL_TARGET = 	enough
STRIP=
MAN1=		scheme48.1

.include <bsd.port.mk>
