# New ports collection makefile for:    scheme48
# Date created:         25 Aug 1997
# Whom:                 jmacd
#
# $FreeBSD: ports/lang/scheme48/Makefile,v 1.16 2000/12/13 01:32:43 ade Exp $
#

PORTNAME=	scheme48
PORTVERSION=	0.53
CATEGORIES=	lang
MASTER_SITES=	http://www.neci.nj.nec.com/homepages/kelsey/ \
		ftp://ftp.nj.nec.com/pub/kelsey/
EXTRACT_SUFX=	.tgz

MAINTAINER=	nectar@FreeBSD.org

FORBIDDEN=	emails love notes to authors on install

GNU_CONFIGURE=  yes
ALL_TARGET = 	enough
STRIP=
MAN1=		scheme48.1

.include <bsd.port.mk>
