# New ports collection makefile for:   wmhm
# Version required:    1.3
# Date created:        21 September 1999
# Whom:                Mike Muir <mmuir@es.co.nz>
#
# $FreeBSD: ports/sysutils/wmhm/Makefile,v 1.6 1999/10/21 05:59:40 cpiazza Exp $
#

DISTNAME=	wmhm-1.3
CATEGORIES=	sysutils windowmaker
MASTER_SITES= 	ftp://mongol.dhis.org/pub/wmhm/ \
		http://www.es.co.nz/~mmuir/

MAINTAINER=	mmuir@es.co.nz

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

WRKSRC=		${WRKDIR}/wmhm/wmhm

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
