# New ports collection makefile for:	mips-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/mips-rtems-gcc/Makefile,v 1.2 2000/10/02 03:10:18 jeh Exp $
#

PORTNAME=	gcc

MAINTAINER=	jeh@FreeBSD.org

BROKEN=		RepoCopy done.  Now it has to be updated.

LCLTARGET=	mips64orion-rtems
.include "${.CURDIR}/../i386-rtems-gcc/Makefile"
