# New ports collection makefile for:	gaa
# Version required:	1.5
# Date created:		2 February 1999
# Whom:			Dima Sivachenko <dima@chg.ru>
#
# $FreeBSD: ports/devel/gaa/Makefile,v 1.2 1999/08/25 05:47:58 obrien Exp $
#

DISTNAME=	gaa-1.5
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.gpad.ac.ru/pub/FreeBSD/distfiles/
EXTRACT_SUFX=	.tgz

MAINTAINER=	dima@chg.ru

GNU_CONFIGURE=	yes

post-install:
		@ ${CAT} ${PKGDIR}/MESSAGE

.include <bsd.port.mk>
