# New ports collection makefile for:	gaa
# Date created:		2 February 1999
# Whom:			Dima Sivachenko <dima@chg.ru>
#
# $FreeBSD: ports/devel/gaa/Makefile,v 1.3 1999/12/24 04:51:17 steve Exp $
#

PORTNAME=	gaa
PORTVERSION=	1.5
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.gpad.ac.ru/pub/FreeBSD/distfiles/
EXTRACT_SUFX=	.tgz

MAINTAINER=	dima@chg.ru

GNU_CONFIGURE=	yes

post-install:
		@ ${CAT} ${PKGMESSAGE}

.include <bsd.port.mk>
