# New ports collection makefile for:	tn5250
# Date created:			20 January 2000
# Whom:				Elias Mandouvalos <ocean@compulink.gr>
#
# $FreeBSD: ports/net/tn5250/Makefile,v 1.3 2000/02/21 17:16:26 taoka Exp $
#

PORTNAME=	tn5250
PORTVERSION=	0.15.7
CATEGORIES=	net
MASTER_SITES=	ftp://cvs.cleveland.lug.net/pub/tn5250/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes

MAN1=		scs2ascii.1 tn5250.1

.include <bsd.port.mk>
