# New ports collection makefile for:	AI-Perceptron
# Date created:				04 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/math/p5-AI-Perceptron/Makefile,v 1.2 2001/01/01 11:06:02 will Exp $
#

PORTNAME=	AI-Perceptron
PORTVERSION=	0.01
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	AI
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		AI::Perceptron.3

.include <bsd.port.mk>
