# New ports collection makefile for: pips for EPSON PM-2200C
# Date created:        2000.11.07
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips2200/Makefile,v 1.1 2000/12/11 02:02:02 taoka Exp $
#

PORTVERSION=	1.3
MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		2200

do-install:     # empty

.include "${MASTERDIR}/Makefile"
