#
# $FreeBSD: ports/net/linphone-base/Makefile.common,v 1.7 2006/05/26 10:23:19 thierry Exp $
#

LINPHONE_PORTNAME=	linphone
LINPHONE_PORTVERSION=	1.3.5
LINPHONE_PORTREVISION=	1
LINPHONE_PORTEPOCH=	1
LINPHONE_MASTER_SITES=	http://simon.morlat.free.fr/download/stable/source/

PATCHDIR=	${.CURDIR}/../../net/linphone-base/files
MD5_FILE=	${.CURDIR}/../../net/linphone-base/distinfo
