#
# $FreeBSD: ports/net/linphone-base/Makefile.common,v 1.4 2005/09/04 00:06:17 sem Exp $
#

LINPHONE_PORTNAME=	linphone
LINPHONE_PORTVERSION=	1.2.0
LINPHONE_PORTREVISION=	0
LINPHONE_PORTEPOCH=	1
LINPHONE_MASTER_SITES=	http://simon.morlat.free.fr/download/stable/source/

PATCHDIR=	${.CURDIR}/../../net/linphone-base/files
MD5_FILE=	${.CURDIR}/../../net/linphone-base/distinfo
