#
# $FreeBSD: ports/net/linphone-base/Makefile.common,v 1.3 2005/04/04 21:42:06 pav Exp $
#

LINPHONE_PORTNAME=	linphone
LINPHONE_PORTVERSION=	1.1.0
LINPHONE_PORTREVISION=	0
LINPHONE_PORTEPOCH=	1
LINPHONE_MASTER_SITES=	http://simon.morlat.free.fr/download/stable/source/

PATCHDIR=	${.CURDIR}/../../net/linphone-base/files
MD5_FILE=	${.CURDIR}/../../net/linphone-base/distinfo
