#
# $FreeBSD: ports/devel/bugzilla3/Makefile.common,v 1.2 2011/06/11 04:27:50 tota Exp $
#

DIST_SUBDIR=	${PORTNAME}

CONFLICTS=	bugzilla-4.*

PORTSCOUT=	limitw:1,even

WWWDIR=	${PREFIX}/www/bugzilla

NO_BUILD=	yes

