# New ports collection makefile for:	xoj
# Date created:				30 March 1998
# Whom:					Andrey Zakhvatov
#
# $FreeBSD: ports/games/xoj/Makefile,v 1.5 2000/04/14 12:27:53 asami Exp $
#

PORTNAME=	xoj
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	X11/demos
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org

USE_XPM=	yes
USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
