# New ports collection makefile for:	bfbtester
# Date created:				31 January 2001
# Whom:					Mike Heffner <mheffner@vt.edu>
#
# $FreeBSD: ports/security/bfbtester/Makefile,v 1.1 2001/04/07 07:33:46 will Exp $
#

PORTNAME=	bfbtester
PORTVERSION=	2.0.1
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	bfbtester

MAINTAINER=	mikeh@FreeBSD.org

HAS_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
