# New ports collection makefile for:	Ruby-Racc-runtime
# Date created:		22 Aug 2000
# Whom:			Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/devel/ruby-racc-runtime/Makefile,v 1.1 2000/08/22 06:48:24 knu Exp $
#

MASTERDIR=	${.CURDIR}/../ruby-racc

PKGNAMESUFFIX=	-runtime

PKGDIR=		${.CURDIR}

RUNTIME=	yes	

.include "${MASTERDIR}/Makefile"
