# New ports collection makefile for:	mule 2.3@19.34 with Wnn4
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-wnn4/Makefile,v 1.36 2000/04/11 14:15:24 knu Exp $
#

PKGNAMESUFFIX=	-wnn4
CATEGORIES=	japanese

WNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
