# New ports collection makefile for:	mule with FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-freewnn/Makefile,v 1.37 2000/04/14 16:47:47 knu Exp $
#

PKGNAMESUFFIX=	-freewnn
CATEGORIES=	japanese

FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
