# New ports collection makefile for:	mule with FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-freewnn/Makefile,v 1.38 2000/09/08 04:34:46 taoka Exp $
#

PKGNAMESUFFIX=	-freewnn
CATEGORIES=	japanese

FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
