# New ports collection makefile for:	weblint
# Date created:		Oct 14, 1995
# Whom:			pst
#
# $FreeBSD: ports/www/weblint/Makefile,v 1.11 2000/04/10 00:07:17 cpiazza Exp $
#

PORTNAME=	weblint
PORTVERSION=	1.020
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.cre.canon.co.uk/pub/weblint/

MAINTAINER=	pst@FreeBSD.org

MAN1=		weblint.1

.include <bsd.port.mk>
