# New ports collection makefile for:	weblint
# Date created:		Oct 14, 1995
# Whom:			pst
#
# $FreeBSD: ports/www/weblint/Makefile,v 1.12 2001/02/05 15:33:55 olgeni Exp $
#

PORTNAME=	weblint
PORTVERSION=	1.020
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.weblint.org/pub/weblint/ \
		${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=../../authors/id/NEILB

MAINTAINER=	pst@FreeBSD.org

MAN1=		weblint.1

.include <bsd.port.mk>
