# New ports collection makefile for:    p5-Errno
# Date created:				June 26th 1997
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Errno/Makefile,v 1.11 2000/11/13 12:43:13 demon Exp $
#

PORTNAME=	Errno
PORTVERSION=	1.09
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Errno
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Errno.3

.include <bsd.port.mk>
