# New ports collection makefile for:    xmountains
# Date created:         16 November 1996
# Whom:                 proff
#
# $FreeBSD: ports/graphics/xmountains/Makefile,v 1.4 1999/08/25 06:15:29 obrien Exp $
#

PORTNAME=	xmountains
PORTVERSION=	2.4
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/math/fractals
EXTRACT_SUFX=	.tgz

MAINTAINER=	proff@iq.org

USE_IMAKE=	yes
MAN6=		xmountains.6

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
