# New ports collection makefile for:    xmountains
# Date created:         16 November 1996
# Whom:                 proff
#
# $FreeBSD: ports/graphics/xmountains/Makefile,v 1.5 2000/04/14 10:47:55 asami Exp $
#

PORTNAME=	xmountains
PORTVERSION=	2.5
CATEGORIES=	graphics
MASTER_SITES=	http://www.epcc.ed.ac.uk/~spb/xmountains/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	proff@iq.org

NO_WRKSUBDIR=	yes

USE_IMAKE=	yes
MAN6=		xmountains.6

.include <bsd.port.mk>
