# New ports collection makefile for:	pwgen
# Date created:		22 July 2000
# Whom:			Oddbjorn Steffensen <oddbjorn@tricknology.org>
#
# $FreeBSD: ports/sysutils/pwgen/Makefile,v 1.2 2000/07/23 09:25:07 alex Exp $
#

PORTNAME=	pwgen
PORTVERSION=	1.15
CATEGORIES=	sysutils
MASTER_SITES=	http://www.tricknology.org/ports/

MAINTAINER=	oddbjorn@tricknology.org

LIB_DEPENDS=	getopt.1:${PORTSDIR}/devel/libgnugetopt

WRKSRC=		${WRKDIR}/${PORTNAME}-1

MAN1=		pwgen.1

.include <bsd.port.mk>
