# New ports collection makefile for:	gnomeaudio
# Date created:				29 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/audio/gnomeaudio/Makefile,v 1.16 2001/03/23 05:42:24 ade Exp $
#

PORTNAME=	gnomeaudio
PORTVERSION=	1.4.0
CATEGORIES=	audio gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/gnome-audio
DISTNAME=	gnome-audio-${PORTVERSION}

MAINTAINER=	ade@FreeBSD.org

USE_X_PREFIX=	yes
USE_GNOMELIBS=	yes
NO_BUILD=	yes
WRKSRC=		${WRKDIR}/${DISTNAME}/sounds

.include <bsd.port.mk>
