# $FreeBSD: ports/archivers/Makefile,v 1.36 2000/06/04 22:53:04 will Exp $
#

    SUBDIR += arc
    SUBDIR += bzip
    SUBDIR += bzip2
    SUBDIR += deepforest
    SUBDIR += fastjar
    SUBDIR += freeze
    SUBDIR += gshar+gunshar
    SUBDIR += ha
    SUBDIR += hpack.non-usa.only
    SUBDIR += lha
    SUBDIR += linux_rar
    SUBDIR += lzo
    SUBDIR += lzop
    SUBDIR += macutils
    SUBDIR += makeself
    SUBDIR += mscompress
    SUBDIR += nulib
    SUBDIR += p5-Compress-Zlib
    SUBDIR += pkzip
    SUBDIR += ppunpack
    SUBDIR += rar
    SUBDIR += unace
    SUBDIR += unarj
    SUBDIR += undms
    SUBDIR += unlzx
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += zip
    SUBDIR += zoo

.include <bsd.port.subdir.mk>
