# $FreeBSD: ports/archivers/Makefile,v 1.26 2000/03/25 00:18:26 knu Exp $
#

    SUBDIR += arc
    SUBDIR += bzip
    SUBDIR += bzip2
    SUBDIR += deepforest
    SUBDIR += fastjar
    SUBDIR += freeze
    SUBDIR += gshar+gunshar
    SUBDIR += ha
    SUBDIR += hpack.non-usa.only
    SUBDIR += lha
    SUBDIR += linux_rar
    SUBDIR += lzo
    SUBDIR += makeself
    SUBDIR += nulib
    SUBDIR += p5-Compress-Zlib
    SUBDIR += pkzip
    SUBDIR += rar
    SUBDIR += unace
    SUBDIR += unarj
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += zip
    SUBDIR += zip.with_encryption
    SUBDIR += zoo

.include <bsd.port.subdir.mk>
