# New ports collection makefile for:    xtestpicture
# Date created:         11 March 1997
# Whom:                 joerg
#
# $FreeBSD: ports/x11/xtestpicture/Makefile,v 1.7 2000/04/13 19:11:05 cpiazza Exp $
#

PORTNAME=	xtestpicture
PORTVERSION=	1.2
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xtestpicture.1

.include <bsd.port.mk>
