# ex:ts=8
# Ports collection makefile for:  xsysstats
# Date created:			  12 December 1994
# Whom:				  asami
#
# $FreeBSD: ports/sysutils/xsysstats/Makefile,v 1.16 2000/02/13 03:24:50 obrien Exp $
#

DISTNAME=	xsysstats1.34
PKGNAME=	xsysstats-1.34
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	obrien@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xsysstats.1

.include <bsd.port.mk>
