# ex:ts=8
# Ports collection makefile for:  xsysstats
# Version required:		  1.34
# Date created:			  12 December 1994
# Whom:				  asami
#
# $FreeBSD: ports/sysutils/xsysstats/Makefile,v 1.15 1999/08/31 06:51:05 mharo Exp $
#

DISTNAME=	xsysstats1.34
PKGNAME=	xsysstats-1.34
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	obrien@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xsysstats.1

.include <bsd.port.mk>
