# ex:ts=8
# Ports collection makefile for:  xsysstats
# Date created:			  12 December 1994
# Whom:				  asami
#
# $FreeBSD: ports/sysutils/xsysstats/Makefile,v 1.19 2000/04/09 19:09:10 cpiazza Exp $
#

PORTNAME=	xsysstats
PORTVERSION=	1.34
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	obrien@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xsysstats.1

.include <bsd.port.mk>
