# New ports collection makefile for:	p5-HTML-Template
# Date Created:				26 Oct, 2000
# Whom:					Jun Kuriyama <kuriyama@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-HTML-Template/Makefile,v 1.3 2001/01/08 06:44:24 kuriyama Exp $
#

PORTNAME=	HTML-Template
PORTVERSION=	2.3
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	HTML
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		HTML::Template.3

MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
