# New ports collection makefile for:	fconv
# Date created:		21 April 1999
# Whom:			Chris Costello <chris@FreeBSD.org>
#
# $FreeBSD: ports/converters/fconv/Makefile,v 1.9 2000/06/29 07:02:08 obrien Exp $
#

PORTNAME=	fconv
PORTVERSION=	1.1
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	chris

MAINTAINER=	chris@FreeBSD.org

.include <bsd.port.mk>
