# New ports collection makefile for:	libffi
# Date created:			14, June, 1998
# Whom:				Horance Chou <horance@freedom.ie.cycu.edu.tw>
#
# $FreeBSD: ports/devel/libffi/Makefile,v 1.12 2000/04/11 21:28:35 mharo Exp $
#

PORTNAME=	libffi
PORTVERSION=	1.20
CATEGORIES=	devel
MASTER_SITES=	ftp://sourceware.cygnus.com/pub/libffi/

MAINTAINER=	horance@freedom.ie.cycu.edu.tw

USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes
CONFIGURE_TARGET=	# empty

.include <bsd.port.mk>
