# New ports collection makefile for:	textproc/p5-Sort-ArbBiLex
# Date created:				02 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-Sort-ArbBiLex/Makefile,v 1.2 2001/03/01 06:38:44 vanilla Exp $
#

PORTNAME=	Sort-ArbBiLex
PORTVERSION=	3.4
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Sort
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Sort::ArbBiLex.3

.include <bsd.port.mk>
