# New ports collection makefile for:	textproc/p5-Sort-ArbBiLex
# Date created:				02 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-Sort-ArbBiLex/Makefile,v 1.1 2001/01/04 00:04:39 will Exp $
#

PORTNAME=	Sort-ArbBiLex
PORTVERSION=	3.32
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Sort
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3=		Sort::ArbBiLex.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
