# New ports collection makefile for:	nail
# Date created:		20 October 2000
# Whom:			Kris Kennaway <kris@FreeBSD.org>
#
# $FreeBSD: ports/mail/nail/Makefile,v 1.3 2001/02/08 12:54:13 kevlo Exp $
#

PORTNAME=	nail
PORTVERSION=	9.26
CATEGORIES=	mail
MASTER_SITES=	http://omnibus.ruf.uni-freiburg.de/~gritter/archive/nail/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		nail.1

.include <bsd.port.mk>
