# New ports collection makefile for:	libcdaudio
# Date created:		01 June 1999
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/audio/libcdaudio/Makefile,v 1.10 2000/06/16 08:47:09 sobomax Exp $
#

PORTNAME=	libcdaudio
PORTVERSION=	0.99.4
CATEGORIES=	audio
MASTER_SITES=	ftp://cdcd.undergrid.net/libcdaudio/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
