# New ports collection makefile for:	libcdaudio
# Version required:	0.99.3
# Date created:		01 June 1999
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/audio/libcdaudio/Makefile,v 1.6 1999/10/16 03:45:55 cpiazza Exp $
#

DISTNAME=	libcdaudio-0.99.3
CATEGORIES=	audio
MASTER_SITES=	ftp://cdcd.undergrid.net/libcdaudio/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
