# New ports collection makefile for:    a2ps (a4)
# Date created:         15 July 1998
# Whom:                 Chuck Robey (chuckr@freebsd.org)
#
# $FreeBSD: ports/print/a2ps-a4/Makefile,v 1.2 1999/08/31 01:44:22 peter Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../a2ps-letter

.include "${MASTERDIR}/Makefile"
