# New ports collection makefile for:	Gnu Chess
# Date created:		04 July 1996
# Whom:			markm
#
# $FreeBSD: ports/games/gnuchess/Makefile,v 1.9 1999/08/31 06:44:15 mharo Exp $
#

PORTNAME=	gnuchess
PORTVERSION=	4.0.80
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gnuchess
DISTNAME=	gnuchess-4.0.pl80

MAINTAINER=	markm@FreeBSD.org

HAS_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${DISTNAME}/src
#CONFIGURE_SCRIPT=	src/configure
#CONFIGURE_ARGS=		-sde -Dprefix=${PREFIX}
MAN6=		game.6 gnuan.6 gnuchess.6 postprint.6

.include <bsd.port.mk>
