# New ports collection makefile for:   glib13
# Date Created:			28 July 1998
# Whom:				Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/devel/glib13/Makefile,v 1.32 2000/06/16 21:49:55 asami Exp $
#

PORTNAME=	glib
PORTVERSION=	1.3.1
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.gimp.org/pub/gtk/v1.3/ \
		ftp://ftp.cs.umn.edu/pub/gimp/gtk/v1.3/ \
		http://www.ameth.org/gimp/gtk/v1.3/

MAINTAINER=	vanilla@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

MAN1=		glib-config-2.0.1

.include <bsd.port.mk>
