# New ports collection makefile for:	lwp
# Date created:				Tue Mar 21 17:51:25 EST 2000
# Whom:					jaharkes
#
# $FreeBSD: ports/devel/lwp/Makefile,v 1.1 2000/05/29 04:13:30 steve Exp $
#

PORTNAME=	lwp
PORTVERSION=	1.4
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.coda.cs.cmu.edu/pub/lwp/src/

MAINTAINER=	coda@cs.cmu.edu

USE_GMAKE=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes

.include <bsd.port.mk>
