# New ports collection makefile for:	lwp
# Date created:				Tue Mar 21 17:51:25 EST 2000
# Whom:					jaharkes
#
# $FreeBSD: ports/devel/lwp/Makefile,v 1.6 2001/04/23 20:41:45 shafeeq Exp $
#

PORTNAME=	lwp
PORTVERSION=	1.8
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.coda.cs.cmu.edu/pub/lwp/src/



USE_GMAKE=	yes
GNU_CONFIGURE=  yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
