# New ports collection makefile for:	xmess
# Date created:				Tue Aug 17 00:21:10 MET DST 1999
# Whom:					nox@jelal.kn-bremen.de
#
# $FreeBSD: ports/emulators/xmess/Makefile,v 1.6 2001/04/14 12:16:58 olgeni Exp $
#

PORTNAME=	xmess
PORTVERSION=	0.37b15.2

MAINTAINER=	stijn@win.tue.nl

MASTERDIR=	${.CURDIR}/../xmame
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr

MAMEMESS=	mess

.include "${MASTERDIR}/Makefile"
