# New ports collection makefile for:	xmess
# Date created:				Tue Aug 17 00:21:10 MET DST 1999
# Whom:					nox@jelal.kn-bremen.de
#
# $FreeBSD: ports/emulators/xmess/Makefile,v 1.4 2001/03/27 10:38:41 olgeni Exp $
#

PORTNAME=	xmess
PORTVERSION=	0.37b12.1

MAINTAINER=	stijn@win.tue.nl

MASTERDIR=	${.CURDIR}/../xmame
PATCHDIR=	${.CURDIR}/files
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr

MAMEMESS=	mess

.include "${MASTERDIR}/Makefile"
