# New ports collection makefile for:	xmess
# Date created:				Tue Aug 17 00:21:10 MET DST 1999
# Whom:					nox@jelal.kn-bremen.de
#
# $FreeBSD: ports/emulators/xmess/Makefile,v 1.3 2000/08/03 09:23:12 asami Exp $
#

PORTNAME=	xmess
PORTVERSION=	0.37b12.1

MAINTAINER=	nox@jelal.kn-bremen.de

MASTERDIR=	${.CURDIR}/../xmame
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr

MAMEMESS=	mess

.include "${MASTERDIR}/Makefile"
