# New ports collection makefile for:	html2ps-a4
# Date created:		Sat Nov 22 12:54:50 CET 1997
# Whom:			andreas
#
# $FreeBSD: ports/print/html2ps-a4/Makefile,v 1.11 1999/09/10 08:41:12 dirk Exp $
#

PAPERSIZE=	A4
MASTERDIR=	${.CURDIR}/../html2ps-letter

.include "${MASTERDIR}/Makefile"
