# New ports collection makefile for:   wmnet
# Date created:        24 November 1998
# Whom:                Rich Neswold <rneswold@mcs.net>
#
# $FreeBSD: ports/net/wmnet/Makefile,v 1.5 2000/02/22 14:25:23 jedgar Exp $
#

PORTNAME=	wmnet
PORTVERSION=	1.2
CATEGORIES=	net windowmaker
MASTER_SITES=	ftp://ftp.enteract.com/users/rneswold/

MAINTAINER=	rneswold@enteract.com

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

MAN1=		wmnet.1

.include <bsd.port.mk>
