# New ports collection makefile for:   wmnet
# Date created:        24 November 1998
# Whom:                Rich Neswold <rneswold@mcs.net>
#
# $FreeBSD: ports/net/wmnet/Makefile,v 1.6 2000/04/09 18:13:57 cpiazza Exp $
#

PORTNAME=	wmnet
PORTVERSION=	1.2
CATEGORIES=	net windowmaker
MASTER_SITES=	ftp://ftp.enteract.com/users/rneswold/

MAINTAINER=	rneswold@enteract.com

USE_XPM=	yes
MAN1=		wmnet.1

.include <bsd.port.mk>
