# New ports collection makefile for:	wamcc
# Version required:	2.22
# Date created:		14 September 1999
# Whom:			Jerry Hicks <wghicks@bellsouth.net>
#
# $FreeBSD: ports/lang/wamcc/Makefile,v 1.1.1.1 1999/11/01 03:46:48 steve Exp $
#

DISTNAME=	wamcc2.22
PKGNAME=	wamcc-2.22
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.inria.fr/INRIA/Projects/loco/wamcc/
DISTFILES=	wamcc2.22.tar.Z prg.tar.Z

DIST_SUBDIR=	wamcc
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
