# New ports collection makefile for:	wamcc
# Version required:	2.22
# Date created:		14 September 1999
# Whom:			Jerry Hicks <wghicks@bellsouth.net>
#
# $FreeBSD: ports/lang/wamcc/Makefile,v 1.2 2000/02/21 19:06:50 fenner Exp $
#

DISTNAME=	wamcc2.22
PKGNAME=	wamcc-2.22
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.inria.fr/INRIA/Projects/loco/wamcc/
DISTFILES=	wamcc2.22.tar.Z prg.tar.Z

MAINTAINER=	jhix@mindspring.com

DIST_SUBDIR=	wamcc
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
