# New ports collection makefile for:   gnet
# Date created:        16 February 2000
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/net/gnet/Makefile,v 1.11 2000/11/25 13:44:08 sobomax Exp $
#

PORTNAME=	gnet
PORTVERSION=	1.1.0
CATEGORIES=	net
MASTER_SITES=	http://www.gnetlibrary.org/src/

MAINTAINER=	nakai@FreeBSD.org

USE_GLIB=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
