# New ports collection makefile for:	ANSIColor
# Date created:				1 December 1999
# Whom:	      				Denis Shaposhnikov <dsh@vlink.ru>
#
# $FreeBSD: ports/devel/p5-Term-ANSIColor/Makefile,v 1.4 2000/08/11 10:30:24 will Exp $
#

PORTNAME=	Term-ANSIColor
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Term
PKGNAMEPREFIX=	p5-
DISTNAME=	ANSIColor-${PORTVERSION}

MAINTAINER=	dsh@vlink.ru

USE_PERL5=	YES
PERL_CONFIGURE=	YES

MAN3=		Term::ANSIColor.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
