# New ports collection makefile for:    jikes
# Date created:         09 December 1998
# Whom:                 Matthew Dillon <dillon@backplane.com>
#
# $FreeBSD: ports/java/jikes/Makefile,v 1.22 2001/02/23 16:08:07 archie Exp $
#

PORTNAME=	jikes
PORTVERSION=	1.13
CATEGORIES=	java
MASTER_SITES=	http://oss.software.ibm.com/pub/jikes/

MAINTAINER=	archie@freebsd.org

MAN1=		jikes.1

HAS_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
