# New ports collection makefile for:    jikes
# Date created:         09 December 1998
# Whom:                 Matthew Dillon <dillon@backplane.com>
#
# $FreeBSD: ports/java/jikes/Makefile,v 1.21 2000/08/09 16:49:27 cpiazza Exp $
#

PORTNAME=	jikes
PORTVERSION=	1.12
CATEGORIES=	java
MASTER_SITES=	http://oss.software.ibm.com/pub/jikes/

MAINTAINER=	archie@freebsd.org

MAN1=		jikes.1

HAS_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
