# ex:ts=8
# ports collection makefile for:	cproto
# Date created:				2000 Feb. 13
# Whom:					Abel Chow <abel_chow@yahoo.com>
#
# $FreeBSD: ports/devel/cproto/Makefile,v 1.3 2000/07/23 19:09:53 obrien Exp $
#

PORTNAME=	cproto
PORTVERSION=	4.6
CATEGORIES=	devel
MASTER_SITES=	http://www.vex.net/~cthuang/cproto/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	YES
MAN1=		cproto.1

.include <bsd.port.mk>
