# New ports collection makefile for: GP + Japanese treatment
# Date created:		15 April 1997
# Whom:			Kiriyama Kazuhiko<kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/gp/Makefile,v 1.12 2000/04/14 17:10:41 knu Exp $
#

CATEGORIES=	japanese

LANGUAGE=	Japanese

MASTERDIR=	${.CURDIR}/../../print/gp
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
