# New ports collection makefile for: GP + Japanese treatment
# Date created:		15 April 1997
# Whom:			Kiriyama Kazuhiko<kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/gp/Makefile,v 1.10 1999/08/25 05:24:13 obrien Exp $
#

CATEGORIES=	japanese print

LANGUAGE=	Japanese

MASTERDIR=	${.CURDIR}/../../print/gp
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
