# New ports collection makefile for: GP + Japanese treatment
# Date created:		15 April 1997
# Whom:			Kiriyama Kazuhiko<kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/gp/Makefile,v 1.11 2000/04/11 14:13:46 knu Exp $
#

CATEGORIES=	japanese

LANGUAGE=	Japanese

MASTERDIR=	${.CURDIR}/../../print/gp
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
