# New ports collection makefile for:	cole
# Date created:				4 November 1999
# Whom:					Maxim Sobolev <sobomax@altavista.net>
#
# $FreeBSD: ports/textproc/cole/Makefile,v 1.1 1999/12/27 02:09:58 steve Exp $
#

PORTNAME=	cole
PORTVERSION= 	2.0.1
CATEGORIES=	textproc
MASTER_SITES=	http://arturo.directmail.org/filters/archive/ \
		http://homepages.go.com/~sobomax/filtersweb/

MAINTAINER=	sobomax@altavista.net

USE_LIBTOOL=	yes

.include <bsd.port.mk>
