# New ports collection makefile for:	cole
# Date created:				4 November 1999
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/textproc/cole/Makefile,v 1.5 2000/06/16 21:52:03 asami Exp $
#

PORTNAME=	cole
PORTVERSION=	2.0.1
CATEGORIES=	textproc
MASTER_SITES=	http://arturo.directmail.org/filters/archive/ \
		http://homepages.go.com/~sobomax/filtersweb/

MAINTAINER=	sobomax@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
