# New ports collection makefile for:	cole
# Date created:				4 November 1999
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/textproc/cole/Makefile,v 1.3 2000/05/17 11:18:26 sobomax Exp $
#

PORTNAME=	cole
PORTVERSION= 	2.0.1
CATEGORIES=	textproc
MASTER_SITES=	http://arturo.directmail.org/filters/archive/ \
		http://homepages.go.com/~sobomax/filtersweb/

MAINTAINER=	sobomax@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes

.include <bsd.port.mk>
