# New ports collection makefile for: English PK fonts at 240dpi
# Date created:		06 Nov 1998
# Whom:			Satoshi Asami <asami@FreeBSD.org>
#
# $FreeBSD: ports/print/pkfonts240/Makefile,v 1.7 1999/08/31 01:45:13 peter Exp $
#

RESOLUTION=	240
MASTERDIR=	${.CURDIR}/../pkfonts300

.include	"${MASTERDIR}/Makefile"
