#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-2.0-devel/files/openoffice-wrapper,v 1.12 2003/09/25 22:43:58 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org%%RELEASE_NR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%-||'`

case $program in
$0)
	$oopath/soffice "$@"
	;;
	*)
	$oopath/$program "$@"
	;;
esac
