# New ports collection makefile for:   libsidplay
# Date created:        31 October 1996
# Whom:                Stefan Zehl <sec@42.org>
#
# $FreeBSD: ports/audio/libsidplay/Makefile,v 1.16 2000/08/22 16:10:39 sobomax Exp $
#

PORTNAME=	libsidplay
PORTVERSION=	1.36.44
CATEGORIES=	audio emulators
MASTER_SITES=	http://www.geocities.com/SiliconValley/Lakes/5147/sidplay/packages/
DISTFILES=	${PORTNAME}-${PORTVERSION:S/./_/g}.tgz

MAINTAINER=	sec@42.org

FETCH_CMD=	/usr/bin/fetch
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
USE_GMAKE=	yes
USE_NEWGCC=	yes

.include <bsd.port.mk>
