# New ports collection makefile for:   libsidplay
# Date created:        31 October 1996
# Whom:                Stefan Zehl <sec@42.org>
#
# $FreeBSD: ports/audio/libsidplay/Makefile,v 1.19 2001/01/09 16:58:13 kevlo Exp $
#

PORTNAME=	libsidplay
PORTVERSION=	1.36.46
CATEGORIES=	audio emulators
MASTER_SITES=	http://www.geocities.com/SiliconValley/Lakes/5147/sidplay/packages/
DISTFILES=	${PORTNAME}-${PORTVERSION}.tgz

MAINTAINER=	sec@42.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
USE_GMAKE=	yes
USE_NEWGCC=	yes

.include <bsd.port.mk>
