# $FreeBSD: ports/databases/Makefile,v 1.46 1999/11/09 19:08:44 nsayer Exp $
#
    SUBDIR += cdb
    SUBDIR += db
    SUBDIR += dbview
    SUBDIR += dbf2mysql
    SUBDIR += freetds
    SUBDIR += gadfly
    SUBDIR += gdbm
    SUBDIR += gmysql
    SUBDIR += gnats
    SUBDIR += gtksql
    SUBDIR += interbase4
    SUBDIR += msql
    SUBDIR += mysql322-client
    SUBDIR += mysql322-server
    SUBDIR += p5-DBD-Pg
    SUBDIR += p5-DBI
    SUBDIR += p5-GDBM
    SUBDIR += p5-MLDBM
    SUBDIR += p5-Msql
    SUBDIR += p5-Mysql
    SUBDIR += p5-Pg
    SUBDIR += p5-SQL-Statement
    SUBDIR += pgaccess
    SUBDIR += postgresql
    SUBDIR += py-PyGreSQL
    SUBDIR += ruby-postgres
    SUBDIR += tcl-Mysql
    SUBDIR += tkgnats
    SUBDIR += typhoon
    SUBDIR += xmbase-grok
    SUBDIR += xmysql
    SUBDIR += xmysqladmin

.include <bsd.port.subdir.mk>
