# New ports collection makefile for:	monitord
# Date created:				5 June 2000
# Whom:					walt
#
# $FreeBSD: ports/sysutils/monitord/Makefile,v 1.1 2000/06/09 21:51:08 will Exp $
#

PORTNAME=	monitord
PORTVERSION=	0.2.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.erudition.net/pub/monitord/

MAINTAINER=	walt@erudition.net

MAN8=		monitord.8

.include <bsd.port.mk>
