# New ports collection makefile for:	Quota
# Date created:				Wed Jan  3 09:06:26 2001
# Whom:					will
#
# $FreeBSD: ports/sysutils/p5-Quota/Makefile,v 1.2 2001/02/26 15:30:57 kevlo Exp $
#

PORTNAME=	Quota
PORTVERSION=	1.3.1
CATEGORIES=	sysutils perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Quota
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Quota.3

.include <bsd.port.mk>
