# New ports collection makefile for:	base64
# Date created:				29 Oct 2000
# Whom:					will
#
# $FreeBSD: ports/converters/base64/Makefile,v 1.2 2000/11/26 14:41:30 kevlo Exp $
#

PORTNAME=	base64
PORTVERSION=	1.3
CATEGORIES=	converters
MASTER_SITES=	http://www.fourmilab.ch/webtools/base64/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
ALL_TARGET=	prog
MAN1=		base64.1

.include <bsd.port.mk>
