# New ports collection makefile for:	rtfm
# Date created:		20 July 1999
# Whom:			Chris Costello <chris@FreeBSD.org>
#
# $FreeBSD: ports/misc/rtfm/Makefile,v 1.8 2000/04/23 22:45:22 chris Exp $
#

PORTNAME=	rtfm
PORTVERSION=	1.0
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	chris

MAINTAINER=    chris@FreeBSD.org

MAN1=          rtfm.1

.include <bsd.port.mk>
