# New ports collection makefile for:	rtfm
# Version required:	1.0
# Date created:		20 July 1999
# Whom:			Chris Costello <chris@calldei.com>
#
# $FreeBSD: ports/misc/rtfm/Makefile,v 1.5 2000/01/18 05:38:22 chris Exp $
#

DISTNAME=	rtfm-1.0
CATEGORIES=	misc
MASTER_SITES= 	http://people.FreeBSD.org/~chris/distfiles/

MAINTAINER=    chris@FreeBSD.org

MAN1=          rtfm.1

.include <bsd.port.mk>
