# New ports collection makefile for:	rtfm
# Version required:	1.0
# Date created:		20 July 1999
# Whom:			Chris Costello <chris@calldei.com>
#
# $FreeBSD: ports/misc/rtfm/Makefile,v 1.4 1999/10/03 23:56:49 chris Exp $
#

DISTNAME=	rtfm-1.0
CATEGORIES=	misc
MASTER_SITES= 	http://www.freebsd.org/~chris/distfiles/

MAINTAINER=    chris@FreeBSD.org

MAN1=          rtfm.1

.include <bsd.port.mk>
