# New ports collection makefile for:	finder
# Date created:				4 September 2000
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11/finder/Makefile,v 1.1 2000/09/05 13:11:29 sobomax Exp $
#

PORTNAME=	finder
PORTVERSION= 	0.80.1
CATEGORIES=	x11 gnome
MASTER_SITES=	http://lfh.hkcampus.net/~lfh-lck/programs/finder/

MAINTAINER=	sobomax@FreeBSD.org

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GNOME=	yes

ALL_TARGET=	default

.include <bsd.port.mk>
