# New ports collection makefile for:	p5-HTML-Clean
# Date created:				March 30th 2001
# Whom:					Alex Kapranoff <kapr@crosswinds.net>
#
# $FreeBSD: ports/www/p5-HTML-Clean/Makefile,v 1.2 2001/05/26 11:52:31 vanilla Exp $
#

PORTNAME=	HTML-Clean
PORTVERSION=	0.8
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	HTML
PKGNAMEPREFIX=	p5-

MAINTAINER=	kapr@crosswinds.net

PERL_CONFIGURE=	yes

MAN1=		htmlclean.1
MAN3=		HTML::Clean.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
