# New ports collection makefile for:	loserjabber
# Date created:				21 October 2000
# Whom:					ryan
#
# $FreeBSD: ports/deskutils/loserjabber/Makefile,v 1.4 2001/02/17 18:58:14 dannyboy Exp $
#

PORTNAME=	loserjabber
PORTVERSION=	2.1.5
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	loserjabber

MAINTAINER=	ryan@manunkind.org

GNU_CONFIGURE=	yes
USE_GTK=	yes
MAN1=		loserjabber.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
