# New ports collection makefile for:	loserjabber
# Date created:				21 October 2000
# Whom:					ryan
#
# $FreeBSD: ports/deskutils/loserjabber/Makefile,v 1.1 2000/12/19 11:44:48 will Exp $
#

PORTNAME=	loserjabber
PORTVERSION=	2.0.1
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	loserjabber

MAINTAINER=	ryan@manunkind.org

GNU_CONFIGURE=	yes
USE_GTK=	yes
MAN1=		loserjabber.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
