# New ports collection makefile for:	loserjabber
# Date created:				21 October 2000
# Whom:					ryan
#
# $FreeBSD: ports/deskutils/loserjabber/Makefile,v 1.2 2001/01/03 21:04:42 vanilla Exp $
#

PORTNAME=	loserjabber
PORTVERSION=	2.1.2
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	loserjabber

MAINTAINER=	ryan@manunkind.org

GNU_CONFIGURE=	yes
USE_GTK=	yes
MAN1=		loserjabber.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
