# New ports collection makefile for:	chard
# Version required:	3.6
# Date created:		24 April 1995
# Whom:			Satoshi Asami
#
# $FreeBSD: ports/misc/chord/Makefile,v 1.7 1999/08/25 07:21:17 obrien Exp $
#

DISTNAME=	chord
PKGNAME=	chord-3.6
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

MAN1=		a2crd.1 chord.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
