# New ports collection makefile for:	chord
# Date created:		24 April 1995
# Whom:			Satoshi Asami
#
# $FreeBSD: ports/misc/chord/Makefile,v 1.8 1999/08/31 06:48:14 mharo Exp $
#

PORTNAME=	chord
PORTVERSION=	3.6
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}
DISTNAME=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

MAN1=		a2crd.1 chord.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
