# ex:ts=8
# New ports collection makefile for:	libFormat
# Date created:			Jun 19, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/devel/libformat/Makefile,v 1.2 2001/06/19 05:25:57 ijliao Exp $
#

PORTNAME=	libformat
PORTVERSION=	0.1.4
CATEGORIES=	devel
MASTER_SITES=	http://members.chello.at/oberzalek/development/
DISTNAME=	Format-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
INSTALLS_SHLIB=	yes

MAN3=	Format.3

.include <bsd.port.mk>
