# ex:ts=8
# New ports collection makefile for:	iverilog
# Date created:		Feb 13, 2001
# Whom:			Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/cad/iverilog/Makefile,v 1.1 2001/02/13 11:02:14 ijliao Exp $
#

PORTNAME=	iverilog
PORTVERSION=	0.4
CATEGORIES=	cad
MASTER_SITES=	ftp://icarus.com/pub/eda/verilog/v${PORTVERSION}/
DISTNAME=	verilog-${PORTVERSION}

MAINTAINER=	ijliao@FreeBSD.org

GNU_CONFIGURE=	yes

USE_BISON=	yes
USE_GMAKE=	yes

MAN1=	iverilog.1

.include <bsd.port.mk>
