# New ports collection makefile for:	gtkportscan
# Date created:		11 March 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/security/gtkportscan/Makefile,v 1.14 2000/07/15 16:45:15 kevlo Exp $
#

PORTNAME=	gtkportscan
PORTVERSION=	1.2
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	cpiazza

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}

USE_GTK=	yes

.include <bsd.port.mk>
