# New ports collection makefile for:    xboard
# Version required:     4.0.5
# Date created:         5 Jan 1997
# Whom:                 xaa@stack.nl
#
# $FreeBSD: ports/games/xboard/Makefile,v 1.20 1999/08/29 21:55:22 cpiazza Exp $
#

DISTNAME=       xboard-4.0.5
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.freechess.org/pub/chess/X/ \
		http://www.research.digital.com/SRC/personal/Tim_Mann/xboard/

MAINTAINER=	xaa@timewasters.nl

USE_XLIB=	yes
GNU_CONFIGURE=  yes
STRIP=
MAN6=		xboard.6 cmail.6 zic2xpm.6

.include <bsd.port.mk>
