# New ports collection makefile for:    xboard
# Date created:         5 Jan 1997
# Whom:                 xaa@stack.nl
#
# $FreeBSD: ports/games/xboard/Makefile,v 1.25 2000/12/30 16:39:36 alex Exp $
#

PORTNAME=	xboard
PORTVERSION=	4.2.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.gnu.org/gnu/xboard/ \
		http://www.research.compaq.com/SRC/personal/Tim_Mann/xboard/
DISTNAME=	xboard-4.2.0beta

MAINTAINER=	xaa+ports@madison-gurkha.com

USE_XLIB=	yes
GNU_CONFIGURE=	yes
STRIP=
MAN6=		xboard.6 cmail.6 zic2xpm.6

.include <bsd.port.mk>
