# New ports collection makefile for:    xboard
# Date created:         5 Jan 1997
# Whom:                 xaa@stack.nl
#
# $FreeBSD: ports/games/xboard/Makefile,v 1.26 2001/01/16 17:30:36 sobomax Exp $
#

PORTNAME=	xboard
PORTVERSION=	4.2.1
CATEGORIES=	games
MASTER_SITES=	http://www.tim-mann.org/xboard/ \
		${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	xboard

MAINTAINER=	xaa+ports@madison-gurkha.com

USE_XLIB=	yes
GNU_CONFIGURE=	yes
STRIP=
MAN6=		xboard.6 cmail.6 zic2xpm.6

.include <bsd.port.mk>
