# New ports collection makefile for:	kinput2-canna+freewnn
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna+freewnn/Makefile,v 1.6 2000/04/11 14:14:27 knu Exp $
#

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
