# New ports collection makefile for:    deneu-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/german/ispell-neu/Makefile,v 1.9 2001/08/14 20:06:11 alex Exp $
#

PORTNAME=	ispell
CATEGORIES=	german
PKGNAMESUFFIX=	-neu-20001109

MAINTAINER=	alex@FreeBSD.org

ISPELL_DENEU=	yes
MASTERDIR=	${.CURDIR}/../../textproc/ispell

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include        "${MASTERDIR}/Makefile"
