# New ports collection makefile for:    deneu-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/deneu-ispell/Makefile,v 1.2 2000/04/09 21:52:18 cpiazza Exp $
#

MAINTAINER=     alex@big.endian.de

ISPELL_DENEU=	yes
PORTNAME=	ispell
PORTVERSION= 	19991219
MASTERDIR=      ${.CURDIR}/../ispell
PKGNAMEPREFIX=	deneu-

.include        "${MASTERDIR}/Makefile"
