# New ports collection makefile for:	ONEW for Canna
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna/Makefile,v 1.8 2000/10/08 10:21:13 asami Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
