# New ports collection makefile for:	ONEW for Canna
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna/Makefile,v 1.6 2000/04/12 14:36:28 knu Exp $
#

CANNA=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=         ${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
