# New ports collection makefile for: ngraph
# Version required:     6.03
# Date created:         18 Aug 1999
# Whom:                 nobu@rd.isac.co.jp
#
# $FreeBSD: ports/math/ngraph/Makefile,v 1.1.1.1 1999/09/09 00:52:53 taoka Exp $
#

DISTNAME=       Ngraph-6.3.05-src
PKGNAME=        ngraph-6.3.05
CATEGORIES=	math
MASTER_SITES=   ${MASTER_SITE_PORTS_JP}

MAINTAINER=     sanpei@jp.FreeBSD.org

REQUIRES_MOTIF=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
