# New ports collection makefile for: ngraph
# Date created:         18 Aug 1999
# Whom:                 nobu@rd.isac.co.jp
#
# $FreeBSD: ports/math/ngraph/Makefile,v 1.3 1999/11/27 01:09:27 steve Exp $
#

PORTNAME=       ngraph
PORTVERSION=	6.3.06
CATEGORIES=	math
MASTER_SITES=   http://www2e.biglobe.ne.jp/~isizaka/bin/ \
		${MASTER_SITE_PORTS_JP}
DISTNAME=       Ngraph-${PORTVERSION}-src

MAINTAINER=     sanpei@jp.FreeBSD.org

REQUIRES_MOTIF=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
