# New ports collection makefile for: ngraph
# Date created:         18 Aug 1999
# Whom:                 nobu@rd.isac.co.jp
#
# $FreeBSD: ports/math/ngraph/Makefile,v 1.6 2000/08/03 14:28:31 sanpei Exp $
#

PORTNAME=       ngraph
PORTVERSION=	6.3.10
CATEGORIES=	math
MASTER_SITES=   http://www2e.biglobe.ne.jp/~isizaka/bin/ \
		${MASTER_SITE_PORTS_JP}
DISTNAME=       Ngraph-${PORTVERSION}-src

MAINTAINER=     sanpei@FreeBSD.org

REQUIRES_MOTIF=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
