# New ports collection makefile for:   brouted
# Date created:        5 May 1999
# Whom:                swjeong
#
# $FreeBSD: ports/net/brouted/Makefile,v 1.2 1999/08/30 14:22:14 peter Exp $
#

PORTNAME=	brouted
PORTVERSION=	1.2b
CATEGORIES=	net
MASTER_SITES=	ftp://www.kitel.co.kr/pub/

MAINTAINER=	swjeong@kitel.co.kr

MAN8=		brouted.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
