# New ports collection makefile for:   brouted
# Date created:        5 May 1999
# Whom:                swjeong
#
# $FreeBSD: ports/net/brouted/Makefile,v 1.3 2000/04/09 18:10:21 cpiazza Exp $
#

PORTNAME=	brouted
PORTVERSION=	1.2b
CATEGORIES=	net
MASTER_SITES=	ftp://www.kitel.co.kr/pub/

MAINTAINER=	swjeong@kitel.co.kr

FORBIDDEN=	"Buffer overflow yielding setgid kmem"

MAN8=		brouted.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
