# New ports collection makefile for:	mp3_check
# Date created:				24 Oct 2000
# Whom:					ericb@thedeepsky.com
#
# $FreeBSD: ports/audio/mp3_check/Makefile,v 1.1 2000/06/02 15:11:13 will Exp $
#

PORTNAME=	mp3_check
PORTVERSION=	1.98
CATEGORIES=	audio
MASTER_SITES=	ftp://mp3check.sourceforge.net/pub/mp3check/

MAINTAINER=	ericb@thedeepsky.com

LIB_DEPENDS=	gnugetopt.1:${PORTSDIR}/devel/libgnugetopt

.include <bsd.port.mk>
