# New ports collection makefile for:	TiMidity++
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/japanese/timidity++-tcltk/Makefile,v 1.3 2000/04/12 14:38:05 knu Exp $
#

CATEGORIES=	japanese

INTERFACE=	tcltk
JAPANESE=	yes

MASTERDIR=	${.CURDIR}/../../audio/timidity++-emacs

.include "${MASTERDIR}/Makefile"
