# New ports collection makefile for:	xroach
# Version required:	4.4BSD-Lite
# Date created:		22 December 1995
# Whom:			markm
#
# $FreeBSD: ports/games/xroach/Makefile,v 1.10 1999/08/25 06:06:02 obrien Exp $
#

DISTNAME=	xroach
PKGNAME=	xroach-4.4
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.cdrom.com/pub/bsd-sources/4.4BSD-Lite/usr/src/games/

MAINTAINER=	markm@FreeBSD.org

MAN6=		xroach.6
MANCOMPRESSED=	maybe

USE_X_PREFIX=	yes
IGNOREFILES=	${DISTFILES}
WRKSRC=		${WRKDIR}/pub/bsd-sources/4.4BSD-Lite/usr/src/games/xroach

.include <bsd.port.mk>
