# New ports collection makefile for:	xroach
# Date created:		22 December 1995
# Whom:			markm
#
# $FreeBSD: ports/games/xroach/Makefile,v 1.13 2000/05/14 05:40:52 billf Exp $
#

PORTNAME=	xroach
PORTVERSION=	4.4
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_BACKUP}
DISTNAME=	${PORTNAME}

MAINTAINER=	markm@FreeBSD.org

MAN6=		xroach.6
MANCOMPRESSED=	maybe

USE_X_PREFIX=	yes
IGNOREFILES=	${DISTFILES}
WRKSRC=		${WRKDIR}/pub/bsd-sources/4.4BSD-Lite/usr/src/games/xroach

.include <bsd.port.mk>
