#!/bin/sh
#
# $FreeBSD: ports/java/shujit/pkg-deinstall,v 1.1 2003/02/16 08:33:22 sobomax Exp $
#

linkfile="${PKG_PREFIX}/etc/shujit-links"
if [ -f "${linkfile}" ]
then
    cat "${linkfile}" | while read link
    do
        rm -f "${link}"
    done
    rm -f "${linkfile}"
fi
