# New ports collection makefile for:   xpostit
# Date created:        6 May 1996
# Whom:                joerg
#
# $FreeBSD: ports/deskutils/xpostit/Makefile,v 1.12 2000/06/03 08:46:30 asami Exp $
#

PORTNAME=	xpostit
PORTVERSION=	3.3.1
CATEGORIES=	deskutils
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	joerg@FreeBSD.org

USE_IMAKE=	yes
WRKSRC=		${WRKDIR}/xpostit
MAN1=		xpostit.1

.include <bsd.port.mk>
