# New ports collection makefile for:   xpostit
# Date created:        6 May 1996
# Whom:                joerg
#
# $FreeBSD: ports/deskutils/xpostit/Makefile,v 1.10 2000/04/08 22:04:07 mharo Exp $
#

PORTNAME=	xpostit
PORTVERSION=	3.3.1
CATEGORIES=	deskutils
MASTER_SITES=	ftp://ftp.x.org/R5contrib/ \
		ftp://ftp.freesoftware.com/pub/X11/R5contrib/
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	joerg@FreeBSD.org

USE_IMAKE=	yes
WRKSRC=		${WRKDIR}/xpostit

.include <bsd.port.mk>
