# New ports collection makefile for:	T-gnus (for mule)
# Date created:		13 September 2000
# Whom: 		Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/news/t-gnus-mule/Makefile,v 1.1 2000/11/03 15:02:29 taoka Exp $
#

MASTERDIR=	${.CURDIR}/../t-gnus-emacs20

EMACS_PORT_NAME=	mule

.include "${MASTERDIR}/Makefile"
