# New ports collection makefile for:	xgrasp
# Version required:     1.7d
# Date created:         23 July 1995
# Whom:                 asami
#
# $FreeBSD: ports/graphics/xgrasp/Makefile,v 1.6 1999/08/25 06:15:23 obrien Exp $
#

DISTNAME=	xgrasp.1.7d
PKGNAME=	xgrasp-1.7d
CATEGORIES=	graphics
MASTER_SITES=	ftp://qiclab.scn.rain.com/pub/X11/	\
		ftp://ftp.cs.ubc.ca/mirror1/x-contrib.R5/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		glib.1 xgrasp.1

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
