# New ports collection makefile for:	xgrasp
# Version required:     1.7d
# Date created:         23 July 1995
# Whom:                 asami
#
# $FreeBSD: ports/graphics/xgrasp/Makefile,v 1.7 1999/08/31 06:45:20 mharo Exp $
#

DISTNAME=	xgrasp.1.7d
PKGNAME=	xgrasp-1.7d
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	../R5contrib
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		glib.1 xgrasp.1

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
