# New ports collection makefile for:	xgrasp
# Date created:		23 July 1995
# Whom:			asami
#
# $FreeBSD: ports/graphics/xgrasp/Makefile,v 1.11 2000/04/14 10:47:48 asami Exp $
#

PORTNAME=	xgrasp
PORTVERSION=	1.7d
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
DISTNAME=	${PORTNAME}.${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		glib.1 xgrasp.1

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
