# New ports collection makefile for:	jvim for Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-wnn6/Makefile,v 1.5 2000/04/11 14:14:09 knu Exp $
#

PKGNAMESUFFIX=	-wnn6
WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
