# New ports collection makefile for:	m68k-rtems-chill
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/m68k-rtems-chill/Makefile,v 1.1 2000/07/10 04:32:20 steve Exp $
#

PORTNAME=	chill

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	m68k-rtems
.include "${.CURDIR}/../i386-rtems-chill/Makefile"
