#!/bin/sh
#
# $FreeBSD: ports/security/portaudit/pkg-deinstall,v 1.1 2004/02/25 09:46:26 eik Exp $
#

case $2 in
POST-DEINSTALL)
  echo
  echo "The portaudit package has been deleted."
  echo "If you're *not* upgrading and won't be using"
  echo "it any longer, you may want to remove the"
  echo "portaudit database:"
  echo
  echo "  rm -Rf %%DATABASEDIR%%"
  echo
  ;;
esac
