#!/bin/sh
#
# $FreeBSD: ports/security/portaudit/pkg-install,v 1.2 2004/03/11 11:11:59 eik Exp $
#

case $2 in
POST-INSTALL)
  if [ ! -f "%%DATABASEDIR%%/auditfile.tbz" ]; then
    echo
    echo "===>  To check your installed ports for known vulnerabilities now do:"
    echo
    echo "      %%PREFIX%%/bin/portaudit -Fda"
    echo
  fi
  ;;
esac
