#!/bin/sh
# $FreeBSD: ports/security/drweb/pkg-deinstall,v 1.1 2001/10/19 10:55:34 ache Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=drweb

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete DrWeb user permanently, use 'pw userdel ${USER}'"
fi

exit 0
