# New ports collection makefile for:    ja-ruby-tk
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/ruby-tk/Makefile,v 1.8 2000/04/25 07:01:59 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	yasuf@bsdclub.org

TK_VERSION?=	80
WITH_TCLTK_JP=	yes

MASTERDIR=	${.CURDIR}/../../x11-toolkits/ruby-tk

.include "${MASTERDIR}/Makefile"
