# New ports collection makefile for:    ja-rubytk
# Version required:     (depends on ${MASTERDIR})
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/rubytk/Makefile,v 1.2 1999/08/25 05:26:46 obrien Exp $
#

PKGNAME=	ja-rubytk-${VERSION}
CATEGORIES=	japanese x11-toolkits

MAINTAINER=	yasuf@big.or.jp

WITH_TCL_JP=	yes

# Temporarily use version 8.0.x of Tcl/Tk until we get the japanese
# equivalents of version 8.2.x.
TCL_VERSION?=	80
TK_VERSION?=	80

MASTERDIR=	${.CURDIR}/../../x11-toolkits/rubytk

.include "${MASTERDIR}/Makefile"
