# New ports collection makefile for:    ja-ruby-tk
# Date created:         15 March 1999
# Whom:                 Yasuhiro Fukuma <yasuf@big.or.jp>
#
# $FreeBSD: ports/japanese/ruby-tk/Makefile,v 1.9 2000/09/07 00:03:28 knu Exp $
#

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

TK_VERSION?=	80
WITH_TCLTK_JP=	yes

MASTERDIR=	${.CURDIR}/../../x11-toolkits/ruby-tk

.include "${MASTERDIR}/Makefile"
