# New ports collection makefile for:	IrcII Client
# Date created:		18 Oct 1994
# Whom:			torstenb
#
# $FreeBSD: ports/irc/ircII/Makefile,v 1.25 2000/08/13 16:44:01 alex Exp $
#

PORTNAME=	ircii
PORTVERSION=	4.4X
CATEGORIES=	irc ipv6
MASTER_SITES=	ftp://ircftp.au.eterna.com.au/pub/ircII/

MAINTAINER=	anders@codefactory.se

GNU_CONFIGURE=	yes
CONFIGURE_ENV=	IRCLIB=${PREFIX}/share/irc

USE_BZIP2=	yes

MAN1=		ircII.1 ircbug.1

.include <bsd.port.mk>
