# New ports collection makefile for:   xlogout
# Date created:                1998-11-06
# Whom:                        Christian Weisgerber <naddy@mips.rhein-neckar.de>
#
# $FreeBSD: ports/x11/xlogout/Makefile,v 1.2 1999/08/31 02:51:06 peter Exp $
#

PORTNAME=	xlogout
PORTVERSION= 	1.1
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.tu-darmstadt.de/pub/X11/other/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	naddy@mips.rhein-neckar.de

WRKSRC=		${WRKDIR}/xlogout
USE_IMAKE=	yes
MAN1=		xlogout.1

.include <bsd.port.mk>
