# New ports collection makefile for: Netscape Navigator for BSDI BSD/OS
# Date created:		10 May 2000
# Whom:			Trevor Johnson <trevor@jpj.net>
# based on work by Dirk Froemberg <dirk@FreeBSD.org> and girgen@partitur.se
#
# $FreeBSD: ports/www/bsdi-netscape47-navigator/Makefile,v 1.50 2000/06/06 21:54:11 will Exp $
#

BROWSER=	navigator

.include "../bsdi-netscape47-communicator/Makefile"
