# New ports collection makefile for: Netscape Navigator for BSDI BSD/OS
# Date created:		10 May 2000
# Whom:			Trevor Johnson <trevor@jpj.net>
# based on work by Dirk Froemberg <dirk@FreeBSD.org> and girgen@partitur.se
#
# $FreeBSD: ports/www/bsdi-netscape47-navigator/Makefile,v 1.52 2000/08/08 16:42:18 sada Exp $
#

BROWSER=	navigator
PKGMESSAGE=	../bsdi-netscape47-communicator/pkg-message

.include "../bsdi-netscape47-communicator/Makefile"
