# New ports collection makefile for:   libtar
# Date created:        06 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/devel/libtar/Makefile,v 1.1 2001/03/10 19:40:14 will Exp $
#

PORTNAME=       	libtar
PORTVERSION=		1.2
CATEGORIES=     	devel
MASTER_SITES=		ftp://ftp-dev.cso.uiuc.edu/pub/libtar/

MAINTAINER=		greid@FreeBSD.org

GNU_CONFIGURE=		yes
USE_GMAKE=		yes

.include "files/manpages"

INSTALLS_SHLIB=		yes

.include <bsd.port.mk>
