# New ports collection makefile for:	x2vnc
# Date created:				12th September 2000
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/x11-servers/x2vnc/Makefile,v 1.3 2001/02/05 21:09:10 olgeni Exp $
#

PORTNAME=	x2vnc
PORTVERSION=	1.2
CATEGORIES=	x11-servers
MASTER_SITES=	http://www.hubbe.net/~hubbe/

MAINTAINER=	ade@FreeBSD.org

USE_IMAKE=	yes
MAN1=		x2vnc.1

.include <bsd.port.mk>
