# New ports collection makefile for:	xautolock
# Date created:		20 Jul 1996
# Whom:			Eric Blood <eblood@cs.unr.edu>
#
# $FreeBSD: ports/x11/xautolock/Makefile,v 1.11 2000/04/13 19:10:16 cpiazza Exp $
#

PORTNAME=	xautolock
PORTVERSION=	1.15
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
DISTNAME=	${PORTNAME}-pl15
EXTRACT_SUFX=	.tgz

MAINTAINER=	eblood@cs.unr.edu

USE_IMAKE=	yes
MAN1=		xautolock.1

.include <bsd.port.mk>
