# New ports collection makefile for:    a2ps (letterdj)
# Date created:         15 July 1998
# Whom:                 Chuck Robey (chuckr@freebsd.org)
#
# $FreeBSD: ports/print/a2ps-letterdj/Makefile,v 1.2 1999/08/31 01:44:23 peter Exp $
#

PAPERSIZE=	letterdj
MASTERDIR=	${.CURDIR}/../a2ps-letter

.include "${MASTERDIR}/Makefile"
