# New ports collection makefile for:	xfm
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $FreeBSD: ports/x11-fm/xfm/Makefile,v 1.16 2000/08/02 05:34:45 kevlo Exp $
#

PORTNAME=	xfm
PORTVERSION= 	1.4.2
CATEGORIES=	x11-fm
MASTER_SITES=	ftp://ftp.uni-koeln.de/windows/xcontrib/

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=    Xaw3d.6:${PORTSDIR}/x11-toolkits/Xaw3d

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		xfm.1 xfmtype.1

.include <bsd.port.mk>
