# New ports collection makefile for:	xfm
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $FreeBSD: ports/x11-fm/xfm/Makefile,v 1.15 2000/04/10 00:39:35 cpiazza Exp $
#

PORTNAME=	xfm
PORTVERSION= 	1.4.2
CATEGORIES=	x11-fm
MASTER_SITES=	ftp://ftp.uni-koeln.de/windows/xcontrib/

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=    Xaw3d.6:${PORTSDIR}/x11-toolkits/Xaw3d \
		Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		xfm.1 xfmtype.1

.include <bsd.port.mk>
