# New ports collection makefile for:	xfm
# Version required:	1.3.2
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $FreeBSD: ports/x11-fm/xfm/Makefile,v 1.13 1999/08/31 02:58:24 peter Exp $
#

DISTNAME=	xfm-1.3.2
CATEGORIES=	x11-fm
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		xfm.1 xfmtype.1

.include <bsd.port.mk>
