# New ports collection makefile for:	xminesweep
# Date created:		31 Januar 1995
# Whom:			janek
#
# $FreeBSD: ports/games/xminesweep/Makefile,v 1.12 1999/09/09 13:13:55 tg Exp $
#

PORTNAME=	xminesweep
PORTVERSION=	3.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.netlab.is.tsukuba.ac.jp/pub/X/our_collections/games/ \
		ftp://ftp.uni-halle.de/pub/X11/contrib/games/ \
		ftp://ftp.warwick.ac.uk/pub/x11/ \
		ftp://ftp.eunet.ch/software/X/games/
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	janek@gaja.ipan.lublin.pl

USE_IMAKE=	yes
MAN1=		xminesweep.1

.include <bsd.port.mk>
