# New ports collection makefile for:	kinput2-canna+wnn6
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna+wnn6/Makefile,v 1.5 1999/08/25 05:24:58 obrien Exp $
#

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../kinput2-wnn4/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
