# New ports collection makefile for:   p5-Locale-PGetText
# Date created:        27 January 2000
# Whom:                Yukihiro Nakai <nakai@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-Locale-PGetText/Makefile,v 1.4 2001/03/10 04:35:32 vanilla Exp $
#

PORTNAME=	Locale-PGetText
PORTVERSION=	0.16
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Locale
PKGNAMEPREFIX=	p5-

MAINTAINER=	nakai@FreeBSD.org

PERL_CONFIGURE=	YES

MAN1=		MsgFormat.1 XText.1
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Locale::PGetText.3

.include <bsd.port.mk>
