# New ports collection makefile for:	Muggy for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/binder/Makefile,v 1.2 1999/08/25 05:23:30 obrien Exp $
#

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../x11-fm/binder

.include	"${MASTERDIR}/Makefile"
