# New ports collection makefile for:	Muggy for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/binder/Makefile,v 1.3 2000/04/11 14:12:53 knu Exp $
#

CATEGORIES=	japanese

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../x11-fm/binder

.include	"${MASTERDIR}/Makefile"
