#! /bin/sh

# $FreeBSD: ports/databases/postgresql7/pkg-install,v 1.3 2001/01/30 07:27:00 jkoshy Exp $

PATH=/bin:/usr/sbin

DB_DIR=${PKG_PREFIX}/pgsql

case $2 in
PRE-INSTALL)
	USER=pgsql
	GROUP=${USER}
	UID=70
	GID=${UID}

	if pw group show "${GROUP}" 2>/dev/null; then
		echo "You already have a group \"${GROUP}\", so I will use it."
	else
		if pw groupadd ${GROUP} -g ${GID}; then
			echo "Added group \"${GROUP}\"."
		else
			echo "Adding group \"${GROUP}\" failed..."
			exit 1
		fi
	fi

	if pw user show "${USER}" 2>/dev/null; then
		echo "You already have a user \"${USER}\", so I will use it."
	else
		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
			-d ${DB_DIR} -c "PostgreSQL Daemon"
		then
			echo "Added user \"${USER}\"."
		else
			echo "Adding user \"${USER}\" failed..."
			exit 1
		fi
	fi

	;;

esac
