# New ports collection makefile for:	gmime
# Date created:			7 Apr 2001
# Whom:				Bas Kruit <baskruit@bsltwr.dnsalias.org>
#
# $FreeBSD: ports/mail/gmime/Makefile,v 1.2 2001/04/07 23:28:19 will Exp $
#

PORTNAME=	gmime
PORTVERSION=	0.5.0
CATEGORIES=	mail
MASTER_SITES=	http://bsltwr.dnsalias.org/ftp/pub/gmime/ \
		http://www.xtorshun.org/gmime/sources/

MAINTAINER=	baskruit@bsltwr.dnsalias.org

USE_X_PREFIX=	YES
USE_GMAKE=	YES
USE_GTK=	YES
USE_LIBTOOL=	YES
GNU_CONFIGURE=	YES

INSTALLS_SHLIB=	YES

.include <bsd.port.mk>
