# New ports collection makefile for:	ONEW for Canna and FreeWnn
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna+freewnn/Makefile,v 1.7 2000/09/08 04:34:19 taoka Exp $
#

CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=         ${.CURDIR}

.include	"${MASTERDIR}/Makefile"
