# New ports collection makefile for:	ONEW for Canna and Wnn4
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna+wnn4/Makefile,v 1.5 1999/08/25 05:26:03 obrien Exp $
#

CANNA=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../onew-wnn4
PKGDIR=         ${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
