# $FreeBSD: ports/java/Makefile,v 1.15 2000/07/02 22:29:14 kris Exp $
#

    SUBDIR += collections
    SUBDIR += cos
    SUBDIR += cryptix-jce
    SUBDIR += guavac
    SUBDIR += infobus
    SUBDIR += jaf
    SUBDIR += java-cup
    SUBDIR += javamail
    SUBDIR += javavmwrapper
    SUBDIR += jce-aba
    SUBDIR += jdbcpool
    SUBDIR += jdk
    SUBDIR += jdk-doc
    SUBDIR += jdk-tutorial
    SUBDIR += jfc
    SUBDIR += jikes
    SUBDIR += jlex
    SUBDIR += jre
    SUBDIR += jsdk
    SUBDIR += kaffe
    SUBDIR += linux-jdk
    SUBDIR += netrexx
    SUBDIR += openjit
    SUBDIR += shujit
    SUBDIR += tya

.include <bsd.port.subdir.mk>
