# $FreeBSD: ports/java/Makefile,v 1.24 2001/01/05 17:42:23 alex Exp $
#
    SUBDIR += xalan-j

    SUBDIR += bugseeker
    SUBDIR += collections
    SUBDIR += cos
    SUBDIR += cryptix-jce
    SUBDIR += gnu-regexp
    SUBDIR += guavac
    SUBDIR += infobus
    SUBDIR += jad
    SUBDIR += jaf
    SUBDIR += java-cup
    SUBDIR += javamail
    SUBDIR += javavmwrapper
    SUBDIR += jce-aba
    SUBDIR += jdbcpool
    SUBDIR += jdk
    SUBDIR += jdk-doc
    SUBDIR += jdk-tutorial
    SUBDIR += jdk12-beta
    SUBDIR += jfc
    SUBDIR += jikes
    SUBDIR += jlex
    SUBDIR += jre
    SUBDIR += jsdk
    SUBDIR += junit
    SUBDIR += kaffe
    SUBDIR += linux-jdk
    SUBDIR += linux-jdk13
    SUBDIR += netrexx
    SUBDIR += openjit
    SUBDIR += orion
    SUBDIR += perltools
    SUBDIR += shujit
    SUBDIR += tya

.include <bsd.port.subdir.mk>
