# New ports collection makefile for:	Crypt-TripleDES
# Date created:				Wed Jan  3 16:20:30 2001
# Whom:					will
#
# $FreeBSD: ports/security/p5-Crypt-TripleDES/Makefile,v 1.1 2001/01/03 23:26:47 will Exp $
#

PORTNAME=	Crypt-TripleDES
PORTVERSION=	0.24
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Crypt
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Crypt::TripleDES.3

.include <bsd.port.mk>
