# New ports collection makefile for:	xlife
# Date created:		15 March 1995
# Whom:			asami
#
# $FreeBSD: ports/games/xlife/Makefile,v 1.17 2000/04/14 12:27:37 asami Exp $
#

PORTNAME=	xlife
PORTVERSION=	3.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
DISTNAME=	xlife
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
INSTALL_TARGET=	install install.patterns
MAN1=		xlife.1

.include <bsd.port.mk>
