# New ports collection makefile for:	exim-ldap
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-ldap/Makefile,v 1.2 2001/06/13 21:19:13 sheldonh Exp $
#

PKGNAMESUFFIX=	-ldap
MASTERDIR=	${.CURDIR}/../exim

# See ${MASTERDIR}/Makefile for options controlling the LDAP lookup type.
WITH_LDAP=	yes

.include "${MASTERDIR}/Makefile"
