# New ports collection makefile for:	exim-ldap
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-ldap/Makefile,v 1.3 2001/06/14 21:37:16 sheldonh Exp $
#

PKGNAMESUFFIX=	-ldap
MASTERDIR=	${.CURDIR}/../exim

WITH_LDAP=	yes

.include "${MASTERDIR}/Makefile"
