# New ports collection makefile for:	zh-kde2-i18n
# Date created:				17 April 2001
# Whom:					Dmitry Sivachenko <demon@FreeBSD.org>
#
# $FreeBSD: ports/chinese/kde2-i18n/Makefile,v 1.3 2001/04/18 09:25:40 demon Exp $
#

CATEGORIES=	chinese kde misc

MAINTAINER=	ports@FreeBSD.org

LINGUAS=	"zh_CN.GB2312"
MASTERDIR=	${.CURDIR}/../../misc/kde2-i18n

SCRIPTS_ENV+=	LINGUAS=${LINGUAS}

.include "${MASTERDIR}/Makefile"
