# New ports collection makefile for:	Wanderlust (for xemacs20)
# Date created:		7 Apr 1999
# Whom: 		MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/mail/wanderlust-xemacs20/Makefile,v 1.5 2000/04/19 06:52:37 knu Exp $
#

MAINTAINER=	nobutaka@nobutaka.com

MASTERDIR=	${.CURDIR}/../../mail/wanderlust-emacs

EMACS_PORT_NAME=	xemacs20

IS_SLAVE=	yes

.include <${MASTERDIR}/Makefile>
