# New ports collection makefile for:	Wanderlust (for xemacs20)
# Date created:		7 Apr 1999
# Whom: 		MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/mail/wanderlust-xemacs20/Makefile,v 1.3 2000/01/19 16:37:22 shige Exp $
#

MAINTAINER=	nobutaka@nobutaka.com

MASTERDIR=	${.CURDIR}/../../mail/wanderlust-emacs

EMACS_NAME=		xemacs
EMACS_PORT=		xemacs20
EMACS_VER=		20.4
EMACS_LIBDIR=		lib/xemacs

IS_SLAVE=	yes

.include <${MASTERDIR}/Makefile>
