# New ports collection makefile for:	jvim for FreeWnn
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-freewnn/Makefile,v 1.6 2000/09/08 04:34:34 taoka Exp $
#

PKGNAMESUFFIX=	-freewnn
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
