# New ports collection makefile for:	jvim for Wnn4
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-wnn4/Makefile,v 1.4 1999/08/25 05:24:38 obrien Exp $
#

PKGNAMESUFFIX=	-wnn4
WNN4=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
