# New ports collection makefile for:	jvim for FreeWnn
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-freewnn/Makefile,v 1.5 2000/04/11 14:14:08 knu Exp $
#

PKGNAMESUFFIX=	-freewnn
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
