# New ports collection makefile for: FreePWING
# Version required:	1.1a
# Date created:		00/01/24
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/freepwing/Makefile,v 1.1.1.1 2000/01/27 13:06:42 taoka Exp $
#

DISTNAME=	freepwing-1.1a
PKGNAME=	ja-freepwing-1.1a
CATEGORIES=	japanese textproc
MASTER_SITES=	ftp://ftp.sra.co.jp/pub/misc/freepwing/freepwing/

MAINTAINER=	taoka@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--datadir=${PREFIX}/share/doc

.include <bsd.port.mk>
