# New ports collection makefile for:	mule with Canna and Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+wnn6/Makefile,v 1.10 2000/09/08 04:34:46 taoka Exp $
#

PKGNAMESUFFIX=	-canna+wnn6
CATEGORIES=	japanese

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
