# New ports collection makefile for:	xskyroot
# Date created:		20 April 1997
# Whom:			nkazushi@highway.or.jp
#
# $FreeBSD: ports/x11/xskyroot/Makefile,v 1.4 2000/03/11 14:29:28 jedgar Exp $
#

PORTNAME=	xskyroot
PORTVERSION= 	920428
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.fit.ac.jp/pub/X/contrib/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
