# New ports collection makefile for:	xklock
# Version required:	2.54
# Date created:		20 April 1997
# Whom:			nkazushi@highway.or.jp
#
# $FreeBSD: ports/x11/xskyroot/Makefile,v 1.2 1999/08/31 02:51:14 peter Exp $
#

DISTNAME=	xskyroot-920428
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.fit.ac.jp/pub/X/contrib/  \
		ftp://ftp.foretune.co.jp/pub/X/clients/xskyroot/  \
		ftp://ftp.waseda.ac.jp/fj/fj.sources/X/
EXTRACT_SUFX=	.tar.Z

USE_IMAKE=	yes
NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
