# New ports collection makefile for:	xenophilia
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/xenophilia/Makefile,v 1.4 2000/10/05 06:42:55 reg Exp $
#

PORTNAME=	xenophilia
PORTVERSION= 	200012301145
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	Xenophilia-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/Xenophilia-0.5

USE_X_PREFIX=	yes
USE_GTK=	yes
ALL_TARGET=	# empty

.include <bsd.port.mk>
