# New ports collection makefile for:	hexpert
# Date created:		09 March 2001
# Whom:			Peter Wemm <peter@FreeBSD.org>
#
# $FreeBSD: ports/editors/hexpert/Makefile,v 1.1 2001/03/10 08:43:36 peter Exp $
#

PORTNAME=	hexpert
PORTVERSION=	2.4.1
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	peter

MAINTAINER=	peter@FreeBSD.org

.include <bsd.port.mk>
