#!/bin/sh
# $FreeBSD: ports/ftp/vsftpd/pkg-deinstall,v 1.2 2009/01/17 06:04:20 dinoex Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=ftp

if pw usershow "${USER}" 2>/dev/null 1>&2; then
        echo "To delete FTP user permanently, use 'pw userdel ${USER}'"
        echo "Don't do this if you're using FreeBSD's anonymous FTP server"
fi

exit 0
