# New ports collection makefile for:    nologin
# Date created:         15 Jul 1998
# Whom:                 Donald Burr <dburr@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/no-login/Makefile,v 1.7 2000/04/22 10:12:50 mharo Exp $
#

PORTNAME=	nologin
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://softweyr.com/pub/softweyr/

MAINTAINER=	wes@FreeBSD.org

.include <bsd.port.mk>
