# New ports collection makefile for:	xzip
# Date created:				28 June 1998
# Whom:					Matthew Hunt <mph@FreeBSD.org>
#
# $FreeBSD: ports/games/xzip/Makefile,v 1.10 2000/04/14 12:28:36 asami Exp $
#

PORTNAME=		xzip
PORTVERSION=		1.8.2
CATEGORIES=		games
MASTER_SITES=   	ftp://ftp.gmd.de/if-archive/infocom/interpreters/zip/
DISTFILES=		xzip182.tar.Z

MAINTAINER=		mph@freebsd.org

WRKSRC=			${WRKDIR}/xzip
ALL_TARGET=

USE_XLIB=		yes

MAN1=			xzip.1

.include <bsd.port.mk>
