#
# $FreeBSD: ports/games/gnushogi/Makefile.common,v 1.3 2010/10/28 21:00:12 erwin Exp $
#

GNUSHOGI_PORTNAME=	gnushogi
GNUSHOGI_PORTVERSION=	1.3.2
GNUSHOGI_MASTER_SITES=	http://www.cs.caltech.edu/~mvanier/hacking/gnushogi/
GNUSHOGI_DISTNAME=	${GNUSHOGI_PORTNAME}-${GNUSHOGI_PORTVERSION}

DISTINFO_FILE=	${.CURDIR}/../../games/gnushogi/distinfo
