# New ports collection makefile for:	rtty
# Version required:	3.2
# Date created:		24 Aug 1996
# Whom:			jkh
#
# Author:		Paul Vixie / Internet Software Consortium
#
# $FreeBSD: ports/sysutils/rtty/Makefile,v 1.4 1999/08/31 02:00:02 peter Exp $
#

DISTNAME=	rtty-3.2
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.vix.com/pub/vixie/

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
