# New ports collection makefile for:	rtty
# Date created:		24 Aug 1996
# Whom:			jkh
#
# $FreeBSD: ports/sysutils/rtty/Makefile,v 1.7 2000/04/22 10:13:08 mharo Exp $
#

PORTNAME=	rtty
PORTVERSION=	3.2
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.vix.com/pub/vixie/ \
		ftp://ftp.digital.com/pub/misc/vixie/

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
