# New ports collection makefile for:	libaudiofile
# Date created:				22 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/audio/libaudiofile/Makefile,v 1.17 2001/03/06 12:32:10 vanilla Exp $
#

PORTNAME=	libaudiofile
PORTVERSION=	0.2.1
PORTREVISION=	1
CATEGORIES=	audio
MASTER_SITES=	ftp://oss.sgi.com/projects/audiofile/download/ \
		${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/audiofile
DISTNAME=	audiofile-${PORTVERSION}

MAINTAINER=	vanilla@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
