# New ports collection makefile for:	libaudiofile
# Date created:				22 Dec 1998
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/audio/libaudiofile/Makefile,v 1.12 2000/06/02 11:39:43 sobomax Exp $
#

PORTNAME=	libaudiofile
PORTVERSION=	0.1.9
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/audiofile
DISTNAME=	audiofile-${PORTVERSION}

MAINTAINER=	vanilla@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes

MAKE_ARGS=	"-E CFLAGS"

.include <bsd.port.mk>
