# New ports collection makefile for:   ruboard
# Date created:                        5 October 1998
# Whom:                                Andrew Maltsev <am@amsoft.ru>
#
# $FreeBSD: ports/www/ruboard/Makefile,v 1.3 1999/08/31 02:43:13 peter Exp $
#

PORTNAME=	ruboard
PORTVERSION= 	1.2.1
CATEGORIES=	www russian
MASTER_SITES=	ftp://ftp.amsoft.ru/software/ruboard/

MAINTAINER=    am@amsoft.ru

.include <bsd.port.mk>
