# New ports collection makefile for:   ruboard
# Date created:                        5 October 1998
# Whom:                                Andrew Maltsev <am@amsoft.ru>
#
# $FreeBSD: ports/www/ruboard/Makefile,v 1.4 2000/04/10 00:06:46 cpiazza Exp $
#

PORTNAME=	ruboard
PORTVERSION=	1.2.1
CATEGORIES=	www russian
MASTER_SITES=	ftp://ftp.amsoft.ru/software/ruboard/

MAINTAINER=	am@amsoft.ru

.include <bsd.port.mk>
