# New ports collection makefile for:    p5-SQL-Statement
# Date created:				August 8th, 1999
# Whom:	      				wolman@cs.washington.edu
#
# $FreeBSD: ports/databases/p5-SQL-Statement/Makefile,v 1.4 2000/06/17 02:36:31 will Exp $
#

PORTNAME=	SQL-Statement
PORTVERSION=	0.1016
CATEGORIES=	databases perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	SQL
PKGNAMEPREFIX=	p5-

MAINTAINER=	wolman@cs.washington.edu

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		SQL::Eval.3 SQL::Statement.3

.include <bsd.port.mk>
