# New ports collection makefile for:	apc
# Date created:		May 1 1997
# Whom:			Eric A. Griff <eagriff@global2000.net>
#
# $FreeBSD: ports/math/apc/Makefile,v 1.12 2000/04/14 07:19:48 asami Exp $
#

PORTNAME=	apc
PORTVERSION=	1.0
CATEGORIES=	math
MASTER_SITES= 	http://members.global2000.net/~eagriff/

MAINTAINER=	eagriff@global2000.net

LIB_DEPENDS=	xforms.0:${PORTSDIR}/x11-toolkits/xforms

USE_X_PREFIX=	yes
MAN1=		apc.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
