#!/bin/sh
# $FreeBSD: ports/audio/murmur/pkg-install,v 1.3 2011/06/25 19:55:42 crees Exp $

PATH=/bin:/usr/sbin
LOGDIR=/var/log/murmur
RUNDIR=/var/run/murmur
DBDIR=/var/db/murmur

case $2 in
	PRE-INSTALL)

		mkdir -m 750 ${LOGDIR} ${DBDIR} ${RUNDIR} 2> /dev/null
		chown -R murmur:murmur ${LOGDIR} ${DBDIR} ${RUNDIR}

		;;
esac
