#!/bin/sh
# $FreeBSD: ports/audio/murmur/pkg-install,v 1.2 2011/02/25 14:08:09 sylvio Exp $

PATH=/bin:/usr/sbin
LOGDIR=/var/log/murmur
RUNDIR=/var/run/murmur
DBDIR=/var/db/murmur

case $2 in
	PRE-INSTALL)

		mkdir -m 750 ${LOGDIR} ${DBDIR} ${RUNDIR} 2> /dev/null
		chown -R ${USER}:${GROUP} ${LOGDIR} ${DBDIR} ${RUNDIR}

		;;
esac
