#!/bin/sh
# $FreeBSD: ports/audio/murmur/pkg-install,v 1.4 2011/10/21 15:01:17 pawel Exp $

PATH=/bin:/usr/sbin
LOGDIR=/var/log/murmur
RUNDIR=/var/run/murmur
DBDIR=/var/db/murmur

case $2 in
	POST-INSTALL)

		mkdir -m 750 ${LOGDIR} ${DBDIR} ${RUNDIR} 2> /dev/null
		chown -R murmur:murmur ${LOGDIR} ${DBDIR} ${RUNDIR}

		;;
esac
