# New ports collection makefile for:   ftrace
# Date created:        06 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/sysutils/ftrace/Makefile,v 1.1 2001/01/06 14:28:05 alex Exp $
#

PORTNAME=	ftrace
PORTVERSION=	0.9
CATEGORIES=	sysutils
MASTER_SITES=	http://software.senko.net/pub/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	greid@ukug.uk.freebsd.org

WRKSRC=		${WRKDIR}/${DISTNAME:S/_/-/}

.include <bsd.port.mk>
