# New ports collection makefile for:   ftrace
# Date created:        06 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/sysutils/ftrace/Makefile,v 1.2 2001/01/16 17:32:34 sobomax Exp $
#

PORTNAME=	ftrace
PORTVERSION=	0.9a
CATEGORIES=	sysutils
MASTER_SITES=	http://software.senko.net/pub/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	greid@ukug.uk.freebsd.org

WRKSRC=		${WRKDIR}/${DISTNAME:S/_/-/}

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
