# New ports collection makefile for:	R (a4)
# Date created:			Tue Jun 23 07:36:55 EST 1998
# Whom:				Maurice Castro <maurice@serc.rmit.edu.au>
#
# $FreeBSD: ports/math/R-a4/Makefile,v 1.3 1999/08/26 22:58:13 cpiazza Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../R-letter

.include "${MASTERDIR}/Makefile"
