# New ports collection makefile for:    prcs
# Date created:         17 Sep 96
# Whom:                 jmacd@FreeBSD.org
#
# $FreeBSD: ports/devel/prcs/Makefile,v 1.16 2000/04/11 21:30:11 mharo Exp $
#

PORTNAME=	prcs
PORTVERSION=	1.2.8
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.xcf.berkeley.edu/pub/prcs/

MAINTAINER=	jmacd@FreeBSD.org

BUILD_DEPENDS=	emacs:${PORTSDIR}/editors/emacs

USE_GMAKE=	yes
HAS_CONFIGURE=	yes
MAN1=		prcs.1

.include <bsd.port.mk>
