#!/bin/sh
# $FreeBSD: ports/www/apache2/pkg-install,v 1.3 2001/10/29 20:05:37 ache Exp $
#

if [ "$2" != "PRE-INSTALL" ]; then
	exit 0
fi

WWWUSER=www
WWWGROUP=${WWWUSER}
WWWUID=80
WWWGID=${WWWUID}

if ! pw groupshow "${WWWGROUP}" 2>/dev/null 1>&2; then
	if pw groupadd ${WWWGROUP} -g ${WWWGID}; then
		echo "Added group \"${WWWGROUP}\"."
	else
		echo "Adding group \"${WWWGROUP}\" failed..."
		exit 1
	fi
fi

if ! pw usershow "${WWWUSER}" 2>/dev/null 1>&2; then
	if pw useradd ${WWWUSER} -u ${WWWUID} -g ${WWWGROUP} -h - \
		-s "/sbin/nologin" -d "/nonexistent" \
		-c "World Wide Web Owner"; \
	then
		echo "Added user \"${WWWUSER}\"."
	else
		echo "Adding user \"${WWWUSER}\" failed..."
		exit 1
	fi
fi

exit 0
