# New ports collection makefile for:	mpage
# Date created:		19 February 1998
# Whom:			Kapil Chowksey
#
# $FreeBSD: ports/print/mpage/Makefile,v 1.2 1999/08/31 01:45:07 peter Exp $
#

PORTNAME=	mpage 
PORTVERSION=	2.5 
CATEGORIES=	print
MASTER_SITES=	ftp://ftp.mesa.nl/pub/mpage/
EXTRACT_SUFX=	.tgz

MAINTAINER=	kchowksey@hss.hns.com

MAN1=		mpage.1
ALL_TARGET=	default

.include <bsd.port.mk>
