# New ports collection makefile for:	mpage
# Date created:		19 February 1998
# Whom:			Kapil Chowksey
#
# $FreeBSD: ports/print/mpage/Makefile,v 1.4 2000/04/09 17:50:16 cpiazza Exp $
#

PORTNAME=	mpage
PORTVERSION=	2.5
CATEGORIES=	print
MASTER_SITES=	ftp://ftp.mesa.nl/pub/mpage/
EXTRACT_SUFX=	.tgz

MAN1=		mpage.1
ALL_TARGET=	default

.include <bsd.port.mk>
