# New ports collection makefile for:    sliderule
# Date created:         4 Aug 1997
# Whom:                 joerg
#
# $FreeBSD: ports/deskutils/sliderule/Makefile,v 1.6 2000/04/08 22:03:51 mharo Exp $
#

PORTNAME=	sliderule
PORTVERSION=	1.0
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org

USE_IMAKE=	yes
MAN1=		sliderule.1

.include <bsd.port.mk>
