# New ports collection makefile for:    dgpsip
# Version required:			1.25
# Date created:         		05 Jun 1999
# Whom:                 		Daniel Baker <dbaker@FreeBSD.org>
#
# $FreeBSD: ports/astro/dgpsip/Makefile,v 1.4 2000/02/02 21:55:59 mharo Exp $
#

DISTNAME=	dgpsip-1.29
CATEGORIES=	astro
MASTER_SITES=	http://www.wsrcc.com/wolfgang/ftp/

MAINTAINER=     dbaker@FreeBSD.org

GNU_CONFIGURE=	YES

MAN1=	dgpsip.1

.include <bsd.port.mk>
