# New ports collection makefile for:    dgpsip
# Date created:         		05 Jun 1999
# Whom:                 		Daniel Baker <dbaker@FreeBSD.org>
#
# $FreeBSD: ports/astro/dgpsip/Makefile,v 1.6 2000/03/27 00:41:20 dbaker Exp $
#

PORTNAME=	dgpsip
PORTVERSION=	1.32
CATEGORIES=	astro
MASTER_SITES=	http://www.wsrcc.com/wolfgang/ftp/

MAINTAINER=     dbaker@FreeBSD.org

GNU_CONFIGURE=	YES

MAN1=	dgpsip.1

.include <bsd.port.mk>
