# Ports collection makefile for:  treecc
# Date created:			  Wed Jul 11 00:45:15 EDT 2001
# Whom:				  Michael Johnson <ahze@ahze.net>
#
# $FreeBSD: ports/lang/treecc/Makefile,v 1.1 2001/08/17 18:04:42 ijliao Exp $
#

PORTNAME=	treecc
PORTVERSION=	0.0.1
CATEGORIES=	lang
MASTER_SITES=	http://www.southern-storm.com.au/download/

MAINTAINER=	ahze@ahze.net

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_BISON=	yes
MAN1=		treecc.1

.include <bsd.port.mk>
