# New ports collection makefile for:	xml-i18n-tools
# Date created:				19th January 2001
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/textproc/xml-i18n-tools/Makefile,v 1.2 2001/01/24 05:10:41 ade Exp $
#

PORTNAME=	xml-i18n-tools
PORTVERSION=	0.6
CATEGORIES=	textproc gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/${PORTNAME}

MAINTAINER=	ade@FreeBSD.org

USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
