# New ports collection makefile for:	xml-i18n-tools
# Date created:				19th January 2001
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/textproc/xml-i18n-tools/Makefile,v 1.3 2001/02/05 16:35:24 olgeni Exp $
#

PORTNAME=	xml-i18n-tools
PORTVERSION=	0.8
CATEGORIES=	textproc gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/${PORTNAME}

MAINTAINER=	ade@FreeBSD.org

USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
