# New ports collection makefile for: tvi
# Date created:		3 Jan 1999
# Whom:			SUGIMURA Takashi <sugimura@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tvi/Makefile,v 1.5 1999/08/31 06:46:34 mharo Exp $
#

PORTNAME=	tvi
PORTVERSION=	0.9.2
CATEGORIES=	japanese
MASTER_SITES=	http://www.kt.rim.or.jp/~motomu/tvi/Arc/

MAINTAINER=	sugimura@jp.FreeBSD.org

RUN_DEPENDS=	wish4.2jp:${PORTSDIR}/japanese/tk42

NO_BUILD=	yes

.include <bsd.port.mk>
