# New ports collection makefile for:    a2ps (a4)
# Date created:         6 November 1994
# Whom:                 jmz & David O'Brien (obrien@cs.ucdavis.edu)
#
# $FreeBSD: ports/print/a2ps43-a4/Makefile,v 1.2 1999/08/31 01:44:24 peter Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../a2ps43-letter

.include "${MASTERDIR}/Makefile"
