# New ports collection makefile for:    p5-MIME-Types
# Date created:                         15 March 2001
# Whom:                                 -
#
# $FreeBSD: ports/mail/p5-MIME-Types/Makefile,v 1.1 2001/05/02 05:54:04 dburr Exp $

PORTNAME=		MIME-Types
PORTVERSION=		0.04
CATEGORIES=		mail perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	MIME
PKGNAMEPREFIX=		p5-

MAINTAINER=		killer@prosalg.no

NO_WRKSUBDIR=		YES
PERL_CONFIGURE=		YES

MAN3PREFIX=		${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=			MIME::Types.3

.include <bsd.port.mk>
