#! /bin/sh

# $FreeBSD: ports/databases/postgresql83-server/pkg-install-server,v 1.7 2008/02/18 12:55:02 girgen Exp $

PATH=/bin:/usr/bin:/usr/sbin

backupwarning() { echo "

  =========== BACKUP YOUR DATA! =============
  As always, backup your data before
  upgrading. If the upgrade leads to a higher
  minor revision (e.g. 7.3.x -> 7.4), a dump
  and restore of all databases is
  required. This is *NOT* done by the port!

  Press ctrl-C *now* if you need to pg_dump.
  ===========================================
"
	sleep 5
}

case $2 in
BACKUPWARNING)
	backupwarning
	;;
esac
