# New ports collection makefile for:	p5-String-Approx
# Date created:				April 15th 2000
# Whom:	      				Ilia Chipitsine <ilia@cgu.chel.su>
#
# $FreeBSD: ports/devel/p5-String-Approx/Makefile,v 1.2 2000/09/17 13:13:16 jedgar Exp $
#

PORTNAME=	String-Approx
PORTVERSION=	3.13
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	String
PKGNAMEPREFIX=	p5-

MAINTAINER=	ilia@cgu.chel.su

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		String::Approx.3

.include <bsd.port.mk>
