# New ports collection makefile for:	xlupe
# Date created:		17 Apr 1999
# Whom:			runge@rostock.zgdv.de
#
# $FreeBSD: ports/x11/xlupe/Makefile,v 1.3 2000/04/13 19:10:45 cpiazza Exp $
#

PORTNAME=	xlupe
PORTVERSION= 	1.0
CATEGORIES=	x11
MASTER_SITES=	http://www.rostock.zgdv.de/~runge/xlupe/

MAINTAINER=	runge@rostock.zgdv.de

USE_IMAKE=	yes
USE_XPM=	yes
REQUIRES_MOTIF=	no

# you can build it with a motif interface as well!
# REQUIRES_MOTIF=	no

#post-install:
#		strip ${PREFIX}/bin/xlupe

.include <bsd.port.mk>
