# New ports collection makefile for:	xlupe
# Date created:		17 Apr 1999
# Whom:			runge@rostock.zgdv.de
#
# $FreeBSD: ports/x11/xlupe/Makefile,v 1.6 2001/02/05 16:18:34 olgeni Exp $
#

PORTNAME=	xlupe
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	http://www.core.de/~coto/xlupe/

MAINTAINER=	runge@core.de

USE_IMAKE=	yes
USE_XPM=	yes
USE_MOTIF=	yes

#post-install:
#		strip ${PREFIX}/bin/xlupe

.include <bsd.port.mk>
