# New ports collection makefile for:	p5-Convert-ASN1
# Date created:				October 27, 2000
# Whom:	      				Marc Fournier <scrappy@FreeBSD.org>
#
# $FreeBSD: ports/converters/p5-Convert-ASN1/Makefile,v 1.1 2000/10/28 01:16:38 scrappy Exp $
#

PORTNAME=	Convert-ASN1
PORTVERSION=	0.07
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Convert
PKGNAMEPREFIX=	p5-

MAINTAINER=	scrappy@FreeBSD.org

PERL_CONFIGURE=	YES

MAN3=		Convert::ASN1.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
