# New ports collection makefile for:    pfe-devel
# Date created:         29 October 2000
# Whom:                 patrick
#
# $FreeBSD: ports/lang/pfe-devel/Makefile,v 1.2 2000/11/25 03:08:39 patrick Exp $
#

PORTNAME=	pfe
PORTVERSION=	0.30.93
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	patrick@FreeBSD.org

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
#USE_BZIP2=	yes

ALL_TARGET=	#

.include <bsd.port.mk>
