# New ports collection makefile for:	kinput2-sj3
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-sj3/Makefile,v 1.8 1999/08/25 05:24:59 obrien Exp $
#

SJ3=		yes

MASTERDIR=	${.CURDIR}/../kinput2-wnn4/
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
