# New ports collection makefile for:	kinput2-sj3
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-sj3/Makefile,v 1.10 2000/09/08 04:34:30 taoka Exp $
#

SJ3=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
