#!/bin/sh
# $FreeBSD: ports/databases/msql/pkg-deinstall,v 1.1 2001/10/21 18:41:42 ache Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=msql

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete MSQL user permanently, use 'pw userdel ${USER}'"
fi

exit 0
