#!/bin/sh
# $FreeBSD: ports/databases/msql/pkg-install,v 1.1 2001/10/21 18:41:42 ache Exp $
#

if [ "$2" != "PRE-INSTALL" ]; then
    exit 0
fi

USER=msql
GROUP=${USER}
UID=98
GID=${UID}

if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
	if pw groupadd ${GROUP} -g ${GID}; then
		echo "Added group \"${GROUP}\"."
	else
		echo "Adding group \"${GROUP}\" failed..."
		exit 1
	fi
fi

if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
		-s "/bin/sh" -d "/var/db/msqldb" \
		-c "mSQL-2 pseudo-user"; \
	then
		echo "Added user \"${USER}\"."
	else
		echo "Adding user \"${USER}\" failed..."
		exit 1
	fi
fi
exit 0
