#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice/files/openoffice-wrapper,v 1.1 2002/08/01 12:29:21 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org1.0/program/
program=`echo $0 | sed -e 's|.*-||'`

case $program in
$0)
	exec $oopath/soffice "$@"
	;;
	*)
	exec $oopath/$program "$@"
	;;
esac
