# New ports collection makefile for:	net/p5-IO-Interface
# Date created:				26 April 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/net/p5-IO-Interface/Makefile,v 1.1 2001/04/28 15:16:30 joe Exp $
#

PORTNAME=	IO-Interface
PORTVERSION=	0.97
CATEGORIES=	net perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	IO
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3=		IO::Interface.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
