# New ports collection makefile for:    icqlib
# Date created:                         16 March 1999
# Whom:                                 Pavel Andreev
#
# $FreeBSD: ports/net/icqlib/Makefile,v 1.5 2000/04/09 18:11:42 cpiazza Exp $
#

PORTNAME=	icqlib
PORTVERSION=	0.1.3
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	paxvel@iname.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
