# New ports collection makefile for:	p5-IO-Stty
# Date created:		14 Jan 2000
# Whom:			Will Andrews <andrews@technologist.com>
#
# $FreeBSD: ports/devel/p5-IO-Stty/Makefile,v 1.6 2000/06/22 05:51:54 will Exp $
#

PORTNAME=	IO-Stty
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	IO
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-.${PORTVERSION:E}

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
