# New ports collection makefile for:   ptex-pkfonts
# Date created:        24 Dec 1999
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/ptex-pkfonts600/Makefile,v 1.3 2000/04/12 14:37:24 knu Exp $
#

USEPK_MODE=	ljfour
RESOLUTION=	600
MASTERDIR=	${.CURDIR}/../ptex-pkfonts300

.include "${MASTERDIR}/Makefile"
