# New ports collection makefile for:	ffsrecov
# Date created:        4 May 1999
# Whom:                jmg
#
# $FreeBSD: ports/sysutils/ffsrecov/Makefile,v 1.8 2000/07/08 02:34:04 obrien Exp $
#

PORTNAME=	ffsrecov
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://www.funkthat.com/~jmg/
DISTNAME=	ffsrecov

MAN8=		ffsrecov.8

.include <bsd.port.mk>
