# New ports collection makefile for:	ffsrecov
# Date created:        4 May 1999
# Whom:                jmg
#
# $FreeBSD: ports/sysutils/ffsrecov/Makefile,v 1.9 2000/07/08 04:13:25 jmg Exp $
#

PORTNAME=	ffsrecov
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://people.freebsd.org/~jmg/
DISTNAME=	ffsrecov

MAN8=		ffsrecov.8

.include <bsd.port.mk>
