# New ports collection makefile for:	ffsrecov
# Date created:        4 May 1999
# Whom:                jmg
#
# $FreeBSD: ports/sysutils/ffsrecov/Makefile,v 1.5 2000/04/22 10:12:10 mharo Exp $
#

PORTNAME=	ffsrecov
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	jmg
DISTNAME=	ffsrecov

MAINTAINER=	jmg@freebsd.org

MAN8=		ffsrecov.8

.include <bsd.port.mk>
