# New ports collection makefile for:    no-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/no-ispell/Makefile,v 1.3 2000/06/10 10:25:49 alex Exp $
#

MAINTAINER=     alex@FreeBSD.org

ISPELL_NO=	yes
PORTNAME=	no-ispell
PORTVERSION= 	2.0
MASTERDIR=      ${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
