# New ports collection makefile for:    no-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/no-ispell/Makefile,v 1.1.1.1 2000/02/11 21:03:11 jmz Exp $
#

MAINTAINER=     alex@big.endian.de

ISPELL_NO=	yes
PORTNAME=	no-ispell
PORTVERSION= 	1.1
MASTERDIR=      ${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
