# New ports collection makefile for:    no-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/no-ispell/Makefile,v 1.5 2001/01/16 17:32:47 sobomax Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_NO=	yes
PORTNAME=	no-ispell
PORTVERSION=	2.0
PORTREVISION=	1
MASTERDIR=	${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
