# New ports collection makefile for:	KDreamSite
# Date created:		12 Nov 1999
# Whom:			Will Andrews <andrews@technologist.com>
#
# $FreeBSD: ports/www/kdreamsite/Makefile,v 1.6 2000/04/10 00:05:32 cpiazza Exp $
#

PORTNAME=	kdreamsite
PORTVERSION= 	0.2
CATEGORIES=	www kde
MASTER_SITES=	http://neptune.spaceports.com/%7Eatnet/files/

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=	kdeui.3:${PORTSDIR}/x11/kdelibs11/

USE_QT=		yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
