# New ports collection makefile for:   tcpstat
# Date created:        29 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/net/tcpstat/Makefile,v 1.1 2001/02/01 23:31:23 dannyboy Exp $
#

PORTNAME=	tcpstat
PORTVERSION=	1.4
CATEGORIES=	net
MASTER_SITES=   http://www.frenchfries.net/paul/tcpstat/

MAINTAINER=	greid@ukug.uk.freebsd.org

GNU_CONFIGURE=	yes

MAN1=		tcpstat.1

.include <bsd.port.mk>
