# New ports collection makefile for:	Text::SimpleTemplate
# Date created:				26 February 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-Text-SimpleTemplate/Makefile,v 1.1 2001/03/01 06:46:49 will Exp $
#

PORTNAME=	Text-SimpleTemplate
PORTVERSION=	0.35
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Text
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Text::SimpleTemplate.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
