# New ports collection makefile for:	chimera
# Date created:		26 December 1994
# Whom:			asami
#
# $FreeBSD: ports/www/chimera/Makefile,v 1.17 1999/09/20 00:39:16 steve Exp $
#

PORTNAME=	chimera
PORTVERSION= 	1.70p0
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.cs.unlv.edu/pub/chimera/

MAINTAINER=	jseger@FreeBSD.org

NO_LATEST_LINK=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
