# New ports collection makefile for:	chimera
# Date created:		26 December 1994
# Whom:			asami
#
# $FreeBSD: ports/www/chimera/Makefile,v 1.19 2001/01/10 14:02:19 sf Exp $
#

PORTNAME=	chimera
PORTVERSION=	1.70p0
PORTREVISION=	1
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.cs.unlv.edu/pub/chimera/

MAINTAINER=	jseger@FreeBSD.org

NO_LATEST_LINK=	yes
USE_IMAKE=	yes

MAN1=		chimera.1

.include <bsd.port.mk>
