# New ports collection makefile for:	gtkextra
# Date created:				17 August 2000
# Whom:					Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/gtkextra/Makefile,v 1.2 2000/08/17 15:03:32 sobomax Exp $
#

PORTNAME=	gtkextra
PORTVERSION= 	0.99.10
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://magnet.fsu.edu/~feiguin/gtk/src/
DISTNAME=	${PORTNAME:S/gtk/gtk+/}-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
