# New ports collection makefile for:	yafc
# Version required:	0.4.9
# Date created:		10 June 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/ftp/yafc/Makefile,v 1.10 1999/11/11 04:48:46 cpiazza Exp $
#

DISTNAME=	yafc-0.5.0
CATEGORIES=	ftp
MASTER_SITES=	ftp://mayer.physto.se/pub/yafc/

MAINTAINER=	cpiazza@FreeBSD.org

GNU_CONFIGURE=	yes
USE_BZIP2=	yes

.include <bsd.port.mk>
