# New ports collection makefile for:    hLaTeXp pkfonts 600dpi
# Date created:                 Jun 29 2000
# Whom:                         CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/hlatexp-pkfonts600/Makefile,v 1.1.1.1 2000/07/02 15:00:58 cjh Exp $
#

MASTERDIR=      ${.CURDIR}/../hlatexp-pkfonts300
FILESDIR=	${.CURDIR}/files
PKGDIR=		${.CURDIR}

# pkfonts dpi
RESOLUTION=	600

.include        "${MASTERDIR}/Makefile"
