# New ports collection makefile for:    Front Line Force Server
# Date created:				Sat Mar 10 16:40:06 EST 2001
# Whom:					pat@databits.net
#
# $FreeBSD: ports/games/hlserver-flf/Makefile,v 1.2 2001/03/24 20:30:46 lioux Exp $
#

PORTNAME=	flf
PORTVERSION=	1.2
MASTER_SITES=	ftp://ftp.icrontic.com/pub/ \
		ftp://ftp.task.gda.pl/vol/d33/ftp.extreme-players.de/exp/hl/mod/frontlineforce/
DISTNAME=	frontline_linux_1.2

HALFLIFE_COUNTERSTRIKE_MASTER=	${.CURDIR}/../hlserver-cs

.include "${HALFLIFE_COUNTERSTRIKE_MASTER}/Makefile"
