# New ports collection makefile for:   pwgen
# Date created:        22 July 2000
# Whom:                Oddbjorn Steffensen <oddbjorn@tricknology.org>
#
# $FreeBSD: ports/sysutils/pwgen/Makefile,v 1.1 2000/07/22 16:37:29 alex Exp $
#

PORTNAME=      pwgen
PORTVERSION=   1.15
CATEGORIES=    sysutils
MASTER_SITES=  http://www.tricknology.org/ports/

MAINTAINER=    oddbjorn@tricknology.org

BUILD_DEPENDS= ${LOCALBASE}/include/getopt.h:${PORTSDIR}/devel/libgnugetopt

MAN1=          pwgen.1
WRKSRC=        ${WRKDIR}/pwgen-1

.include <bsd.port.mk>
