# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.08
# Date created:		13 Mar 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape4-navigator/Makefile,v 1.13 1999/08/25 05:25:51 obrien Exp $
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator

MAINTAINER=	sada@FreeBSD.org

BROWSER=	navigator

.include	"${MASTERDIR}/Makefile"
