# New ports collection makefile for: Netscape browser with Japanese resources
# Version required:	4.08
# Date created:		13 Mar 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape4-navigator/Makefile,v 1.14 1999/08/31 06:45:58 mharo Exp $
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator

BROWSER=	navigator

.include	"${MASTERDIR}/Makefile"
