# New ports collection makefile for: Netscape browser with Japanese resources
# Date created:		13 Mar 1998
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/netscape4-navigator/Makefile,v 1.15 2000/03/26 19:59:44 sada Exp $
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator

BROWSER=	navigator

.include	"${MASTERDIR}/Makefile"
