# ex:ts=8
# New ports collection makefile for:	txt2man
# Date created:			Jun 14, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/textproc/txt2man/Makefile,v 1.2 2001/06/14 10:02:50 ijliao Exp $
#

PORTNAME=	txt2man
PORTVERSION=	1.4.2
CATEGORIES=	textproc
MASTER_SITES=	http://mvertes.free.fr/download/

MAINTAINER=	ports@FreeBSD.org

ALL_TARGET=	txt2man.1
INSTALL_TARGET=	install prefix=${PREFIX}

MAN1=	txt2man.1

.include <bsd.port.mk>
