# ports collection makefile for:	Constant DataBase
# Version required:			0.55
# Date created:				18th July 1998
# Whom:					Gary Palmer <gpalmer@freebsd.org>
#
# $FreeBSD: ports/databases/cdb/Makefile,v 1.7 1999/08/31 06:41:08 mharo Exp $
#

DISTNAME=	cdb-0.55
CATEGORIES=	databases
MASTER_SITES=	http://cr.yp.to/software/

MAINTAINER=	ports@FreeBSD.org

ALL_TARGET=	it
MAN1=		cdbget.1 cdbmake.1 cdbdump.1 cdbstats.1 cdbtest.1
MAN3=		cdb.3

.include <bsd.port.mk>
