# New ports collection makefile for:	acroread-korfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/acroread-korfont/Makefile,v 1.5 2000/04/13 09:15:54 asami Exp $
#

DISTNAME=	korfont
CATEGORIES=	korean

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
