# New ports collection makefile for:   nickle
# Date created:        16 April 2001
# Whom:                Christopher Elkins <chrise@scardini.com>
#
# $FreeBSD: ports/lang/nickle/Makefile,v 1.1 2001/04/17 08:32:28 ijliao Exp $
#

PORTNAME=	nickle
PORTVERSION=	1.99.2
CATEGORIES=	lang
MASTER_SITES=	http://www.nickle.org/release/

MAINTAINER=	ports@FreeBSD.org

USE_BZIP2=	yes
GNU_CONFIGURE=	yes

MAN1=	nickle.1

.include <bsd.port.mk>
