# New ports collection makefile for:    xkobo
# Date created:		18 Jul 1995
# Whom:			jkh
#
# $FreeBSD: ports/games/xkobo/Makefile,v 1.16 2000/03/21 22:46:59 will Exp $
#

PORTNAME=       xkobo
PORTVERSION=	1.11
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}  \
		ftp://ftp.uoknor.edu/mirrors/X/contrib/games/
MASTER_SITE_SUBDIR=	games

MAINTAINER=	will@FreeBSD.org

USE_IMAKE=	yes
ALL_TARGET=	xkobo
MAN1=		xkobo.1

.include <bsd.port.mk>
