# New ports collection makefile for:    xkobo
# Version required:	1.11
# Date created:		18 Jul 1995
# Whom:			jkh
#
# $FreeBSD: ports/games/xkobo/Makefile,v 1.15 2000/01/28 00:45:30 jedgar Exp $
#

DISTNAME=       xkobo-1.11
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}  \
		ftp://ftp.uoknor.edu/mirrors/X/contrib/games/
MASTER_SITE_SUBDIR=	games

MAINTAINER=	will@FreeBSD.org

USE_IMAKE=	yes
ALL_TARGET=	xkobo
MAN1=		xkobo.1

.include <bsd.port.mk>
