# New ports collection makefile for:	jls
# Date created:		4 January 1999
# Whom:			shige
#
# $FreeBSD: ports/japanese/jls/Makefile,v 1.8 2000/06/29 07:02:22 obrien Exp $
#

PORTNAME=	ls
PORTVERSION=	0.2
CATEGORIES=	japanese
MASTER_SITES=	${MASTER_SITE_PORTS_JP} \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	shige
DISTNAME=	j${PORTNAME}-${PORTVERSION}

MAINTAINER=	shige@FreeBSD.org

MAN1=		jls.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
