# New ports collection makefile for:	jls
# Version required:	0.x
# Date created:		4 January 1999
# Whom:			shige
#
# $FreeBSD: ports/japanese/jls/Makefile,v 1.3 1999/08/25 05:24:28 obrien Exp $
#

DISTNAME=	jls-0.1
PKGNAME=	ja-ls-0.1
CATEGORIES=	japanese
MASTER_SITES=	http://www.freebsd.org/~shige/ports/ \
		http://www.yuasa.kuis.kyoto-u.ac.jp/~shige/FreeBSD/programs/

MAINTAINER=	shige@FreeBSD.org

MAN1=		jls.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
