# New ports collection makefile for:	jls
# Date created:		4 January 1999
# Whom:			shige
#
# $FreeBSD: ports/japanese/jls/Makefile,v 1.6 2000/02/08 09:26:52 peter Exp $
#

PORTNAME=	ls
PORTVERSION=	0.1
CATEGORIES=	japanese
MASTER_SITES=	${MASTER_SITE_PORTS_JP} \
		http://people.FreeBSD.org/~shige/ports/
DISTNAME=	j${PORTNAME}-${PORTVERSION}

MAINTAINER=	shige@FreeBSD.org

MAN1=		jls.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
