# New ports collection makefile for:	p5-File-MMagic
# Date created:		25 February 2000
# Whom:	      		Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/devel/p5-File-MMagic/Makefile,v 1.8 2000/10/26 20:37:11 knu Exp $
#

PORTNAME=	File-MMagic
PORTVERSION=	1.09
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	../../authors/id/K/KN/KNOK
PKGNAMEPREFIX=	p5-

MAINTAINER=	knu@FreeBSD.org

PERL_CONFIGURE=	YES

MAN3=		File::MMagic.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
