# New ports collection makefile for:	acroread-korfont
# Version required:	1999.7.20
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/acroread-korfont/Makefile,v 1.3 1999/08/30 12:08:36 peter Exp $
#

DISTNAME=	korfont
CATEGORIES=	korean linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
