# New ports collection makefile for:	acroread-korfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/acroread-korfont/Makefile,v 1.4 2000/02/28 08:33:44 asami Exp $
#

DISTNAME=	korfont
CATEGORIES=	korean linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
