# New ports collection makefile for:	engradient
# Date Created:				21 August 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/engradient/Makefile,v 1.2 2000/09/20 18:18:22 sobomax Exp $
#

PORTNAME=	engradient
PORTVERSION= 	200008151005
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	EnGradient-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/gtk-${PORTNAME}-0.1

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
