# New ports collection makefile for: pips for EPSON PM-820C PM-3300C
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips820_3300/Makefile,v 1.1.1.1 2000/09/01 16:29:44 taoka Exp $
#

CATEGORIES?=	japanese print linux
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		820_3300

do-install:     # empty

.include "${MASTERDIR}/Makefile"
