# New ports collection makefile for: linux-tiff
# Date created:		2001.02.08
# Whom:                 taoka@FreeBSD.org
#
# $FreeBSD: ports/graphics/linux-tiff/Makefile,v 1.1 2001/02/12 16:41:11 taoka Exp $
#

PORTNAME=	tiff
PORTVERSION=	3.4
CATEGORIES=	graphics linux

MAINTAINER=	taoka@FreeBSD.org

RPM_SET=	libtiff-${PORTVERSION}-6.${MACHINE_ARCH}.rpm

.include "../../x11-toolkits/linux-gtk/Makefile"
