# ex:ts=8
# New ports collection makefile for:	whatmask
# Date created:			May 20, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/net/whatmask/Makefile,v 1.1 2001/05/20 11:23:36 ijliao Exp $
#

PORTNAME=	whatmask
PORTVERSION=	1.1
CATEGORIES=	net
MASTER_SITES=	http://downloads.laffeycomputer.com/current_builds/whatmask/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
