# New ports collection makefile for:	JDE's JGV for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/jgv/Makefile,v 1.3 2000/04/11 14:13:58 knu Exp $
#

CATEGORIES=	japanese

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../graphics/jgv

.include	"${MASTERDIR}/Makefile"
