# New ports collection makefile for:	JDE's JGV for ja-TkStep
# Date created:		25 March 1999
# Whom:			KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/jgv/Makefile,v 1.2 1999/08/25 05:24:26 obrien Exp $
#

LANGUAGE=	Japanese
MASTERDIR=	${.CURDIR}/../../graphics/jgv

.include	"${MASTERDIR}/Makefile"
