# New ports collection makefile for:	tnef
# Date created:		19 September 2000
# Whom:			Cyrus Rahman <cr@jcmax.com>
#
# $FreeBSD: ports/converters/tnef/Makefile,v 1.1 2000/10/23 02:59:44 jeh Exp $
#

PORTNAME=	tnef
PORTVERSION=	0.15
CATEGORIES=	converters mail
MASTER_SITES=	http://world.std.com/~damned/

MAINTAINER=	cr@jcmax.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
