# New ports collection makefile for:	tnef
# Date created:		19 September 2000
# Whom:			Cyrus Rahman <cr@jcmax.com>
#
# $FreeBSD: ports/converters/tnef/Makefile,v 1.3 2001/03/13 01:40:03 kris Exp $
#

PORTNAME=	tnef
PORTVERSION=	1.0
CATEGORIES=	converters mail
MASTER_SITES=	http://world.std.com/~damned/

MAINTAINER=	cr@jcmax.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
