# New ports collection makefile for:	tnef
# Date created:		19 September 2000
# Whom:			Cyrus Rahman <cr@jcmax.com>
#
# $FreeBSD: ports/converters/tnef/Makefile,v 1.2 2000/11/22 11:01:41 kris Exp $
#

PORTNAME=	tnef
PORTVERSION=	0.16
CATEGORIES=	converters mail
MASTER_SITES=	http://world.std.com/~damned/

MAINTAINER=	cr@jcmax.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
