# New ports collection makefile for:	links
# Date created:		21 January 2000
# Whom:			Michael Vasilenko <acid@stu.cn.ua>
#
# $FreeBSD: ports/www/links/Makefile,v 1.9 2001/01/16 17:32:56 sobomax Exp $
#

PORTNAME=	links
PORTVERSION=	0.95
PORTREVISION=	1
CATEGORIES=	www
MASTER_SITES=	http://artax.karlin.mff.cuni.cz/~mikulas/vyplody/links/download/ \
		http://www.add.com.pl/links/download/ \
		http://ice.dammit.lt/links/download/

MAINTAINER=	demon@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=		links.1

.include <bsd.port.mk>
