# New ports collection makefile for:	Blackbox
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $FreeBSD: ports/x11-wm/blackbox/Makefile,v 1.33 2000/06/17 16:34:37 cpiazza Exp $
#

PORTNAME=	blackbox
PORTVERSION= 	0.60.3
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://portal.alug.org/pub/blackbox/0.6x.x/

MAINTAINER=	patseal@hyperhost.net

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
USE_BZIP2=	yes
CONFIGURE_ARGS= --disable-styled-frames

.include <bsd.port.mk>
