#!/bin/sh
# $FreeBSD: ports/www/rt40/pkg-deinstall,v 1.1 2008/12/27 03:38:24 pgollucci Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

GROUP=rt

if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
    if pw groupdel ${GROUP}; then
        echo "Removed group \"${GROUP}\"."
    else
        echo "Removing group \"${GROUP}\" failed..."
        exit 1
    fi
fi

exit 0
