#!/bin/sh
# $FreeBSD: ports/www/rt40/pkg-install,v 1.1 2008/12/27 03:38:24 pgollucci Exp $
#

if [ "$2" != "PRE-INSTALL" ]; then
    exit 0
fi

GROUP=rt
GROUPID=180

if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
    if pw groupadd ${GROUP} -g ${GROUPID}; then
        echo "Added group \"${GROUP}\"."
    else
        echo "Adding group \"${GROUP}\" failed..."
        exit 1
    fi
fi

exit 0
