# New ports collection makefile for:	p5-NNTPClient
# Date created:				1st June 2000
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/news/p5-NNTPClient/Makefile,v 1.6 2001/06/11 23:59:47 ade Exp $
#

PORTNAME=	NNTPClient
PORTVERSION=	0.37
CATEGORIES=	news perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	News
PKGNAMEPREFIX=	p5-

MAINTAINER=	petef@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		News::NNTPClient.3

.include <bsd.port.mk>
