# New ports collection makefile for:	ve
# Date created:		25 Aug 1999
# Whom:			Ching-Hong Wu <woju@freebsd.ntu.edu.tw>
#
# $FreeBSD: ports/chinese/ve/Makefile,v 1.2 2000/04/13 08:28:19 asami Exp $
#

PORTNAME=	ve
PORTVERSION=	1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://freebsd.ntu.edu.tw/FreeBSD/woju/source/ \
		ftp://freebsd.csie.nctu.edu.tw/pub/taiwan/NTU/woju/source/
EXTRACT_SUFX=	.tgz

MAINTAINER=	woju@freebsd.ntu.edu.tw

.include <bsd.port.mk>
