# New ports collection makefile for:	ve
# Version required:	1.0
# Date created:		25 Aug 1999
# Whom:			Ching-Hong Wu <woju@freebsd.ntu.edu.tw>
#
# $FreeBSD: Makefile,v 1.1.1.1 1999/04/03 01:36:11 steve Exp $
#

DISTNAME=	ve-1.0
PKGNAME=	zh-ve-1.0
CATEGORIES=	chinese
MASTER_SITES=	ftp://freebsd.ntu.edu.tw/freebsd/woju/source/ \
		ftp://bsd.sinica.edu.tw/pub/FreeBSD/taiwan/users/woju/source/
EXTRACT_SUFX=	.tgz

MAINTAINER=	woju@freebsd.ntu.edu.tw

.include <bsd.port.mk>
