# New ports collection makefile for:   dvi2tty
# Date created:		17th February 1997
# Whom:			Joel Sutton <jsutton@bbcon.com.au>
#
# $FreeBSD: ports/print/dvi2tty/Makefile,v 1.12 2001/02/14 20:19:04 lioux Exp $
#
 
PORTNAME=	dvi2tty
PORTVERSION=	1.0
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_TEX_CTAN}
MASTER_SITE_SUBDIR=	nonfree/dviware
DISTNAME=	${PORTNAME}
EXTRACT_SUFX=	.tar

MAINTAINER=	ports@FreeBSD.org

IGNOREFILES=	${DISTFILES}
MAN1=		dvi2tty.1

.include <bsd.port.mk>
