# New ports collection makefile for:   dvi2tty
# Date created:		17th February 1997
# Whom:			Joel Sutton <jsutton@bbcon.com.au>
#
# $FreeBSD: ports/print/dvi2tty/Makefile,v 1.8 2000/04/09 17:39:50 cpiazza Exp $
#
     
PORTNAME=	dvi2tty
PORTVERSION=	1.0
CATEGORIES=	print
MASTER_SITES=	ftp://ctan.unsw.edu.au/ctan/tex-archive/dviware/
DISTNAME=	dvi2tty

MAINTAINER=	jsutton@bbcon.com.au

IGNOREFILES=	${DISTFILES}
MAN1=		dvi2tty.1

.include <bsd.port.mk>
