# New ports collection makefile for: Netscape browser with Japanese resources
# Date created:		26 Mar 2000
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/linux-netscape47-navigator/Makefile,v 1.2 2000/04/11 14:14:45 knu Exp $
#

BROWSER_NAME=	navigator

.include	"${.CURDIR}/../linux-netscape47-communicator/Makefile"
