# New ports collection makefile for: Netscape browser with Japanese resources
# Date created:		26 Mar 2000
# Whom:			sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/linux-netscape47-navigator/Makefile,v 1.1.1.1 2000/03/26 20:09:40 sada Exp $
#

BROWSER=	navigator

.include	"${.CURDIR}/../linux-netscape47-communicator/Makefile"
