# New ports collection makefile for:	Crypt-ECB
# Date created:				Wed Jan  3 16:09:46 2001
# Whom:					will
#
# $FreeBSD: ports/security/p5-Crypt-ECB/Makefile,v 1.1 2001/01/03 23:26:02 will Exp $
#

PORTNAME=	Crypt-ECB
PORTVERSION=	1.1
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Crypt
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Crypt::ECB.3

.include <bsd.port.mk>
