# New ports collection makefile for:    mpeg_encode
# Date created:         
# Whom:                 erich@FreeBSD.org
#
# $FreeBSD: ports/graphics/mpeg_encode/Makefile,v 1.9 2000/04/14 10:46:42 asami Exp $
#

PORTNAME=	mpeg_encode
PORTVERSION=	1.5b
CATEGORIES=	graphics
MASTER_SITES=	ftp://mm-ftp.CS.Berkeley.EDU/pub/multimedia/mpeg/encode/
DISTNAME=	${PKGNAME}-src

MAINTAINER=	ports@FreeBSD.org

USE_GMAKE=	yes

MAN1=		mpeg_encode.1
MANCOMPRESSED=	yes

WRKSRC=		${WRKDIR}/mpeg_encode

.include <bsd.port.mk>
