# New ports collection makefile for:	p5-Socket6
# Date created:		24 May 2000
# Whom:	      		Hajimu UMEMOTO <ume@FreeBSD.org>
#
# $FreeBSD: ports/net/p5-Socket6/Makefile,v 1.5 2001/03/01 06:38:43 vanilla Exp $
#

PORTNAME=	Socket6
PORTVERSION=	0.10
CATEGORIES=	net perl5 ipv6
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Socket6
PKGNAMEPREFIX=	p5-

MAINTAINER=	ume@FreeBSD.org

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
