# New ports collection makefile for:	lookup for Emacs20
# Date created:		98/11/19
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/lookup-emacs20/Makefile,v 1.6 2000/04/11 14:14:51 knu Exp $
#

RUN_DEPENDS=	${PREFIX}/share/emacs/site-lisp/bitmap/bitmap.el:${PORTSDIR}/editors/bitmap-emacs20 \

MASTERDIR=	${.CURDIR}/../lookup-mule
EMACS_PORT_NAME=	emacs20

.include	"${MASTERDIR}/Makefile"
