# New ports collection makefile for:	libneural
# Date created:				14 Jun 2000
# Whom:					will
#
# $FreeBSD: ports/math/libneural/Makefile,v 1.2 2000/07/30 14:41:27 kevlo Exp $
#

PORTNAME=	libneural
PORTVERSION=	1.0.2
CATEGORIES=	math devel
MASTER_SITES=	http://ieee.uow.edu.au/documents/contrib/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
