# New ports collection makefile for:	xipmsg
# Date created:		29 May 1997
# Whom:			candy@fct.kgc.co.jp
#
# $FreeBSD: ports/net/xipmsg/Makefile,v 1.3 1999/08/30 14:24:34 peter Exp $
#

PORTNAME=	xipmsg
PORTVERSION=	0.8087
CATEGORIES=	net
MASTER_SITES=	http://hp.vector.co.jp/authors/VA004959/xipmsg/
DISTNAME=	xipmsg-8087

MAINTAINER=	candy@kgc.co.jp

USE_IMAKE=	yes
MAN1=		xipmsg.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
