# New ports collection makefile for:    html2latex
# Version required:     0.9c
# Date created:         29-March-1996
# Whom:                 joerg
#
# $FreeBSD: ports/print/html2latex/Makefile,v 1.6 1999/08/31 01:44:52 peter Exp $
#

DISTNAME=	html2latex-0.9c
PKGNAME=	html2latex-0.9
CATEGORIES=	print
# I can't seem to find the original dist site
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/
DISTFILES=	html2latex-0.9c.tar.Z

MAINTAINER=	joerg@FreeBSD.org

MAN1=		html2latex.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
