# New ports collection makefile for:    html2latex
# Date created:         29-March-1996
# Whom:                 joerg
#
# $FreeBSD: ports/print/html2latex/Makefile,v 1.8 2000/04/09 17:40:23 cpiazza Exp $
#

PORTNAME=	html2latex
PORTVERSION=	0.9c
CATEGORIES=	print
# I can't seem to find the original dist site
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	joerg@FreeBSD.org

MAN1=		html2latex.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
