# ports collection makefile for: tdir
# Date Created:		03 July 2001
# Whom:			tundra
#
# $FreeBSD: ports/sysutils/tdir/Makefile,v 1.2 2001/07/19 13:55:53 markp Exp $

PORTNAME=	tdir
PORTVERSION=	1.66
CATEGORIES=	sysutils
MASTER_SITES=	http://www.tundraware.com/Software/tdir/

MAINTAINER=	tundra@tundraware.com

USE_PYTHON=	yes
MANCOMPRESSED=	yes
MAN1=		tdir.1

.include	<bsd.port.mk>
