# New ports collection makefile for:	aXe-6.1.2
# Version required:	6.1.2
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $FreeBSD: ports/editors/axe/Makefile,v 1.6 1999/08/25 05:43:25 obrien Exp $
#

DISTNAME=	aXe-6.1.2
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	editors
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
