# New ports collection makefile for:	aXe
# Date created:		28 December 1994
# Whom:			jc@irbs.com John Capo
#
# $FreeBSD: ports/editors/axe/Makefile,v 1.7 2000/02/05 10:55:41 dirk Exp $
#

PORTNAME=	aXe
PORTVERSION=	6.1.2
CATEGORIES=	editors
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	editors
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
