# New ports collection makefile for:	gdrdao
# Date created:				November 5 2000
# Whom:					Anders Nordby <anders@fix.no>
#
# $FreeBSD: ports/audio/gdrdao/Makefile,v 1.2 2001/03/23 06:36:32 dinoex Exp $

PORTNAME=	gdrdao
PORTVERSION=	0.4.1
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

RUN_DEPENDS=	cdrdao:${PORTSDIR}/audio/cdrdao

USE_GNOME=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
