# New ports collection makefile for: xdvi-17miyu + patches + vector font library
# Date created:		8 Nov 1996
# Whom:			Mita Yoshio <mita@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/vfxdvi360/Makefile,v 1.4 1999/08/25 05:27:43 obrien Exp $
#

RESOLUTION=	360
MASTERDIR=	${.CURDIR}/../vfxdvi300

.include	"${MASTERDIR}/Makefile"
