# New ports collection makefile for:   brs
# Date created:        10 July 2000
# Whom:                Kim Scarborough <user@unknown.nu>
#
# $FreeBSD: ports/misc/brs/Makefile,v 1.1.1.1 2000/07/12 15:37:32 kevlo Exp $
#

PORTNAME=      brs
PORTVERSION=   4.0
CATEGORIES=    misc
MASTER_SITES=  ${MASTER_SITE_SUNSITE} 
MASTER_SITE_SUBDIR=    apps/religion

DISTNAME=      brs.4.00.l1

MAINTAINER=    user@unknown.nu

WRKSRC=	       ${WRKDIR}/bible
ALL_TARGET=

MAN1=          bible.1
MANCOMPRESSED= no

.include <bsd.port.mk>
