# $FreeBSD: ports/german/Makefile,v 1.14 2000/09/22 07:02:16 asami Exp $
#

    SUBDIR += BBBike
    SUBDIR += cheapcall
    SUBDIR += citrix_ica
    SUBDIR += dict
    SUBDIR += ispell
    SUBDIR += ispell-alt
    SUBDIR += ispell-neu
    SUBDIR += manpages
    SUBDIR += phone
    SUBDIR += staroffice5
    SUBDIR += staroffice52
    SUBDIR += webalizer
    SUBDIR += webalizer2

.include <bsd.port.subdir.mk>
