# $FreeBSD: ports/german/Makefile,v 1.13 2000/09/21 01:52:35 asami Exp $
#

    SUBDIR += BBBike
    SUBDIR += cheapcall
    SUBDIR += dict
    SUBDIR += ispell
    SUBDIR += ispell-alt
    SUBDIR += ispell-neu
    SUBDIR += manpages
    SUBDIR += phone
    SUBDIR += staroffice5
    SUBDIR += staroffice52
    SUBDIR += webalizer
    SUBDIR += webalizer2

.include <bsd.port.subdir.mk>
