# $FreeBSD: ports/german/Makefile,v 1.10 2000/01/14 02:09:48 asami Exp $
#

    SUBDIR += BBBike
    SUBDIR += cheapcall
    SUBDIR += dict
    SUBDIR += manpages
    SUBDIR += phone
    SUBDIR += spinne
    SUBDIR += staroffice5
    SUBDIR += webalizer
    SUBDIR += webalizer2

.include <bsd.port.subdir.mk>
