# $FreeBSD: ports/cad/Makefile,v 1.21 2001/03/07 11:00:30 knu Exp $
#

    SUBDIR += acs
    SUBDIR += chipmunk
    SUBDIR += cider
    SUBDIR += electric
    SUBDIR += felt
    SUBDIR += geda
    SUBDIR += irsim
    SUBDIR += iverilog
    SUBDIR += kaskade
    SUBDIR += magic
    SUBDIR += mars
    SUBDIR += oregano
    SUBDIR += pcb
    SUBDIR += pisces
    SUBDIR += qcad
    SUBDIR += sceptre
    SUBDIR += sis
    SUBDIR += spice
    SUBDIR += tkgate
    SUBDIR += vipec
    SUBDIR += xcircuit

.include <bsd.port.subdir.mk>
