# $FreeBSD: ports/cad/Makefile,v 1.18 2000/07/30 07:14:47 sada Exp $
#

    SUBDIR += acs
    SUBDIR += chipmunk
    SUBDIR += cider
    SUBDIR += electric
    SUBDIR += felt
    SUBDIR += geda
    SUBDIR += irsim
    SUBDIR += kaskade
    SUBDIR += magic
    SUBDIR += mars
    SUBDIR += pcb
    SUBDIR += pisces
    SUBDIR += qcad
    SUBDIR += sceptre
    SUBDIR += sis
    SUBDIR += spice
    SUBDIR += tkgate
    SUBDIR += xcircuit

.include <bsd.port.subdir.mk>
