# New ports collection makefile for:	xarchie
# Date created:		24 September 1994
# Whom:			jkh
#
# $FreeBSD: ports/net/xarchie/Makefile,v 1.16 2000/04/09 18:13:58 cpiazza Exp $
#

PORTNAME=	xarchie
PORTVERSION=	2.0.10
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_GMAKE=	yes
MAN1=		xarchie.1

.include <bsd.port.mk>
