# New ports collection makefile for:	xarchie
# Date created:		24 September 1994
# Whom:			jkh
#
# $FreeBSD: ports/net/xarchie/Makefile,v 1.15 1999/08/30 14:24:32 peter Exp $
#

PORTNAME=	xarchie
PORTVERSION=	2.0.10
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
