# New ports collection makefile for:	acm
# Date created:		23 February 1998
# Whom:			Peter Mutsaers
#
# $FreeBSD: ports/games/blackjack/Makefile,v 1.7 2000/04/14 00:45:29 mharo Exp $
#

PORTNAME=	blackjack
PORTVERSION=	1.1
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	games/strategy

USE_QT=		yes
WRKSRC=		${WRKDIR}/blackjack

MAN1=		blackjack.1

.include <bsd.port.mk>
