# New ports collection makefile for:    stat
# Date created:         16 Februar 1996
# Whom:                 wosch
#
# $FreeBSD: ports/sysutils/stat/Makefile,v 1.8 2000/04/09 19:08:33 cpiazza Exp $
#

PORTNAME=	stat
PORTVERSION=	1.3
CATEGORIES=	sysutils
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		stat.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
