# New ports collection makefile for:    stat
# Version required:     1.3
# Date created:         16 Februar 1996
# Whom:                 wosch
#
# $FreeBSD: ports/sysutils/stat/Makefile,v 1.6 1999/08/31 02:00:07 peter Exp $

DISTNAME=       stat-1.3
CATEGORIES=	sysutils
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		stat.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
