# New ports collection makefile for:    stat
# Date created:         16 Februar 1996
# Whom:                 wosch
#
# $FreeBSD: ports/sysutils/stat/Makefile,v 1.9 2000/04/22 10:13:19 mharo Exp $
#

PORTNAME=	stat
PORTVERSION=	1.3
CATEGORIES=	sysutils
MASTER_SITES=	http://www.de.freebsd.org/~wosch/src/

MAINTAINER=	wosch@FreeBSD.org

MAN1=		stat.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
