# New ports collection makefile for:	ja-tcsh NLS catalog (Multi)
# Version required:	6.08.05
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-multi/Makefile,v 1.7 1999/08/25 05:27:22 obrien Exp $
#

DISTNAME=	tcsh-6.08.05.add2
PKGNAME=	ja-tcsh-nls-multi-6.08.05
CATEGORIES=	japanese shells
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST
NLSSRC=		${DISTNAME}/nls/ja.multi

.include	"${MASTERDIR}/Makefile"
