# New ports collection makefile for:	ja-tcsh NLS catalog (Multi)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-multi/Makefile,v 1.9 2000/04/12 14:37:58 knu Exp $
#

CATALOGNAME=	multi

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

.include	"${MASTERDIR}/Makefile"
