# New ports collection makefile for:	ja-tcsh NLS catalog (Multi)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-multi/Makefile,v 1.8 1999/08/31 06:46:28 mharo Exp $
#

CATALOGNAME=	multi

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
