# New ports collection makefile for:	xpostit+
# Date created:		26 Sep 1997
# Whom:			mi
#
# $FreeBSD: ports/deskutils/xpostitPlus/Makefile,v 1.6 1999/10/26 21:18:42 fenner Exp $
#

PORTNAME=	XPostitPlus
PORTVERSION=	2.3
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	office

MAINTAINER=	mi@aldan.algebra.com

USE_IMAKE=	yes
MAN1=		xpostit+.1

.include <bsd.port.mk>
