# New ports collection makefile for:	xpostit+
# Version required:	2.3
# Date created:		26 Sep 1997
# Whom:			mi
#
# $FreeBSD: ports/deskutils/xpostitPlus/Makefile,v 1.5 1999/08/25 05:27:03 obrien Exp $
#

DISTNAME=	XPostitPlus-2.3
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	office

MAINTAINER=	mi@aldan.algebra.com

USE_IMAKE=	yes
MAN1=		xpostit+.1

.include <bsd.port.mk>
