# New ports collection makefile for:	xpostit+
# Date created:		26 Sep 1997
# Whom:			mi
#
# $FreeBSD: ports/deskutils/xpostitPlus/Makefile,v 1.7 2000/04/08 22:04:09 mharo Exp $
#

PORTNAME=	XPostitPlus
PORTVERSION=	2.3
PORTREVISION=	1
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	office

MAINTAINER=	mi@aldan.algebra.com

USE_IMAKE=	yes
MAN1=		xpostit+.1

.include <bsd.port.mk>
