# New ports collection makefile for:	Wnn for Chinese
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/Wnn/Makefile,v 1.8 1999/08/25 04:57:35 obrien Exp $
#

CATEGORIES=	chinese

## COMMENT, DESCR, PLIST is used in a local 'pkg' directory
COMMENT=	${.CURDIR}/pkg/COMMENT
DESCR=		${.CURDIR}/pkg/DESCR
PLIST=		${.CURDIR}/pkg/PLIST

MASTERDIR=	${.CURDIR}/../../japanese/Wnn

.include "${MASTERDIR}/Makefile"
