# New ports collection makefile for:	server of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/FreeWnn-server/Makefile,v 1.9 2000/04/12 14:46:52 knu Exp $
#

PKGNAMESUFFIX=	-server
CATEGORIES=	chinese
MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}/pkg
PKGINSTALL=	${.CURDIR}/../../japanese/FreeWnn-server/pkg/INSTALL
WNN=		cWnn

.include "${MASTERDIR}/Makefile"
