# New ports collection makefile for:	server of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/FreeWnn-server/Makefile,v 1.10 2000/09/12 17:08:25 taoka Exp $
#

PKGNAMESUFFIX=	-server
CATEGORIES=	chinese
MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}
PKGINSTALL=	${.CURDIR}/../../japanese/FreeWnn-server/pkg-install
WNN=		cWnn

.include "${MASTERDIR}/Makefile"
