# New ports collection makefile for:	team
# Date created:		1 July 1995
# Whom:			joerg
#
# $FreeBSD: ports/misc/team/Makefile,v 1.12 2000/06/09 21:59:05 asami Exp $
#

PORTNAME=	team
PORTVERSION=	3.1
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS

MAINTAINER=	joerg@FreeBSD.org

MAN1=		team.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
