# New ports collection makefile for:	team
# Date created:		1 July 1995
# Whom:			joerg
#
# $FreeBSD: ports/misc/team/Makefile,v 1.9 2000/04/14 08:46:48 asami Exp $
#

PORTNAME=	team
PORTVERSION=	3.1
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	joerg@FreeBSD.org

MAN1=		team.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
