# New ports collection makefile for:	team
# Version required:	3.1 (From the RCS Id line of team.c)
# Date created:		1 July 1995
# Whom:			joerg
#
# $FreeBSD: ports/misc/team/Makefile,v 1.8 1999/08/25 07:22:42 obrien Exp $
#

PORTNAME=	team
PORTVERSION=	3.1
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	joerg@FreeBSD.org

MAN1=		team.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
