# New ports collection makefile for:  rshell
# Version required:    1.0
# Date created:        1997/06/09
# Whom:                wosch
#
# $FreeBSD: ports/net/rshell/Makefile,v 1.8 1999/08/30 14:24:03 peter Exp $
#

DISTNAME=	rshell-1.0
CATEGORIES=	net
MASTER_SITES=	http://www.freebsd.org/~wosch/src/

MAINTAINER=	wosch@FreeBSD.org

MAN1=		rshell.1
MLINKS=		rshell.1 rcopy.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
