# New ports collection makefile for:  rshell
# Date created:        1997/06/09
# Whom:                wosch
#
# $FreeBSD: ports/net/rshell/Makefile,v 1.10 1999/09/19 10:30:45 wosch Exp $
#

PORTNAME=	rshell
PORTVERSION=	1.0
DISTNAME=	rshell-1.0
CATEGORIES=	net
MASTER_SITES=	http://www.de.freebsd.org/~wosch/src/

MAINTAINER=	wosch@FreeBSD.org

MAN1=		rshell.1
MLINKS=		rshell.1 rcopy.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
