#!/bin/sh
# $FreeBSD: ports/www/apache13/pkg-deinstall,v 1.1 2001/10/21 17:33:37 ache Exp $
#

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER=www

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "To delete Apache user permanently, use 'pw userdel ${USER}'"
fi

exit 0
