# New ports collection makefile for:    british-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/british-ispell/Makefile,v 1.4 2001/01/16 17:32:41 sobomax Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_BRITISH=	yes
PORTNAME=	british-ispell
PORTVERSION=	3.1
PORTREVISION=	1
MASTERDIR=	${.CURDIR}/../ispell

SCRIPTS_ENV=	ISPELL_BRITISH=yes

.include        "${MASTERDIR}/Makefile"
