# New ports collection makefile for:    british-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/british-ispell/Makefile,v 1.1.1.1 2000/02/11 17:18:32 jmz Exp $
#

MAINTAINER=     alex@big.endian.de

ISPELL_BRITISH=	yes
PORTNAME=	british-ispell
PORTVERSION= 	3.1
MASTERDIR=      ${.CURDIR}/../ispell

SCRIPTS_ENV=	ISPELL_BRITISH=yes

.include        "${MASTERDIR}/Makefile"
