# New ports collection makefile for:	bcc
# Date created:		26 March 1995
# Whom:			joerg
#
# $FreeBSD: ports/devel/sdcc/Makefile,v 1.7 2000/12/11 02:23:46 steve Exp $
#

PORTNAME=	sdcc
PORTVERSION=	2.1.9
CATEGORIES=	devel lang
MASTER_SITES=	http://www.geocities.com/ResearchTriangle/Forum/1353/
DISTNAME=	${PORTNAME}-${PORTVERSION}Ea

MAINTAINER=	ambrisko@whistle.com

WRKSRC=		${WRKDIR}/sdcc219Ea
GNU_CONFIGURE=	yes
USE_BISON=	yes
USE_GMAKE=	yes
ALL_TARGET=	dep all

.include <bsd.port.mk>
