# New ports collection makefile for:	bcc
# Date created:		26 March 1995
# Whom:			joerg
#
# $FreeBSD: ports/devel/sdcc/Makefile,v 1.3 2000/04/14 05:44:24 asami Exp $
#

PORTNAME=	sdcc
PORTVERSION=	2.1.9
CATEGORIES=	devel lang
MASTER_SITES=	http://www.geocities.com/ResearchTriangle/Forum/1353/
DISTNAME=	${PORTNAME}-${PORTVERSION}Ea

MAINTAINER=	ambrisko@whistle.com

WRKSRC=         ${WRKDIR}/sdcc219Ea
GNU_CONFIGURE=	yes
USE_GMAKE=      yes
ALL_TARGET=	dep all

.include <bsd.port.mk>
