# New ports collection makefile for:	ruby-man-jp
# Date created:			19 Aug 2000
# Whom:				Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/ruby-man/Makefile,v 1.1 2000/08/18 18:53:10 knu Exp $
#

MASTERDIR=	${.CURDIR}/../../lang/ruby-man

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

FILESDIR=	${.CURDIR}/files
PKGDIR=		${.CURDIR}

LANGSUFFIX=	-jp

.include "${MASTERDIR}/Makefile"
