# New ports collection makefile for:	ruby-man-jp
# Date created:			19 Aug 2000
# Whom:				Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/ruby-man/Makefile,v 1.2 2000/10/08 10:21:19 asami Exp $
#

MASTERDIR=	${.CURDIR}/../../lang/ruby-man

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

MD5_FILE=	${.CURDIR}/distinfo
PKGDIR=		${.CURDIR}

LANGSUFFIX=	-jp

.include "${MASTERDIR}/Makefile"
