# New ports collection makefile for:	kdegames2
# Date created:				Sun 14 May 2000 02:47:57
# Whom:					Will Andrews <will@FreeBSD.org>
#
# $FreeBSD: ports/games/kdegames2/Makefile,v 1.51 2001/03/24 22:15:40 will Exp $
#

PORTNAME=	kdegames
PORTVERSION=	2.1.1
CATEGORIES=	games kde
MASTER_SITES=	${MASTER_SITE_KDE}
MASTER_SITE_SUBDIR=	stable/${PORTVERSION}/distribution/tar/generic/src

MAINTAINER=	will@FreeBSD.org

USE_KDELIBS_VER=2
USE_BZIP2=	yes
USE_AUTOCONF=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
