# New ports collection makefile for:    nl-ispell
# Date created:                         13 January 2001
# Whom:                                 alex
#
# $FreeBSD: ports/textproc/nl-ispell/Makefile,v 1.3 2001/01/26 16:57:41 alex Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_NL=	yes
PORTNAME=	nl-ispell
PORTVERSION=	1.0.0
PORTREVISION=	2
MASTERDIR=	${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
