# New ports collection makefile for:    nl-ispell
# Date created:                         13 January 2001
# Whom:                                 alex
#
# $FreeBSD: ports/textproc/nl-ispell/Makefile,v 1.2 2001/01/16 17:32:46 sobomax Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_NL=	yes
PORTNAME=	nl-ispell
PORTVERSION=	1.0.0
PORTREVISION=	1
MASTERDIR=	${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
