# New ports collection makefile for:    nl-ispell
# Date created:                         13 January 2001
# Whom:                                 alex
#
# $FreeBSD: ports/textproc/nl-ispell/Makefile,v 1.1 2001/01/13 15:50:15 alex Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_NO=	yes
PORTNAME=	nl-ispell
PORTVERSION=	1.0.0
MASTERDIR=	${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
