# New ports collection makefile for:	pike-gtk
# Date created:		June 29, 1999
# Whom:	      		Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
#
# $FreeBSD: ports/x11-toolkits/pike-gtk/Makefile,v 1.3 2000/04/21 07:01:54 mharo Exp $
#

PORTNAME=	pike-gtk
PORTVERSION=	1.1.3
CATEGORIES=	x11-toolkits lang
MASTER_SITES=	http://pike-community.org/sites/pigtk/download/
DISTNAME=	pigtk_${PORTVERSION}

MAINTAINER=	ijliao@csie.nctu.edu.tw

BUILD_DEPENDS=	pike:${PORTSDIR}/lang/pike

USE_XLIB=	yes
USE_GTK=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
