# New ports collection makefile for:	xtoolwait
# Date created:		31 May 1997
# Whom:			jonny
#
# $FreeBSD: ports/x11/xtoolwait/Makefile,v 1.4 2000/04/13 19:11:08 cpiazza Exp $
#

PORTNAME=	xtoolwait
PORTVERSION=	1.3
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xtoolwait.1

.include <bsd.port.mk>
