# New ports collection makefile for:	AI-NeuralNet-BackProp
# Date created:				15 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/math/p5-AI-NeuralNet-BackProp/Makefile,v 1.1 2001/01/01 08:00:37 will Exp $
#

PORTNAME=	AI-NeuralNet-BackProp
PORTVERSION=	0.89
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	AI
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

USE_PERL5=	yes
USE_ZIP=	yes
NO_WRKSUBDIR=	yes
PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		AI::NeuralNet::BackProp.3

.include <bsd.port.mk>
