# New ports collection makefile for:	jvim3 for Canna and Wnn6
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-canna+wnn6/Makefile,v 1.9 2000/04/11 14:14:13 knu Exp $
#

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
