# New ports collection makefile for:    splay
# Date created:         1 Apr 1997
# Whom:                 cjh
#
# $FreeBSD: ports/audio/splay/Makefile,v 1.11 2001/04/02 13:57:01 cjh Exp $
#
# pthread library can be used, but sound quality is buggy
#

PORTNAME=		splay
PORTVERSION=		0.9.5.2
CATEGORIES=		audio
MASTER_SITES=		http://splay.sourceforge.net/tgz/

MAINTAINER=		cjh@FreeBSD.org

GNU_CONFIGURE=		yes
MAN1=			splay.1

.include <bsd.port.mk>
