# New ports collection makefile for:    splay
# Date created:         1 Apr 1997
# Whom:                 cjh
#
# $FreeBSD: ports/audio/splay/Makefile,v 1.10 2000/04/08 21:24:29 mharo Exp $
#
# pthread library can be used, but sound quality is buggy
#

PORTNAME=		splay
PORTVERSION=		0.9.5.1
CATEGORIES=		audio
MASTER_SITES=		ftp://splay.sourceforge.net/pub/splay/

MAINTAINER=		cjh@FreeBSD.org

GNU_CONFIGURE=		yes
MAN1=			splay.1

.include <bsd.port.mk>
