# New ports collection makefile for:	diction
# Date created:		2 August 1998
# Whom:			J Han <hjh@best.com>
#
# $FreeBSD: ports/misc/diction/Makefile,v 1.6 2000/04/14 08:45:36 asami Exp $
#

PORTNAME=	diction
PORTVERSION=	0.9
CATEGORIES=	misc
MASTER_SITES=	http://www.moria.de/~michael/diction/

MAINTAINER=	ports@FreeBSD.org

USE_AUTOCONF=	yes

MAN1=		diction.1 style.1

.include <bsd.port.mk>
