# New ports collection makefile for: diction
# Version required:	0.8
# Date created:		2 August 1998
# Whom:			J Han <hjh@best.com>
#
# $FreeBSD: ports/misc/diction/Makefile,v 1.4 1999/08/25 07:21:31 obrien Exp $
#

DISTNAME=		diction-0.8
CATEGORIES=		misc
MASTER_SITES=		ftp://cantor.informatik.rwth-aachen.de/pub/unix/

MAINTAINER=		ports@FreeBSD.org

GNU_CONFIGURE=		yes
USE_GMAKE=		yes

MAKE_ENV=		MKDIR="$(MKDIR)"

MAN1=			diction.1 style.1

.include <bsd.port.mk>
