# New ports collection makefile for:	diction
# Date created:		2 August 1998
# Whom:			J Han <hjh@best.com>
#
# $FreeBSD: ports/misc/diction/Makefile,v 1.7 2000/12/19 08:17:41 sobomax Exp $
#

PORTNAME=	diction
PORTVERSION=	1.01
CATEGORIES=	misc
MASTER_SITES=	http://www.moria.de/~michael/diction/

MAINTAINER=	ports@FreeBSD.org

USE_AUTOCONF=	yes

MAN1=		diction.1 style.1

.include <bsd.port.mk>
