# New ports collection makefile for:	python-doc-postscript-letter
# Date created:		02 June 1999
# Whom:			Thomas Gellekum <tg@FreeBSD.org>
#
# $FreeBSD: ports/lang/python-doc-postscript-letter/Makefile,v 1.3 1999/09/10 18:58:20 peter Exp $
#

DOCFORMAT=	postscript-letter
MASTERDIR=	${.CURDIR}/../python-doc-html

.include "${MASTERDIR}/Makefile"
