# New ports collection makefile for:	p5-Convert-BER
# Date created:				October 27, 2000
# Whom:	      				Marc Fournier <scrappy@FreeBSD.org>
#
# $FreeBSD: ports/converters/p5-Convert-BER/Makefile,v 1.1 2000/10/28 00:03:48 scrappy Exp $
#

PORTNAME=	Convert-BER
PORTVERSION=	1.31
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Convert
PKGNAMEPREFIX=	p5-

MAINTAINER=	scrappy@FreeBSD.org

PERL_CONFIGURE=	YES

MAN3=		Convert::BER.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
