# New ports collection makefile for:	sh-rtems-chill
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sh-rtems-chill/Makefile,v 1.1 2000/07/10 04:32:29 steve Exp $
#

PORTNAME=	chill

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sh-rtems
.include "${.CURDIR}/../i386-rtems-chill/Makefile"
