# New ports collection makefile for: ja-jlatex209
# Date created:		4 Nov 1996
# Whom:			Mita Yoshio <mita@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/jtex209-ascii/Makefile,v 1.6 2000/04/11 14:14:01 knu Exp $
#

BATCH_TEX=	ASCII

MANUAL_PACKAGE_BUILD=	incompatible with other versions of jtex-*

MASTERDIR=	${.CURDIR}/../jtex209-both/
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
