#! /bin/sh
#
# $FreeBSD: ports/net/smokeping/pkg-install,v 1.4 2004/05/18 13:23:20 erwin Exp $
#

case $2 in
PRE-INSTALL)
	if ! pw groupshow %%GROUP%% 2>/dev/null 1>&2; then
		if pw groupadd %%GROUP%% -g %%GID%% ; then
			echo 'Added group "%%GROUP%%".'
		else
			echo 'Adding group "%%GROUP%%" failed...'
			exit 1
		fi
	fi

	if ! pw usershow %%USER%% 2>/dev/null 1>&2; then
                if pw useradd %%USER%% -u %%UID%% -g %%GROUP%% -h - \
			-s /nonexistent -c "SmokePing Daemon"; \
		then
			echo 'Added user "%%USER%%".'
		else
			echo 'Adding user "%%USER%%" failed...'
			exit 1
		fi
	fi

	exit 0
	;;
esac
