# New ports collection makefile for:	sendip
# Date created:				Wed 29 Nov 2000
# Whom:					joseph@randomnetworks.com
#
# $FreeBSD: ports/net/sendip/Makefile,v 1.1 2000/12/19 11:01:57 will Exp $
#

PORTNAME=	sendip
PORTVERSION=	1.4
CATEGORIES=	net
MASTER_SITES=	http://www.earth.li/projectpurple/files/

MAINTAINER=	joseph@randomnetworks.com

WRKSRC=		${WRKDIR}/sendip

MAN1=		sendip.1

.include <bsd.port.mk>
