# New ports collection makefile for:	p5-LJ-TextMessage
# Date created:				25 Mar 2001
# Whom:					Michael Johnson <ahze@ahze.net>
#
# $FreeBSD: ports/sysutils/p5-LJ-TextMessage/Makefile,v 1.1 2001/03/31 02:08:19 will Exp $

PORTNAME=	LJ-TextMessage
PORTVERSION=	1.3
CATEGORIES=	sysutils perl5
MASTER_SITES=	http://livejournal.com/files/code/textmessage/ \
		ftp://ftp.livejournal.com/code/textmessage/
PKGNAMEPREFIX=	p5-

MAINTAINER=	ahze@ahze.net

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		LJ::TextMessage.3

.include <bsd.port.mk>
