# New ports collection makefile for:	iconv
# Date created:				10 September 2000
# Whom:			Konstantin Chuguev <Konstantin.Chuguev@dante.org.uk>
#
# $FreeBSD: ports/converters/iconv-rfc1345/Makefile,v 1.1 2000/09/12 10:12:18 sobomax Exp $
#

PORTNAME=	iconv-rfc1345
PORTVERSION=	1.1
CATEGORIES=	converters
MASTER_SITES=	http://www.dante.net/staff/konstantin/FreeBSD/iconv/

MAINTAINER=	Konstantin.Chuguev@dante.org.uk

LIB_DEPENDS=	iconv.1:${PORTSDIR}/converters/iconv

USE_PERL5=	yes

.include <bsd.port.mk>
