# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/editors/xemacs21-mule-sumo/Makefile,v 1.8 2000/07/10 01:18:46 steve Exp $
#

XEMACS_MAJOR_VER=	21
NAMEPREFIX=		mule-

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-sumo

.include	"${MASTERDIR}/Makefile"
