# New ports collection makefile for: xyagamo
# Date created:		5 Nov 1999
# Whom:			Morita Shinya <shinmaru@dokidoki.ne.jp>
#
# $FreeBSD: ports/japanese/xyagamo/Makefile,v 1.3 2000/08/03 09:25:17 asami Exp $
#

PORTNAME=	xyagamo
PORTVERSION=	0.1b
CATEGORIES=	japanese games
MASTER_SITES=	http://www.dokidoki.ne.jp/home2/shinmaru/mahjong/

MAINTAINER=	ports@freebsd.org

USE_X_PREFIX=	YES
USE_XPM=	yes

MAN6=		xyagamo.6
MANLANG=	ja
MAN6COMPRESSED=	no

.include <bsd.port.mk>
