# New ports collection makefile for: Mew (for emacs20)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-emacs20/Makefile,v 1.6 2000/01/04 14:29:22 shige Exp $
#

EMACS_PORT_NAME=	emacs20

.include "${.CURDIR}/../mew/Makefile"
