# New ports collection makefile for: Mew (for emacs20)
# Version required:	1.94.1
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-emacs20/Makefile,v 1.5 1999/09/09 08:06:21 taoka Exp $
#

EMACS_PORT_NAME=	emacs20

.include "${.CURDIR}/../mew/Makefile"
