# New ports collection makefile for:   tund
# Date created:        20 July 1999
# Whom:                Sergey Kosyakov <ks@itp.ac.ru>
#
# $FreeBSD: ports/net/tund/Makefile,v 1.4 2000/02/06 22:14:03 kris Exp $
#

PORTNAME=	tund
PORTVERSION=	0.20
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.chg.ru/pub/networking/freebsd/

MAINTAINER=	ks@itp.ac.ru

USE_OPENSSL=   RSA

MAN8=		tund.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
