# New ports collection makefile for:   tund
# Date created:        20 July 1999
# Whom:                Sergey Kosyakov <ks@itp.ac.ru>
#
# $FreeBSD: ports/net/tund/Makefile,v 1.5 2000/04/09 18:13:53 cpiazza Exp $
#

PORTNAME=	tund
PORTVERSION=	0.20
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.chg.ru/pub/networking/freebsd/

MAINTAINER=	ks@itp.ac.ru

USE_OPENSSL=	YES

MAN8=		tund.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
