# New ports collection makefile for:	xqf
# Date created:				08 February 1999
# Whom:					steve farrell
#
# $FreeBSD: ports/games/xqf/Makefile,v 1.9 2000/07/07 19:59:24 steve Exp $
#

PORTNAME=	xqf
PORTVERSION=	0.9.1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.linuxgames.com/xqf/

MAINTAINER=	steve@farrell.org

RUN_DEPENDS=	qstat:${PORTSDIR}/games/qstat

USE_GMAKE=	yes
USE_GTK=	yes

.include <bsd.port.mk>
