# New ports collection makefile for: id3ren
# Date created:         28 February 1999
# Whom:                 Joao Carlos Mendes Luis <jonny@jonny.eng.br>
#
# $FreeBSD: ports/audio/id3ren/Makefile,v 1.4 1999/12/27 01:02:25 steve Exp $
#

PORTNAME=	id3ren
PORTVERSION=	0.97a
CATEGORIES=	audio
MASTER_SITES=	http://tscnet.com/pages/badcrc/apps/id3ren/
DISTNAME=	id3ren97a

MAINTAINER=	jonny@jonny.eng.br

USE_ZIP=	yes
WRKSRC=		${WRKDIR}/id3ren/src

.include <bsd.port.mk>
