# New ports collection makefile for:	jvim3 for Canna without ONEW library
# Version required:	3.0-1.7j
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-direct_canna/Makefile,v 1.7 1999/08/25 05:24:43 obrien Exp $
#

DIRECT_CANNA=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
