# New ports collection makefile for:	jvim3 for Canna without ONEW library
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-direct_canna/Makefile,v 1.10 2000/04/11 14:14:14 knu Exp $
#

DIRECT_CANNA=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
