# New ports collection makefile for:	jvim3 for Canna without ONEW library
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-direct_canna/Makefile,v 1.9 2000/02/07 16:40:32 taoka Exp $
#

DIRECT_CANNA=	yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
