# New ports collection makefile for:	ish
# Date created:		13 August 1997
# Whom:			hosokawa
#
# $FreeBSD: ports/converters/ish/Makefile,v 1.4 2000/04/08 23:24:31 mharo Exp $

PORTNAME=	ish
PORTVERSION=	1.11
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	hosokawa@jp.FreeBSD.org

MAKEFILE=	makefile
ALL_TARGET=	ish

.include <bsd.port.mk>
