# New ports collection makefile for:	ish
# Date created:		13 August 1997
# Whom:			hosokawa
#
# $FreeBSD: ports/converters/ish/Makefile,v 1.3 1999/08/25 05:16:20 obrien Exp $

PORTNAME=	ish
PORTVERSION=	1.11
CATEGORIES=	converters
MASTER_SITES=	ftp://ports.jp.freebsd.org/pub/FreeBSD-jp/ports-jp/LOCAL_PORTS/

MAINTAINER=	hosokawa@jp.FreeBSD.org

MAKEFILE=	makefile
ALL_TARGET=	ish

.include <bsd.port.mk>
