# New ports collection makefile for:	cdindex
# Date created:		15 June 1999
# Whom:			Marc E E van Woerkom <van.woerkom@netcologne.de>
#
# $FreeBSD: ports/audio/cdindex/Makefile,v 1.2 1999/08/25 04:35:22 obrien Exp $
#

PORTNAME=	cdindex
PORTVERSION=	1.1.0
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.cdindex.org/pub/cdindex/

MAINTAINER=	van.woerkom@netcologne.de

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
