# New ports collection makefile for:	cdindex
# Date created:		15 June 1999
# Whom:			Marc E E van Woerkom <van.woerkom@netcologne.de>
#
# $FreeBSD: ports/audio/cdindex/Makefile,v 1.3 2000/04/08 21:23:22 mharo Exp $
#

PORTNAME=	cdindex
PORTVERSION=	1.2.0
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.cdindex.org/pub/cdindex/ \
		ftp://ftp.musicbrainz.org/pub/cdindex/

MAINTAINER=	ports@freebsd.org

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
