# New ports collection makefile for:   xprompt
# Date created:        23 March 1997
# Whom:                Matthew Hunt <mph@pobox.com>
#
# $FreeBSD: ports/x11/xprompt/Makefile,v 1.6 2000/02/08 09:29:24 peter Exp $
#

PORTNAME=	xprompt
PORTVERSION= 	1.4
CATEGORIES=	x11
MASTER_SITES=   http://people.FreeBSD.org/~mph/distfiles/

MAINTAINER=	mph@freebsd.org

USE_IMAKE=	yes

MAN1=		xprompt.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
