# New ports collection makefile for:   xprompt
# Date created:        23 March 1997
# Whom:                Matthew Hunt <mph@pobox.com>
#
# $FreeBSD: ports/x11/xprompt/Makefile,v 1.7 2000/04/13 19:10:54 cpiazza Exp $
#

PORTNAME=	xprompt
PORTVERSION= 	1.4
CATEGORIES=	x11
MASTER_SITES=   ${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	mph

MAINTAINER=	mph@freebsd.org

USE_IMAKE=	yes

MAN1=		xprompt.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
