# New ports collection makefile for:   xprompt
# Version required:    1.4
# Date created:        23 March 1997
# Whom:                Matthew Hunt <mph@pobox.com>
#
# $FreeBSD: ports/x11/xprompt/Makefile,v 1.5 1999/08/31 02:51:12 peter Exp $
#

DISTNAME=	xprompt-1.4
CATEGORIES=	x11
MASTER_SITES=   http://people.FreeBSD.org/~mph/distfiles/

MAINTAINER=	mph@freebsd.org

USE_IMAKE=	yes

MAN1=		xprompt.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
