# New ports collection makefile for:	libicq
# Date Created:				31 Oct 1998
# Whom:					Seiichirou Hiraoka
#
# $FreeBSD: ports/net/libicq/Makefile,v 1.14 2000/08/08 05:08:12 flathill Exp $
#

PORTNAME=	libicq
PORTVERSION=	0.33
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_LOCAL} \
		ftp://ftp.korsoft.com/pub/gicq/
MASTER_SITE_SUBDIR=	flathill

MAINTAINER=	flathill@FreeBSD.org

USE_GLIB=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
