# New ports collection makefile for: info2html
# Date created:         9 October 1997
# Whom:                 wosch
#
# $FreeBSD: ports/textproc/info2html/Makefile,v 1.4 1999/09/19 10:30:46 wosch Exp $
#

PORTNAME=	info2html
PORTVERSION= 	1.1
CATEGORIES=	textproc
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		info2html.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
