# New ports collection makefile for: info2html
# Version required:     1.1
# Date created:         9 October 1997
# Whom:                 wosch
#
# $FreeBSD: ports/textproc/info2html/Makefile,v 1.3 1999/08/31 02:09:22 peter Exp $
#

DISTNAME=       info2html-1.1
CATEGORIES=	textproc
MASTER_SITES=   http://www.de.freebsd.org/~wosch/src/

MAINTAINER=     wosch@FreeBSD.org

MAN1=		info2html.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
