# New ports collection makefile for:	xbl
# Date created:		May 25 1997
# Whom:			pgs (original)
#
# $FreeBSD: ports/games/xbl/Makefile,v 1.8 2000/04/14 12:27:00 asami Exp $
#

PORTNAME=	xbl
PORTVERSION=	1.0j
CATEGORIES=	games
MASTER_SITES=	ftp://ftp710.univ-lyon1.fr/pub/xbl/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
CFLAGS+=	-I${PREFIX}/include
MANN=		xbl.n

.include <bsd.port.mk>
