# New ports collection makefile for:	xbl
# Date created:		May 25 1997
# Whom:			pgs (original)
#
# $FreeBSD: ports/games/xbl/Makefile,v 1.7 1999/08/25 06:04:45 obrien Exp $
#

PORTNAME=	xbl
PORTVERSION=	1.0j
CATEGORIES=	games
MASTER_SITES=	ftp://ftp710.univ-lyon1.fr/pub/xbl/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
CFLAGS+=	-I${PREFIX}/include
MANn=		xbl.n

.include <bsd.port.mk>
