# New ports collection makefile for:	zh-dia
# Date created:			6 March 2001
# Whom:				Jing-Tang Keith Jang <keith@FreeBSD.org>
#
# $FreeBSD: ports/chinese/dia/Makefile,v 1.1 2001/03/06 08:35:42 keith Exp $
#

CATEGORIES=	chinese

PATCH_SITES=	ftp://freebsd.sinica.edu.tw/pub/keith/
PATCHFILES=	zh-dia-0.86.diff.gz

MAINTAINER=	keith@FreeBSD.org

MASTERDIR=	${.CURDIR}/../../graphics/dia

MD5_FILE=	${.CURDIR}/distinfo

# For png output
USE_GNOMELIBS=	yes

.include "${MASTERDIR}/Makefile"
