# ex:ts=8
# New ports collection makefile for:	Crank
# Date created:			Apr 18, 2001
# Whom:				Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/security/crank/Makefile,v 1.2 2001/04/23 06:26:56 ijliao Exp $
#

PORTNAME=	crank
PORTVERSION=	0.1.4
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

USE_GTK=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
