# New ports collection makefile for:	rvm
# Date created:				Thu Apr  6 21:30:52 EDT 2000
# Whom:					jaharkes
#
# $FreeBSD: ports/devel/rvm/Makefile,v 1.5 2000/06/20 10:02:05 sobomax Exp $
#

PORTNAME=	rvm
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.coda.cs.cmu.edu/pub/rvm/src/

MAINTAINER=	coda@cs.cmu.edu

LIB_DEPENDS=	lwp.2:${PORTSDIR}/devel/lwp

USE_GMAKE=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
