# New ports collection makefile for:	rvm
# Date created:				Thu Apr  6 21:30:52 EDT 2000
# Whom:					jaharkes
#
# $FreeBSD: ports/devel/rvm/Makefile,v 1.1 2000/05/29 04:17:23 steve Exp $
#

PORTNAME=	rvm
PORTVERSION=	1.1
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.coda.cs.cmu.edu/pub/rvm/src/

MAINTAINER=	lioux@linf.unb.br

LIB_DEPENDS=	lwp.1:${PORTSDIR}/devel/lwp

USE_GMAKE=	yes
USE_LIBTOOL=	yes
INSTALL_SHLIBS=	yes

.include <bsd.port.mk>
