# New ports collection makefile for:    xrisk
# Date created:		4 Jan 1995
# Whom:			swallace
#
# $FreeBSD: ports/games/xrisk/Makefile,v 1.17 2001/01/27 05:40:10 will Exp $
#

PORTNAME=	xrisk
PORTVERSION=	2.15
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.pvv.org/pvv/games/

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN6=		xrisk.6

RESTRICTED=	"Possible trademark infringement"

.include <bsd.port.mk>
