# New ports collection makefile for:    xrisk
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xrisk/Makefile,v 1.14 2000/04/14 12:28:09 asami Exp $
#

PORTNAME=	xrisk
PORTVERSION=	2.13
CATEGORIES=	games
MASTER_SITES=	http://people.freebsd.org/~steve/distfiles/ \
		ftp://geocub.greco-prog.fr/pub/Games/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	swallace@FreeBSD.org

MAN6=		xrisk.6
MANCOMPRESSED=	yes

USE_X_PREFIX=	yes
RESTRICTED=	"Possible trademark infringement"

.include <bsd.port.mk>
