# New ports collection makefile for:    xrisk
# Date created:		4 Jan 1995
# Whom:			swallace
#
# $FreeBSD: ports/games/xrisk/Makefile,v 1.18 2001/02/28 14:28:38 kevlo Exp $
#

PORTNAME=	xrisk
PORTVERSION=	2.15
CATEGORIES=	games
MASTER_SITES=	http://my.pages.de/pub/comp/games/xrisk/ \
		http://www.mikro.biologie.tu-muenchen.de/pub/rec/games/xrisk/

MAINTAINER=	adam@alameda.edu

USE_IMAKE=	yes
MAN6=		xrisk.6

RESTRICTED=	"Possible trademark infringement"

.include <bsd.port.mk>
