# New ports collection makefile for:   xzoom
# Date created:        30 June 1997
# Whom:                Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11/xzoom/Makefile,v 1.5 2000/01/08 11:23:56 nakai Exp $
#

PORTNAME=	xzoom
PORTVERSION= 	0.3	
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	libs/X
EXTRACT_SUFX=	.tgz

MAINTAINER=	nakai@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xzoom.1

.include <bsd.port.mk>
