#!/bin/sh
# $FreeBSD: ports/textproc/xerces-c2/scripts/check-config-options,v 1.1 2004/10/25 08:18:57 vs Exp $

rc=0

if test -n "${WITH_NATIVE}"; then
	rc=$(expr $rc + 1)
fi
if test -n "${WITH_ICU}"; then
	rc=$(expr $rc + 1)
fi
if test -n "${WITH_ICONVFBSD}"; then
	rc=$(expr $rc + 1)
fi

if test ${rc} -gt 1; then
	echo "ERROR: please re-run make config and" >&2
	echo "only select one of the three transcoders." >&2
	exit 254
fi

exit 0

# end
