# New ports collection makefile for:	xcoloredit
# Date created:		6 Jun 1997
# Whom:			Satoshi TAOKA
#
# $FreeBSD: ports/x11/xcoloredit/Makefile,v 1.6 2001/02/05 16:18:27 olgeni Exp $
#

PORTNAME=	xcoloredit
PORTVERSION=	1.2
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
DISTNAME=	${PORTNAME}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	taoka@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xcoloredit.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
