# New ports collection makefile for:	sniff
# Version required:	1.0
# Date created:		7 December 1998
# Whom:			Rick & Samu
#
# $FreeBSD: ports/security/sniff/Makefile,v 1.2 1999/08/31 01:51:45 peter Exp $
#

DISTNAME=	sniff-1.0
CATEGORIES=	security
MASTER_SITES=   http://people.FreeBSD.org/~fenner/distfiles/

MAINTAINER=	veraldi@cs.unibo.it

MAN1=		sniff.1
HAS_CONFIGURE=          yes
CONFIGURE_SCRIPT=       configure

.include <bsd.port.mk>
