# New ports collection makefile for:	clean-theme-gtk
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/clean-theme-gtk/Makefile,v 1.6 2000/12/04 11:41:43 sobomax Exp $
#

PORTNAME=	clean-theme-gtk
PORTVERSION=	200011261817
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	clean-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/gtk-clean-theme

USE_X_PREFIX=	yes
USE_LIBTOOL=	yes
USE_GTK=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
