# New ports collection makefile for: YaTeX
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-xemacs-mule/Makefile,v 1.17 2000/04/09 17:41:40 cpiazza Exp $
#

PORTNAME=	yatex-xemacs-mule
PORTVERSION=	1.67

XEMACS-MULE=	yes

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg/COMMENT

.include	"${MASTERDIR}/Makefile"
