# New ports collection makefile for: YaTeX
# Version required:	1.67
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-xemacs-mule/Makefile,v 1.15 1999/10/25 23:39:38 asami Exp $
#

PKGNAME=	yatex-xemacs-mule-1.67

XEMACS-MULE=	yes

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg/COMMENT

.include	"${MASTERDIR}/Makefile"
