# New ports collection makefile for:   cgoban
# Version required:    1.9.8
# Date created:        28 October 1996
# Whom:                simonm@dcs.gla.ac.uk
#
# $FreeBSD: ports/games/cgoban/Makefile,v 1.10 1999/08/25 06:03:05 obrien Exp $
#

DISTNAME=	cgoban-1.9.8
CATEGORIES=	games
MASTER_SITES=	http://www.inetarena.com/~wms/comp/cgoban/

MAINTAINER=	simonm@dcs.gla.ac.uk

GNU_CONFIGURE=	yes
USE_X_PREFIX=	yes
ALL_TARGET=
MAN6=		cgoban.6

.include <bsd.port.mk>
