# New ports collection makefile for:	libole2
# Date created:				20th June 2000
# Whom:					Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD: ports/devel/libole2/Makefile,v 1.3 2000/06/29 21:04:14 ade Exp $
#

PORTNAME=	libole2
PORTVERSION=	0.1.6
CATEGORIES=	devel gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	unstable/sources/libole2

MAINTAINER=	ade@FreeBSD.org

USE_GMAKE=	yes
USE_GLIB=	yes
USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
