# New ports collection makefile for:	xbaby
# Date created:			21 January 2000
# Whom:				HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xbaby/Makefile,v 1.4 2001/03/27 03:53:42 kuriyama Exp $
#

PORTNAME=	xbaby
PORTVERSION=	pl2
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.inria.fr/X/contrib-R5/games/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	hym@cocoa.freemail.ne.jp

USE_IMAKE=	yes

MAN1=		xbaby.1

.include <bsd.port.mk>
