# New ports collection makefile for:	xbaby
# Date created:			21 January 2000
# Whom:				HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xbaby/Makefile,v 1.3 2000/04/14 12:26:57 asami Exp $
#

PORTNAME=	xbaby
PORTVERSION=	pl2
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.inria.fr/X/contrib-R5/games/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	cbc06942@pop06.odn.ne.jp

USE_IMAKE=	yes

MAN1=		xbaby.1

.include <bsd.port.mk>
