# New ports collection makefile for:	xshodo
# Version required:	2.0
# Date created:		11 October 1996
# Whom:			Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/japanese/xshodo/Makefile,v 1.9 2000/01/07 02:27:32 nakai Exp $
#

DISTNAME=	xshodo2.0
PKGNAME=	ja-xshodo-2.0
CATEGORIES=	japanese
MASTER_SITES=	ftp://cclub.tutcc.tut.ac.jp/pub/xwin/

MAINTAINER=	nakai@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xshodo.1

.include <bsd.port.mk>
