# New ports collection makefile for:	srm
# Date created:				25 Oct 2000
# Whom:					Keith J. Jones <keith.jones@ieee.org>
#
# $FreeBSD: ports/security/srm/Makefile,v 1.1 2000/10/25 18:55:25 trevor Exp $
#

PORTNAME=	srm
PORTVERSION=	1.2.2
CATEGORIES=	security sysutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	srm

MAINTAINER=	keith.jones@ieee.org

USE_LIBTOOL=	YES

MAN1=		srm.1

.include <bsd.port.mk>
