# New ports collection makefile for:   xdvik + jp-patch
# Date created:        15 Jun 1998
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/xdvik-vflib-pk400/Makefile,v 1.12 2000/01/25 14:23:32 taoka Exp $
#

RUN_DEPENDS=	${LOCALBASE}/share/texmf/fonts/pk/${MF_MODE}/pk${BDPI}:${PORTSDIR}/japanese/ptex-pkfonts${BDPI}

FONTTYPE=	pkfont
BDPI=		400
SHRINK=		7
MASTERDIR=	${.CURDIR}/../xdvik-vflib

.include	"${MASTERDIR}/Makefile"
