# New ports collection makefile for:    xcd
# Date created:         22 November 1994
# Whom:                 jmz
#
# $FreeBSD: ports/audio/xcd/Makefile,v 1.25 2000/02/08 09:25:47 peter Exp $
#

PORTNAME=	xcd
PORTVERSION=	1.7
CATEGORIES=	audio tk82
MASTER_SITES=	http://people.FreeBSD.org/~jmz/

MAINTAINER=	jmz@FreeBSD.org

RUN_DEPENDS=    wish8.2:${PORTSDIR}/x11-toolkits/tk82

WRKSRC=		${WRKDIR}/xcd
MAN1=		xcd.1

.include <bsd.port.mk>
