# New ports collection makefile for:    xcd
# Version required:     1.7
# Date created:         22 November 1994
# Whom:                 jmz
#
# $FreeBSD: ports/audio/xcd/Makefile,v 1.24 1999/11/28 18:17:22 steve Exp $
#

DISTNAME=	xcd-1.7
CATEGORIES=	audio tk82
MASTER_SITES=	http://people.FreeBSD.org/~jmz/

MAINTAINER=	jmz@FreeBSD.org

RUN_DEPENDS=    wish8.2:${PORTSDIR}/x11-toolkits/tk82

WRKSRC=		${WRKDIR}/xcd
MAN1=		xcd.1

.include <bsd.port.mk>
