# New ports collection makefile for:	lifelines
# Date created:		10 August 2000
# Whom:			Matt Emmerton <matt@gsicomp.on.ca>
#
# $FreeBSD: ports/misc/lifelines/Makefile,v 1.1 2000/09/04 14:38:51 sobomax Exp $
#

PORTNAME=	lifelines
PORTVERSION=	3.0.6
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	matt@gsicomp.on.ca

GNU_CONFIGURE=	yes
USE_BISON=	yes

.include <bsd.port.mk>
