# ex:ts=8
# ports collection makefile for:	cscope
# Date created:		1998-11-21
# Whom:			Castor Fu
#
# $FreeBSD: ports/devel/cscope/Makefile,v 1.13 2001/01/12 20:16:18 sobomax Exp $
#

PORTNAME=	cscope
PORTVERSION=	15.1
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

CONFIGURE_TARGET=	${ARCH}-portbld-freebsd${OSREL}
GNU_CONFIGURE=	yes
MAN1=		cscope.1

.include <bsd.port.mk>
