# ex:ts=8
# ports collection makefile for:	cscope
# Date created:		1998-11-21
# Whom:			Castor Fu
#
# $FreeBSD: ports/devel/cscope/Makefile,v 1.9 2000/06/18 18:47:46 obrien Exp $
#

PORTNAME=	cscope
PORTVERSION=	15.1
CATEGORIES=	devel
#MASTER_SITES=	ftp://download.sourceforge.net/pub/sourceforge/cscope/  \
MASTER_SITES=	http://download.sourceforge.net/cscope/

MAINTAINER=	obrien@FreeBSD.org

CONFIGURE_TARGET=	${ARCH}-portbld-freebsd${OSREL}
GNU_CONFIGURE=	yes
MAN1=		cscope.1

.include <bsd.port.mk>
