# New ports collection makefile for:	lookup for XEmacs
# Date created:		98/11/19
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/lookup-xemacs/Makefile,v 1.12 2000/07/10 17:31:25 taoka Exp $
#

MASTERDIR=	${.CURDIR}/../lookup-mule
EMACS_PORT_NAME=xemacs21-mule

.if defined(PARALLEL_PACKAGE_BUILD)
FORBIDDEN=	hang
.endif

.include	"${MASTERDIR}/Makefile"
