# New ports collection makefile for:	lookup for XEmacs
# Version required:	1.0
# Date created:		98/11/19
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/lookup-xemacs/Makefile,v 1.4 1999/09/27 13:42:05 taoka Exp $
#

PKGNAME=	ja-lookup-xemacs-1.0

MASTERDIR=	${.CURDIR}/../lookup-mule
EMACS=		xemacs

.include	"${MASTERDIR}/Makefile"
