# New ports collection makefile for:   xdvik + jp-patch
# Date created:        15 Jun 1998
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/xdvik-vflib-pkall/Makefile,v 1.12 2000/01/25 14:23:46 taoka Exp $
#

FONTTYPE=	pkall
BDPI=		300
SHRINK=		6
MASTERDIR=	${.CURDIR}/../xdvik-vflib

.include	"${MASTERDIR}/Makefile"
