# New ports collection makefile for:	mule 2.3@19.34 with Canna, sj3 and Wnn4
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+sj3+wnn4/Makefile,v 1.6 1999/08/25 05:25:36 obrien Exp $
#

PKGNAMESUFFIX=	-canna+sj3+wnn4
CATEGORIES=	japanese editors

CANNA=		yes
SJ3=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
