# New ports collection makefile for:	mule with Canna, sj3 and FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+freewnn+sj3/Makefile,v 1.9 2000/09/08 04:34:41 taoka Exp $
#

PKGNAMESUFFIX=	-canna+freewnn+sj3
CATEGORIES=	japanese

CANNA=		yes
SJ3=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
