# New ports collection makefile for:	mule with Canna, sj3 and FreeWnn
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+freewnn+sj3/Makefile,v 1.8 2000/04/14 16:47:41 knu Exp $
#

PKGNAMESUFFIX=	-canna+freewnn+sj3
CATEGORIES=	japanese

CANNA=		yes
SJ3=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
