# New ports collection makefile for:    swisswatch
# Date created:         16 December 1995
# Whom:                 Yoshiro MIHIRA <sanpei@yy.cs.keio.ac.jp>
#
# $FreeBSD: ports/x11-clocks/swisswatch/Makefile,v 1.12 2000/08/03 14:28:33 sanpei Exp $
#

PORTNAME=	swisswatch
PORTVERSION=	0.06
CATEGORIES=	x11-clocks
MASTER_SITES=	${MASTER_SITE_PORTS_JP}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	sanpei@FreeBSD.org

USE_IMAKE=	yes
MAN1=		swisswatch.1

.include <bsd.port.mk>
