# New ports collection makefile for:    swisswatch
# Version required:     0.0.6
# Date created:         16 December 1995
# Whom:                 Yoshiro MIHIRA <sanpei@yy.cs.keio.ac.jp>
#
# $FreeBSD: ports/x11-clocks/swisswatch/Makefile,v 1.8 1999/08/31 02:58:01 peter Exp $
#

DISTNAME=	swisswatch-0.06
CATEGORIES=	x11-clocks
MASTER_SITES=	${MASTER_SITE_PORTS_JP}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	sanpei@jp.FreeBSD.org

USE_IMAKE=	yes
MAN1=		swisswatch.1

.include <bsd.port.mk>
