# New ports collection makefile for:	p5-File-BasicFlock
# Date created:				1996/10/24
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/devel/p5-File-BasicFlock/Makefile,v 1.15 2000/10/23 21:02:47 will Exp $
#

PORTNAME=	File-BasicFlock
PORTVERSION=	98.1202
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	YES

MAN3=		File::BasicFlock.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
