# New ports collection makefile for:   qvwm
# Version required:    1.1
# Date created:        2 January 1997
# Whom:                Yukihiro Nakai<Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11-wm/qvwm/Makefile,v 1.22 1999/08/31 03:00:15 peter Exp $
#

DISTNAME=	qvwm-1.1
CATEGORIES=	x11-wm
MASTER_SITES=	http://www-masuda.is.s.u-tokyo.ac.jp/~kourai/qvwm/program/

MAINTAINER=	nacai@iname.com

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		qvwm.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
