# New ports collection makefile for:	freeciv-gtk
# Date created:         29 Feb 2000
# Whom:                 sheldonh
#
# $FreeBSD: ports/games/freeciv-gtk/Makefile,v 1.3 2000/04/26 06:56:18 asami Exp $
#

PKGNAMESUFFIX=	-gtk
MASTERDIR=	${.CURDIR}/../freeciv

WITH_GTK=	yes

.include "${MASTERDIR}/Makefile"
