# New ports collection makefile for:	freeciv-gtk
# Date created:         29 Feb 2000
# Whom:                 sheldonh
#
# $FreeBSD: ports/games/freeciv-gtk/Makefile,v 1.1 2000/02/29 15:25:59 sheldonh Exp $
#

MASTERDIR=	${.CURDIR}/../freeciv

USE_GTK=	yes

.include "${MASTERDIR}/Makefile"
