# New ports collection makefile for:	freeciv-gtk
# Date created:         29 Feb 2000
# Whom:                 sheldonh
#
# $FreeBSD: ports/games/freeciv-gtk/Makefile,v 1.2 2000/04/14 06:42:54 mharo Exp $
#

MASTERDIR=	${.CURDIR}/../freeciv

WITH_GTK=	yes

.include "${MASTERDIR}/Makefile"
