# New ports collection makefile for: wmeyes
# Date created:        18 March 1999
# Whom:                Zenin <zenin@archive.rhps.org>
#
# $FreeBSD: ports/games/wmeyes/Makefile,v 1.4 2000/04/14 12:26:46 asami Exp $
#

PORTNAME=	wmeyes
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://thrush.omix.com/pub/misc/

MAINTAINER=	zenin@archive.rhps.org

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		wmeyes.1

.include <bsd.port.mk>
