# New ports collection makefile for: wmeyes
# Date created:        18 March 1999
# Whom:                Zenin <zenin@archive.rhps.org>
#
# $FreeBSD: ports/games/wmeyes/Makefile,v 1.3 1999/08/25 06:04:36 obrien Exp $
#

PORTNAME=	wmeyes
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://thrush.omix.com/pub/misc/

MAINTAINER=	zenin@archive.rhps.org

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

.include <bsd.port.mk>
