# New ports collection makefile for: wmeyes
# Date created:        18 March 1999
# Whom:                Zenin <zenin@archive.rhps.org>
#
# $FreeBSD: ports/games/wmeyes/Makefile,v 1.5 2000/06/07 09:05:38 asami Exp $
#

PORTNAME=	wmeyes
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://thrush.omix.com/pub/misc/

MAINTAINER=	zenin@archive.rhps.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		wmeyes.1

.include <bsd.port.mk>
