# New ports collection makefile for: pips for EPSON PM-760C
# Date created:        2000.08.04
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips760/Makefile,v 1.2 2000/10/08 10:21:15 asami Exp $
#

MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		760

do-install:     # empty

.include "${MASTERDIR}/Makefile"
