# New ports collection makefile for:	tkgnats
# Date created:		Sat 18 Apr 1998 10:12:20 CEST
# Whom:			andreas
#
# $FreeBSD: ports/databases/tkgnats/Makefile,v 1.15 2000/04/08 22:49:02 mharo Exp $
#

PORTNAME=	tkgnats
PORTVERSION=	3.0.16
CATEGORIES=	databases tk82
MASTER_SITES=	http://www.cuug.ab.ca/~macdonal/tkgnats/

MAINTAINER=	jeremy@external.org

BUILD_DEPENDS=	nedit-pr:${PORTSDIR}/databases/gnats
LIB_DEPENDS=	tk82.1:${PORTSDIR}/x11-toolkits/tk82

.include <bsd.port.mk>
