# New ports collection makefile for:	tkgnats
# Version required:	3.0.14
# Date created:		Sat 18 Apr 1998 10:12:20 CEST
# Whom:			andreas
#
# $FreeBSD: ports/databases/tkgnats/Makefile,v 1.12 1999/08/31 06:41:24 mharo Exp $
#

DISTNAME=	tkgnats-3.0.14
CATEGORIES=	databases tk82
MASTER_SITES=	http://www.cuug.ab.ca/~macdonal/tkgnats/

MAINTAINER=	andreas@FreeBSD.org

BUILD_DEPENDS=	nedit-pr:${PORTSDIR}/databases/gnats
LIB_DEPENDS=	tk82.1:${PORTSDIR}/x11-toolkits/tk82

.include <bsd.port.mk>
