# New ports collection makefile for:	netscape (navigator only)
# Date created:         24 Feb 1997
# Whom:                 ache
#
# $FreeBSD: ports/www/netscape4-navigator/Makefile,v 1.44 2000/01/25 03:21:58 asami Exp $
#

MASTER_SITES=	ftp://ftp.netscape.com/pub/communicator/${BROWSER_VER}/english/unix/unsupported/freebsd/navigator_standalone/
DISTFILES=	navigator-v408-export.x86-unknown-freebsd.tar.gz

MASTERDIR=	${.CURDIR}/../netscape4-communicator
NO_LATEST_LINK=	yes

BROWSER=	navigator
INFILE_HEAD=	'Navigator,4.08.0.98306'

.include "${MASTERDIR}/Makefile"
