# New ports collection makefile for: mtpfs
# Date created: 1 July 2007
# Whom: John Hixson <john@divinix.org>
#
# $FreeBSD: ports/sysutils/mtpfs/Makefile.bak,v 1.1 2007/09/08 05:10:39 edwin Exp $
#

PORTNAME=	mtpfs
PORTVERSION=	0.6
CATEGORIES=	sysutils
MASTER_SITES=	http://www.adebenham.com/mtpfs/

MAINTAINER=	john@pcbsd.org
COMMENT=	MTP device filesystem

RUN_DEPENDS=	${LOCALBASE}/modules/fuse.ko:${PORTSDIR}/sysutils/fusefs-kmod
LIB_DEPENDS=	mtp:${PORTSDIR}/audio/libmtp \
		fuse:${PORTSDIR}/sysutils/fusefs-libs \
		id3-3.8:${PORTSDIR}/audio/id3lib

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/mtpfs

.include <bsd.port.mk>
