# New ports collection makefile for: play
# Date created:		20 May 1998
# Whom:			Masanori Kiriake <seiken@nbs.co.jp>
#
# $FreeBSD: ports/audio/play/Makefile,v 1.7 2000/04/08 21:24:11 mharo Exp $
#

PORTNAME=	play
PORTVERSION=	1.0
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	seiken@ARGV.AC

MANLANG=	ja
MAN1=		play.1
MANCOMPRESSED = yes
.include <bsd.port.mk>
