# New ports collection makefile for: play
# Date created:		20 May 1998
# Whom:			Masanori Kiriake <seiken@nbs.co.jp>
#
# $FreeBSD: ports/audio/play/Makefile,v 1.6 1999/08/25 04:35:57 obrien Exp $
#

PORTNAME=	play
PORTVERSION=	1.0
CATEGORIES=	audio
MASTER_SITES=	ftp://ports.jp.FreeBSD.org/pub/FreeBSD-jp/ports-jp/LOCAL_PORTS/

MAINTAINER=	seiken@ARGV.AC

MANLANG=	ja
MAN1=		play.1
MANCOMPRESSED = yes
.include <bsd.port.mk>
