# New ports collection makefile for:	libraries of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/FreeWnn-lib/Makefile,v 1.9 2000/04/12 14:46:52 knu Exp $
#

PKGNAMESUFFIX=	-lib
CATEGORIES=	chinese
MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}/pkg
WNN=		cWnn

.include "${MASTERDIR}/Makefile"
