# New ports collection makefile for:	xeji
# Date created:		10 Aug 1999
# Whom:			HIYAMA Takeshi <th@cis.ibaraki.ac.jp>
#
# $FreeBSD: ports/games/xeji/Makefile,v 1.4 2000/10/13 20:31:38 ade Exp $
#

PORTNAME=	xeji
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://yindy1.aist-nara.ac.jp/~tetu-s/sofken/software/
DISTNAME=	${PORTNAME}${PORTVERSION}
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	cbc06942@pop06.odn.ne.jp

USE_IMAKE=	yes
USE_XPM=	yes
NO_INSTALL_MANPAGES=	yes

WRKSRC=		${WRKDIR}/xeji

.include <bsd.port.mk>
