# New ports collection makefile for:	xtattr
# Date created:		6 August 1997
# Whom:			jeff@cetlink.net
#
# $FreeBSD: ports/x11/xtattr/Makefile,v 1.4 1999/08/31 06:53:29 mharo Exp $
#

PORTNAME=	xtattr
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xtattr.1

.include <bsd.port.mk>
