# New ports collection makefile for:	xtattr
# Version required:	1.0
# Date created:		6 August 1997
# Whom:			jeff@cetlink.net
#
# $FreeBSD: ports/x11/xtattr/Makefile,v 1.3 1999/08/31 02:51:18 peter Exp $
#

DISTNAME=	xtattr-1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xtattr.1

.include <bsd.port.mk>
