# New ports collection makefile for:	xtattr
# Date created:		6 August 1997
# Whom:			jeff@cetlink.net
#
# $FreeBSD: ports/x11/xtattr/Makefile,v 1.5 2000/04/13 19:11:02 cpiazza Exp $
#

PORTNAME=	xtattr
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xtattr.1

.include <bsd.port.mk>
