# New ports collection makefile for:	comserv
# Date created:				12 November 2000
# Whom:					Brian Dean <bsd@FreeBSD.org>
#
# $FreeBSD: ports/comms/comserv/Makefile,v 1.2 2000/12/10 19:02:04 bsd Exp $
#

PORTNAME=	comserv
PORTVERSION=	1.0.1
CATEGORIES=	comms net
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	bsd

MAINTAINER=	bsd@FreeBSD.org

MAN8=		comservd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
