# New ports collection makefile for:	comserv
# Date created:				12 November 2000
# Whom:					Brian Dean <bsd@FreeBSD.org>
#
# $FreeBSD: ports/comms/comserv/Makefile,v 1.5 2001/02/25 16:46:50 bsd Exp $
#

PORTNAME=	comserv
PORTVERSION=	1.3.1
CATEGORIES=	comms net
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	bsd

MAINTAINER=	bsd@FreeBSD.org

MAN8=		comservd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
