# New ports collection makefile for:	p5-Tie-DB_FileLock
# Date created:				August 17 2000
# Whom:	      				Josh Tiefenbach <josh@zipperup.org>
#
# $FreeBSD: ports/devel/p5-Tie-DB_FileLock/Makefile,v 1.1 2000/09/16 04:50:58 will Exp $
#

PORTNAME=	Tie-DB_FileLock
PORTVERSION=	0.10
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Tie
PKGNAMEPREFIX=	p5-

MAINTAINER=	josh@zipperup.org

PERL_CONFIGURE=	yes

MAN3=			Tie::DB_FileLock.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
