# New ports collection makefile for:	exim-postgresql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-postgresql/Makefile,v 1.1 2001/06/11 12:00:06 sheldonh Exp $
#

PKGNAMESUFFIX=	-postgresql
CATEGORIES=	mail
PKGDIR=		../exim
FILESDIR=	${PKGDIR}/files
PATCHDIR=	${PKGDIR}/files

WITH_PGSQL=	yes

.include "../exim/Makefile"
