# New ports collection makefile for:	exim-postgresql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-postgresql/Makefile,v 1.2 2001/06/13 21:19:14 sheldonh Exp $
#

PKGNAMESUFFIX=	-postgresql
MASTERDIR=	${.CURDIR}/../exim

WITH_PGSQL=	yes

.include "${MASTERDIR}/Makefile"
