# New ports collection makefile for:	sup
# Version required:	<own lineage>
# Date created:		21 August 1994
# Whom:			jkh
#
# $FreeBSD: ports/net/sup/Makefile,v 1.12 1999/08/30 14:24:13 peter Exp $
#

DISTNAME=	sup
PKGNAME=	sup-2.0
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	ports@FreeBSD.org

MAN1=		sup.1
MAN8=		supservers.8

.include <bsd.port.mk>
