# New ports collection makefile for:	sup
# Date created:		21 August 1994
# Whom:			jkh
#
# $FreeBSD: ports/net/sup/Makefile,v 1.14 2000/04/09 18:13:37 cpiazza Exp $
#

PORTNAME=	sup
PORTVERSION=	2.0
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	asami/LOCAL_PORTS
DISTNAME=	sup

MAINTAINER=	ports@FreeBSD.org

MAN1=		sup.1
MAN8=		supservers.8

.include <bsd.port.mk>
