# New ports collection makefile for:	sup
# Date created:		21 August 1994
# Whom:			jkh
#
# $FreeBSD: ports/net/sup/Makefile,v 1.13 2000/02/05 10:55:47 dirk Exp $
#

PORTNAME=	sup
PORTVERSION=	2.0
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_LOCAL}
DISTNAME=	sup

MAINTAINER=	ports@FreeBSD.org

MAN1=		sup.1
MAN8=		supservers.8

.include <bsd.port.mk>
