# New ports collection makefile for:    xinvaders
# Date created:         3 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xinvaders/Makefile,v 1.13 1999/08/25 06:05:20 obrien Exp $
#

PORTNAME=	xinvaders
PORTVERSION=	1.1
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	games/arcade/invaders
DISTNAME=       ${PORTNAME}

MAINTAINER=	swallace@FreeBSD.org

NO_CDROM=	"don't sell for profit"
USE_IMAKE=	yes
MAN6=		xinvaders.6

.include <bsd.port.mk>
