# New ports collection makefile for:    6811sim
# Date created:         Thu Sep 14 11:10:01 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/emulators/sim6811/Makefile,v 1.6 2000/04/12 04:55:46 mharo Exp $
#

PORTNAME=	sim6811
PORTVERSION=	1.6
CATEGORIES=	emulators
MASTER_SITES=	ftp://crl.nmsu.edu/pub/non-lexical/6811/
DISTNAME=	sim
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
