# New ports collection makefile for:	libtool
# Version required:	1.3.3
# Date created:		6 May 1998
# Whom:			Motoyuki Kasahara <m-kasahr@sra.co.jp>
#
# $FreeBSD: ports/devel/libtool/Makefile,v 1.8 2000/01/29 21:22:08 steve Exp $
#

DISTNAME=	libtool-1.3.3
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	libtool

MAINTAINER=	reg@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--disable-ltdl-install
CONFIGURE_ENV=	PREFIX=${PREFIX}

.include <bsd.port.mk>
