# New ports collection makefile for:    xevil
# Date created:         6 May 1995
# Whom:                 jmz
#
# $FreeBSD: ports/games/xevil/Makefile,v 1.9 2000/03/20 22:37:09 mharo Exp $
#

PORTNAME=	xevil
PORTVERSION=	1.5
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games/${PORTNAME}${PORTVERSION}
DISTFILES=	${PORTNAME}${PORTVERSION}.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_XLIB=	yes
MAN6=		xevil.6
MANCOMPRESSED=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
