# New ports collection makefile for:    xevil
# Version required:     1.5
# Date created:         6 May 1995
# Whom:                 jmz
#
# $FreeBSD: ports/games/xevil/Makefile,v 1.8 1999/08/25 06:05:08 obrien Exp $
#

DISTNAME=	xevil1.5
PKGNAME=	xevil-1.5
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games/xevil1.5
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	jmz@FreeBSD.org

USE_XLIB=	yes
MAN6=		xevil.6
MANCOMPRESSED=	yes

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
