# New ports collection makefile for:	ipfm
# Date Created:				4 Mar 2000
# Whom:					Roman Shterenzon <roman@xpert.com>
#
# $FreeBSD: ports/net/ipfm/Makefile,v 1.1.1.1 2000/03/11 15:36:23 jedgar Exp $
#

PORTNAME=	ipfm
PORTVERSION=	0.10.4
CATEGORIES=     net
MASTER_SITES=	http://www.via.ecp.fr/~tibob/ipfm/archive/
EXTRACT_SUFX=	.tgz

MAINTAINER=	roman@xpert.com

WRKSRC=		${WRKDIR}/${PKGNAME}
PATCH_STRIP=	-p1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
