# New ports collection makefile for:	corkscrew
# Date created:			Apr 12, 2001
# Whom:				Mark Pulford <mark@kyne.com.au>
#
# $FreeBSD: ports/net/corkscrew/Makefile,v 1.1 2001/04/17 18:10:48 will Exp $
#

PORTNAME=	corkscrew
PORTVERSION=	1.4
CATEGORIES=	net
MASTER_SITES=	http://www.agroman.net/corkscrew/

MAINTAINER=	mark@kyne.com.au

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
