# New ports collection makefile for:	corkscrew
# Date created:			Apr 12, 2001
# Whom:				Mark Pulford <mark@kyne.com.au>
#
# $FreeBSD: ports/net/corkscrew/Makefile,v 1.2 2001/05/29 14:28:57 ijliao Exp $
#

PORTNAME=	corkscrew
PORTVERSION=	1.4
CATEGORIES=	net
MASTER_SITES=	http://www.agroman.net/corkscrew/

MAINTAINER=	markp@FreeBSD.org

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
