# New ports collection makefile for:	corkscrew
# Date created:			Apr 12, 2001
# Whom:				Mark Pulford <mark@kyne.com.au>
#
# $FreeBSD: ports/net/corkscrew/Makefile,v 1.3 2001/06/08 05:36:37 markp Exp $
#

PORTNAME=	corkscrew
PORTVERSION=	1.5
CATEGORIES=	net
MASTER_SITES=	http://www.agroman.net/corkscrew/

MAINTAINER=	markp@FreeBSD.org

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
