# New ports collection makefile for:	fragrouter
# Date created:         7 Jan 2000
# Whom:                 kris@FreeBSD.ORG
#
# $FreeBSD: ports/security/fragrouter/Makefile,v 1.1 2000/01/08 09:24:19 kris Exp $
#

PORTNAME=	fragrouter
PORTVERSION= 	1.6
CATEGORIES=	security
MASTER_SITES=	http://www.anzen.com/research/nidsbench/

MAINTAINER=	kris@FreeBSD.ORG

GNU_CONFIGURE=	yes

MAN8=	fragrouter.8

.include <bsd.port.mk>
