# New ports collection makefile for:	fragrouter
# Date created:         7 Jan 2000
# Whom:                 kris@FreeBSD.ORG
#
# $FreeBSD: ports/security/fragrouter/Makefile,v 1.3 2000/04/21 08:18:21 mharo Exp $
#

PORTNAME=	fragrouter
PORTVERSION=	1.6
CATEGORIES=	security
MASTER_SITES=	http://www.anzen.com/research/nidsbench/ \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=kris

MAINTAINER=	kris@FreeBSD.ORG

GNU_CONFIGURE=	yes

MAN8=	fragrouter.8

.include <bsd.port.mk>
