# New ports collection makefile for:	sysutils/p5-Schedule-Match
# Date created:				03 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/sysutils/p5-Schedule-Match/Makefile,v 1.1 2001/01/03 09:26:38 nbm Exp $
#

PORTNAME=	Schedule-Match
PORTVERSION=	0.07
CATEGORIES=	sysutils perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Schedule
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3=		Schedule::Match.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
