# New ports collection makefile for:	uzap
# Date created:		19 Jun 1995
# Whom:			joerg
#
# $FreeBSD: ports/editors/uzap/Makefile,v 1.8 2000/04/14 00:25:46 mharo Exp $
#

PORTNAME=	uzap
PORTVERSION=	1.0
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org

# restrictive Copyright; the author is no longer reachable, however :-(
RESTRICTED=	"Restrictive copyright"
NO_WRKSUBDIR=	yes
MAN1=		uzap.1

.include <bsd.port.mk>
