# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		25 Oct 1998
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape4-navigator/Makefile,v 1.13 2000/04/13 09:17:07 asami Exp $
#
# based on japanese/netscape4-*

MASTERDIR=	${.CURDIR}/../netscape4-communicator
BROWSER=	navigator

.include "${MASTERDIR}/Makefile"
