# ex:ts=8
# Ports collection makefile for:  lprps (a4)
# Date created:			  Sat Aug 3, 1996
# Whom:				  David O'Brien (obrien@cs.ucdavis.edu)
#
# $FreeBSD: ports/print/lprps-a4/Makefile,v 1.5 2000/03/22 00:27:04 obrien Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../lprps-letter

.include "${MASTERDIR}/Makefile"
