# ex:ts=8
# Ports collection makefile for:  lprps (a4)
# Version required:		  2.50
# Date created:			  Sat Aug 3, 1996
# Whom:				  David O'Brien (obrien@cs.ucdavis.edu)
#
# $FreeBSD: ports/print/lprps-a4/Makefile,v 1.2 1999/08/31 01:44:58 peter Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../lprps-letter

.include "${MASTERDIR}/Makefile"
