# ex:ts=8
# Ports collection makefile for:  lprps (a4)
# Version required: 0.0
# Date created:			  Sat Aug 3, 1996
# Whom:				  David O'Brien (obrien@cs.ucdavis.edu)
#
# $FreeBSD: ports/print/lprps-a4/Makefile,v 1.4 2000/03/20 02:36:41 obrien Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../lprps-letter

.include "${MASTERDIR}/Makefile"
