# New ports collection makefile for:	mule with Canna and sj3
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+sj3/Makefile,v 1.9 2000/09/08 04:34:44 taoka Exp $
#

PKGNAMESUFFIX=	-canna+sj3
CATEGORIES=	japanese

CANNA=		yes
SJ3=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
