# New ports collection makefile for:	mule 2.3@19.34 with Canna and sj3
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+sj3/Makefile,v 1.6 1999/08/25 05:25:35 obrien Exp $
#

PKGNAMESUFFIX=	-canna+sj3
CATEGORIES=	japanese editors

CANNA=		yes
SJ3=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
