# New ports collection makefile for:	starlanes
# Date created:				7 May 1997
# Whom:					Andrey Zakhvatov
#
# $FreeBSD: ports/games/starlanes/Makefile,v 1.4 2000/04/02 00:59:17 mharo Exp $
#

PORTNAME=	starlanes
PORTVERSION=	1.2.2
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	games/strategy

MAINTAINER=	ports@FreeBSD.org

ALL_TARGET=	# empty
MAN6=		starlanes.6

post-extract:
	@${RM} ${WRKSRC}/starlanes

.include <bsd.port.mk>
