# New ports collection makefile for: p5-dTemplate
# Date created:			9 December 2000
# Whom:				Jeremy Shaffner <jeremy@external.org>
#
# $FreeBSD: ports/textproc/p5-dTemplate/Makefile,v 1.2 2001/03/01 06:39:13 vanilla Exp $

PORTNAME=	dTemplate
PORTVERSION=	2.0
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	dTemplate
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeremy@external.org

PERL_CONFIGURE=	yes

MAN3=		dTemplate.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
