# New ports collection makefile for:   qt22-static
# Date created:		22 February 2001
# Whom:			alex
#
# $FreeBSD: ports/x11-toolkits/qt2-static/Makefile,v 1.1 2001/02/22 14:18:24 alex Exp $
#

PORTNAME=	qt
PKGNAMESUFFIX=	-static

MAINTAINER=	ports@freebsd.org

WANT_STATIC=	yes

MASTERDIR=	${.CURDIR}/../qt23

.include        "${MASTERDIR}/Makefile"
