# New ports collection makefile for:   qt22-static
# Date created:		22 February 2001
# Whom:			alex
#
# $FreeBSD: ports/x11-toolkits/qt2-static/Makefile,v 1.3 2001/08/25 02:17:59 will Exp $
#

PORTNAME=	qt
PKGNAMESUFFIX=	-static
DIST_SUBDIR=	KDE

MAINTAINER=	kde@FreeBSD.org

WANT_STATIC=	yes

MASTERDIR=	${.CURDIR}/../qt23

.include        "${MASTERDIR}/Makefile"
