# New ports collection makefile for:   ngrep-lib
# Date created:        28 August 2001
# Whom:                Edwin Groothuis (edwin@mavetju.org)
#
# $FreeBSD: ports/net/ngrep-lib/Makefile,v 1.1 2001/09/17 06:21:39 kevlo Exp $
#

PORTNAME=	ngrep-lib
PORTVERSION=	1.1
CATEGORIES=	net
MASTER_SITES=	http://www.mavetju.org/download/

MAINTAINER=	edwin@mavetju.org

MAN3=		ngrep-lib.3
HAS_CONFIGURE=	yes

CONFIGURE_ARGS+=--prefix=${PREFIX}

INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
