# New ports collection makefile for:	nstreams
# Date created:		22 September 1999
# Whom:			darius@dons.net.au
#
# $FreeBSD: ports/net/nstreams/Makefile,v 1.4 2000/12/29 07:44:40 ben Exp $
#

PORTNAME=	nstreams
PORTVERSION=	1.0.0
CATEGORIES=	net
MASTER_SITES=	http://www.hsc.fr/ressources/outils/nstreams/download/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/nstreams

MAN1=		nstreams.1

.include <bsd.port.mk>
