# New ports collection makefile for:    dealt-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/german/ispell-alt/Makefile,v 1.4 2000/06/10 10:25:46 alex Exp $
#

MAINTAINER=     alex@FreeBSD.org

ISPELL_DEALT=	yes
PORTNAME=	ispell
PORTVERSION= 	19991219
PKGNAMESUFFIX=	-alt
MASTERDIR=      ${.CURDIR}/../../textproc/ispell

.include        "${MASTERDIR}/Makefile"

