# New ports collection makefile for:    dealt-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/dealt-ispell/Makefile,v 1.2 2000/04/09 21:52:17 cpiazza Exp $
#

MAINTAINER=     alex@big.endian.de

ISPELL_DEALT=	yes
PORTNAME=	ispell
PORTVERSION= 	19991219
PKGNAMEPREFIX=	dealt-
MASTERDIR=      ${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"

