# New ports collection makefile for:    dealt-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/german/ispell-alt/Makefile,v 1.7 2001/02/06 13:13:15 olgeni Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_DEALT=	yes
PORTNAME=	ispell
PORTVERSION=	19991219
PORTREVISION=	3
CATEGORIES=	german
PKGNAMESUFFIX=	-alt
MASTERDIR=	${.CURDIR}/../../textproc/ispell

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include        "${MASTERDIR}/Makefile"

