# New ports collection makefile for:	links
# Version required:	0.84
# Date created:		21 January 2000
# Whom:			Michael Vasilenko <acid@stu.cn.ua>
#
# $FreeBSD: ports/www/links/Makefile,v 1.2 2000/02/12 23:37:40 jedgar Exp $
#

DISTNAME=	links-0.84
CATEGORIES=	www
MASTER_SITES=	http://artax.karlin.mff.cuni.cz/~mikulas/vyplody/links/download/ \
		http://www.add.com.pl/links/download/

MAINTAINER=	dima@Chg.RU

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
