# New ports collection makefile for:	links
# Version required:	0.83
# Date created:		21 January 2000
# Whom:			Michael Vasilenko <acid@stu.cn.ua>
#
# $FreeBSD: ports/www/links/Makefile,v 1.1 2000/01/29 06:02:00 steve Exp $
#

DISTNAME=	links-0.83
CATEGORIES=	www
MASTER_SITES=	http://artax.karlin.mff.cuni.cz/~mikulas/vyplody/links/download/ \
		http://www.add.com.pl/links/download/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
