# New ports collection makefile for:   NAMG
# Date created:        1 January 2001
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $FreeBSD: ports/mail/namg/Makefile,v 1.2 2001/02/18 15:28:25 kevlo Exp $
#

PORTNAME=	namg
PORTVERSION=	0.3.1
CATEGORIES=	mail
MASTER_SITES=	http://www.zip.com.au/~gsymonds/NAMG/
DISTNAME=	NAMG-${PORTVERSION}

MAINTAINER=	greid@ukug.uk.freebsd.org

GNU_CONFIGURE=	yes

MAN1=		namg.1

.include <bsd.port.mk>
