# New ports collection makefile for:    9e
# Date created:         17 Mar 1999
# Whom:			Jerry Hicks
#
# $FreeBSD: ports/archivers/9e/Makefile,v 1.1.1.1 2000/06/27 03:55:26 wes Exp $
#

PORTNAME=	9e
PORTVERSION=	1.0
CATEGORIES=	archivers
MASTER_SITES=	http://www.eecs.harvard.edu/~wkj/Software/9e/
DISTNAME=	9e

MAINTAINER=	gehicks@cisco.co

WWW=		http://www.eecs.harvard.edu/~wkj/Software/9e/

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/9e ${PREFIX}/bin

.include <bsd.port.mk>
