# New ports collection makefile for:	jvim3 for Wnn6
# Version required:	3.0-1.3j
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-wnn6/Makefile,v 1.6 1999/08/25 05:24:45 obrien Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
