# New ports collection makefile for:	jvim3 for Wnn6
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-wnn6/Makefile,v 1.8 2000/02/07 16:40:36 taoka Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
