# New ports collection makefile for:	Math-Bezier
# Date created:				Wed Jan  3 10:40:02 2001
# Whom:					will
#
# $FreeBSD: ports/math/p5-Math-Bezier/Makefile,v 1.1 2001/01/03 23:38:33 will Exp $
#

PORTNAME=	Math-Bezier
PORTVERSION=	0.01
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Math
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Math::Bezier.3

.include <bsd.port.mk>
