# $FreeBSD: src/usr.sbin/diskcheckd/Makefile,v 1.2 2001/06/23 19:24:18 ben Exp $

PROG=	diskcheckd
MAN8=	diskcheckd.8

MLINKS=	diskcheckd.8 diskcheckd.conf.5

BINDIR?=	/usr/sbin

.include <bsd.prog.mk>
