# $FreeBSD: src/usr.sbin/diskcheckd/Makefile,v 1.3 2001/07/20 04:23:01 obrien Exp $

BINDIR?=	/usr/sbin

PROG=	diskcheckd
MAN8=	diskcheckd.8
MLINKS=	diskcheckd.8 diskcheckd.conf.5

.include <bsd.prog.mk>
