# $FreeBSD: src/usr.sbin/diskcheckd/Makefile,v 1.1 2001/06/03 20:02:03 phk Exp $

CFLAGS+= -W -Wall

PROG=	diskcheckd
MAN8=	diskcheckd.8

MLINKS=	diskcheckd.8 diskcheckd.conf.5

BINDIR?=	/usr/sbin

.include <bsd.prog.mk>
