# New ports collection makefile for:	mule with Canna
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna/Makefile,v 1.38 2000/09/08 04:34:39 taoka Exp $
#

PKGNAMESUFFIX=	-canna
CATEGORIES=	japanese

CANNA=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
