# New ports collection makefile for:	mule with Canna
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna/Makefile,v 1.37 2000/04/14 16:47:39 knu Exp $
#

PKGNAMESUFFIX=	-canna
CATEGORIES=	japanese

CANNA=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
