# New ports collection makefile for:	mule 2.3@19.34 with Canna
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna/Makefile,v 1.35 1999/08/25 05:25:34 obrien Exp $
#

PKGNAMESUFFIX=	-canna
CATEGORIES=	japanese editors

CANNA=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
