# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Version required:	21.1.8
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs-sumo-canna+wnn6/Makefile,v 1.7 1999/09/09 14:46:02 taoka Exp $
#

LANGPREFIX=	ja-
NAMEEXT=	-canna+wnn6

MASTERDIR=	${.CURDIR}/../../editors/xemacs-mule-sumo

.include	"${MASTERDIR}/Makefile"
