# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Version required:	21.1
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-sumo-canna+wnn6/Makefile,v 1.8 1999/11/27 04:00:10 steve Exp $
#

.include	<bsd.port.pre.mk>

XEMACS_MAJOR_VER=	${.CURDIR:S!^${PORTSDIR}/japanese/xemacs!!:S!-sumo-canna+wnn6$!!}
LANGPREFIX=		ja-
NAMEEXT=		-canna+wnn6

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-mule-sumo

.include	"${MASTERDIR}/Makefile"
