# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-sumo-canna+wnn6/Makefile,v 1.11 2000/04/13 08:33:48 knu Exp $
#

CATEGORIES=	japanese

XEMACS_MAJOR_VER=	21
PKGNAMESUFFIX=		-canna+wnn6

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-mule-sumo

.include	"${MASTERDIR}/Makefile"
