# New ports collection makefile for:	bclock
# Date created:		13 May 1997
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $FreeBSD: ports/x11-clocks/bclock/Makefile,v 1.9 2000/04/10 00:32:32 cpiazza Exp $
#

PORTNAME=	bclock
PORTVERSION=	1.0
CATEGORIES=	x11-clocks
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	X11/clocks

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		bclock.1

.include <bsd.port.mk>
