# New ports collection makefile for:   gma
# Date created:         22 June 1999
# Whom:                 Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
#
# $FreeBSD: ports/games/gma/Makefile,v 1.6 2000/04/29 22:08:02 kris Exp $
#

PORTNAME=	gma
PORTVERSION=	0.6
CATEGORIES=	games
MASTER_SITES=	http://www.student.nada.kth.se/~d92-jwa/code/gma/

MAINTAINER=	ijliao@csie.nctu.edu.tw

GNU_CONFIGURE= yes

.include <bsd.port.mk>
