# New ports collection makefile for: pips for EPSON PM-3300C
# Date created:        2000.12.09
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips3300/Makefile,v 1.1 2000/12/11 02:06:50 taoka Exp $
#

PORTVERSION=	1.3
MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		3300

do-install:     # empty

.include "${MASTERDIR}/Makefile"
