# New ports collection makefile for:	ONEW for Canna and Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna+wnn6/Makefile,v 1.7 2000/09/08 04:34:21 taoka Exp $
#

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=         ${.CURDIR}

.include	"${MASTERDIR}/Makefile"
