# New ports collection makefile for:	exim-mysql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-mysql/Makefile,v 1.1 2001/06/11 11:59:36 sheldonh Exp $
#

PKGNAMESUFFIX=	-mysql
CATEGORIES=	mail
PKGDIR=		../exim
FILESDIR=	${PKGDIR}/files
PATCHDIR=	${PKGDIR}/files

WITH_MYSQL=	yes

.include "../exim/Makefile"
