# New ports collection makefile for:	exim-mysql
# Date created:				11 Jun 2001
# Whom:					Sheldon Hearn <sheldonh@FreeBSD.org>
#
# $FreeBSD: ports/mail/exim-mysql/Makefile,v 1.2 2001/06/13 21:19:14 sheldonh Exp $
#

PKGNAMESUFFIX=	-mysql
MASTERDIR=	${.CURDIR}/../exim

WITH_MYSQL=	yes

.include "${MASTERDIR}/Makefile"
