# New ports collection makefile for:	most
# Date created:		31 May 1997
# Whom:			rhwang@bigpanda.com
#
# $FreeBSD: ports/misc/most/Makefile,v 1.6 1999/08/25 07:22:12 obrien Exp $
#

PORTNAME=	most
PORTVERSION=	4.9.0
CATEGORIES=	misc
MASTER_SITES=	ftp://space.mit.edu/pub/davis/most/ \
		ftp://ftp.uni-stuttgart.de/pub/unix/misc/slang/most/

MAINTAINER=	rhwang@bigpanda.com

LIB_DEPENDS=	slang.1:${PORTSDIR}/devel/libslang

GNU_CONFIGURE=	yes
MAN1=		most.1

.include <bsd.port.mk>
