# New ports collection makefile for: ppxp
# Date created:         01 Jan 1999
# Whom:                 sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/ppxp/Makefile,v 1.3 1999/08/31 06:46:12 mharo Exp $
#

MASTERDIR=	${.CURDIR}/../../net/ppxp

MAINTAINER=	sada@FreeBSD.org

USE_TCLJP=	yes

.include "${MASTERDIR}/Makefile"
