# New ports collection makefile for: ppxp
# Date created:         01 Jan 1999
# Whom:                 sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/ppxp/Makefile,v 1.5 2000/04/14 17:10:45 knu Exp $
#

CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../net/ppxp

MAINTAINER=	sada@FreeBSD.org

WITH_TCLJP=	yes

.include "${MASTERDIR}/Makefile"
