# New ports collection makefile for: ppxp
# Version required:	depend on ports/net/ppxp
# Date created:         01 Jan 1999
# Whom:                 sada@FreeBSD.org
#
# $FreeBSD: ports/japanese/ppxp/Makefile,v 1.2 1999/08/25 05:26:33 obrien Exp $
#

PKGNAME=	ja-${DISTNAME}
MASTERDIR=	${.CURDIR}/../../net/ppxp

MAINTAINER=	sada@FreeBSD.org

USE_TCLJP=	yes

.include "${MASTERDIR}/Makefile"
