# New ports collection makefile for:	libxode
# Date created:			4 April 2000
# Whom:				Kostya Lukin <lukin@okbmei.msk.su>
#
# $FreeBSD: ports/textproc/libxode/Makefile,v 1.3 2000/06/16 08:47:59 sobomax Exp $
#

PORTNAME=	libxode
PORTVERSION=	1.0
CATEGORIES=	textproc
MASTER_SITES=	http://download.jabber.org/dists/1.0/

MAINTAINER=	lukin@okbmei.msk.su

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
