# New ports collection makefile for:	libxode
# Date created:			4 April 2000
# Whom:				Kostya Lukin <lukin@okbmei.msk.su>
#
# $FreeBSD: ports/textproc/libxode/Makefile,v 1.5 2000/07/07 16:16:32 steve Exp $
#

PORTNAME=	libxode
PORTVERSION=	1.2
CATEGORIES=	textproc
MASTER_SITES=	http://download.jabber.org/dists/1.2/

MAINTAINER=	lukin@okbmei.msk.su

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
