# New ports collection makefile for:	libxode
# Date created:			4 April 2000
# Whom:				Kostya Lukin <lukin@okbmei.msk.su>
#
# $FreeBSD: ports/textproc/libxode/Makefile,v 1.1 2000/05/01 02:37:53 steve Exp $
#

PORTNAME=	libxode
PORTVERSION=	1.0
CATEGORIES=	textproc
MASTER_SITES=	http://download.jabber.org/dists/1.0/

MAINTAINER=	lukin@okbmei.msk.su

USE_LIBTOOL=	yes

.include <bsd.port.mk>
