# New ports collection makefile for:   scwm-icons
# Date created:        07 April 1998
# Whom:                Yukihiro Nakai <nacai@iname.com>
#
# $FreeBSD: ports/graphics/scwm-icons/Makefile,v 1.4 1999/10/06 04:51:47 nakai Exp $
#

PORTNAME=	scwm-icons
PORTVERSION=	0.99.2
CATEGORIES=	graphics
MASTER_SITES=	ftp://scwm.mit.edu/pub/scwm/

MAINTAINER=	nakai@FreeBSD.org

GNU_CONFIGURE=	yes
USE_X_PREFIX=	yes

NO_BUILD=	yes

.include <bsd.port.mk>
