# New ports collection makefile for:	gnugo
# Version required:	2.4
# Date created:		29 December 1996
# Whom:			jseger@scds.com
#
# $FreeBSD: ports/games/gnugo/Makefile,v 1.4 1999/08/25 06:03:36 obrien Exp $
#

DISTNAME=	gnugo-2.4
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gnugo

MAINTAINER=	jseger@FreeBSD.org

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

MAN6=		gnugo.6
MANCOMPRESSED=	no

.include <bsd.port.mk>
