# New ports collection makefile for:	gnugo
# Date created:		29 December 1996
# Whom:			jseger@scds.com
#
# $FreeBSD: ports/games/gnugo/Makefile,v 1.5 1999/11/02 03:04:23 jseger Exp $
#

PORTNAME=	gnugo
PORTVERSION=	2.4
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gnugo

MAINTAINER=	jseger@FreeBSD.org

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

MAN6=		gnugo.6
MANCOMPRESSED=	no

.include <bsd.port.mk>
