# $FreeBSD: ports/irc/Makefile,v 1.10 1999/12/22 19:43:39 jedgar Exp $
#

    SUBDIR += bitchx
    SUBDIR += blackened
    SUBDIR += bnc
    SUBDIR += epic4
    SUBDIR += ezbounce
    SUBDIR += irc
    SUBDIR += ircII
    SUBDIR += ircd-hybrid
    SUBDIR += irssi
    SUBDIR += kvirc
    SUBDIR += muh
    SUBDIR += nethirc
    SUBDIR += ninja
    SUBDIR += olirc
    SUBDIR += p5-IRC
    SUBDIR += party
    SUBDIR += quirc
    SUBDIR += roxirc
    SUBDIR += scrollz
    SUBDIR += sic
    SUBDIR += sirc
    SUBDIR += tirc
    SUBDIR += tircproxy
    SUBDIR += tkirc
    SUBDIR += trickyirc
    SUBDIR += xchat
    SUBDIR += xgirc
    SUBDIR += yagirc
    SUBDIR += zircon

.include <bsd.port.subdir.mk>
