# $FreeBSD: ports/irc/Makefile,v 1.14 2000/07/31 15:31:14 nbm Exp $
#

    SUBDIR += bitchx
    SUBDIR += blackened
    SUBDIR += bnc
    SUBDIR += epic4
    SUBDIR += ezbounce
    SUBDIR += infobot
    SUBDIR += irc
    SUBDIR += ircII
    SUBDIR += ircatlite
    SUBDIR += ircd-hybrid
    SUBDIR += irssi
    SUBDIR += kvirc
    SUBDIR += muh
    SUBDIR += nethirc
    SUBDIR += ninja
    SUBDIR += olirc
    SUBDIR += p5-IRC
    SUBDIR += party
    SUBDIR += quirc
    SUBDIR += roxirc
    SUBDIR += scrollz
    SUBDIR += sic
    SUBDIR += sirc
    SUBDIR += tirc
    SUBDIR += tircproxy
    SUBDIR += tkirc
    SUBDIR += trickyirc
    SUBDIR += xchat
    SUBDIR += xchat-devel
    SUBDIR += yagirc
    SUBDIR += zircon

.include <bsd.port.subdir.mk>
