# New ports collection makefile for:	textedit
# Date created:		3 January 1998
# Whom:			jraynard
#
# $FreeBSD: ports/editors/textedit/Makefile,v 1.13 2000/06/10 10:26:52 alex Exp $
#

PORTNAME=	textedit
PORTVERSION=	1.0
CATEGORIES=	editors
MASTER_SITES=		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	fenner

MAINTAINER=	alex@FreeBSD.org

LIB_DEPENDS=	xview.3:${PORTSDIR}/x11-toolkits/xview

WRKSRC=		${WRKDIR}/textedit
USE_IMAKE=	yes
MAN1=		textedit.1

.include <bsd.port.mk>
