# New ports collection makefile for:	textedit
# Date created:		3 January 1998
# Whom:			jraynard
#
# $FreeBSD: ports/editors/textedit/Makefile,v 1.12 2000/04/14 00:25:43 mharo Exp $
#

PORTNAME=	textedit
PORTVERSION=	1.0
CATEGORIES=	editors
MASTER_SITES=	http://people.FreeBSD.org/~fenner/distfiles/

MAINTAINER=	alex@FreeBSD.org

LIB_DEPENDS=	xview.3:${PORTSDIR}/x11-toolkits/xview

WRKSRC=		${WRKDIR}/textedit
USE_IMAKE=	yes
MAN1=		textedit.1

.include <bsd.port.mk>
