# New ports collection makefile for:	kinput2-canna+sj3+wnn6
# Date created:		19 Dec 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/kinput2-canna+sj3+wnn6/Makefile,v 1.7 2000/09/08 04:34:27 taoka Exp $
#

CANNA=		yes
SJ3=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../kinput2-freewnn/
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
