# New ports collection makefile for:	sparc-rtems-gcj
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sparc-rtems-gcj/Makefile,v 1.1 2000/07/10 04:32:34 steve Exp $
#

PORTNAME=	gcj

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sparc-rtems
.include "${.CURDIR}/../i386-rtems-gcj/Makefile"
