# New ports collection makefile for:	mkmf
# Date created:		14 Mar 1996
# Whom:			se
#
# $FreeBSD: ports/devel/mkmf/Makefile,v 1.6 1999/08/25 05:48:44 obrien Exp $
#

PORTNAME=	mkmf
PORTVERSION=	4.11
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.uni-koeln.de/util/
DISTNAME=	${PORTNAME}

MAINTAINER=	se@FreeBSD.org

MAN1=		mkmf.1
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
