# New ports collection makefile for:	mnews-im
# Date created:			03 Jan 2000
# Whom:				SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mnews-im/Makefile,v 1.1.1.1 2000/01/03 19:57:22 sada Exp $
#

PKGNAMESUFFIX=	-im

RUN_DEPENDS=	imput:${PORTSDIR}/mail/im

MASTERDIR=	${.CURDIR}/../mnews
COMMENT=	${.CURDIR}/pkg/COMMENT

GNSPOOL=	0
IMPUT=		1

.include "${MASTERDIR}/Makefile"
