# ex:ts=8
# New ports collection makefile for:	log4cpp
# Date created:			May 1, 2001
# Whom:				ijliao
#
# $FreeBSD: ports/devel/log4cpp/Makefile,v 1.1 2001/05/01 17:30:29 ijliao Exp $
#

PORTNAME=	log4cpp
PORTVERSION=	0.2.5
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION:S,b,,}
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
