# New ports collection makefile for:	acroread-chsfont
# Version required:	1999.7.20
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chsfont/Makefile,v 1.4 1999/08/25 04:57:36 obrien Exp $
#

DISTNAME=	chsfont
CATEGORIES=	chinese linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
