# New ports collection makefile for:	acroread-chsfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chsfont/Makefile,v 1.5 2000/02/28 08:33:20 asami Exp $
#

DISTNAME=	chsfont
CATEGORIES=	chinese linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
