# New ports collection makefile for:	acroread-chsfont
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/acroread-chsfont/Makefile,v 1.7 2000/04/14 16:55:48 knu Exp $
#

CATEGORIES=	chinese
DISTNAME=	chsfont

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
