# New ports collection makefile for:	vtwm
# Date created:		21 December 1998
# Whom:			bmah@ca.sandia.gov
#
# $FreeBSD: ports/x11-wm/vtwm/Makefile,v 1.5 2000/08/03 09:28:17 asami Exp $
#

PORTNAME=	vtwm
PORTVERSION=	5.4.5a
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://ftp.visi.com/users/hawkeyd/X/

MAINTAINER=	bmah@freebsd.org

USE_IMAKE=	yes
USE_XPM=	yes

MAN1=		vtwm.1

.include <bsd.port.mk>
