# New ports collection makefile for:	vtwm
# Date created:		21 December 1998
# Whom:			bmah@ca.sandia.gov
#
# $FreeBSD: ports/x11-wm/vtwm/Makefile,v 1.3 2000/04/10 19:50:27 cpiazza Exp $
#

PORTNAME=	vtwm
PORTVERSION=	5.4.5a
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://ftp.visi.com/users/hawkeyd/X/

MAINTAINER=	bmah@acm.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

MAN1=		vtwm.1

.include <bsd.port.mk>
