# New ports collection makefile for:	mpeg_lib
# Date created:		16 November 1994
# Whom:			torstenb
#
# $FreeBSD: ports/graphics/mpeg-lib/Makefile,v 1.16 2000/04/14 10:46:40 asami Exp $
#

PORTNAME=	mpeg_lib
PORTVERSION=	1.3.1
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.bic.mni.mcgill.ca/pub/mpeg/ \
		http://starship.python.net/~gward/mpeglib/

MAINTAINER=	ports@FreeBSD.org

INSTALLS_SHLIBS=	yes
GNU_CONFIGURE=	yes
CONFIGURE_ENV=	OPTIMIZE="${CFLAGS}"

.include <bsd.port.mk>
