# New ports collection makefile for:	xgraph
# Version required:	11.3.2
# Date created:		24 November 1994
# Whom:			asami
#
# $FreeBSD: ports/math/xgraph/Makefile,v 1.13 1999/08/31 06:47:57 mharo Exp $
#

DISTNAME=	xgraph-11.3.2
CATEGORIES=	math print
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	sanpei@sanpei.org

USE_IMAKE=	yes
MAN1=		xgraph.1

.include <bsd.port.mk>
