# New ports collection makefile for:	smalltalk
# Date created:		09 Feb 1995
# Whom:			gpalmer
#
# $FreeBSD: ports/lang/smalltalk/Makefile,v 1.26 2000/07/09 08:45:38 alex Exp $
#

PORTNAME=	smalltalk
PORTVERSION=	1.8.1
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	smalltalk

MAINTAINER=	ports@FreeBSD.org

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		gst.1

# Set all-target to test the stuff
ALL_TARGET=	optimize info check

.include <bsd.port.mk>
