# New ports collection makefile for:	smalltalk
# Date created:		09 Feb 1995
# Whom:			gpalmer
#
# $FreeBSD: ports/lang/smalltalk/Makefile,v 1.23 2000/03/31 17:02:41 will Exp $
#

PORTNAME=	smalltalk
PORTVERSION=	1.7.3
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	smalltalk

MAINTAINER=	alex@big.endian.de

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		gst.1

# Set all-target to test the stuff
ALL_TARGET=	optimize info check

.include <bsd.port.mk>
