# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-sumo-wnn4/Makefile,v 1.10 2000/04/25 08:01:15 knu Exp $
#

CATEGORIES=	japanese

XEMACS_MAJOR_VER=	21
PKGNAMESUFFIX=		-wnn4

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-sumo

.include	"${MASTERDIR}/Makefile"
