# New ports collection makefile for:    rinfo
# Date created:         23th March 1998
# Whom:                 Mark Chapman <markc@ctgi.net>
#
# $FreeBSD: ports/devel/rinfo/Makefile,v 1.2 1999/08/25 05:50:06 obrien Exp $
#

PORTNAME=	rinfo
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	ftp://www.ctgi.net/pub/ctgi/

MAINTAINER=	markc@ctgi.net

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/rinfo ${PREFIX}/bin/rinfo

.include <bsd.port.mk>
