# New ports collection makefile for:	kon2 with 14dot font
# Date created:         11 Apr 1997
# Whom:                 Makoto Matsushita <matusita@jp.freebsd.org>
#
# $FreeBSD: ports/japanese/kon2-14dot/Makefile,v 1.2 1999/08/25 05:25:04 obrien Exp $
#

KONFONT=	14dot

MASTERDIR=	${.CURDIR}/../kon2-16dot

.include "${MASTERDIR}/Makefile"
