# New ports collection makefile for:	XML-TreeBuilder
# Date created:				Tue Jan  2 00:03:51 2001
# Whom:					will
#
# $FreeBSD: ports/textproc/p5-XML-TreeBuilder/Makefile,v 1.1 2001/01/03 23:48:47 will Exp $
#

PORTNAME=	XML-TreeBuilder
PORTVERSION=	3.08
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	XML
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		XML::TreeBuilder.3 XML::Element.3

.include <bsd.port.mk>
