# New ports collection makefile for:    Text::CSV_XS
# Date created:         Fri Nov 19 03:11:08 MSK 1999
# Whom:                 Ache
#
# $FreeBSD: ports/textproc/p5-Text-CSV_XS/Makefile,v 1.5 2001/03/01 06:38:55 vanilla Exp $
#

PORTNAME=	Text-CSV_XS
PORTVERSION=	0.22
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Text
PKGNAMEPREFIX=	p5-

MAINTAINER=	ache@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Text::CSV_XS.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
