# New ports collection makefile for:    psmisc
# Date created:         10 March 1998
# Whom:                 rantapaa@uswest.net
#
# $FreeBSD: ports/sysutils/psmisc/Makefile,v 1.6 2000/05/14 05:40:50 billf Exp $
#

PORTNAME=	psmisc
PORTVERSION=	17
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.bitcon.no/pub/linux/slackware/source/a/procps/

MAINTAINER=	rantapaa@uswest.net

INSTALL_TARGET=	install-all
MAN1=		pidof.1 pstree.1 killall.1
WRKSRC=		${WRKDIR}/psmisc

.include <bsd.port.mk>
