# New ports collection makefile for:    psmisc
# Date created:         10 March 1998
# Whom:                 rantapaa@uswest.net
#
# $FreeBSD: ports/sysutils/psmisc/Makefile,v 1.5 2000/04/22 10:13:03 mharo Exp $
#

PORTNAME=	psmisc
PORTVERSION=	17
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.freesoftware.com/pub/linux/slackware/slackware-3.6/source/a/procps/ \
		ftp://ftp.bitcon.no/pub/linux/slackware/source/a/procps/

MAINTAINER=	rantapaa@uswest.net

INSTALL_TARGET=	install-all
MAN1=		pidof.1 pstree.1 killall.1
WRKSRC=		${WRKDIR}/psmisc

.include <bsd.port.mk>
