# New ports collection makefile for:    fr-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/french/ispell/Makefile,v 1.4 2000/09/22 07:20:21 asami Exp $
#

MAINTAINER=     alex@FreeBSD.org

ISPELL_FR=	yes
PORTVERSION= 	1.4
CATEGORIES=	french
MASTERDIR=      ${.CURDIR}/../../textproc/ispell

.include        "${MASTERDIR}/Makefile"
