# New ports collection makefile for:    fr-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/french/ispell/Makefile,v 1.5 2000/09/22 12:20:57 asami Exp $
#

MAINTAINER=	alex@FreeBSD.org

ISPELL_FR=	yes
PORTVERSION=	1.4
CATEGORIES=	french
MASTERDIR=	${.CURDIR}/../../textproc/ispell

.include        "${MASTERDIR}/Makefile"
