# New ports collection makefile for:    fr-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/french/ispell/Makefile,v 1.3 2000/06/10 10:25:46 alex Exp $
#

MAINTAINER=     alex@FreeBSD.org

ISPELL_FR=	yes
PORTVERSION= 	1.4
MASTERDIR=      ${.CURDIR}/../../textproc/ispell

.include        "${MASTERDIR}/Makefile"
