# New ports collection makefile for:	archie
# Version required:	1.4.1
# Date created:		20 Oct 1994
# Whom:			torstenb
#
# $FreeBSD: ports/net/archie/Makefile,v 1.8 1999/08/30 14:22:02 peter Exp $
#

DISTNAME=	c-archie-1.4.1-FIXED
PKGNAME=	archie-1.4.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.uu.net/networking/info-service/archie/clients/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	torstenb@FreeBSD.org

WRKSRC=		${WRKDIR}/archie-1.4.1-FIX
MAN1=		archie.1

.include <bsd.port.mk>
