# New ports collection makefile for:	archie
# Date created:		20 Oct 1994
# Whom:			torstenb
#
# $FreeBSD: ports/net/archie/Makefile,v 1.10 2000/04/09 18:10:08 cpiazza Exp $
#

PORTNAME=	archie
PORTVERSION=	1.4.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.uu.net/networking/info-service/archie/clients/
DISTNAME=	c-archie-1.4.1-FIXED
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

WRKSRC=		${WRKDIR}/archie-1.4.1-FIX
MAN1=		archie.1

.include <bsd.port.mk>
