# New ports collection makefile for:	ipa
# Date created:				2 December 2000
# Whom:					Andrey Simonenko
#
# $FreeBSD: ports/sysutils/ipa/Makefile,v 1.7 2001/03/28 13:14:10 kevlo Exp $
#

PORTNAME=	ipa
PORTVERSION=	1.1.2
CATEGORIES=	sysutils
MASTER_SITES=	http://www.simon.org.ua/ipa/

MAINTAINER=	simon@simon.org.ua

NO_PACKAGE=	"Needs to be built uniquely for each site"
ALL_TARGET=	FreeBSD

MAN5=		ipa.5 ipa.conf.5
MAN8=		ipa.8 ipastat.8

.include <bsd.port.mk>
