# New ports collection makefile for:	iselect
# Date created:		03-Jan-1998
# Whom:			Ralf S. Engelschall <rse@engelschall.com>
#
# $FreeBSD: ports/misc/iselect/Makefile,v 1.3 1999/08/25 07:21:50 obrien Exp $
#

PORTNAME=	iselect
PORTVERSION=	1.2.0
CATEGORIES=	misc
MASTER_SITES=	http://www.engelschall.com/sw/iselect/distrib/ \
		ftp://ftp.engelschall.com/sw/iselect/

MAINTAINER=	rse@engelschall.com

HAS_CONFIGURE=	yes

MAN1=	iselect.1

.include <bsd.port.mk>
