# New ports collection makefile for:   ion
# Date created:        20 January 2001
# Whom:                ricci@cs.utah.edu
#
# $FreeBSD: ports/x11-wm/ion/Makefile,v 1.2 2001/01/21 20:53:38 clive Exp $
#

PORTNAME=	ion
PORTVERSION=	20010215
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.students.tut.fi/~tuomov/dl/

MAINTAINER=	ricci@cs.utah.edu

MAN1=		ion.1x

USE_X_PREFIX=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
