# New ports collection makefile for:   cmp3
# Date created:        10 April 1999
# Whom:                Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/audio/cmp3/Makefile,v 1.9 2000/04/08 21:23:24 mharo Exp $
#

PORTNAME=	cmp3
PORTVERSION=	2.0.p4
CATEGORIES=	audio
MASTER_SITES=	http://www.personal.psu.edu/users/n/k/nkk104/cmp3/
DISTNAME=	cmp3-2.0pre4

MAINTAINER= 	ports@FreeBSD.org

RUN_DEPENDS= 	mpg123:${PORTSDIR}/audio/mpg123

USE_GMAKE=	yes

WRKSRC=		${WRKDIR}/cmp3
PKGMESSAGE=	${WRKSRC}/MESSAGE

.include <bsd.port.mk>
