# New ports collection makefile for:   cmp3
# Version required:    2.0pre4
# Date created:        10 April 1999
# Whom:                Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/audio/cmp3/Makefile,v 1.7 2000/01/29 20:01:24 mharo Exp $
#

DISTNAME=	cmp3-2.0pre4
PKGNAME=	cmp3-2.0p4
CATEGORIES=	audio
MASTER_SITES=	http://www.personal.psu.edu/users/n/k/nkk104/cmp3/

MAINTAINER=	cpiazza@FreeBSD.org

RUN_DEPENDS= 	mpg123:${PORTSDIR}/audio/mpg123

USE_GMAKE=	yes

WRKSRC=		${WRKDIR}/cmp3
PKGMESSAGE=	${WRKSRC}/MESSAGE

.include <bsd.port.mk>
