# New ports collection makefile for:	xmaddressbook
# Date created:		31 Jul 1996
# Whom:			shanee@augusta.de
#
# $FreeBSD: ports/deskutils/xmaddressbook/Makefile,v 1.7 2000/04/08 22:04:00 mharo Exp $
#

PORTNAME=	xmaddressbook
PORTVERSION=	1.5.3
CATEGORIES=	deskutils
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	office
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	shanee@augusta.de

USE_MOTIF=	yes
USE_IMAKE=	yes
WRKSRC=		${WRKDIR}/xmaddressbook
MAN1=		xmaddressbook.1

.include <bsd.port.mk>
