# New ports collection makefile for:    p5-Digest-MD2
# Date created:				24 May 2001
# Whom:					petef@FreeBSD.org
#
# $FreeBSD: ports/security/p5-Digest-MD2/Makefile,v 1.1 2001/05/27 05:35:20 vanilla Exp $
#

PORTNAME=	Digest-MD2
PORTVERSION=	2.00
CATEGORIES=	security perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Digest
PKGNAMEPREFIX=	p5-

MAINTAINER=	petef@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Digest::MD2.3

.include <bsd.port.mk>
