# New ports collection makefile for:	E-Run 1.2
# Date created:				17 June 2000
# Whom:					Kelly Yancey <kbyanc@posi.net>
#
# $FreeBSD: ports/x11/erun/Makefile,v 1.4 2001/01/16 17:33:11 sobomax Exp $
#

PORTNAME=	E-Run
PORTVERSION=	1.2
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR = kbyanc

MAINTAINER=	kbyanc@posi.net

LIB_DEPENDS=	epplet.1:${PORTSDIR}/x11-wm/libepplet

WRKSRC=		${WRKDIR}/${PORTNAME}

USE_X_PREFIX=	yes
USE_IMLIB=	yes

.include <bsd.port.mk>
