# New ports collection makefile for:	E-Run 1.2
# Date created:				17 June 2000
# Whom:					Kelly Yancey <kbyanc@posi.net>
#
# $FreeBSD: ports/x11/erun/Makefile,v 1.2 2000/07/18 07:02:57 kbyanc Exp $
#

PORTNAME=	E-Run
PORTVERSION= 	1.2
CATEGORIES=	x11
MASTER_SITES=	http://void.mapopolis.com/~jacob/c0de/

MAINTAINER=	kbyanc@posi.net

LIB_DEPENDS=    epplet.1:${PORTSDIR}/x11-wm/libepplet

WRKSRC=		${WRKDIR}/${PORTNAME}

USE_X_PREFIX=	yes
USE_IMLIB=	yes

.include <bsd.port.mk>
