# New ports collection makefile for:	Blackbox
# Date created:		June 15, 1998
# Whom:			Brian Handy <handy@physics.montana.edu>
#
# $FreeBSD: ports/x11-wm/blackbox/Makefile,v 1.34 2000/06/18 01:43:15 cpiazza Exp $
#

PORTNAME=	blackbox
PORTVERSION= 	0.61.0
CATEGORIES=	x11-wm
MASTER_SITES=	ftp://portal.alug.org/pub/blackbox/0.6x.x/

MAINTAINER=	patseal@hyperhost.net

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
USE_BZIP2=	yes

.include <bsd.port.mk>
