# New ports collection makefile for:	gnomekiss
# Date created:				4 Apr 2001
# Whom:					UMENO Takashi <umeno@rr.iij4u.or.jp>
#
# $FreeBSD: ports/games/gnomekiss/Makefile,v 1.4 2001/08/01 16:50:13 lioux Exp $
#

PORTNAME=	gnomekiss
PORTVERSION=	0.9.1
CATEGORIES=	games gnome
MASTER_SITES=	http://www.ecs.soton.ac.uk/~njl98r/code/kiss/
DISTNAME=	gnomekiss-${PORTVERSION}

MAINTAINER=	umeno@rr.iij4u.or.jp

USE_X_PREFIX=	yes
USE_GNOME=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
