#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice-devel/files/openoffice-wrapper,v 1.10 2003/09/16 06:50:17 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org%%FRELEASE_NR%%/program/
program=`echo $0 | sed -e 's|.*-%%RELEASE_NR%%-||'`

case $program in
$0)
	cd $oopath && ./soffice "$@"
	;;
	*)
	cd $oopath && exec ./$program "$@"
	;;
esac
