# New ports collection makefile for: English PK fonts at 600dpi
# Date created:		06 Nov 1998
# Whom:			Satoshi Asami <asami@FreeBSD.org>
#
# $FreeBSD: ports/print/pkfonts600/Makefile,v 1.5 1999/08/31 01:45:17 peter Exp $
#

RESOLUTION=	600
MASTERDIR=	${.CURDIR}/../pkfonts300

.include	"${MASTERDIR}/Makefile"
