# New ports collection makefile for:	p5-Convert-UUlib
# Date created:				November 19th 2000
# Whom:					Blaz Zupan <blaz@amis.net>
#
# $FreeBSD: ports/converters/p5-Convert-UUlib/Makefile,v 1.3 2001/03/01 06:37:12 vanilla Exp $
#

PORTNAME=	Convert-UUlib
PORTVERSION=	0.111
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Convert
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Convert::UUlib.3

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
