# New ports collection makefile for:	acroread-jpnfont
# Date created:		99/06/16
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/acroread-jpnfont/Makefile,v 1.5 2000/04/11 14:12:51 knu Exp $
#

DISTNAME=	jpnfont
CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
