# New ports collection makefile for:	acroread-jpnfont
# Date created:		99/06/16
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/acroread-jpnfont/Makefile,v 1.4 2000/02/28 08:33:43 asami Exp $
#

DISTNAME=	jpnfont
CATEGORIES=	japanese linux

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
