# New ports collection makefile for:	p5-IO-String
# Date created:		13 March 2001
# Whom:	      		Johann Visagie <johann@egenetics.com>
#
# $FreeBSD: ports/devel/p5-IO-String/Makefile,v 1.2 2001/03/20 12:57:39 kevlo Exp $
#

PORTNAME=	IO-String
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	IO
PKGNAMEPREFIX=	p5-

MAINTAINER=	wjv@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		IO::String.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
