#!/bin/sh
#
# $FreeBSD: ports/net/spread4/pkg-deinstall,v 1.1 2005/10/28 18:30:58 ehaupt Exp $

if [ "$2" != "POST-DEINSTALL" ]; then
	exit 0
fi

USER=spread
GROUP=spread

echo "===> deinstall note:"
echo "      Please note that user ${USER} and group ${GROUP} was not removed"
echo "      from this system:"
echo ""

if pw usershow "${USER}" 2>/dev/null 1>&2; then
	echo "      To delete spread user permanently"
	echo "         $ pw userdel ${USER}"
	echo ""
fi

if pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
	echo "      To delete spread group permanently"
	echo "         $ pw groupdel ${GROUP}"
	echo ""
fi

exit 0
