# New ports collection makefile for:	libjabber
# Date created:			4 April 2000
# Whom:				Kostya Lukin <lukin@okbmei.msk.su>
#
# $FreeBSD: ports/net/libjabber/Makefile,v 1.5 2000/07/07 16:15:37 steve Exp $
#

PORTNAME=	libjabber
PORTVERSION=	1.0
CATEGORIES=	net
MASTER_SITES=	http://download.jabber.org/dists/1.0/final/

MAINTAINER=	lukin@okbmei.msk.su

LIB_DEPENDS=	xode.1:${PORTSDIR}/textproc/libxode

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes

MAN1=		jabber-config.1

.include <bsd.port.mk>
