# New ports collection makefile for:	libjabber
# Date created:			4 April 2000
# Whom:				Kostya Lukin <lukin@okbmei.msk.su>
#
# $FreeBSD: ports/net/libjabber/Makefile,v 1.6 2001/01/16 17:31:51 sobomax Exp $
#

PORTNAME=	libjabber
PORTVERSION=	1.2
CATEGORIES=	net
MASTER_SITES=	http://download.jabber.org/dists/1.2/

MAINTAINER=	lukin@okbmei.msk.su

LIB_DEPENDS=	xode.2:${PORTSDIR}/textproc/libxode

GNU_CONFIGURE=	yes

MAN1=		jabber-config.1

.include <bsd.port.mk>
