# New ports collection makefile for:	i386-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/rtems-gcc/Makefile,v 1.3 2001/08/13 20:58:09 obrien Exp $
#

PORTNAME=	gcc
PORTVERSION=	2.95.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	gcc
EXTRACT_ONLY=	# Empty

MAINTAINER=	jeh@FreeBSD.org

PKGNAMEPREFIX=	rtems-

NO_BUILD=	YES
NO_INSTALL=	YES

.include <bsd.port.mk>
