# New ports collection makefile for:	i386-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/rtems-gcc/Makefile,v 1.2 2001/07/01 02:03:06 jeh Exp $
#

PORTNAME=	gcc
PORTVERSION=	2.95.3
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEWARE}
MASTER_SITE_SUBDIR=	gcc/releases/gcc-2.95.3
EXTRACT_ONLY=	# Empty

MAINTAINER=	jeh@FreeBSD.org

PKGNAMEPREFIX=	rtems-

USE_BZIP2=	yes
NO_BUILD=	YES
NO_INSTALL=	YES

.include <bsd.port.mk>
