# New ports collection makefile for:	TiMidity++
# Version required:	1.3.10
# Date created:		27 Feb 1999
# Whom:			Yoichi Asai <yatt@msc.biglobe.ne.jp>
#
# $FreeBSD: ports/audio/timidity++-motif/Makefile,v 1.3 1999/12/10 00:59:27 imura Exp $
#

INTERFACE=	motif

MASTERDIR=	${.CURDIR}/../../audio/timidity++-emacs

.include "${MASTERDIR}/Makefile"
