# New ports collection makefile for:	gtkyahoo
# Date created:			18 August 1999
# Whom:				dannyman@dannyland.org
#
# $FreeBSD: ports/net/gtkyahoo/Makefile,v 1.3 2000/10/05 06:42:17 reg Exp $
#

PORTNAME=	gtkyahoo
PORTVERSION=	0.16
CATEGORIES=	net
MASTER_SITES=	http://download.sourceforge.net/gtkyahoo/

MAINTAINER=	dannyman@dannyland.org

USE_X_PREFIX=	yes
USE_GTK=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
