# New ports collection makefile for:	gtkyahoo
# Date created:			18 August 1999
# Whom:				dannyman@dannyland.org
#
# $FreeBSD: ports/net/gtkyahoo/Makefile,v 1.4 2000/11/12 01:36:41 fenner Exp $
#

PORTNAME=	gtkyahoo
PORTVERSION=	0.17
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	gtkyahoo

MAINTAINER=	dannyman@dannyland.org

USE_X_PREFIX=	yes
USE_GTK=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
