# New ports collection makefile for:	sitecopy
# Version required:     0.8.*
# Date created:		15 January 1999
# Whom:			nik
#
# $FreeBSD: ports/www/sitecopy/Makefile,v 1.11 1999/08/31 06:52:17 mharo Exp $
#

DISTNAME=       sitecopy-0.8.0
CATEGORIES=	www
MASTER_SITES=   http://www.lyra.org/sitecopy/

MAINTAINER=     nik@FreeBSD.org

FETCH_BEFORE_ARGS=	-b
GNU_CONFIGURE=  yes
USE_GMAKE=      yes
ALL_TARGET=     sitecopy

MAN1=		sitecopy.1

.include <bsd.port.mk>
