# New ports collection makefile for:	cucipop
# Date created:		7 Jun 1997
# Whom:			igor@zynaps.ru
#
# $FreeBSD: ports/mail/cucipop/Makefile,v 1.10 2000/04/13 19:59:29 cpiazza Exp $
#
# NOTE: APOP works only for virtual hosts as designed!
#       Virtual hosts works only with Berkeley DB2.
#       Berkeley DB2 is in conflict with libc, so commented out. :-(

PORTNAME=	cucipop
PORTVERSION=	1.31
CATEGORIES=	mail
MASTER_SITES=	ftp://ftp.informatik.rwth-aachen.de/pub/packages/cucipop/

#BUILD_DEPENDS=  ${PREFIX}/include/db2/db.h:${PORTSDIR}/databases/db

MAINTAINER=	vanilla@FreeBSD.org

MAN8=   cucipop.8 #makevpopdb.8

.include <bsd.port.mk>
