# New ports collection makefile for:    xpacman
# Date created:         19 Aug 1995
# Whom:                 joerg
#
# $FreeBSD: ports/games/xpacman/Makefile,v 1.9 2000/04/14 12:27:58 asami Exp $
#

PORTNAME=	xpacman
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.nvg.unit.no/pub/pacman/
DISTNAME=	pacman10

MAINTAINER=	joerg@FreeBSD.org

NO_WRKSUBDIR=	Does not unpack into subdir.
USE_ZIP=	yes
USE_IMAKE=	yes
MAN1=		pacman.1

.include <bsd.port.mk>
