# New ports collection makefile for:    xpilot
# Date created:         18 July 1995
# Whom:                 jmacd
#
# $FreeBSD: ports/games/xpilot/Makefile,v 1.23 2001/05/07 07:32:51 sheldonh Exp $
#

PORTNAME=	xpilot
PORTVERSION=	4.4.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.xpilot.org/pub/xpilot/ \
		ftp://ftp.xpilot.org/pub/xpilot/old/ \
		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games/multiplayer

MAINTAINER=	goranrunfeldt@home.se

USE_IMAKE=	yes
MAN6=		xpilot.6 xpilots.6 xp-replay.6

.include <bsd.port.mk>
