# New ports collection makefile for:    xpilot
# Date created:         18 July 1995
# Whom:                 jmacd
#
# $FreeBSD: ports/games/xpilot/Makefile,v 1.18 1999/08/25 06:05:54 obrien Exp $
#

PORTNAME=       xpilot
PORTVERSION=	4.1.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.xpilot.org/pub/xpilot/ \
		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	games/multiplayer

MAINTAINER=	sheldonh@FreeBSD.org

USE_IMAKE=	yes
MAN6=		xpilot.6 xpilots.6 xp-replay.6

.include <bsd.port.mk>
