# New ports collection makefile for:	geekcode generator
# Version required:	1.3
# Date created:		30 Aug 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/misc/geekcode/Makefile,v 1.1.1.1 1999/08/30 07:48:44 cpiazza Exp $
#

DISTNAME=	geekcode-1.3
CATEGORIES= 	misc
MASTER_SITES=	http://seymour.napalm.net/

MAINTAINER=	cpiazza@FreeBSD.org

do-install:
	@${INSTALL_PROGRAM} ${WRKSRC}/geekcode ${PREFIX}/bin

.include <bsd.port.mk>
