# New ports collection makefile for:   	ipw
# Date created:				29 January 1999
# Whom:					mph
#
# $FreeBSD: ports/net/ipw/Makefile,v 1.3 1999/08/30 14:23:00 peter Exp $
#

PORTNAME=	ipw
PORTVERSION=	3.3.a
CATEGORIES=	net
MASTER_SITES=	http://mjhb.marina-del-rey.ca.us/ipw/
DISTNAME=	ipw

MAINTAINER=	mph@freebsd.org

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
