# New ports collection makefile for:   	ipw
# Date created:				29 January 1999
# Whom:					mph
#
# $FreeBSD: ports/net/ipw/Makefile,v 1.4 2000/04/09 18:11:46 cpiazza Exp $
#

PORTNAME=	ipw
PORTVERSION=	3.3.a
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_FREEBSD}
DISTNAME=	ipw

MAINTAINER=	ports@freebsd.org

NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
