# New ports collection makefile for:   ja-w3m-image
# Date Created:                22 July 2001
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/w3m-img/Makefile,v 1.1 2001/07/21 18:21:55 sf Exp $
#

PKGNAMESUFFIX=	-img
CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../../www/w3m
PKGDIR=		${.CURDIR}
PLIST=		${MASTERDIR}/pkg-plist

JAPANESE=	Yes
INLINE_IMAGE=	yes

.include "${MASTERDIR}/Makefile"
