# New ports collection makefile for:	tcpflow
# Version required:	0.12
# Date created:		20 August 1999
# Whom:			Jose M. Alcaide <jose@we.lc.ehu.es>
#
# $FreeBSD: ports/net/tcpflow/Makefile,v 1.3 1999/08/30 14:24:14 peter Exp $
#

DISTNAME=	tcpflow-0.12
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.circlemud.org/pub/jelson/tcpflow/

MAINTAINER=	jose@we.lc.ehu.es

HAS_CONFIGURE=	yes
CONFIGURE_ARGS= --prefix=${PREFIX}

MAN1=		tcpflow.1

.include <bsd.port.mk>
