# New ports collection makefile for:	tcpflow
# Date created:		20 August 1999
# Whom:			Jose M. Alcaide <jose@we.lc.ehu.es>
#
# $FreeBSD: ports/net/tcpflow/Makefile,v 1.5 2000/01/09 03:31:10 kris Exp $
#

PORTNAME=	tcpflow
PORTVERSION=	0.12
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.circlemud.org/pub/jelson/tcpflow/

MAINTAINER=	jose@we.lc.ehu.es

HAS_CONFIGURE=	yes

MAN1=		tcpflow.1

.include <bsd.port.mk>
