# New ports collection makefile for:	tcpflow
# Version required:	0.12
# Date created:		20 August 1999
# Whom:			Jose M. Alcaide <jose@we.lc.ehu.es>
#
# $FreeBSD: ports/net/tcpflow/Makefile,v 1.4 1999/09/17 13:09:35 jmas Exp $
#

DISTNAME=	tcpflow-0.12
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.circlemud.org/pub/jelson/tcpflow/

MAINTAINER=	jose@we.lc.ehu.es

HAS_CONFIGURE=	yes

MAN1=		tcpflow.1

.include <bsd.port.mk>
