# New ports collection makefile for:	mpd
# Version required:			3.0b4
# Date created:				31 Jan 2000
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/mpd-netgraph/Makefile,v 1.4 2000/02/01 00:40:43 archie Exp $
#

DISTNAME=	mpd-3.0b5
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.whistle.com/pub/archie/mpd/

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	${FILESDIR}/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
