# New ports collection makefile for:	mpd
# Date created:				31 Jan 2000
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/mpd-netgraph/Makefile,v 1.7 2000/04/15 08:57:37 asami Exp $
#

PORTNAME=	mpd
PORTVERSION=	3.0.b6
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.whistle.com/pub/archie/mpd/
DISTNAME=	mpd-3.0b6

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	${FILESDIR}/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
