# New ports collection makefile for:	mpd
# Date created:				31 Jan 2000
# Whom:					Archie Cobbs
#
# $FreeBSD: ports/net/mpd-netgraph/Makefile,v 1.5 2000/02/01 01:22:34 archie Exp $
#

PORTNAME=	mpd
PORTVERSION=	3.0.b5
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.whistle.com/pub/archie/mpd/

MAINTAINER=	archie@freebsd.org

MTREE_FILE=	${FILESDIR}/mpd.mtree
MAN8=		mpd.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
