# New ports collection makefile for:   XStarRoll
# Date created:        14 January 1999
# Whom:                Sakai Hiroaki <sakai@miya.ee.kagu.sut.ac.jp>
#
# $FreeBSD: ports/x11/xstarroll/Makefile,v 1.5 2000/08/03 09:28:56 asami Exp $
#

PORTNAME=	xstarroll
PORTVERSION=	1.04
CATEGORIES=	x11
MASTER_SITES=	http://wwwmiya.ee.kagu.sut.ac.jp/~sakai/

MAINTAINER=	sakai@miya.ee.kagu.sut.ac.jp

ALL_TARGET=	xstarroll

USE_X_PREFIX=	yes
USE_XPM=	yes

MAN1=		xstarroll.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
