# New ports collection makefile for:   xmsg
# Date created:        21 September 1999
# Whom:                jsellens
#
# $FreeBSD: ports/x11/xmsg/Makefile,v 1.2 2000/04/13 19:10:52 cpiazza Exp $
#

PORTNAME=	xmsg
PORTVERSION=	1.0
CATEGORIES=	x11
MASTER_SITES=	http://www.generalconcepts.com/resources/software/

MAINTAINER=	jsellens@generalconcepts.com

MAN1=		xmsg.1
MANCOMPRESSED=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
