# New ports collection makefile for:   ptex-pkfonts
# Date created:        24 Dec 1999
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/ptex-pkfonts360/Makefile,v 1.2 2000/01/02 01:50:55 steve Exp $
#

RESOLUTION=	360
MASTERDIR=	${.CURDIR}/../ptex-pkfonts300

.include "${MASTERDIR}/Makefile"
