# New ports collection makefile for:   ptex-pkfonts
# Version required:    ?
# Date created:        24 Dec 1999
# Whom:                Kentaro Inagaki <inagaki@tg.rim.or.jp>
#
# $FreeBSD: ports/japanese/ptex-pkfonts360/Makefile,v 1.1 1999/12/27 01:15:36 steve Exp $
#

RESOLUTION=	360
MASTERDIR=	${.CURDIR}/../ptex-pkfonts300

.include "${MASTERDIR}/Makefile"
