# New ports collection makefile for: YaTeX
# Version required:	1.67
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-mule/Makefile,v 1.9 1999/09/30 07:02:25 taoka Exp $
#

PKGNAME=	yatex-mule-1.67
CATEGORIES=	print elisp

MULE=		yes

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg/COMMENT

.include	"${MASTERDIR}/Makefile"
