# New ports collection makefile for: YaTeX
# Version required:	1.67
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-mule/Makefile,v 1.8 1999/08/31 01:45:30 peter Exp $
#

PKGNAME=	yatex-mule-1.67
CATEGORIES=	print elisp

MULE=		yes

MASTERDIR=	${.CURDIR}/../yatex
PLIST=		${.CURDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
