# New ports collection makefile for: YaTeX
# Date created:		98/11/17
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/yatex-mule/Makefile,v 1.14 2000/09/18 02:05:43 taoka Exp $
#

PKGNAMESUFFIX=	-mule

MASTERDIR=	${.CURDIR}/../yatex
COMMENT=	${.CURDIR}/pkg-comment
EMACS_PORT_NAME=mule

.include	"${MASTERDIR}/Makefile"
