# New ports collection makefile for:	thinice
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/thinice/Makefile,v 1.1.1.1 2000/06/13 08:51:08 sobomax Exp $
#

PORTNAME=	thinice
PORTVERSION= 	1.0.3
CATEGORIES=	x11-toolkits
MASTER_SITES=	http://www.ing.umu.se/~stric/theme/
DISTNAME=	gtk-${PORTNAME}-theme-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
