# New ports collection makefile for:   consolehm
# Date created:        27 September 1999
# Whom:                Mike Muir <mmuir@es.co.nz>
#
# $FreeBSD: ports/sysutils/consolehm/Makefile,v 1.7 2000/07/30 14:58:35 kevlo Exp $
#

PORTNAME=	consolehm
PORTVERSION=	1.31
CATEGORIES=	sysutils
MASTER_SITES= 	ftp://muir.yi.org/pub/consolehm/ \
		http://www.es.co.nz/~mmuir/

MAINTAINER=	mmuir@es.co.nz

WRKSRC=		${WRKDIR}/consolehm/consolehm

GNU_CONFIGURE=	yes
MAN8=		chm.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
