# New ports collection makefile for:   consolehm
# Date created:        27 September 1999
# Whom:                Mike Muir <mmuir@es.co.nz>
#
# $FreeBSD: ports/sysutils/consolehm/Makefile,v 1.5 2000/05/22 00:50:07 will Exp $
#

PORTNAME=	consolehm
PORTVERSION=	1.3A
CATEGORIES=	sysutils
MASTER_SITES= 	ftp://muir.yi.org/pub/consolehm/ \
		http://www.es.co.nz/~mmuir/

MAINTAINER=	mmuir@es.co.nz

WRKSRC=		${WRKDIR}/consolehm/consolehm
GNU_CONFIGURE=	yes
MAN8=		chm.8
MANCOMPRESSED=	maybe

.include <bsd.port.mk>
