# New ports collection makefile for:   consolehm
# Date created:        27 September 1999
# Whom:                Mike Muir <mmuir@es.co.nz>
#
# $FreeBSD: ports/sysutils/consolehm/Makefile,v 1.3 2000/04/09 19:07:21 cpiazza Exp $
#

PORTNAME=	consolehm
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES= 	ftp://mongol.dhis.org/pub/consolehm/ \
		http://www.es.co.nz/~mmuir/

MAINTAINER=	mmuir@es.co.nz

WRKSRC=		${WRKDIR}/consolehm/consolehm
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
