# New ports collection makefile for:	BladeEnc
# Date created:		Thu Jan 14 23:28:40 CET 1999
# Whom:			Dirk Froemberg <dirk@FreeBSD.org>
#
# $FreeBSD: ports/audio/bladeenc/Makefile,v 1.11 2000/02/28 21:59:06 dirk Exp $
#

PORTNAME=	bladeenc
PORTVERSION=	0.92
CATEGORIES=	audio
MASTER_SITES=	http://bladeenc.mp3.no/source/ \
		http://www.physik.TU-Berlin.DE/~ibex/ports/distfiles/
EXTRACT_SUFX=	.0-src-stable.tar.gz

MAINTAINER=	dirk@FreeBSD.org

WRKSRC=		${WRKDIR}/${PKGNAME}.0
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
