# New ports collection makefile for:	BladeEnc
# Version required:	0.90
# Date created:		Thu Jan 14 23:28:40 CET 1999
# Whom:			Dirk Froemberg <dirk@FreeBSD.org>
#
# $FreeBSD: ports/audio/bladeenc/Makefile,v 1.8 1999/08/25 04:35:19 obrien Exp $
#

DISTNAME=	bladeenc-0.90-src-stable
PKGNAME=	bladeenc-0.90
CATEGORIES=	audio
MASTER_SITES=	http://bladeenc.mp3.no/source/ \
		http://www.physik.TU-Berlin.DE/~ibex/ports/distfiles/

MAINTAINER=	dirk@FreeBSD.org

WRKSRC=		${WRKDIR}/${PKGNAME}.0
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
