# New ports collection makefile for:	dirdiff
# Whom:			grog
# Date created:		7 May 2001
#
# $FreeBSD: ports/sysutils/dirdiff/Makefile,v 1.1 2001/05/07 06:47:15 grog Exp $
#

PORTNAME=	dirdiff
PORTVERSION=	1.2
CATEGORIES=	sysutils
MASTER_SITES=	ftp://samba.org/pub/paulus/

MAINTAINER=	grog

BUILD_DEPENDS=	tclsh8.2:${PORTSDIR}/lang/tcl82
RUN_DEPENDS=	wish8.2:${PORTSDIR}/x11-toolkits/tk82

.include <bsd.port.mk>
