# New ports collection makefile for:    sls
# Date created:         16. Dec 97
# Whom:                 sec@42.org
#
# $FreeBSD: ports/misc/sls/Makefile,v 1.2 1999/08/25 07:22:37 obrien Exp $
#

PORTNAME=	sls
PORTVERSION=	1.00
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.cse.psu.edu/pub/src/
DISTNAME=       ${PORTNAME}

MAINTAINER=	sec@42.org

WRKSRC=		${WRKDIR}/sls

MAN1=		sls.1

.include <bsd.port.mk>
