# New ports collection makefile for: d1489
# Date created:         1 May 1995
# Whom:                 ache
#
# $FreeBSD: ports/russian/d1489/Makefile,v 1.12 1999/08/31 06:49:57 mharo Exp $
#

PORTNAME=	d1489
PORTVERSION= 	1.4
CATEGORIES=     russian
MASTER_SITES=   ftp://ftp.kiarchive.ru/pub/unix/convert/char/
EXTRACT_SUFX=   .tgz

MAINTAINER=	ache@FreeBSD.org

.include <bsd.port.mk>
