# New ports collection makefile for:	mips64orion-rtems-gdb
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/mips64orion-rtems-gdb/Makefile,v 1.1 2000/07/10 04:32:24 steve Exp $
#

PORTNAME=	gdb

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	mips64orion-rtems
.include "${.CURDIR}/../i386-rtems-gdb/Makefile"
