# New ports collection makefile for:	Math-GMP
# Date created:				Wed Jan  3 11:09:25 2001
# Whom:					will
#
# $FreeBSD: ports/math/p5-Math-GMP/Makefile,v 1.1 2001/01/03 23:40:35 will Exp $
#

PORTNAME=	Math-GMP
PORTVERSION=	1.01
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Math
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Math::GMP.3

.include <bsd.port.mk>
