# New ports collection makefile for: pips for EPSON PM-770C
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips770/Makefile,v 1.2 2000/10/08 10:22:46 asami Exp $
#

MASTER_SITES=	http://www.epkowa.on.arena.ne.jp/pips/data/${PRTYPE}/
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		770

.include "${MASTERDIR}/Makefile"
