# New ports collection makefile for: pips for EPSON PM-770C
# Version required:    1.0
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips770/Makefile,v 1.1.1.1 2000/09/01 16:40:01 taoka Exp $
#

MASTER_SITES=	http://www.epkowa.on.arena.ne.jp/pips/data/${PRTYPE}/
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		770

.include "${MASTERDIR}/Makefile"
