# New ports collection makefile for: pips for EPSON PM-770C
# Date created:        00/04/21
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips770/Makefile,v 1.3 2000/11/23 11:56:09 sobomax Exp $
#

MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		770

.include "${MASTERDIR}/Makefile"
