# New ports collection makefile for:	wmglobe
# Date created:		23 Jun 1999
# Whom:			Will Andrews <andrews@technologist.com>
#
# $FreeBSD: ports/astro/wmglobe/Makefile,v 1.9 2000/04/08 22:01:57 mharo Exp $
#

PORTNAME=	wmglobe
PORTVERSION=	1.0
CATEGORIES=	astro windowmaker
MASTER_SITES=	http://perso.linuxfr.org/jdumont/wmg/

MAINTAINER=	will@FreeBSD.org

LIB_DEPENDS=	wraster.4:${PORTSDIR}/x11-wm/windowmaker

USE_X_PREFIX=	yes

MAN1=		wmglobe.1

.include <bsd.port.mk>
