# New ports collection makefile for: pips for EPSON PM-820C PM-3300C
# Date created:        2000.08.04
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips820_3300/Makefile,v 1.1.1.1 2000/09/01 16:37:25 taoka Exp $
#

MASTER_SITES=	http://www.epkowa.on.arena.ne.jp/pips/data/${PRTYPE:S,_3300,,}/

MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		820_3300

.include "${MASTERDIR}/Makefile"
