# New ports collection makefile for:	libogg
# Date created:				18 October 2000
# Whom:					t.vanklaveren@student.utwente.nl
#
# $FreeBSD: ports/audio/libogg/Makefile,v 1.5 2001/03/01 09:36:27 sf Exp $
#

PORTNAME=	libogg
PORTVERSION=	1.0b4
PORTEPOCH=	1
CATEGORIES=	audio
MASTER_SITES=	http://www.vorbis.com/files/beta4/unix/ \
		http://home.student.utwente.nl/t.vanklaveren/distfiles/
DISTNAME=	${PORTNAME}-${PORTVERSION:S/b/beta/}

MAINTAINER=	Christian Weisgerber <naddy@mips.inka.de>

USE_LIBTOOL=	yes

.include <bsd.port.mk>
