# New ports collection makefile for:    cpdup
# Date created:         28 Oct 1999
# Whom:                 dillon
#
# $FreeBSD: ports/sysutils/cpdup/Makefile,v 1.3 2000/04/22 10:11:55 mharo Exp $
#

PORTNAME=	cpdup
PORTVERSION=	1.02
CATEGORIES=	sysutils
MASTER_SITES=   http://apollo.backplane.com/FreeBSDPorts/
#MASTER_SITE_SUBDIR=	cp

MAINTAINER=	dillon@FreeBSD.ORG

MAN1=		cpdup.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
