# New ports collection makefile for:    cpdup
# Date created:         28 Oct 1999
# Whom:                 dillon
#
# $FreeBSD: ports/sysutils/cpdup/Makefile,v 1.4 2000/07/21 18:44:31 dillon Exp $
#

PORTNAME=	cpdup
PORTVERSION=	1.03
CATEGORIES=	sysutils
MASTER_SITES=   http://apollo.backplane.com/FreeBSDPorts/
#MASTER_SITE_SUBDIR=	cp

MAINTAINER=	dillon@FreeBSD.ORG

MAN1=		cpdup.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
