# New ports collection makefile for: Mew (for xemacs21)
# Version required:	1.94.1
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs21/Makefile,v 1.5 1999/09/10 19:00:07 peter Exp $
#

EMACS_PORT_NAME=	xemacs21

.include "${.CURDIR}/../mew/Makefile"
