# New ports collection makefile for: Mew (for xemacs21)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-xemacs21/Makefile,v 1.6 2000/01/04 14:29:34 shige Exp $
#

EMACS_PORT_NAME=	xemacs21

.include "${.CURDIR}/../mew/Makefile"
