# New ports collection makefile for:	kpuzzle
# Date created:				2000-11-04
# Whom:					trevor
#
# $FreeBSD: ports/games/kpuzzle/Makefile,v 1.2 2001/03/25 07:08:58 trevor Exp $
#

PORTNAME=		kpuzzle
PORTVERSION=		0.2
CATEGORIES=		games
MASTER_SITES=		${MASTER_SITE_KDE}
MASTER_SITE_SUBDIR=	unstable/apps/games

MAINTAINER=	trevor@FreeBSD.org

BUILD_DEPENDS=	gettext:${PORTSDIR}/devel/gettext

USE_KDELIBS_VER=2
GNU_CONFIGURE=	yes
USE_BZIP2=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
