# New ports collection makefile for:	xantfarm
# Version required:	1.16
# Date created:		13 February 1997
# Whom:			Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11/xantfarm/Makefile,v 1.5 2000/01/08 11:23:54 nakai Exp $
#

DISTNAME=	xantfarm_23oct91
PKGNAME=	xantfarm-1.16
CATEGORIES=	x11
MASTER_SITES=	http://www.acme.com/software/xantfarm/

MAINTAINER=	nakai@FreeBSD.org

WRKSRC=		${WRKDIR}/xantfarm
USE_IMAKE=	yes
MAN1=		xantfarm.1

.include <bsd.port.mk>
