# New ports collection makefile for:   isync
# Date created:		2000-12-23
# Whom:			eivind
#
# $FreeBSD: ports/mail/isync/Makefile,v 1.1 2001/01/02 10:38:34 eivind Exp $

PORTNAME=	isync
PORTVERSION=	0.5
CATEGORIES=	mail
MASTER_SITES=	http://www.sigpipe.org/isync/

MAINTAINER=	eivind@FreeBSD.org

GNU_CONFIGURE=	yes

MAN1=		isync.1

.include <bsd.port.mk>
