# New ports collection makefile for: Mew (for mule)
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD: ports/mail/mew-mule/Makefile,v 1.9 2000/04/13 19:59:59 cpiazza Exp $
#

EMACS_PORT_NAME=	mule19

.include "${.CURDIR}/../mew/Makefile"
