# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		25 Oct 1998
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape4-navigator/Makefile,v 1.14 2000/06/25 13:28:20 cjh Exp $
#
# based on japanese/netscape4-*

MASTERDIR=	${.CURDIR}/../netscape4-communicator
BROWSER_NAME=	navigator

.include "${MASTERDIR}/Makefile"
