# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		25 Oct 1998
# Whom:			CHOI Junho <junker@jazz.snu.ac.kr>
#
# $FreeBSD: ports/korean/netscape4-navigator/Makefile,v 1.12 1999/08/30 12:09:05 peter Exp $
#
# based on japanese/netscape4-*

MASTER_DIR=	${.CURDIR}/../netscape4-communicator

MAINTAINER=	cjh@kr.freebsd.org

BROWSER=	navigator

.include "${MASTER_DIR}/Makefile"
