# New ports collection makefile for:	strobe
# Date created:		23 Sep 1996
# Whom:			proff
#
# $FreeBSD: ports/security/strobe/Makefile,v 1.8 2000/04/09 18:30:36 cpiazza Exp $
#

PORTNAME=	strobe
PORTVERSION=	1.06
CATEGORIES=	security net
MASTER_SITES=	ftp://ftp.win.or.jp/pub/network/misc/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jseger@FreeBSD.org

WRKSRC=		${WRKDIR}/strobe
ALL_TARGET=	strobe
MAN1=		strobe.1

.include <bsd.port.mk>
