# New ports collection makefile for:	xless
# Date created:		23 December 1996
# Whom:			Conrad Sabatier <conrads@home.com>
#
# $FreeBSD: ports/misc/xless/Makefile,v 1.9 2000/04/14 08:47:08 asami Exp $
#

PORTNAME=	xless
PORTVERSION=	1.7
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_XCONTRIB} \
		ftp://ftp.cs.berkeley.edu/ucb/people/dglo/xless/
MASTER_SITE_SUBDIR=	applications

MAINTAINER=	conrads@home.com

USE_IMAKE=	yes
MAN1=		xless.1
MANCOMPRESSED=	yes	

.include <bsd.port.mk>
