# New ports collection makefile for:	xless
# Version required:	1.7
# Date created:		23 December 1996
# Whom:			Conrad Sabatier <conrads@home.com>
#
# $FreeBSD: ports/misc/xless/Makefile,v 1.7 1999/11/27 01:33:06 steve Exp $
#

DISTNAME=	xless-1.7
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_XCONTRIB} \
		ftp://ftp.cs.berkeley.edu/ucb/people/dglo/xless/
MASTER_SITE_SUBDIR=     applications

MAINTAINER=	conrads@home.com

USE_IMAKE=	yes
MAN1=		xless.1
MANCOMPRESSED= 	yes	

.include <bsd.port.mk>
