# New ports collection makefile for:	libt1
# Version required:		1.0
# Date created:			13, May, 1999
# Whom:				Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
#
# $FreeBSD: ports/devel/t1lib/Makefile,v 1.7 1999/12/23 18:56:54 steve Exp $
#

DISTNAME=	t1lib-1.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	libs/graphics

MAINTAINER=	ijliao@csie.nctu.edu.tw

WRKSRC=		${WRKDIR}/T1-1.0

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_LIBTOOL=	yes
USE_XLIB=	yes
ALL_TARGET=	without_doc

.include <bsd.port.mk>
