# New ports collection makefile for:	libt1
# Date created:			13, May, 1999
# Whom:				Ying-Chieh Liao <ijliao@csie.nctu.edu.tw>
#
# $FreeBSD: ports/devel/t1lib/Makefile,v 1.10 2000/04/20 02:55:59 chuckr Exp $
#

PORTNAME=	t1lib
PORTVERSION=	1.0.1
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	libs/graphics

MAINTAINER=	ijliao@csie.nctu.edu.tw

WRKSRC=		${WRKDIR}/T1-1.0.1

USE_GMAKE=	yes
USE_LIBTOOL=	yes
USE_XLIB=	yes
ALL_TARGET=	without_doc

.include <bsd.port.mk>
