# New ports collection makefile for:	server of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/FreeWnn-server/Makefile,v 1.9 2000/04/12 14:46:54 knu Exp $
#

PKGNAMESUFFIX=	-server
CATEGORIES=	korean
MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}/pkg
PKGINSTALL=	${.CURDIR}/../../japanese/FreeWnn-server/pkg/INSTALL
WNN=		kWnn

.include "${MASTERDIR}/Makefile"
