# $FreeBSD: ports/vietnamese/Makefile,v 1.6 2001/01/06 07:20:07 obrien Exp $
#
    SUBDIR += vntex

    SUBDIR += vn7to8
    SUBDIR += vnconvert
    SUBDIR += vnelvis
    SUBDIR += vnless
    SUBDIR += vnlpr
    SUBDIR += vnpstext
    SUBDIR += vnroff
    SUBDIR += vnterm


.include <bsd.port.subdir.mk>
