# $FreeBSD: ports/vietnamese/Makefile,v 1.5 1999/08/31 02:11:43 peter Exp $
#

    SUBDIR += vn7to8
    SUBDIR += vnconvert
    SUBDIR += vnelvis
    SUBDIR += vnless
    SUBDIR += vnlpr
    SUBDIR += vnpstext
    SUBDIR += vnroff
    SUBDIR += vnterm


.include <bsd.port.subdir.mk>
