# $FreeBSD: ports/vietnamese/Makefile,v 1.7 2001/02/07 11:34:25 obrien Exp $
#
    SUBDIR += vntex

    SUBDIR += libviet
    SUBDIR += vn7to8
    SUBDIR += vnconvert
    SUBDIR += vnelvis
    SUBDIR += vnless
    SUBDIR += vnlpr
    SUBDIR += vnpstext
    SUBDIR += vnroff
    SUBDIR += vnterm


.include <bsd.port.subdir.mk>
