# New ports collection makefile for:	tcpcat
# Date created:		18 October 2000
# Whom:			roam@orbitel.bg
#
# $FreeBSD: ports/net/tcpcat/Makefile,v 1.1 2000/10/29 12:23:52 jeh Exp $
#

PORTNAME=	tcpcat
PORTVERSION=	1.0.1
CATEGORIES=	net
MASTER_SITES=	http://www.gusnet.cx/proj/tcpcat/

MAINTAINER=	roam@FreeBSD.org

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
