# New ports collection makefile for:	xmahjongg
# Version required:	3.2
# Date created:		16 Aug 1996
# Whom:			joerg@freebsd.org
#
# $FreeBSD: ports/games/xmahjongg/Makefile,v 1.7 1999/08/25 06:05:30 obrien Exp $
#

DISTNAME=	xmahjongg-3.2
CATEGORIES=	games
MASTER_SITES=	http://www.lcdf.org/xmahjongg/

MAINTAINER=	joerg@freebsd.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
MAN6=		xmahjongg.6

.include <bsd.port.mk>
