# New ports collection makefile for:	xmahjongg
# Date created:		16 Aug 1996
# Whom:			joerg@freebsd.org
#
# $FreeBSD: ports/games/xmahjongg/Makefile,v 1.9 2000/04/14 12:27:39 asami Exp $
#

PORTNAME=	xmahjongg
PORTVERSION=	3.3
CATEGORIES=	games
MASTER_SITES=	http://www.lcdf.org/xmahjongg/

MAINTAINER=	joerg@freebsd.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
MAN6=		xmahjongg.6

.include <bsd.port.mk>
