# New ports collection makefile for:	xmahjongg
# Date created:		16 Aug 1996
# Whom:			joerg@freebsd.org
#
# $FreeBSD: ports/games/xmahjongg/Makefile,v 1.8 2000/02/19 19:28:59 joerg Exp $
#

PORTNAME=	xmahjongg
PORTVERSION=	3.2
CATEGORIES=	games
MASTER_SITES=	http://www.lcdf.org/xmahjongg/

MAINTAINER=	joerg@freebsd.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes
MAN6=		xmahjongg.6

.include <bsd.port.mk>
