# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-sumo-canna+freewnn/Makefile,v 1.11 2000/07/13 09:52:57 taoka Exp $
#

CATEGORIES=	japanese

XEMACS_MAJOR_VER=	21
PKGNAMESUFFIX=		-canna+freewnn

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-sumo

.include	"${MASTERDIR}/Makefile"
