# New ports collection makefile for:	libxml
# Version required:			1.8.2
# Date created:				28 September 1998
# Whom:					Yukihiro Nakai <Nakai@technologist.com>
#
# $FreeBSD: ports/textproc/libxml/Makefile,v 1.15 1999/12/28 02:32:16 nakai Exp $
#

DISTNAME=	libxml-1.8.2
CATEGORIES=	textproc gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	stable/sources/libxml

MAINTAINER=	ade@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
