# New ports collection makefile for:	libxml
# Version required:			1.7.3
# Date created:				28 September 1998
# Whom:					Yukihiro Nakai <Nakai@technologist.com>
#
# $FreeBSD: ports/textproc/libxml/Makefile,v 1.11 1999/08/31 02:09:30 peter Exp $
#

DISTNAME=	libxml-1.7.3
CATEGORIES=	textproc gnome
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	sources/libxml

MAINTAINER=	nakai@FreeBSD.org

USE_LIBTOOL=	yes

.include <bsd.port.mk>
