# New ports collection makefile for:	setquota
# Date created:		27 September 1997
# Whom:			winter@jurai.net
#
# $FreeBSD: ports/sysutils/setquota/Makefile,v 1.4 2000/04/09 19:08:29 cpiazza Exp $
#

PORTNAME=	setquota
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.jurai.net/users/winter/

MAINTAINER=	winter@jurai.net

WRKSRC=		${WRKDIR}/setquota/

MAN8=		getquota.8 setquota.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
