#!/bin/sh
#
# $FreeBSD: ports/sysutils/pkg_install-devel/pkg-deinstall,v 1.1 2004/01/26 00:07:11 eik Exp $
#

PAX=/bin/pax
ECHO_CMD=echo
RM=/bin/rm
BACKUPDIR=/var/backups

PREFIX=${PKG_PREFIX:-/usr/local}
if [ "${PREFIX}" = "/usr" ]; then
  MANPREFIX="${PREFIX}/share"
else
  MANPREFIX="${PREFIX}"
fi

case $2 in
POST-DEINSTALL)
  if [ "${PREFIX}" = "/usr" ]; then
    if [ -e "${BACKUPDIR}/pkg_install.tgz" ]; then
      ${PAX} -r -pe -z -f "${BACKUPDIR}/pkg_install.tgz"
      ${RM} "${BACKUPDIR}/pkg_install.tgz"
      ${ECHO_CMD} "===>  Base pkg_install restored."
    fi
  fi
  ;;
esac
