#!/bin/sh
#
# $FreeBSD: ports/sysutils/pkg_install-devel/pkg-req,v 1.2 2004/07/02 00:31:18 eik Exp $
#

if [ -z "$OSVERSION" ]; then
  if [ -x /sbin/sysctl ]; then
    OSVERSION=`/sbin/sysctl -n kern.osreldate`
  else
    OSVERSION=`/usr/sbin/sysctl -n kern.osreldate`
  fi
fi

case $2 in
INSTALL)
  if [ %%OSVERSIONCHK%% ]; then
    echo "$1: Your base pkg_install tools are already up-to-date."
    exit 1
  fi
  ;;
esac
