#!/bin/sh
#
# $FreeBSD: ports/sysutils/pkg_install-devel/pkg-req,v 1.1 2004/06/30 10:31:45 eik Exp $
#

if [ -z "$OSVERSION" ]; then
  if [ -x /sbin/sysctl ]; then
    OSVERSION=`/sbin/sysctl -n kern.osreldate`
  else
    OSVERSION=`/usr/sbin/sysctl -n kern.osreldate`
  fi
fi

case $2 in
INSTALL)
  if [ "$OSVERSION" -ge 492000 -a "$OSVERSION" -lt 500000 -o "$OSVERSION" -ge 502120 ]; then
    echo "$1: Your base pkg_install tools are already up-to-date."
    exit 1
  fi
  ;;
esac
