# New ports collection makefile for:    mips-rtems-binutils
# Date created:         9 June 2000
# Whom:                 James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/mips-rtems-binutils/Makefile,v 1.5 2000/12/18 13:54:20 jeh Exp $
#

PORTNAME=       binutils

MAINTAINER=     jeh@FreeBSD.org

#BROKEN=         RepoCopy done.  Now it has to be updated.
#
LCLTARGET=      mips-rtems
.include "${.CURDIR}/../i386-rtems-binutils/Makefile"
