# $FreeBSD: ports/russian/Makefile,v 1.31 2001/03/28 17:45:39 sobomax Exp $
#
    SUBDIR += xxkb

    SUBDIR += X.language
    SUBDIR += apache13
    SUBDIR += apache13-modssl
    SUBDIR += cyrproxy
    SUBDIR += d1489
    SUBDIR += elm.language
    SUBDIR += gd
    SUBDIR += kde2-i18n
    SUBDIR += koi8r-ps
    SUBDIR += messarge
    SUBDIR += netscape4.language
    SUBDIR += p5-Lingua-RU-Charset
    SUBDIR += pgp.language
    SUBDIR += pine.language
    SUBDIR += rispell
    SUBDIR += rus-ispell
    SUBDIR += wmcyrx
    SUBDIR += xcode
    SUBDIR += xruskb

.include <bsd.port.subdir.mk>
