# $FreeBSD: ports/russian/Makefile,v 1.34 2001/04/17 11:11:23 sobomax Exp $
#

    SUBDIR += X.language
    SUBDIR += apache13
    SUBDIR += apache13-modssl
    SUBDIR += cyrproxy
    SUBDIR += d1489
    SUBDIR += elm.language
    SUBDIR += gd
    SUBDIR += kde2-i18n
    SUBDIR += koi8r-ps
    SUBDIR += messarge
    SUBDIR += netscape4.language
    SUBDIR += p5-Lingua-RU-Charset
    SUBDIR += pgp.language
    SUBDIR += pine.language
    SUBDIR += pscyr
    SUBDIR += rispell
    SUBDIR += rus-ispell
    SUBDIR += wmcyrx
    SUBDIR += xcode
    SUBDIR += xcyrBGR
    SUBDIR += xruskb
    SUBDIR += xxkb

.include <bsd.port.subdir.mk>
