# New ports collection makefile for:	sgf2tex
# Date created:				24 August 1999
# Whom:					spcoltri@unm.edu
#
# $FreeBSD: ports/print/sgf2tex/Makefile,v 1.1 2000/09/19 16:03:03 ade Exp $
#

PORTNAME=	sgf2tex
PORTVERSION=	3.2
CATEGORIES=	print
MASTER_SITES=	ftp://match.stanford.edu/pub/

MAINTAINER=	spcoltri@omcl.org

BUILD_DEPENDS=	tex:${PORTSDIR}/print/teTeX
RUN_DEPENDS=	tex:${PORTSDIR}/print/teTeX

MAN1=		sgf2tex.1 sgfsplit.1

.include <bsd.port.mk>
