# New ports collection makefile for:	xquote
# Date created:		4 Jan 1998
# Whom:			Ian Struble <ian@broken.net>
#
# $FreeBSD: ports/misc/xquote/Makefile,v 1.7 2000/11/07 23:28:14 asami Exp $

PORTNAME=	xquote
PORTVERSION=	1.1
CATEGORIES=	misc
MASTER_SITES=	http://sunsite.auc.dk/xinvest/	\
		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR= applications

MAINTAINER=	mph@freebsd.org

USE_MOTIF=	yes
USE_IMAKE=	yes
USE_XPM=	yes

.include <bsd.port.mk>
