# New ports collection makefile for:    seahaven
# Version required:     1.04
# Date created:         23 Dec 1998
# Whom:                 imp
#
# $FreeBSD: ports/games/seahaven/Makefile,v 1.6 1999/08/25 06:04:23 obrien Exp $
#

DISTNAME=	seahaven-1.41
CATEGORIES=	games
MASTER_SITES=	http://www.cinenet.net/users/spitzak/seahaven/
EXTRACT_SUFX=	.tgz

MAINTAINER=	imp@FreeBSD.org

USE_XLIB=	yes
GNU_CONFIGURE=	yes
MAN6?=		seahaven.6

.include <bsd.port.mk>
