# New ports collection makefile for:	mule with Canna and Wnn6
# Date created:		7 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/mule-canna+wnn6/Makefile,v 1.9 2000/04/14 16:47:43 knu Exp $
#

PKGNAMESUFFIX=	-canna+wnn6
CATEGORIES=	japanese

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
