# New ports collection makefile for:	sparc-rtems-gdb
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/sparc-rtems-gdb/Makefile,v 1.1 2000/07/10 04:32:34 steve Exp $
#

PORTNAME=	gdb

MAINTAINER=	jim@thehousleys.net

LCLTARGET=	sparc-rtems
CONFIGURE_ARGS+=	--verbose --enable-sim
.include "${.CURDIR}/../i386-rtems-gdb/Makefile"
