# New ports collection makefile for:	links
# Date created:		21 January 2000
# Whom:			Michael Vasilenko <acid@stu.cn.ua>
#
# $FreeBSD: ports/www/links/Makefile,v 1.3 2000/03/20 21:30:08 jedgar Exp $
#

PORTNAME=	links
PORTVERSION= 	0.84
CATEGORIES=	www
MASTER_SITES=	http://artax.karlin.mff.cuni.cz/~mikulas/vyplody/links/download/ \
		http://www.add.com.pl/links/download/

MAINTAINER=	dima@Chg.RU

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
