#!/bin/sh
#
# $FreeBSD: ports/editors/openoffice/files/openoffice-wrapper,v 1.2 2002/08/04 00:18:09 mbr Exp $

oopath=%%PREFIX%%/OpenOffice.org1.0/program/
program=`echo $0 | sed -e 's|.*-||'`

if [ ! $LANG ]; then
	export LANG=%%LANG%%
fi

case $program in
$0)
	exec $oopath/soffice "$@"
	;;
	*)
	exec $oopath/$program "$@"
	;;
esac
