# New ports collection makefile for:	p5-Set-IntSpan
# Date created:		February 7, 1998
# Whom:			Don Croyle <croyle@gelemna.org>
#
# $FreeBSD: ports/math/p5-Set-IntSpan/Makefile,v 1.5 2000/05/21 11:52:05 knu Exp $
#

PORTNAME=	Set-IntSpan
PORTVERSION=	1.07
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Set
PKGNAMEPREFIX=	p5-

MAINTAINER=	croyle@gelemna.org

PERL_CONFIGURE=	yes

MAN3=		Set::IntSpan.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
