# New ports collection makefile for:	textproc/p5-String-Strip
# Date created:				31 December 2000
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/textproc/p5-String-Strip/Makefile,v 1.1 2001/01/03 10:28:01 nbm Exp $
#

PORTNAME=	String-Strip
PORTVERSION=	1.01
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	String
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@tobez.org

PERL_CONFIGURE=	yes

MAN3=		String::Strip.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
