# New ports collection makefile for: viz
# Date created:                      8 Mar 1997
# Whom:                              Brent J. Nordquist <bjn@visi.com>
#
# $FreeBSD: ports/misc/viz/Makefile,v 1.3 2000/03/22 15:49:29 fenner Exp $
#

PORTNAME=	viz
PORTVERSION=	1.1.1
CATEGORIES=	misc
MASTER_SITES=	http://people.FreeBSD.org/~fenner/distfiles/
EXTRACT_SUFX=	.tgz

MAINTAINER=	bjn@visi.com

MAN1=		viz.1 inviz.1

.include <bsd.port.mk>
