# New ports collection makefile for: viz
# Date created:                      8 Mar 1997
# Whom:                              Brent J. Nordquist <bjn@visi.com>
#
# $FreeBSD: ports/misc/viz/Makefile,v 1.5 2000/06/22 19:15:32 fenner Exp $
#

PORTNAME=	viz
PORTVERSION=	1.1.1
CATEGORIES=	misc
MASTER_SITES=		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	fenner
EXTRACT_SUFX=	.tgz

MAN1=		viz.1 inviz.1

.include <bsd.port.mk>
