# New ports collection makefile for: ja-tcsh NLS catalog (Roomi)
# Date created:		19 August 1998
# Whom:			Issei Suzuki <issei@jp.FreeBSD.org>
#
# $FreeBSD: ports/japanese/tcsh-nls-roomi/Makefile,v 1.8 1999/08/31 06:46:30 mharo Exp $
#

CATALOGNAME=	roomi

MAINTAINER=	issei@jp.FreeBSD.org

MASTERDIR=	${.CURDIR}/../tcsh-nls-generic
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST

.include	"${MASTERDIR}/Makefile"
