# ex:ts=8
# Ports collection makefile for:  urlview
# Date created:			  21 April 1998
# Whom:				  Josh Gilliam <josh@quick.net>
#
# $FreeBSD: ports/textproc/urlview/Makefile,v 1.9 2000/03/22 00:27:56 obrien Exp $
#

PORTNAME=	urlview
PORTVERSION= 	0.7
CATEGORIES=	textproc www
MASTER_SITES=	ftp://ftp.cs.hmc.edu/pub/me/ \
		ftp://ftp.cs.tu-berlin.de/pub/net/mail/mutt/ \
		ftp://ftp.ilog.fr/pub/Mirrors/mutt/contrib/ \
		ftp://ftp.etri.re.kr/pub/mail/mutt/ \
		ftp://ftp.pnm.net/pub/unix/mutt/contrib/

PATCH_SITES=	http://feeding.frenzy.com/~rainking/
PATCHFILES=	urlview.diff

MAINTAINER=	obrien@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		urlview.1

.include <bsd.port.mk>
