# New ports collection makefile for:    tintin++
# Date created:         15 Nov 1994
# Whom:                 ache
#
# $FreeBSD: ports/net/tintin++/Makefile,v 1.15 2000/09/26 10:26:26 foxfair Exp $
#

PORTNAME=	tintin
PORTVERSION=	1.5.9
CATEGORIES=     net games
MASTER_SITES=   ftp://ftp.walrus.com/pub/avatar/clients/ \
		ftp://ftp.cctpu.edu.ru/pub/comp/networking/mud/ \
		ftp://iclub.nsu.ru/pub/mud/clients/tintin++/
DISTNAME=	tintin++v1.5pl9

MAINTAINER=	jhp@cocoja.holywar.net

WRKSRC=         ${WRKDIR}/tintin++/v1.5/src
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
