# New ports collection makefile for:    tintin++
# Date created:         15 Nov 1994
# Whom:                 ache
#
# $FreeBSD: ports/net/tintin++/Makefile,v 1.19 2001/01/16 17:31:57 sobomax Exp $
#

PORTNAME=	tintin
PORTVERSION=	1.5.9
CATEGORIES+=	net games
MASTER_SITES=	http://mail.newclear.net/tintin/download/ \
		http://freebsd.hanirc.org/~jhp/tintin++/
DISTNAME=	tintin++v1.5pl9

MAINTAINER=	jhp@cocoja.holywar.net

WRKSRC=		${WRKDIR}/tintin++/v1.5/src
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
