# New ports collection makefile for:   xmascot
# Version required:    2.5p2
# Date created:        20 November 1996
# Whom:                Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11/xmascot/Makefile,v 1.4 1999/08/31 02:51:09 peter Exp $
#

DISTNAME=	xmascot2.5p2
PKGNAME=	xmascot-2.5p2
CATEGORIES=	x11
MASTER_SITES=	ftp://cclub.tutcc.tut.ac.jp/pub/xmascot/

MAINTAINER=	nakai@FreeBSD.org

USE_GMAKE=	yes
USE_IMAKE=	yes
MAN1=		xmascot.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
