# New ports collection makefile for:	xmascot
# Date created:		20 November 1996
# Whom:			Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11/xmascot/Makefile,v 1.7 2000/04/13 19:10:47 cpiazza Exp $
#

PORTNAME=	xmascot
PORTVERSION=	2.6a
CATEGORIES=	x11
MASTER_SITES=	ftp://cclub.tutcc.tut.ac.jp/pub/xmascot/ \
		http://cclub-flying.dsl.gr.jp/products/xmascot/
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	nakai@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xmascot.1

.include <bsd.port.mk>
