# New ports collection makefile for:	xmascot
# Version required:	2.6a
# Date created:		20 November 1996
# Whom:			Yukihiro Nakai <Nakai@Mlab.t.u-tokyo.ac.jp>
#
# $FreeBSD: ports/x11/xmascot/Makefile,v 1.5 2000/01/08 11:23:55 nakai Exp $
#

DISTNAME=	xmascot2.6a
PKGNAME=	xmascot-2.6a
CATEGORIES=	x11
MASTER_SITES=	ftp://cclub.tutcc.tut.ac.jp/pub/xmascot/ \
		http://cclub-flying.dsl.gr.jp/products/xmascot/

MAINTAINER=	nakai@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xmascot.1

.include <bsd.port.mk>
