# New ports collection makefile for:    xdtm
# Version required:     		2.5.8
# Date created:         		26th April 1995
# Whom:                 		gpalmer
#
# $FreeBSD: ports/x11/xdtm/Makefile,v 1.8 1999/08/31 02:50:57 peter Exp $
#

DISTNAME=		xdtm-2.5.8
CATEGORIES=		x11
MASTER_SITES=		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications

MAINTAINER=		gpalmer@FreeBSD.org

LIB_DEPENDS=		Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=		yes
WRKSRC=			${WRKDIR}/xdtm
MAN1=			xdtm.1

.include <bsd.port.mk>
