# New ports collection makefile for:   tcpreplay
# Date created:        2 November 2000
# Whom:                cnh@ivmg.net
#
# $FreeBSD: ports/net/tcpreplay/Makefile,v 1.1 2000/11/29 02:29:03 msmith Exp $
#

PORTNAME=	tcpreplay
PORTVERSION=	1.0.1
CATEGORIES=	net
MASTER_SITES=	http://www.anzen.com/research/nidsbench/

MAINTAINER=	ports@FreeBSD.org

BUILD_DEPENDS=	${LOCALBASE}/lib/libnet.a:${PORTSDIR}/net/libnet

USE_AUTOCONF=	yes

MAN8=		tcpreplay.8

.include <bsd.port.mk>
