# New ports collection makefile for:	xfsm
# Version required:			1.97
# Date Created:				24 Nov 1997
# Whom:					Vanilla I. Shu <vanilla@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/xfsm/Makefile,v 1.8 1999/08/31 06:51:03 mharo Exp $
#

DISTNAME=	xfsm-1.99
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/status/xstatus
EXTRACT_SUFX=	.tgz

MAINTAINER=	vanilla@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xfsm.1

.include <bsd.port.mk>
