# New ports collection makefile for: Netscape browser with Korean resources
# Version required:	4.7
# Date created:		14 Jun 1999
# Whom:			cjh@kr.freebsd.org
#
# $FreeBSD: ports/korean/netscape47-navigator/Makefile,v 1.13 1999/08/30 12:09:07 peter Exp $
#

MAINTAINER=	cjh@kr.freebsd.org

FILESDIR=	${BASEDIR}/files

BASEDIR=	${.CURDIR}/../netscape47-communicator
BROWSER=	navigator

.include	"${BASEDIR}/Makefile"
