# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		14 Jun 1999
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape47-navigator/Makefile,v 1.15 2000/04/13 09:17:10 asami Exp $
#

MASTERDIR=	${.CURDIR}/../netscape47-communicator
BROWSER=	navigator

.include	"${MASTERDIR}/Makefile"
