# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		14 Jun 1999
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape47-navigator/Makefile,v 1.16 2000/06/25 13:33:48 cjh Exp $
#

MASTERDIR=	${.CURDIR}/../netscape47-communicator
BROWSER_NAME=	navigator

.include	"${MASTERDIR}/Makefile"
