# New ports collection makefile for:    xfractint
# Version required:     3.10
# Date created:         7 Sept 1995
# Whom:                 cacho@mexicano.gdl.iteso.mx
#
# $FreeBSD: ports/graphics/xfractint/Makefile,v 1.6 1999/08/31 06:45:19 mharo Exp $
#

DISTNAME=       xfrac310
PKGNAME=	xfractint-3.10
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.phoenix.net/pub/USERS/twegner/

MAINTAINER=	ports@FreeBSD.org

USE_ZIP=	yes
USE_XLIB=	yes
NO_WRKSUBDIR=	yes
MAN1=		xfractint.1

.include <bsd.port.mk>
