# New ports collection makefile for:	xfractint
# Date created:		7 Sept 1995
# Whom:			cacho@mexicano.gdl.iteso.mx
#
# $FreeBSD: ports/graphics/xfractint/Makefile,v 1.8 1999/10/13 14:31:20 flathill Exp $
#

PORTNAME=	xfractint
PORTVERSION=	3.10
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.phoenix.net/pub/USERS/twegner/ \
		http://spanky.triumf.ca/pub/fractals/programs/unix/
DISTNAME=	xfrac310

MAINTAINER=	ports@FreeBSD.org

USE_ZIP=	yes
USE_XLIB=	yes
NO_WRKSUBDIR=	yes
MAN1=		xfractint.1

.include <bsd.port.mk>
