# New ports collection makefile for:	xfractint
# Version required:	3.10
# Date created:		7 Sept 1995
# Whom:			cacho@mexicano.gdl.iteso.mx
#
# $FreeBSD: ports/graphics/xfractint/Makefile,v 1.7 1999/10/10 23:42:42 steve Exp $
#

DISTNAME=	xfrac310
PKGNAME=	xfractint-3.10
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.phoenix.net/pub/USERS/twegner/ \
		http://spanky.triumf.ca/pub/fractals/programs/unix/

MAINTAINER=	ports@FreeBSD.org

USE_ZIP=	yes
USE_XLIB=	yes
NO_WRKSUBDIR=	yes
MAN1=		xfractint.1

.include <bsd.port.mk>
