# New ports collection makefile for:	enscript (a4)
# Date created:			24 Jul, 1997
# Whom:				kline
#
# $FreeBSD: ports/print/enscript-a4/Makefile,v 1.2 1999/08/31 01:44:42 peter Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../enscript-letter

.include "${MASTERDIR}/Makefile"
