# New ports collection makefile for:	lmmon
# Version required:			0.61
# Date created:				24 September 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/sysutils/lmmon/Makefile,v 1.6 1999/11/14 03:31:15 cpiazza Exp $
#

DISTNAME=	lmmon-0.61
CATEGORIES=	sysutils
MASTER_SITES=	http://www.fxp.org/~jedgar/

MAINTAINER=	jedgar@fxp.org

GNU_CONFIGURE=	yes
MAN8=		lmmon.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
