# New ports collection makefile for:	lmmon
# Date created:				24 September 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/sysutils/lmmon/Makefile,v 1.10 2000/04/22 10:12:36 mharo Exp $
#

PORTNAME=	lmmon
PORTVERSION=	0.65
CATEGORIES=	sysutils
MASTER_SITES=	http://www.fxp.org/~jedgar/lmmon/

MAINTAINER=	jedgar@FreeBSD.org

GNU_CONFIGURE=	yes
MAN8=		lmmon.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
