# $FreeBSD: ports/comms/Makefile,v 1.39 1999/12/27 01:36:38 steve Exp $
#

    SUBDIR += asmodem
    SUBDIR += bpl+
    SUBDIR += conserver
    SUBDIR += ecu
    SUBDIR += gnokii
    SUBDIR += hylafax
    SUBDIR += kermit
    SUBDIR += lrzsz
    SUBDIR += mgetty+sendfax
    SUBDIR += minicom
    SUBDIR += mlan
    SUBDIR += mserver
    SUBDIR += qpage
    SUBDIR += rzsz
    SUBDIR += seyon
    SUBDIR += snooper
    SUBDIR += sredird
    SUBDIR += tkhylafax
    SUBDIR += viewfax
    SUBDIR += xcept
    SUBDIR += yaps
    SUBDIR += zmtx-zmrx

.include <bsd.port.subdir.mk>
