# $FreeBSD: ports/comms/Makefile,v 1.47 2000/12/03 16:37:23 bsd Exp $
#

    SUBDIR += asmodem
    SUBDIR += bayonne
    SUBDIR += bpl+
    SUBDIR += comserv
    SUBDIR += conserver
    SUBDIR += ecu
    SUBDIR += gkermit
    SUBDIR += gnokii
    SUBDIR += hylafax
    SUBDIR += kermit
    SUBDIR += lrzsz
    SUBDIR += mgetty+sendfax
    SUBDIR += minicom
    SUBDIR += mlan
    SUBDIR += mserver
    SUBDIR += plp
    SUBDIR += qico
    SUBDIR += qpage
    SUBDIR += seyon
    SUBDIR += sms_client
    SUBDIR += snooper
    SUBDIR += sredird
    SUBDIR += tkhylafax
    SUBDIR += viewfax
    SUBDIR += vpb2
    SUBDIR += xcept
    SUBDIR += yaps
    SUBDIR += zmtx-zmrx

.include <bsd.port.subdir.mk>
