# New ports collection makefile for:   kmamerun
# Date created:		24 Nov 1999
# Whom:			Nick Sayer <nsayer@freebsd.org>
#
# $FreeBSD: ports/emulators/kmamerun/Makefile,v 1.8 2001/04/03 08:14:08 will Exp $
#

PORTNAME=	kmamerun
PORTVERSION=	1.0.0
CATEGORIES=	emulators kde
MASTER_SITES=	ftp://ftp.sad.it/pub/kde/local/

MAINTAINER=	ports@freebsd.org

RUN_DEPENDS=	xmame:${PORTSDIR}/emulators/xmame

USE_KDELIBS_VER=1
USE_AUTOCONF=	yes

.include <bsd.port.mk>
