# Ports collection makefile for:	xspringies
# Date created:				12 January 1997
# Whom:					jkh
#
# $FreeBSD: ports/games/xspringies/Makefile,v 1.4 1999/08/31 06:44:51 mharo Exp $
#

PORTNAME=	xspringies
PORTVERSION=	1.1
CATEGORIES=	games
MASTER_SITES=	http://aixpdslib.seas.ucla.edu/pub/xspringies/RISC/3.2/src/
DISTFILES=	xspringies.1.1.tar.Z

MAINTAINER=	jkh@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xspringies.1

.include <bsd.port.mk>
