# New ports collection makefile for:	tua
# Date created:		11 Feb. 1995
# Whom:			torstenb
#
# $FreeBSD: ports/sysutils/tua/Makefile,v 1.12 2000/02/13 19:29:48 torstenb Exp $
#

PORTNAME=	tua
PORTVERSION= 	4.0
CATEGORIES=	sysutils
MASTER_SITES=   ftp://ftp.vmunix.org/pub/misc/tua/

MAINTAINER=	torstenb@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		tua.1

.include <bsd.port.mk>
