# New ports collection makefile for:	tua
# Version required:     4.0
# Date created:		11 Feb. 1995
# Whom:			torstenb
#
# $FreeBSD: ports/sysutils/tua/Makefile,v 1.10 1999/08/31 02:00:12 peter Exp $
#

DISTNAME=       tua-4.0
CATEGORIES=	sysutils
MASTER_SITES=   ftp://itnsg1.cineca.it/pub/local/tua/

MAINTAINER=	torstenb@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		tua.1

.include <bsd.port.mk>
