# New ports collection makefile for:	tua
# Date created:		11 Feb. 1995
# Whom:			torstenb
#
# $FreeBSD: ports/sysutils/tua/Makefile,v 1.14 2000/04/22 10:13:26 mharo Exp $
#

PORTNAME=	tua
PORTVERSION=	4.0
CATEGORIES=	sysutils
MASTER_SITES=   ftp://ftp.vmunix.org/pub/misc/tua/

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes
MAN1=		tua.1

.include <bsd.port.mk>
