# New ports collection makefile for:   stmpclean
# Date created:        4 August 1999
# Whom:                shalunov
#
# $FreeBSD: ports/sysutils/stmpclean/Makefile,v 1.3 2000/04/09 19:08:34 cpiazza Exp $
#

PORTNAME=	stmpclean
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.mccme.ru/users/shalunov/

MAINTAINER=	shalunov@mccme.ru

MAN8=		stmpclean.8
MANCOMPRESSED=	no

.include <bsd.port.mk>
