# New ports collection makefile for:    rmonitor
# Date created:         March 1st, 2001
# Whom:                 Konrad Heuer
#
# $FreeBSD: ports/sysutils/rmonitor/Makefile,v 1.1 2001/03/01 15:31:42 clive Exp $
#

PORTNAME=	rmonitor
PORTVERSION=	1.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://gwdu60.gwdg.de/pub/FreeBSD/misc/ \
		ftp://gwdu61.gwdg.de/pub/FreeBSD/misc/

MAINTAINER=	kheuer@gwdu60.gwdg.de

MAN1=		rmonitor.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
