# New ports collection makefile for:	xtu
# Date created:		17 Apr 1999
# Whom:			runge@rostock.zgdv.de
#
# $FreeBSD: ports/x11-clocks/xtu/Makefile,v 1.4 2000/08/03 09:27:09 asami Exp $
#

PORTNAME=	xtu
PORTVERSION=	1.1
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.rostock.zgdv.de/~runge/xtu/

MAINTAINER=	runge@rostock.zgdv.de

USE_IMAKE=	yes
USE_XPM=	yes

#post-install:
#		strip ${PREFIX}/bin/xtu

.include <bsd.port.mk>
