# New ports collection makefile for:	xtu
# Date created:		17 Apr 1999
# Whom:			runge@rostock.zgdv.de
#
# $FreeBSD: ports/x11-clocks/xtu/Makefile,v 1.3 2000/04/10 00:33:10 cpiazza Exp $
#

PORTNAME=	xtu
PORTVERSION= 	1.0
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.rostock.zgdv.de/~runge/xtu/

MAINTAINER=	runge@rostock.zgdv.de

USE_IMAKE=	yes
USE_XPM=	yes

#post-install:
#		strip ${PREFIX}/bin/xtu

.include <bsd.port.mk>
