# New ports collection makefile for:	xtu
# Date created:		17 Apr 1999
# Whom:			runge@rostock.zgdv.de
#
# $FreeBSD: ports/x11-clocks/xtu/Makefile,v 1.2 1999/08/31 02:58:12 peter Exp $
#

PORTNAME=	xtu
PORTVERSION= 	1.0
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.rostock.zgdv.de/~runge/xtu/

MAINTAINER=	runge@rostock.zgdv.de

LIB_DEPENDS=    Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

#post-install:
#		strip ${PREFIX}/bin/xtu

.include <bsd.port.mk>
