# New ports collection makefile for:   c2ps (a4)
# Date created:        19 March 1997
# Whom:                Matthew Hunt <mph@pobox.com>
#
# $FreeBSD: ports/print/c2ps-a4/Makefile,v 1.2 1999/08/31 01:44:32 peter Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../c2ps-letter

.include "${MASTERDIR}/Makefile"
