# New ports collection makefile for:	jvim3 for Wnn6
# Date created:		98/11/17
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim3-wnn6/Makefile,v 1.9 2000/04/11 14:14:16 knu Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../jvim3
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
