# New ports collection makefile for:  	bbdate
# Date created:		May 3 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/x11-clocks/bbdate/Makefile,v 1.11 2000/06/27 11:04:36 alex Exp $
#

PORTNAME=	bbdate
PORTVERSION=	0.2.1
CATEGORIES=	x11-clocks
MASTER_SITES=	http://bbtools.thelinuxcommunity.org/sources/

MAINTAINER=	patseal@hyperhost.net

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
