# New ports collection makefile for:  	bbdate
# Date created:		May 3 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/x11-clocks/bbdate/Makefile,v 1.8 2000/02/08 21:56:39 cpiazza Exp $
#

PORTNAME=	bbdate
PORTVERSION= 	0.2.1
CATEGORIES=	x11-clocks
MASTER_SITES=	http://bbtools.windsofstorm.net/sources/

MAINTAINER=	cpiazza@FreeBSD.org

GNU_CONFIGURE=	yes
USE_XLIB=	yes

.include <bsd.port.mk>
