# New ports collection makefile for:  	bbdate
# Version required:   	0.2.1
# Date created:		May 3 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/x11-clocks/bbdate/Makefile,v 1.7 1999/08/31 02:57:56 peter Exp $
#

DISTNAME=	bbdate-0.2.1
CATEGORIES=	x11-clocks
MASTER_SITES=	http://bbtools.windsofstorm.net/sources/

MAINTAINER=	cpiazza@FreeBSD.org

GNU_CONFIGURE=	yes
USE_XLIB=	yes

.include <bsd.port.mk>
