# New ports collection makefile for:	p5-Test-Simple
# Date Created:				12 Aug 2001
# Whom:					Shell Hung <shell@shellhung.org>
#
# $FreeBSD: ports/devel/p5-Test-Simple/Makefile,v 1.4 2001/08/25 13:54:09 petef Exp $
#

PORTNAME=	Test-Simple
PORTVERSION=	0.17
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Test
PKGNAMEPREFIX=	p5-

MAINTAINER=	shell@shellhung.org

PERL_CONFIGURE=	yes

MAN3=		Test::More.3 Test::Simple.3 Test::Tutorial.3
MAN3PREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
