# New ports collection makefile for:    xchomp
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xchomp/Makefile,v 1.13 2001/01/27 05:40:09 will Exp $
#

PORTNAME=	xchomp
PORTVERSION=	pl1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/

MAINTAINER=		ports@FreeBSD.org

WRKSRC=			${WRKDIR}/xchomp
USE_IMAKE=		yes

.include <bsd.port.mk>
