# New ports collection makefile for:    xchomp
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $FreeBSD: ports/games/xchomp/Makefile,v 1.12 2001/01/09 19:35:50 sf Exp $
#

PORTNAME=	xchomp
PORTVERSION=	pl1
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/ \
		ftp://ftp.freesoftware.com/pub/X11/R5contrib/

MAINTAINER=		ports@FreeBSD.org

WRKSRC=			${WRKDIR}/xchomp
USE_IMAKE=		yes

.include <bsd.port.mk>
