# New ports collection makefile for:	nqc
# Version required:    2.0.2
# Date created:        11 Aug 1999
# Whom:                kbyanc
#
# $FreeBSD: ports/lang/nqc/Makefile,v 1.3 1999/10/10 23:30:18 steve Exp $
#

DISTNAME=	nqc_src_2_0_2
PKGNAME=	nqc-2.0.2
CATEGORIES=	lang
MASTER_SITES=	http://www.enteract.com/~dbaum/nqc/release/

MAINTAINER=	kbyanc@posi.net

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/bin/nqc ${PREFIX}/bin

.include <bsd.port.mk>
