# New ports collection makefile for:	buffer
# Date created:         23 February 1998
# Whom:                 Joao Carlos Mendes Luis <jonny@jonny.eng.br>
#
# $FreeBSD: ports/misc/buffer/Makefile,v 1.14 2000/06/17 00:14:39 steve Exp $
#

PORTNAME=	buffer
PORTVERSION=	1.17.1
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	steve

MAINTAINER=	jonny@jonny.eng.br

USE_BZIP2=	yes
NO_WRKSUBDIR=	yes
MAN1=		buffer.1

.include <bsd.port.mk>
