# New ports collection makefile for:    afm
# Version required:     ?
# Date created:         23 November 1994
# Whom:                 ljo
#
# $FreeBSD: ports/print/afm/Makefile,v 1.10 1999/08/31 01:44:28 peter Exp $
#

DISTNAME=	afm
PKGNAME=	afm-1.0
CATEGORIES=	print
MASTER_SITES=	ftp://sgi.com/sgi/fax/source/
EXTRACT_SUFX=   -tar.Z

MAINTAINER=	ports@FreeBSD.org

pre-patch:
	@${RM} -rf ${WRKSRC}/RCS

do-build:
	@${TRUE}

.include <bsd.port.mk>
