# New ports collection makefile for:    afm
# Date created:         23 November 1994
# Whom:                 ljo
#
# $FreeBSD: ports/print/afm/Makefile,v 1.12 2000/04/09 17:39:33 cpiazza Exp $
#

PORTNAME=	afm
PORTVERSION=	1.0
CATEGORIES=	print
MASTER_SITES=	ftp://sgi.com/sgi/fax/source/
DISTNAME=	afm
EXTRACT_SUFX=   -tar.Z

MAINTAINER=	ports@FreeBSD.org

pre-patch:
	@${RM} -rf ${WRKSRC}/RCS

do-build:
	@${TRUE}

.include <bsd.port.mk>
