# New ports collection makefile for:	bcc
# Date created:		26 March 1995
# Whom:			joerg
#
# $FreeBSD: ports/devel/bcc/Makefile,v 1.8 1999/08/25 05:47:25 obrien Exp $
#

PORTNAME=	bcc
PORTVERSION=	1995.03.12
CATEGORIES=	devel lang
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org

MAN1=		as86.1 bcc.1 bcc-cc1.1 ld86.1
.if !defined(NOMANCOMPRESS)
MANCOMPRESSED=	yes
.endif

.include <bsd.port.mk>
