# New ports collection makefile for:   jafm
# Version required:		0.5
# Date created:                31 August 1998
# Whom:                        brett@peloton.physics.montana.edu
#
# $FreeBSD: ports/x11-fm/jafm/Makefile,v 1.6 1999/08/31 02:58:19 peter Exp $
#

DISTNAME=	jafm-0.5
CATEGORIES=	x11-fm
MASTER_SITES=	http://www-personal.usyd.edu.au/~rlittlew/jafm/ \
		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	X11/desktop

MAINTAINER=	brett@peloton.runet.edu

USE_QT=		yes
USE_GMAKE=	yes
ALL_TARGET=	jafm

MAN8=	jafm.8

.include <bsd.port.mk>
