# New ports collection makefile for:	llnlxdir
# Date created:				9 November 1997
# Whom: Dima Ruban <dima@FreeBSD.org>
#
# $FreeBSD: ports/ftp/llnlxdir/Makefile,v 1.9 2000/04/12 05:31:13 mharo Exp $
#

PORTNAME=	llnlxdir
PORTVERSION=	2.1.2
CATEGORIES=	ftp
MASTER_SITES=	ftp://ftp.llnl.gov/pub/ia/llnlxdir/
DISTNAME=	latest_xdir
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	dima@FreeBSD.org

MAN1=	xdir.1

WRKSRC=		${WRKDIR}/llnlxdir2_1_2/sources
REQUIRES_MOTIF=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
