# New ports collection makefile for:	llnlxdir
# Version required:			2.0
# Date created:				9 November 1997
#
# Whom: Dima Ruban <dima@FreeBSD.org>
#
# $FreeBSD: ports/ftp/llnlxdir/Makefile,v 1.7 1999/08/25 05:55:14 obrien Exp $
#

DISTNAME=	latest_xdir
PKGNAME=	llnlxdir-2.1
CATEGORIES=	ftp
MASTER_SITES=	ftp://ftp-lc.llnl.gov/pub/ia/llnlxdir/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	dima@FreeBSD.org

MAN1=	xdir.1

WRKSRC=		${WRKDIR}/llnlxdir2_1/sources
REQUIRES_MOTIF=	yes
USE_IMAKE=	yes

.include <bsd.port.mk>
