# New ports collection makefile for:    lha
# Version required:     1.14d
# Date created:         26 Dec 1994
# Whom:                 ache
#
# $FreeBSD: ports/archivers/lha/Makefile,v 1.12 1999/08/25 04:25:10 obrien Exp $
#

DISTNAME=       lha-114d
PKGNAME=        lha-1.14d
CATEGORIES=	archivers
MASTER_SITES=   ftp://ftp.cs.titech.ac.jp/pub/tool/lha/ \
		ftp://ftp.hipecs.hokudai.ac.jp/pub/unix/lha/ \
		ftp://ftp.win.or.jp/pub/misc/

MAINTAINER=     ache@FreeBSD.org

MAN1=		lha.1
MANLANG=	ja

.include <bsd.port.mk>
