# New ports collection makefile for:    lha
# Date created:         26 Dec 1994
# Whom:                 ache
#
# $FreeBSD: ports/archivers/lha/Makefile,v 1.16 2000/07/31 10:20:08 kevlo Exp $
#

PORTNAME=	lha
PORTVERSION=    1.14h
CATEGORIES=	archivers
MASTER_SITES=	http://www2m.biglobe.ne.jp/~dolphin/lha/prog/ \
		ftp://ftp.win.ne.jp/pub/misc/
DISTNAME=      	${PORTNAME}-${PORTVERSION:S/.//}

MAINTAINER=	ache@FreeBSD.org

MAN1=		lha.1
MANLANG=	ja

.include <bsd.port.mk>
