# New ports collection makefile for:	libspigot.a
# Version required:	1.7
# Date Created:		Fri Sep 15 10:04:46 CDT 1995
# Whom:			james@cs.uwm.edu
#
# $FreeBSD: ports/graphics/spigot/Makefile,v 1.7 1999/08/25 06:14:58 obrien Exp $
#

DISTNAME= 	spigot-1.7
CATEGORIES=	graphics
MASTER_SITES=	http://www.freebsd.org/~fenner/distfiles/
DISTFILES=	spigot.1.7.tar.gz

MAINTAINER=	james@cs.uwm.edu

# binary package
NO_BUILD=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
