# New ports collection makefile for:	p5-HTML-Stream
# Date created:				October 20th 1996
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/www/p5-HTML-Stream/Makefile,v 1.18 2001/03/01 06:37:51 vanilla Exp $
#

PORTNAME=	HTML-Stream
PORTVERSION=	1.49
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	HTML
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		HTML::Stream.3

.include <bsd.port.mk>
