# New ports collection makefile for:   isic
# Date created:                25 February 2000
# Whom:                        Brad Hendrickse <bradh@uunet.co.za>
#
# $FreeBSD: ports/net/isic/Makefile,v 1.2 2000/04/09 18:11:49 cpiazza Exp $
#

PORTNAME=	isic
PORTVERSION=	0.05
CATEGORIES=	net
MASTER_SITES=	http://www.packetfactory.net/Projects/ISIC/
EXTRACT_SUFX=	.tgz

MAINTAINER=	bradh@uunet.co.za

BUILD_DEPENDS=	${LOCALBASE}/lib/libnet.a:${PORTSDIR}/net/libnet

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
