# New ports collection makefile for:    dviselect
# Date created:         12 October 1994
# Whom:                 jmz
#
# $FreeBSD: ports/print/dviselect/Makefile,v 1.16 2000/04/09 17:49:34 cpiazza Exp $
#

PORTNAME=	dviselect
PORTVERSION=	1.3
CATEGORIES=	print
MASTER_SITES=	ftp://ftp.kobe-u.ac.jp/pub/TeX/dvi-tools/
DISTNAME=	${PORTNAME}

MAINTAINER=	jmz@FreeBSD.org

SCRIPTS_ENV=	CFLAGS="${CFLAGS}"

USE_GMAKE=	yes

MAN1=		dviselect.1


.include <bsd.port.mk>
