# New ports collection makefile for:    dviselect
# Date created:         12 October 1994
# Whom:                 jmz
#
# $FreeBSD: ports/print/dviselect/Makefile,v 1.18 2000/07/02 22:45:46 jmz Exp $
#

PORTNAME=	dviselect
PORTVERSION=	1.3
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	jmz

DISTNAME=	${PORTNAME}

MAINTAINER=	jmz@FreeBSD.org

SCRIPTS_ENV=	CFLAGS="${CFLAGS}"

MAN1=		dviselect.1


.include <bsd.port.mk>
