# New ports collection makefile for:	xzx
# Date created:         13 Nov 1997
# Whom:                 Sheldon Hearn <axl@iafrica.com>
#
# $FreeBSD: ports/emulators/xzx/Makefile,v 1.16 1999/08/30 12:06:47 sheldonh Exp $
#

PORTNAME=	xzx
PORTVERSION=	2.9.1
CATEGORIES=	emulators
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR= system/emulators/zx

MAINTAINER=	sheldonh@FreeBSD.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

MAN1=		xzx.1

.include <bsd.port.mk>
