# New ports collection makefile for:	xzx
# Version required:     2.9.0
# Date created:         13 Nov 1997
# Whom:                 Sheldon Hearn <axl@iafrica.com>
#
# $FreeBSD: ports/emulators/xzx/Makefile,v 1.14 1999/08/25 05:49:55 obrien Exp $
#

DISTNAME=	xzx-2.9.0
CATEGORIES=	emulators
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR= system/emulators/zx

MAINTAINER=	sheldonh@FreeBSD.org

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

BROKEN=		"bison build error"

MAN1=		xzx.1

.include <bsd.port.mk>
