# New ports collection makefile for:	gwm
# Date created:		14 November 1996
# Whom:			markm
#
# $FreeBSD: ports/x11-wm/gwm/Makefile,v 1.14 2001/02/05 21:05:38 olgeni Exp $
#

PORTNAME=	gwm
PORTVERSION=	1.8d
CATEGORIES=	x11-wm
MASTER_SITES=	http://koala.ilog.fr/ftp/pub/gwm/
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		gwm.1

.include <bsd.port.mk>
