# New ports collection makefile for:	gwm
# Date created:		14 November 1996
# Whom:			markm
#
# $FreeBSD: ports/x11-wm/gwm/Makefile,v 1.13 2000/11/27 21:54:12 markm Exp $
#

PORTNAME=	gwm
PORTVERSION=	1.8d
CATEGORIES=	x11-wm
MASTER_SITES=	${MASTER_SITE_XCONTRIB} \
		ftp://koala.inria.fr/pub/gwm/
MASTER_SITE_SUBDIR=	window_managers/gwm
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
USE_XPM=	yes
MAN1=		gwm.1

.include <bsd.port.mk>
