# New ports collection makefile for:	gwm
# Version required:	1.8c
# Date created:		14 November 1996
# Whom:			markm
#
# $FreeBSD: ports/x11-wm/gwm/Makefile,v 1.9 1999/08/31 03:00:08 peter Exp $
#

DISTNAME=	gwm-1.8c
CATEGORIES=	x11-wm
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	window_managers/gwm

MAINTAINER=	markm@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes
MAN1=		gwm.1

.include <bsd.port.mk>
