# ex:ts=8
# New ports collection makefile for:	rpc
# Date created:			Mar 21, 2001
# Whom:				Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/math/rpc/Makefile,v 1.2 2001/06/08 17:18:36 ijliao Exp $
#

PORTNAME=	rpc
PORTVERSION=	0.95
CATEGORIES=	math
MASTER_SITES=	http://www.eecs.umich.edu/~pelzlpj/rpc/

MAINTAINER=	ijliao@FreeBSD.org

BUILD_DEPENDS=	${LOCALBASE}/lib/libccm.so:${PORTSDIR}/math/ccmath
RUN_DEPENDS=	${LOCALBASE}/lib/libccm.so:${PORTSDIR}/math/ccmath

.include <bsd.port.mk>
