# New ports collection makefile for:	mule 2.3@19.34 with Wnn4
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/mule-wnn4/Makefile,v 1.9 2000/04/14 16:47:37 knu Exp $
#

CATEGORIES=	chinese
PKGNAMESUFFIX=	-wnn4

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

CWNN4=		yes

.include "${MASTERDIR}/Makefile"
