# New ports collection makefile for:	mule 2.3@19.34 with Wnn4
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/mule-wnn4/Makefile,v 1.7 1999/08/25 04:57:54 obrien Exp $
#

PKGNAMESUFFIX=	-wnn4
CATEGORIES=	chinese editors
CWNN4=		yes

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
