# New ports collection makefile for:	mule with FreeWnn
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/chinese/mule-freewnn/Makefile,v 1.10 2000/04/20 10:23:06 mharo Exp $
#

CATEGORIES=	chinese
PKGNAMESUFFIX=	-freewnn

MASTERDIR=	${.CURDIR}/../../editors/mule
PKGDIR=		${.CURDIR}/pkg

CFREEWNN=	yes

.include "${MASTERDIR}/Makefile"
