# New ports collection makefile for:   pspp
# Date created:                        22 Apr 2000
# Whom:                                Andrew L. Neporada <andrew@chg.ru>
#
# $FreeBSD: ports/math/pspp/Makefile,v 1.1 2000/05/13 14:15:13 hoek Exp $
#

PORTNAME=	pspp
PORTVERSION=	0.2.4
CATEGORIES=	math
MASTER_SITES=	ftp://alpha.gnu.org/gnu/pspp/ \
		ftp://pspp.stat.wisc.edu/pub/PSPP/

MAINTAINER=	ports@freebsd.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
