# New ports collection makefile for:	cxref
# Version required:	1.4b
# Date created:		23 October 1996
# Whom:			Thomas Gellekum <tg@freebsd.org>
#
# $FreeBSD: ports/devel/cxref/Makefile,v 1.8 1999/08/25 05:47:48 obrien Exp $
#

DISTNAME=	cxref-1.4b
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.demon.co.uk/pub/unix/tools/
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org

USE_GMAKE=	yes
ALL_TARGET=	cxref-inst cxref-query
MAN1=		cxref.1 cxref-query.1

.include <bsd.port.mk>
