# New ports collection makefile for:	jvim for Canna and Wnn4
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna+wnn4/Makefile,v 1.4 1999/08/25 05:24:35 obrien Exp $
#

PKGNAMESUFFIX=	-canna+wnn4
CANNA=		yes
WNN4=		yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
