# New ports collection makefile for:	jvim for Canna and FreeWnn
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna+freewnn/Makefile,v 1.6 2000/09/08 04:34:33 taoka Exp $
#

PKGNAMESUFFIX=	-canna+freewnn
CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}

.include "${MASTERDIR}/Makefile"
