# New ports collection makefile for:	jvim for Canna and FreeWnn
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/jvim-canna+freewnn/Makefile,v 1.5 2000/04/11 14:14:05 knu Exp $
#

PKGNAMESUFFIX=	-canna+freewnn
CANNA=		yes
FREEWNN=	yes

MASTERDIR=	${.CURDIR}/../jvim
PKGDIR=		${.CURDIR}/pkg

.include "${MASTERDIR}/Makefile"
