# $FreeBSD: ports/x11-clocks/Makefile,v 1.21 2001/02/26 19:24:49 will Exp $
#

    SUBDIR += abclock
    SUBDIR += asclock
    SUBDIR += asclock-gtk
    SUBDIR += asclock-xlib
    SUBDIR += astime
    SUBDIR += bbdate
    SUBDIR += bclock
    SUBDIR += dclock
    SUBDIR += emiclock
    SUBDIR += eyeclock
    SUBDIR += glclock
    SUBDIR += kdetoys2
    SUBDIR += mlclock
    SUBDIR += mouseclock
    SUBDIR += pclock
    SUBDIR += rclock
    SUBDIR += sanduhr
    SUBDIR += swisswatch
    SUBDIR += t3d
    SUBDIR += tclock
    SUBDIR += wmcalclock
    SUBDIR += wmdate
    SUBDIR += wmfishtime
    SUBDIR += wmitime
    SUBDIR += wmtime
    SUBDIR += wmtz
    SUBDIR += xalarm
    SUBDIR += xdaliclock
    SUBDIR += xtimer
    SUBDIR += xtu

.include <bsd.port.subdir.mk>
