# New ports collection makefile for:	libraries of FreeWnn
# Date created:		00/08/25
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/FreeWnn-lib/Makefile,v 1.10 2000/09/12 17:08:23 taoka Exp $
#

PKGNAMESUFFIX=	-lib
CATEGORIES=	korean
MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}
WNN=		kWnn

.include "${MASTERDIR}/Makefile"
