# New ports collection makefile for:	Wnn for Korea
# Date created:		20 July 1997
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/korean/Wnn/Makefile,v 1.8 1999/08/30 12:08:35 peter Exp $
#

CATEGORIES=	korean

## COMMENT, DESCR, PLIST is used in a local 'pkg' directory
MASTERDIR=	${.CURDIR}/../../japanese/Wnn
COMMENT=	${.CURDIR}/pkg/COMMENT
DESCR=		${.CURDIR}/pkg/DESCR
PLIST=		${.CURDIR}/pkg/PLIST

.include "${MASTERDIR}/Makefile"
