# New ports collection makefile for:   EyeClock
# Version required:    2.0
# Date created:        4 September 1998
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/x11-clocks/eyeclock/Makefile,v 1.6 1999/08/31 02:57:58 peter Exp $
#

DISTNAME=	eyeclock-2.0
CATEGORIES=	x11-clocks
MASTER_SITES=	http://www.seki.ee.kagu.sut.ac.jp/~sakai/

MAINTAINER=	kiri@pis.toba-cmt.ac.jp

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

#ALL_TARGET=	all

USE_X_PREFIX=	yes

MAN1=		eyeclock.1
MANCOMPRESSED=	yes

.include <bsd.port.mk>
