# New ports collection makefile for: bbpager
# Date created:        17 June 2000
# Whom:                Patrick Seal <patseal@hyperhost.net>
#
# $FreeBSD: ports/x11-wm/bbpager/Makefile,v 1.1 2000/08/12 12:04:40 alex Exp $
#

PORTNAME=	bbpager
PORTVERSION=	0.3.0
CATEGORIES=	x11-wm
MASTER_SITES=	http://bbtools.windsofstorm.net/sources/

MAINTAINER=	patseal@hyperhost.net

RUN_DEPENDS=	blackbox:${PORTSDIR}/x11-wm/blackbox

USE_X_PREFIX=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
