# New ports collection makefile for:	i960-rtems-gcc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD: ports/devel/i960-rtems-gcc/Makefile,v 1.1 2000/07/10 04:32:18 steve Exp $
#

PORTNAME=	gcc

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	i960-rtems
.include "${.CURDIR}/../i386-rtems-gcc/Makefile"
