# New ports collection makefile for:	whichman
# Date created:				6 June 2000
# Whom:	      				Yen-Ming Lee <leeym@cae.ce.ntu.edu.tw>
#
# $FreeBSD: ports/misc/whichman/Makefile,v 1.2 2000/06/23 13:22:00 sobomax Exp $
#

PORTNAME=	whichman
PORTVERSION=	2.0
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_SUNSITE} \
		http://www.linuxfocus.org/~guido.socher/
MASTER_SITE_SUBDIR=	apps/doctools

MAINTAINER=	ports@FreeBSD.org

MAN1=		whichman.1 ftff.1 ftwhich.1

.include <bsd.port.mk>
