# New ports collection makefile for: cstream
# Date created:         19990304
# Whom:                 cracauer@cons.org "Martin Cracauer"
#
# $FreeBSD: ports/misc/cstream/Makefile,v 1.10 2000/06/29 07:02:34 obrien Exp $
#

PORTNAME=	cstream
PORTVERSION=	2.0
CATEGORIES=	misc
MASTER_SITES=	http://www.cons.org/cracauer/download/ \
		http://www2.cons.org/cracauer/download/ \
		http://www3.cons.org/cracauer/download/ \
		http://www.hanse.de/~cracauer/homepage-mirror/download/ \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	cracauer/homepage-mirror/download/

MAINTAINER=	cracauer@cons.org

MAN1=		cstream.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
