# New ports collection makefile for: cstream
# Version required:     1.0
# Date created:         19990304
# Whom:                 cracauer@cons.org "Martin Cracauer"
#
# $FreeBSD: ports/misc/cstream/Makefile,v 1.7 2000/02/08 09:28:15 peter Exp $
#

DISTNAME=	cstream-2.0
CATEGORIES=     misc
MASTER_SITES=   http://www.cons.org/cracauer/download/ \
		http://www2.cons.org/cracauer/download/ \
		http://www3.cons.org/cracauer/download/ \
		http://www.hanse.de/~cracauer/homepage-mirror/download/ \
		http://people.FreeBSD.org/~cracauer/homepage-mirror/download/

MAINTAINER=	cracauer@cons.org

MAN1=		cstream.1

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
