# New ports collection makefile for:	ruby-usersguide-jp
# Date created:			30 Aug 2000
# Whom:				Akinori MUSHA aka knu <knu@idaemons.org>
#
# $FreeBSD: ports/japanese/ruby-usersguide/Makefile,v 1.3 2000/10/08 10:21:20 asami Exp $
#

MASTERDIR=	${.CURDIR}/../../lang/ruby-usersguide

MASTER_SITES=	${MASTER_SITE_RUBY}
MASTER_SITE_SUBDIR=	doc
DISTNAME=	${SHORTNAME}-${VERSION}

CATEGORIES=	japanese

MAINTAINER=	knu@FreeBSD.org

VERSION=	980206

MD5_FILE=	${.CURDIR}/distinfo
PKGDIR=		${.CURDIR}

LANGSUFFIX=	-jp

.include "${MASTERDIR}/Makefile"
