# New ports collection makefile for:	xcb
# Date created:		1 August 1995
# Whom:			jkh
#
# $FreeBSD: ports/x11/xcb/Makefile,v 1.7 2000/04/13 19:10:22 cpiazza Exp $
#

PORTNAME=	xcb
PORTVERSION=	2.3
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xcb.1

.include <bsd.port.mk>
