# New ports collection makefile for:	xcb
# Date created:		1 August 1995
# Whom:			jkh
#
# $FreeBSD: ports/x11/xcb/Makefile,v 1.8 2001/02/05 16:18:27 olgeni Exp $
#

PORTNAME=	xcb
PORTVERSION=	2.3i
CATEGORIES=	x11
MASTER_SITES=	http://www.goof.com/pcg/marc/data/

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
MAN1=		xcb.1

.include <bsd.port.mk>
