# New ports collection makefile for:    tclock
# Date created:		So   7 Feb 1999 20:50:43 MET
# Whom:			Lars Koeller <lkoeller@cc.fh-lippe.de>
#
# $FreeBSD: ports/x11-clocks/tclock/Makefile,v 1.4 2000/04/10 00:32:52 cpiazza Exp $
#

PORTNAME=	tclock
PORTVERSION=	1.0.1
CATEGORIES=	x11-clocks
MASTER_SITES=	ftp://ftp.uni-potsdam.de/pub/X11/tools/clocks/		\
		ftp://ftp.fh-anhalt.de/pub/soft/Xwindow/tools/clocks/	\
		ftp://ftp.uni-bielefeld.de/pub/systems/FreeBSD/lkoeller/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	Lars.Koeller@Uni-Bielefeld.DE

NO_WRKSUBDIR=	yes
USE_IMAKE=	yes
MAN1=		tclock.1

.include <bsd.port.mk>
