# New ports collection makefile for:	ONEW for Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-wnn6/Makefile,v 1.7 2000/09/08 04:34:24 taoka Exp $
#

WNN6=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=		${.CURDIR}

.include	"${MASTERDIR}/Makefile"
