# New ports collection makefile for:	math/p5-Statistics-Distributions
# Date created:				01 January 2001
# Whom:					Anton Berezin <tobez@tobez.org>
#
# $FreeBSD: ports/math/p5-Statistics-Distributions/Makefile,v 1.3 2001/03/07 15:12:01 kevlo Exp $
#

PORTNAME=	Statistics-Distributions
PORTVERSION=	0.06
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

PERL_CONFIGURE=	yes

MAN3=		Statistics::Distributions.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
