# New ports collection makefile for:	streamripper
# Date created:		6 Apr 2000
# Whom:			trevor@jpj.net
#
# $FreeBSD: ports/audio/streamripper/Makefile,v 1.1 2000/06/04 22:42:14 will Exp $
#

PORTNAME=	streamripper
PORTVERSION=	0.7.0b
CATEGORIES=	audio
MASTER_SITES=	ftp://ftp.bigfreakinserver.com/pub/

MAINTAINER=	trevor@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
