# New ports collection makefile for:   aggregate
# Date created:        16 Feb 2001
# Whom:                jabley
#
# $FreeBSD: ports/net/aggregate/Makefile,v 1.3 2001/06/25 03:35:38 dwcjr Exp $
#

PORTNAME=	aggregate
PORTVERSION=	1.3
CATEGORIES=	net
MASTER_SITES=	http://buffoon.automagic.org/dist/ \
		http://maggie.automagic.org/dist/

MAINTAINER=	jabley@automagic.org

GNU_CONFIGURE=	yes

MAN1=	aggregate.1 aggregate-ios.1

.include <bsd.port.mk>
