# New ports collection makefile for:   aggregate
# Date created:        16 Feb 2001
# Whom:                jabley
#
# $FreeBSD: ports/net/aggregate/Makefile,v 1.2 2001/05/27 16:33:59 ijliao Exp $
#

PORTNAME=	aggregate
PORTVERSION=	1.3
CATEGORIES=	net
MASTER_SITES=	http://www.automagic.org/~jabley/

MAINTAINER=	jabley@automagic.org

GNU_CONFIGURE=	yes

MAN1=	aggregate.1 aggregate-ios.1

.include <bsd.port.mk>
