# New ports collection makefile for:	wavplay
# Date created:				14 January 2000
# Whom:					greg
#
# $FreeBSD: ports/audio/wavplay/Makefile,v 1.1.1.1 2000/06/07 16:07:54 sobomax Exp $
#

PORTNAME=	wavplay
PORTVERSION=	1.4
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	apps/sound/players

MAINTAINER=	greg@rosevale.com.au

MAN1=		wavplay.1

.include <bsd.port.mk>
