# New ports collection makefile for:	psgml for emacs20
# Date created:		23 January 1999
# Whom:			shige
#
# $FreeBSD: ports/editors/psgml-emacs20/Makefile,v 1.9 2000/07/10 01:11:45 steve Exp $
#

MAINTAINER=	shige@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../psgml-emacs

# emacs port setup
EMACS_PORT_NAME=	emacs20

# pkg/* files are used in ${.CURDIR}
PKGDIR=		${.CURDIR}/pkg

.include <${MASTERDIR}/Makefile>
