# New ports collection makefile for:	psgml for emacs20
# Date created:		23 January 1999
# Whom:			shige
#
# $FreeBSD: ports/editors/psgml-emacs20/Makefile,v 1.10 2000/07/12 15:57:08 shige Exp $
#

MAINTAINER=	shige@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../psgml-emacs

# emacs port setup
EMACS_PORT_NAME=	emacs20

# pkg-* files in ${.CURDIR} are used
PKGDIR=		${.CURDIR}

.include <${MASTERDIR}/Makefile>
