# New ports collection makefile for: pips for EPSON PM-750C PM-2000C
# Date created:        2000.11.07
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/pips750_2000/Makefile,v 1.1 2000/12/11 02:07:51 taoka Exp $
#

PORTVERSION=	1.3
MASTERDIR=	${.CURDIR}/../pips800
PRTYPE=		750_2000

do-install:     # empty

.include "${MASTERDIR}/Makefile"
