# New ports collection makefile for:	trueprint
# Date created:			17 February 2000
# Whom:				Dmitry Sivachenko <dima@Chg.RU>
#
# $FreeBSD: ports/print/trueprint/Makefile,v 1.3 2000/04/09 17:50:46 cpiazza Exp $
#

PORTNAME=	trueprint
PORTVERSION=	5.2
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	trueprint

MAINTAINER=	demon@FreeBSD.org

USE_GMAKE=	yes

GNU_CONFIGURE=	yes

MAN1=		trueprint.1

.include <bsd.port.mk>
