# $FreeBSD: ports/astro/Makefile,v 1.20 2000/07/02 07:22:53 will Exp $
#

    SUBDIR += dgpsip
    SUBDIR += ephem
    SUBDIR += luna
    SUBDIR += pyweather
    SUBDIR += rmap
    SUBDIR += saoimage
    SUBDIR += sattrack
    SUBDIR += seti_applet
    SUBDIR += setiathome
    SUBDIR += ssystem
    SUBDIR += stars
    SUBDIR += sunclock
    SUBDIR += tkseti
    SUBDIR += wmglobe
    SUBDIR += wmmoonclock
    SUBDIR += wmspaceweather
    SUBDIR += wmsun
    SUBDIR += x3arth
    SUBDIR += xearth
    SUBDIR += xephem
    SUBDIR += xglobe
    SUBDIR += xphoon
    SUBDIR += xplanet
    SUBDIR += xtide

.include <bsd.port.subdir.mk>
