# $FreeBSD: ports/astro/Makefile,v 1.33 2001/06/28 02:55:32 lioux Exp $
#

    SUBDIR += SETIsupport
    SUBDIR += dgpsip
    SUBDIR += ephem
    SUBDIR += gkrellmearth
    SUBDIR += gkrellmoon
    SUBDIR += glunarclock
    SUBDIR += jday
    SUBDIR += ksetiwatch
    SUBDIR += luna
    SUBDIR += openuniverse
    SUBDIR += p5-Astro-MoonPhase
    SUBDIR += p5-Astro-Sunrise
    SUBDIR += p5-Astro-SunTime
    SUBDIR += p5-GPS
    SUBDIR += p5-Geo-METAR
    SUBDIR += pyweather
    SUBDIR += rmap
    SUBDIR += saoimage
    SUBDIR += sattrack
    SUBDIR += seti_applet
    SUBDIR += setiathome
    SUBDIR += sscalc
    SUBDIR += stars
    SUBDIR += sunclock
    SUBDIR += tkseti
    SUBDIR += wmglobe
    SUBDIR += wmmoonclock
    SUBDIR += wmspaceweather
    SUBDIR += wmsun
    SUBDIR += x3arth
    SUBDIR += xearth
    SUBDIR += xephem
    SUBDIR += xglobe
    SUBDIR += xphoon
    SUBDIR += xplanet
    SUBDIR += xtide

.include <bsd.port.subdir.mk>
