# $FreeBSD: ports/astro/Makefile,v 1.24 2000/12/06 05:43:03 will Exp $
#

    SUBDIR += dgpsip
    SUBDIR += ephem
    SUBDIR += glunarclock
    SUBDIR += luna
    SUBDIR += openuniverse
    SUBDIR += p5-GPS
    SUBDIR += pyweather
    SUBDIR += rmap
    SUBDIR += saoimage
    SUBDIR += sattrack
    SUBDIR += seti_applet
    SUBDIR += setiathome
    SUBDIR += sscalc
    SUBDIR += stars
    SUBDIR += sunclock
    SUBDIR += tkseti
    SUBDIR += wmglobe
    SUBDIR += wmmoonclock
    SUBDIR += wmspaceweather
    SUBDIR += wmsun
    SUBDIR += x3arth
    SUBDIR += xearth
    SUBDIR += xephem
    SUBDIR += xglobe
    SUBDIR += xphoon
    SUBDIR += xplanet
    SUBDIR += xtide

.include <bsd.port.subdir.mk>
