# New ports collection makefile for:	wmlmmon
# Date created:				24 September 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/sysutils/wmlmmon/Makefile,v 1.10 2000/07/08 03:25:23 jedgar Exp $
#

PORTNAME=	wmlmmon
PORTVERSION=	0.60
CATEGORIES=	sysutils windowmaker
MASTER_SITES=	http://www.fxp.org/~jedgar/wmlmmon/

MAINTAINER=	jedgar@fxp.org

USE_X_PREFIX=	yes
USE_XPM=	yes

GNU_CONFIGURE=	yes
MAN8=		wmlmmon.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
