# New ports collection makefile for:	wmlmmon
# Date created:				24 September 1999
# Whom:					Chris D. Faulhaber <jedgar@fxp.org>
#
# $FreeBSD: ports/sysutils/wmlmmon/Makefile,v 1.8 2000/04/09 19:08:52 cpiazza Exp $
#

PORTNAME=	wmlmmon
PORTVERSION=	0.60
CATEGORIES=	sysutils windowmaker
MASTER_SITES=	http://www.fxp.org/~jedgar/

MAINTAINER=	jedgar@fxp.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_X_PREFIX=	yes

GNU_CONFIGURE=	yes
MAN8=		wmlmmon.8
MANCOMPRESSED=	yes

.include <bsd.port.mk>
