# New ports collection makefile for:	gtk-gnutella
# Date created:				19 May, 2000
# Whom:					rbt@zort.on.ca
#
# $FreeBSD: ports/net/gtk-gnutella/Makefile,v 1.1 2000/06/02 15:54:04 will Exp $
#

PORTNAME=	gtk-gnutella
PORTVERSION=	0.12
CATEGORIES=	net
MASTER_SITES=	http://gtk-gnutella.sourceforge.net/download/ \
		ftp://gtk-gnutella.sourceforge.net/pub/gtk-gnutella/

MAINTAINER=	rbt@zort.on.ca

USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_GTK=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
