# New ports collection makefile for:	p5-Time-Period
# Date created:			October 30th, 2000
# Whom:	      			Nicholas Esborn <nick@netdot.net>
#
# $FreeBSD: ports/devel/p5-Time-Period/Makefile,v 1.1 2000/10/31 18:39:27 jim Exp $
#

PORTNAME=	Time-Period
PORTVERSION=	1.20
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Time
PKGNAMEPREFIX=	p5-
DISTNAME=	Period-${PORTVERSION}

MAINTAINER=	nick@netdot.net

PERL_CONFIGURE=	YES

MAN3=		Time::Period.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
