# ex:ts=8
# New ports collection makefile for:   gtgt
# Date created:                Feb 13, 2001
# Whom:                        Ying-Chieh Liao <ijliao@FreeBSD.org>
#
# $FreeBSD: ports/devel/gtgt/Makefile,v 1.1 2001/02/13 11:41:08 ijliao Exp $
#

PORTNAME=	gtgt
PORTVERSION=	1.2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE} \
		http://www.karubik.de/gtgt/
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
