# New ports collection makefile for:	colorstep
# Date Created:				21 August 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/colorstep/Makefile,v 1.3 2000/10/05 06:42:36 reg Exp $
#

PORTNAME=	colorstep
PORTVERSION= 	200011041447
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	ColorStep-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}-0.6

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
