# New ports collection makefile for: linux-jpeg
# Date created:         9 April 2000
# Whom:                 sada@FreeBSD.org
#
# $FreeBSD: ports/graphics/linux-jpeg/Makefile,v 1.1.1.1 2000/04/15 17:23:49 sada Exp $
#

PORTNAME=	jpeg
PORTVERSION=	6b.9
CATEGORIES=	graphics linux

RPM_SET=	libjpeg-6b-9.${MACHINE_ARCH}.rpm

.include "../../x11-toolkits/linux-gtk/Makefile"
