# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		14 Jun 1999
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape47-communicator/Makefile,v 1.26 2001/02/06 13:25:11 olgeni Exp $
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator
SUBMASTERDIR=	${.CURDIR}/../netscape${BROWSER_VER}-communicator
FILESDIR=	${SUBMASTERDIR}/files
PATCHDIR=	${SUBMASTERDIR}/files
PKGDIR=		${SUBMASTERDIR}
MD5_FILE=	${SUBMASTERDIR}/distinfo

BROWSER_VER=	47
BROWSER_VERSION?=	4.76
NETHELP=	nethelp-v451
KOREAN_KIT=	netscape-korean-kit-v476.20001031

#PORTREVISION=	1

.include "${MASTERDIR}/Makefile"
