# New ports collection makefile for: Netscape browser with Korean resources
# Date created:		14 Jun 1999
# Whom:			CHOI Junho <cjh@FreeBSD.org>
#
# $FreeBSD: ports/korean/netscape47-communicator/Makefile,v 1.23 2000/10/08 07:20:59 asami Exp $
#

MASTERDIR=	${.CURDIR}/../netscape4-communicator
SUBMASTERDIR=	${.CURDIR}/../netscape${BROWSER_VER}-communicator
FILESDIR=	${SUBMASTERDIR}/files
PATCHDIR=	${SUBMASTERDIR}/files
PKGDIR=		${SUBMASTERDIR}
MD5_FILE=	${SUBMASTERDIR}/distinfo

BROWSER_VER=	47
BROWSER_VERSION=	4.75
NETHELP=        nethelp-v451
KOREAN_KIT=	netscape-korean-kit-v475.20001028

PORTREVISION=	1

.include "${MASTERDIR}/Makefile"
