# New ports collection makefile for:	gtkstep-pastel
# Date Created:				1 June 2000
# Whom:				 	Maxim Sobolev <sobomax@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/gtkstep-pastel/Makefile,v 1.3 2000/09/20 18:18:23 sobomax Exp $
#

PORTNAME=	gtkstep-pastel
PORTVERSION= 	200007290343
CATEGORIES=	x11-toolkits
MASTER_SITES=	${MASTER_SITE_THEMES}
MASTER_SITE_SUBDIR=	gtk
DISTNAME=	${PORTNAME}-1.2.x-${PORTVERSION}

MAINTAINER=	sobomax@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}-0.10.1

USE_X_PREFIX=	yes
USE_GTK=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
