# New ports collection makefile for:   mlan
# Date created:        4 January 2000
# Whom:                phk
#
# $FreeBSD: ports/comms/mlan/Makefile,v 1.2 2000/01/04 22:20:08 phk Exp $
#

PORTNAME=	mlan
PORTVERSION=	1.03
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.dalsemi.com/pub/auto_id/public/
DISTNAME=	mlpb103

MAINTAINER=	phk@FreeBSD.org

USE_ZIP=	yes
WRKSRC=		${WRKDIR}

.include <bsd.port.mk>
