# New ports collection makefile for:    de-ispell
# Date created:                         10 February 2000
# Whom:                                 Alexander Langer <alex@big.endian.de>
#
# $FreeBSD: ports/textproc/de-ispell/Makefile,v 1.2 2000/04/09 21:52:16 cpiazza Exp $
#

MAINTAINER=	alex@big.endian.de

ISPELL_DEALT=	yes
ISPELL_DENEU=	yes
PORTNAME=	ispell
PORTVERSION= 	19991219
PKGNAMEPREFIX=	de-
MASTERDIR=      ${.CURDIR}/../ispell

.include        "${MASTERDIR}/Makefile"
