# New ports collection makefile for:	ewipe
# Date created:		17 October 1997
# Whom:			itojun@itojun.org
#
# $FreeBSD: ports/japanese/ewipe/Makefile,v 1.16 2000/04/11 14:13:37 knu Exp $
#

CATEGORIES=	japanese

RUN_DEPENDS=	wish4.2jp:${PORTSDIR}/japanese/tk42

MASTERDIR=	${.CURDIR}/../../misc/ewipe
PATCHDIR=	${.CURDIR}/patches
COMMENT=	${.CURDIR}/pkg/COMMENT

KANJI=		yes

.include "${MASTERDIR}/Makefile"
