# New ports collection makefile for:	ewipe
# Date created:		17 October 1997
# Whom:			itojun@itojun.org
#
# $FreeBSD: ports/japanese/ewipe/Makefile,v 1.17 2000/04/14 17:10:38 knu Exp $
#

CATEGORIES=	japanese

RUN_DEPENDS=	wish4.2jp:${PORTSDIR}/japanese/tk42

MASTERDIR=	${.CURDIR}/../../misc/ewipe
PATCHDIR=	${.CURDIR}/files
COMMENT=	${.CURDIR}/pkg-comment

KANJI=		yes

.include "${MASTERDIR}/Makefile"
