# New ports collection makefile for:	ewipe
# Date created:		17 October 1997
# Whom:			itojun@itojun.org
#
# $FreeBSD: ports/japanese/ewipe/Makefile,v 1.15 1999/08/25 05:24:02 obrien Exp $
#

MASTERDIR=	${.CURDIR}/../../misc/ewipe
PATCHDIR=	${.CURDIR}/patches
COMMENT=	${.CURDIR}/pkg/COMMENT

KANJI=		yes

.include "${MASTERDIR}/Makefile"

CATEGORIES=	japanese misc tk42

MAINTAINER=	itojun@itojun.org

RUN_DEPENDS=	wish4.2jp:${PORTSDIR}/japanese/tk42
