# New ports collection makefile for:    Half Life Admin Mod
# Date created:				Sun Apr 29 15:58:33 EDT 2001
# Whom:					pat@databits.net et al
#
# $FreeBSD: ports/games/hlserver-admin/Makefile,v 1.1 2001/05/03 01:45:50 lioux Exp $
#

PORTNAME=	admin
PORTVERSION=	2.50e
CATEGORIES=	games
MASTER_SITES=	http://www.adminmod.org/downloads/
DISTNAME=	halflife-${PORTNAME}-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	pat@databits.net

WRKSRC=		${WRKDIR}/Admin

HALFLIFE_COUNTERSTRIKE_MASTER=	${.CURDIR}/../hlserver-cs

.include "${HALFLIFE_COUNTERSTRIKE_MASTER}/Makefile"
