# New ports collection makefile for:	Algorithm::MarkovChain
# Date created:				04 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/devel/p5-Algorithm-MarkovChain/Makefile,v 1.1 2001/01/03 23:15:46 will Exp $
#

PORTNAME=	Algorithm-MarkovChain
PORTVERSION=	0.03
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Algorithm
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Algorithm::MarkovChain.3

.include <bsd.port.mk>
