# New ports collection makefile for:	pslist
# Date created:				27 October 2000
# Whom:					roam@orbitel.bg
#
# $FreeBSD: ports/sysutils/pslist/Makefile,v 1.2 2000/11/22 10:20:13 roam Exp $
#

PORTNAME=	pslist
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://ringwraith.online.bg/~roam/devel/sysutils/

MAINTAINER=	roam@FreeBSD.org

NO_BUILD=	yes

.include <bsd.port.mk>
