# New ports collection makefile for:	pslist
# Date created:				27 October 2000
# Whom:					roam@orbitel.bg
#
# $FreeBSD: ports/sysutils/pslist/Makefile,v 1.3 2000/12/29 15:45:17 roam Exp $
#

PORTNAME=	pslist
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://ringwraith.online.bg/devel/sysutils/

MAINTAINER=	roam@FreeBSD.org

NO_BUILD=	yes

.include <bsd.port.mk>
