# New ports collection makefile for:	pslist
# Date created:				27 October 2000
# Whom:					roam@orbitel.bg
#
# $FreeBSD: ports/sysutils/pslist/Makefile,v 1.1 2000/10/29 01:14:36 will Exp $
#

PORTNAME=	pslist
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://mail.orbitel.bg/~roam/devel/sysutils/ \
		http://ringwraith.online.bg/~roam/devel/sysutils/

MAINTAINER=	roam@FreeBSD.org

NO_BUILD=	yes

.include <bsd.port.mk>
