# New ports collection makefile for:	getline library
# Date created:		3 June 1995
# Whom:			roberto
#
# $FreeBSD: ports/devel/libgetline/Makefile,v 1.8 2000/06/16 21:50:02 asami Exp $
#

PORTNAME=	getline
PORTVERSION=	3.9
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.sco.com/skunkware/src/lib/
DISTNAME=	${PORTNAME}-39-src

MAINTAINER=	gehicks@cisco.com

MAN3=		getline.3

WRKSRC=		${WRKDIR}/getline-39

INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
