# New ports collection makefile for:	getline library
# Version required:	3.9
# Date created:		3 June 1995
# Whom:			roberto
#
# $FreeBSD: ports/devel/libgetline/Makefile,v 1.4 2000/02/21 19:06:47 fenner Exp $
#

DISTNAME=	getline-39-src
PKGNAME=	getline-3.9
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.sco.com/skunkware/src/lib/

MAINTAINER=	jhix@mindspring.com

MAN3=		getline.3

WRKSRC=		${WRKDIR}/getline-39

.include <bsd.port.mk>
