# New ports collection makefile for:	xtar
# Date created:		31 Jul 1996
# Whom:			shanee@augusta.de
#
# $FreeBSD: ports/misc/xtar/Makefile,v 1.6 2000/04/14 08:47:19 asami Exp $
#

PORTNAME=	xtar
PORTVERSION=	1.4
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities

MAINTAINER=	shanee@augusta.de

USE_MOTIF=	yes
USE_IMAKE=	yes
MAN1=		xtar.1

.include <bsd.port.mk>
