# ex:ts=8
# Ports collection makefile for:  mp (a4)
# Version required: 0.0
# Date created:			  11 July 1996
# Whom:				  David O'Brien <obrien@cs.ucdavis.edu>
#
# $FreeBSD: ports/print/mp-a4/Makefile,v 1.4 2000/03/20 02:36:48 obrien Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../mp-letter

.include "${MASTERDIR}/Makefile"
