# ex:ts=8
# Ports collection makefile for:  mp (a4)
# Date created:			  11 July 1996
# Whom:				  David O'Brien <obrien@cs.ucdavis.edu>
#
# $FreeBSD: ports/print/mp-a4/Makefile,v 1.3 2000/02/13 03:23:46 obrien Exp $
#

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../mp-letter

.include "${MASTERDIR}/Makefile"
