# New ports collection makefile for:    icqlib
# Date created:                         16 March 1999
# Whom:                                 Pavel Andreev
#
# $FreeBSD: ports/net/icqlib/Makefile,v 1.7 2000/06/16 10:38:25 sobomax Exp $
#

PORTNAME=	icqlib
PORTVERSION=	0.1.3
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	paxvel@iname.com

INSTALLS_SHLIB=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
