# New ports collection makefile for:    icqlib
# Date created:                         16 March 1999
# Whom:                                 Pavel Andreev
#
# $FreeBSD: ports/net/icqlib/Makefile,v 1.4 1999/12/23 18:11:58 steve Exp $
#

PORTNAME=	icqlib
PORTVERSION=	0.1.3
CATEGORIES=	net
MASTER_SITES=	http://download.sourceforge.net/icqlib/

MAINTAINER=	paxvel@iname.com

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
