# New ports collection makefile for:	Algorithm::Diff
# Date created:				04 Nov 2000
# Whom:					will
#
# $FreeBSD: ports/devel/p5-Algorithm-Diff/Makefile,v 1.2 2001/03/01 06:36:49 vanilla Exp $
#

PORTNAME=	Algorithm-Diff
PORTVERSION=	1.11a
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Algorithm
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org

WRKSRC=		${WRKDIR}/${PORTNAME}-1.11
PERL_CONFIGURE=	yes

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Algorithm::Diff.3 Algorithm::DiffOld.3

.include <bsd.port.mk>
