# New ports collection makefile for: pips for EPSON PM-760C
# Date created:        2000.08.04
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips760/Makefile,v 1.1.1.1 2000/09/01 16:41:18 taoka Exp $
#

MASTER_SITES=	http://www.epkowa.on.arena.ne.jp/pips/data/${PRTYPE}/
MASTERDIR=	${.CURDIR}/../pips800
COMMENT=	${.CURDIR}/pkg-comment
DESCR=		${.CURDIR}/pkg-descr
PRTYPE=		760

.include "${MASTERDIR}/Makefile"
