# New ports collection makefile for:	ONEW for Canna and Wnn6
# Date created:		5 Sep 1997
# Whom:			Satoshi TAOKA <taoka@FreeBSD.org>
#
# $FreeBSD: ports/japanese/onew-canna+wnn6/Makefile,v 1.6 2000/04/12 14:36:30 knu Exp $
#

CANNA=		yes
WNN6=		yes

MASTERDIR=	${.CURDIR}/../onew-freewnn
PKGDIR=         ${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
