# New ports collection makefile for:	gnapster	
# Version required:	1.3
# Date created:		24 December 1999
# Whom:			Chris Piazza <cpiazza@FreeBSD.org>
#
# $FreeBSD: ports/audio/gnapster/Makefile,v 1.1 1999/12/25 02:32:28 cpiazza Exp $
#

DISTNAME=	gnapster-1.3
CATEGORIES=	audio
MASTER_SITES=	http://www.gotlinux.org/~jasta/files/

MAINTAINER=	cpiazza@FreeBSD.org

LIB_DEPENDS=	gnome.3:${PORTSDIR}/x11/gnomelibs

.include <bsd.port.mk>
