# New ports collection makefile for:   w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-ssl/Makefile,v 1.6 2000/04/11 12:48:47 knu Exp $
#

PKGNAMESUFFIX=	-ssl

MASTERDIR=     ${.CURDIR}/../../www/w3m
PKGDIR=        ${.CURDIR}/pkg
PLIST=         ${MASTERDIR}/pkg/PLIST

USE_OPENSSL=	RSA

.include "${MASTERDIR}/Makefile"
