# New ports collection makefile for:   w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-ssl/Makefile,v 1.8 2000/09/22 01:59:06 kris Exp $
#

PKGNAMESUFFIX=	-ssl

MASTERDIR=     ${.CURDIR}/../../www/w3m
PKGDIR=        ${.CURDIR}
PLIST=         ${MASTERDIR}/pkg-plist

USE_OPENSSL=	YES

.include "${MASTERDIR}/Makefile"
