# New ports collection makefile for:   w3m-ssl
# Version required:            991028-2
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-ssl/Makefile,v 1.2 2000/01/18 12:34:26 sumikawa Exp $
#

PKGNAME=       w3m-ssl-${W3M_VER}
CATEGORIES=    www ipv6

MASTERDIR=     ${.CURDIR}/../../www/w3m
PKGDIR=        ${.CURDIR}/pkg
PLIST=         ${MASTERDIR}/pkg/PLIST

USE_OPENSSL=	RSA	

.include "${MASTERDIR}/Makefile"
