# New ports collection makefile for:	xmms-crossfade
# Date created:			21 September 2000
# Whom:				Espen Skoglund <esk@ira.uka.de>
#
# $FreeBSD: ports/audio/xmms-crossfade/Makefile,v 1.4 2001/04/18 04:09:20 lioux Exp $
#

PORTNAME=	xmms-crossfade
PORTVERSION=	0.2.6
CATEGORIES=	audio
MASTER_SITES=	http://www.netcologne.de/~nc-eisenlpe2/xmms-crossfade/ \
		ftp://ftp.falsehope.com/pub/xmms-crossfade/

MAINTAINER=	esk@ira.uka.de

LIB_DEPENDS=	xmms.1:${PORTSDIR}/audio/xmms

USE_X_PREFIX=	yes
USE_LIBTOOL=	yes
USE_GMAKE=	yes
USE_GTK=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
