# New ports collection makefile for:	cim
# Date created:			21 Sept 1996
# Whom:				giffunip
#
# $FreeBSD: ports/lang/cim/Makefile,v 1.14 2000/04/12 06:17:57 obrien Exp $
#

PORTNAME=	cim
PORTVERSION=	3.33
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.ifi.uio.no/pub/cim/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIBS=	yes
MAN1=		cim.1

.include <bsd.port.mk>
