# New ports collection makefile for:	cim
# Date created:			21 Sept 1996
# Whom:				giffunip
#
# $FreeBSD: ports/lang/cim/Makefile,v 1.15 2000/06/16 10:37:10 sobomax Exp $
#

PORTNAME=	cim
PORTVERSION=	3.33
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.ifi.uio.no/pub/cim/

MAINTAINER=	ports@FreeBSD.org

USE_LIBTOOL=	yes
INSTALLS_SHLIB=	yes
MAN1=		cim.1

.include <bsd.port.mk>
