# New ports collection makefile for:	p5-HTML-TableExtract
# Date created:				October 21th 2000
# Whom:					Sergey Osokin aka oZZ <ozz@FreeBSD.org.ru>
#
# $FreeBSD: ports/www/p5-HTML-TableExtract/Makefile,v 1.3 2001/02/05 15:33:43 olgeni Exp $
#

PORTNAME=	HTML-TableExtract
PORTVERSION=	1.06
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	HTML
PKGNAMEPREFIX=	p5-

MAINTAINER=	ozz@FreeBSD.org.ru

PERL_CONFIGURE=	yes

MAN3=		HTML::TableExtract.3
MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}

.include <bsd.port.mk>
