# New ports collection makefile for:	kb2mb2
# Date created:		24 December 1997
# Whom:			Tatsumi Hosokawa
#
# $FreeBSD: ports/x11/kb2mb2/Makefile,v 1.5 2000/04/13 19:09:35 cpiazza Exp $
#

PORTNAME=	kb2mb2
PORTVERSION= 	1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_PORTS_JP}

MAINTAINER=	sada@FreeBSD.org

USE_IMAKE=	yes

.include <bsd.port.mk>
