#!/bin/sh
#
# $FreeBSD: ports/shells/bash/pkg-install,v 1.1 2004/07/30 22:01:13 eik Exp $
#

BASH="${PKG_PREFIX-/usr/local}/bin/bash"
SHELLS="${PKG_DESTDIR-}/etc/shells"

case $2 in
POST-INSTALL)
  if [ -d "${SHELLS%/*}" ] && ! grep -qs "^$BASH\$" "$SHELLS"; then
    if [ `id -u` -eq 0 ]; then
      echo "$BASH" >> "$SHELLS"
    else
      echo "Not root, please add $BASH to $SHELLS manually"
    fi
  fi
  ;;
esac
