# New ports collection makefile for: pips for EPSON Stylus Color777/EPSON Stylus Color680
# Date created:        2001.01.05
# Whom:                Satoshi Taoka <taoka@FreeBSD.org>
#
# $FreeBSD: ports/print/pips-sc680_777/Makefile,v 1.1 2001/01/09 01:53:42 taoka Exp $
#

MASTER_SITES?=	http://www.epkowa.on.arena.ne.jp/pips/data/777_680/
MASTERDIR=	${.CURDIR}/../pips-sc880
PRTYPE=		-sc680_777

.include "${MASTERDIR}/Makefile"
