# New ports collection makefile for:	xcolors
# Date created:		10 May 1995
# Whom:			asami
#
# $FreeBSD: ports/x11/xcolors/Makefile,v 1.14 2000/02/07 16:57:44 ade Exp $
#

PORTNAME=	xcolors
PORTVERSION= 	1.3
CATEGORIES=	x11
MASTER_SITES=	http://www.lovett.com/~ade/FreeBSD/
DISTNAME=	${PORTNAME}	

MAINTAINER=	ade@FreeBSD.org

WRKSRC=		${WRKDIR}/xcolors
USE_IMAKE=	yes
MAN1=		xcolors.1

.include <bsd.port.mk>
