# New ports collection makefile for:	xcolors
# Date created:		10 May 1995
# Whom:			asami
#
# $FreeBSD: ports/x11/xcolors/Makefile,v 1.15 2000/04/13 19:10:26 cpiazza Exp $
#

PORTNAME=	xcolors
PORTVERSION= 	1.3
CATEGORIES=	x11
MASTER_SITES=	http://people.FreeBSD.org/~ade/distfiles/
DISTNAME=	${PORTNAME}	

MAINTAINER=	ade@FreeBSD.org

WRKSRC=		${WRKDIR}/xcolors
USE_IMAKE=	yes
MAN1=		xcolors.1

.include <bsd.port.mk>
