# New ports collection makefile for:	xcolors
# Version required:	R6 contrib
# Date created:		10 May 1995
# Whom:			asami
#
# $FreeBSD: ports/x11/xcolors/Makefile,v 1.13 1999/10/10 23:21:34 steve Exp $
#

DISTNAME=	xcolors
PKGNAME=	xcolors-1.3
CATEGORIES=	x11
MASTER_SITES=	http://www.lovett.com/~ade/FreeBSD/

MAINTAINER=	ade@FreeBSD.org

WRKSRC=		${WRKDIR}/xcolors
USE_IMAKE=	yes
MAN1=		xcolors.1

.include <bsd.port.mk>
