# Ports collection makefile for:	gom
# Date created:				12 Nov 2000
# Whom:					Jeremy Norris <ishmael27@home.com>
#
# $FreeBSD: ports/graphics/gozer/Makefile,v 1.1 2000/12/19 08:46:57 will Exp $
#

PORTNAME=	gozer
PORTVERSION=	0.2
CATEGORIES=	graphics
MASTER_SITES=	http://www.linuxbrit.co.uk/downloads/

MAINTAINER=	ishmael27@home.com

LIB_DEPENDS=	giblib.1:${PORTSDIR}/graphics/giblib

GNU_CONFIGURE=	yes
USE_X_PREFIX=	yes

MAN1=		gozer.1

.include <bsd.port.mk>
