# New ports collection makefile for:	gtar
# Date created:		Sa   6 Jun 1998 10:24:51 CEST
# Whom:			Andreas Klemm <andreas@klemm.gtn.com>
#
# $FreeBSD: ports/sysutils/gtar/Makefile,v 1.8 2000/04/09 19:07:44 cpiazza Exp $
#

PORTNAME=	tar
PORTVERSION= 	1.13
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	tar

MAINTAINER=	andreas@FreeBSD.org

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=--program-prefix=g

.include <bsd.port.mk>
