# New ports collection makefile for:  tintin++ with Chinese(Big5) support.
# Date created:			  Tue 26, 2000
# Whom:				  Foxfair Hu <foxfair@FreeBSD.org>
#
# $FreeBSD: ports/chinese/tintin++/Makefile,v 1.2 2000/10/07 23:30:50 asami Exp $
#

CATEGORIES=	chinese

MASTERDIR=	${.CURDIR}/../../net/tintin++

MAINTAINER=	foxfair@FreeBSD.org

EXTRA_PATCHES=	${.CURDIR}/files/extra-patch.1

.include "${MASTERDIR}/Makefile"
