# New ports collection makefile for:	asmodem
# Date created:		11 May 1998
# Whom:			Sean Cole <scole@aracnet.com>
#
# $FreeBSD: ports/comms/asmodem/Makefile,v 1.6 1999/10/10 23:47:35 steve Exp $
#

PORTNAME=	asmodem
PORTVERSION=	0.6.1
CATEGORIES=	comms
MASTER_SITES=	${MASTER_SITE_AFTERSTEP}
MASTER_SITE_SUBDIR=	apps/asmodem
DISTNAME=	${PORTNAME}-0.6-1

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

MAN1=		asmodem.1

.include <bsd.port.mk>
