# New ports collection makefile for:	asmodem
# Version required:	0.6.1
# Date created:		11 May 1998
# Whom:			Sean Cole <scole@aracnet.com>
#
# $FreeBSD: ports/comms/asmodem/Makefile,v 1.5 1999/08/31 06:40:52 mharo Exp $
#

DISTNAME=	asmodem-0.6-1
PKGNAME=	asmodem-0.6.1
CATEGORIES=	comms
MASTER_SITES=	${MASTER_SITE_AFTERSTEP}
MASTER_SITE_SUBDIR=	apps/asmodem

MAINTAINER=	ports@FreeBSD.org

LIB_DEPENDS=	Xpm.4:${PORTSDIR}/graphics/xpm

USE_IMAKE=	yes

MAN1=		asmodem.1

.include <bsd.port.mk>
