# $FreeBSD: ports/japanese/mecab/Makefile.common,v 1.2 2003/08/18 19:25:59 knu Exp $

MECAB_PORTNAME=		mecab
MECAB_PORTVERSION=	0.81

MECAB_PORTDIR=		${PORTSDIR}/japanese/${MECAB_PORTNAME}
MECAB_WRKSRC_CMD=	cd ${MECAB_PORTDIR} && ${MAKE} -V WRKSRC
