# $FreeBSD: ports/japanese/mecab/Makefile.common,v 1.1 2003/04/23 08:16:47 knu Exp $

MECAB_PORTNAME=		mecab
MECAB_PORTVERSION=	0.76

MECAB_PORTDIR=		${PORTSDIR}/japanese/${MECAB_PORTNAME}
MECAB_WRKSRC_CMD=	cd ${MECAB_PORTDIR} && ${MAKE} -V WRKSRC
