# New ports collection makefile for:   Meta port of XEmacs mule with sumo package
# Version required:	21.1
# Date created:        19 August 1999
# Whom:                KIRIYAMA Kazuhiko <kiri@pis.toba-cmt.ac.jp>
#
# $FreeBSD: ports/japanese/xemacs21-sumo-canna/Makefile,v 1.7 2000/01/06 01:51:46 shige Exp $
#

XEMACS_MAJOR_VER=	21
LANGPREFIX=		ja-
NAMEEXT=		-canna

MASTERDIR=	${.CURDIR}/../../editors/xemacs${XEMACS_MAJOR_VER}-mule-sumo

.include	"${MASTERDIR}/Makefile"
