# New ports collection makefile for:	GLPK
# Date created:		16 December 2000
# Whom:			Dmitry Sivachenko <demon@FreeBSD.org>
#
# $FreeBSD: ports/math/glpk/Makefile,v 1.1 2000/12/18 10:17:22 demon Exp $
#

PORTNAME=	glpk
PORTVERSION=	1.1.1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	glpk

MAINTAINER=	demon@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
