# New ports collection makefile for:	GLPK
# Date created:		16 December 2000
# Whom:			Dmitry Sivachenko <demon@FreeBSD.org>
#
# $FreeBSD: ports/math/glpk/Makefile,v 1.2 2001/02/05 15:04:46 olgeni Exp $
#

PORTNAME=	glpk
PORTVERSION=	2.1
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	glpk

MAINTAINER=	demon@FreeBSD.org

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
