# New ports collection makefile for:	pngcrush
# Version required:			1.3.5
# Date created:				07 December 1999
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
#
# $FreeBSD: ports/graphics/pngcrush/Makefile,v 1.5 2000/01/14 14:51:13 jedgar Exp $
#

DISTNAME=	pngcrush-1.3.5
CATEGORIES=	graphics
MASTER_SITES=	http://download.sourceforge.net/pmt/

MAINTAINER=	jedgar@FreeBSD.org

do-configure:
	@${CP} ${FILESDIR}/Makefile ${WRKSRC}

.include <bsd.port.mk>
