# New ports collection makefile for:	pngcrush
# Version required:			1.3.4
# Date created:				07 December 1999
# Whom:					Chris D. Faulhaber <jedgar@FreeBSD.org>
#
# $FreeBSD: ports/graphics/pngcrush/Makefile,v 1.4 2000/01/13 12:55:11 jedgar Exp $
#

DISTNAME=	pngcrush-1.3.4
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.xnot.com/pmt/pub/pngcrush/src/

MAINTAINER=	jedgar@FreeBSD.org

do-configure:
	@${CP} ${FILESDIR}/Makefile ${WRKSRC}

.include <bsd.port.mk>
