# New ports collection makefile for:    es
# Date created:         Sun Aug 13 12:36:14 CDT 1995
# Whom:                 erich@rrnet.com
#
# $FreeBSD: ports/shells/es/Makefile,v 1.9 2000/04/23 22:59:11 kris Exp $
#

PORTNAME=	es
PORTVERSION=	0.9.b1
CATEGORIES=	shells
MASTER_SITES=	ftp://ftp.sys.toronto.edu/pub/es/
DISTNAME=	es-0.9-beta1

MAINTAINER=	ports@FreeBSD.org

GNU_CONFIGURE=	yes

ALL_TARGET=	es
MAN1=		es.1

.include <bsd.port.mk>
