# New ports collection makefile for:    p5-Locale-Codes
# Date created:				June 26th 1997
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/misc/p5-Locale-Codes/Makefile,v 1.12 2001/03/01 06:37:59 vanilla Exp $
#

PORTNAME=	Locale-Codes
PORTVERSION=	1.06
CATEGORIES=	misc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Locale
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Locale::Country.3 Locale::Constants.3 Locale::Currency.3 \
		Locale::Language.3

.include <bsd.port.mk>
