# New ports collection makefile for:	libident
# Date created:		9 October 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/security/libident/Makefile,v 1.12 2000/06/02 03:18:40 will Exp $
#

PORTNAME=	libident
PORTVERSION=	0.22
CATEGORIES=	security
MASTER_SITES=	ftp://ftp.lysator.liu.se/pub/ident/libs/

MAINTAINER=	ports@FreeBSD.org

ALL_TARGET=	freebsd
MAN3=		ident.3

.include <bsd.port.mk>
