# New ports collection makefile for:	libident
# Version required:	0.21
# Date created:		9 October 1995
# Whom:			torstenb@FreeBSD.org
#
# $FreeBSD: ports/security/libident/Makefile,v 1.8 1999/08/31 01:51:14 peter Exp $
#

DISTNAME=	libident-0.22
CATEGORIES=	devel net security
MASTER_SITES=	ftp://ftp.lysator.liu.se/pub/ident/libs/

MAINTAINER=	torstenb@FreeBSD.org

ALL_TARGET=	freebsd
MAN3=		ident.3

.include <bsd.port.mk>
