# New ports collection makefile for:	p5-Business-CreditCard
# Date created:				October 20th 1996
# Whom:	      				James FitzGibbon <jfitz@FreeBSD.org>
#
# $FreeBSD: ports/misc/p5-Business-CreditCard/Makefile,v 1.14 2001/04/17 13:28:57 roam Exp $
#

PORTNAME=	Business-CreditCard
PORTVERSION=	0.23
CATEGORIES=	misc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Business
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Business::CreditCard.3

.include <bsd.port.mk>
