#!/bin/sh
#
# $FreeBSD: ports/x11/kdebase3/pkg-install,v 1.2 2004/08/30 19:55:40 lofi Exp $
#

if [ "$2" != "POST-INSTALL" ]; then
        exit 0
fi

kdmrcscript=%%PREFIX%%/etc/rc.d/genkdmconf.sh

if [ -f $kdmrcscript ]; then
	sh -c "$kdmrcscript"
fi

exit 0
