# Ports collection Makefile for:	Math-MatrixReal
# Date Created:				Aug 14 1997
# Whom:					Sander Vesik <sander@haldjas.folklore.ee>
#
# $FreeBSD: ports/math/p5-MatrixReal/Makefile,v 1.7 2000/04/23 12:24:49 vanilla Exp $

PORTNAME=	MatrixReal
PORTVERSION=	1.3a5
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Math
PKGNAMEPREFIX=	p5-
DISTNAME=	Math-${PORTNAME}-${PORTVERSION}

MAINTAINER=	sander@haldjas.folklore.ee

PERL_CONFIGURE=	YES

MANPREFIX=	${PREFIX}/lib/perl5/${PERL_VERSION}
MAN3=		Math::MatrixReal.3 Math::Kleene.3

.include <bsd.port.mk>
