# New ports collection makefile for:	avrprog
# Date created:				25 Febuary 2001
# Whom:					Brian Dean <bsd@FreeBSD.org>
#
# $FreeBSD: ports/devel/avrprog/Makefile,v 1.1 2001/02/27 01:13:42 bsd Exp $
#

PORTNAME=	avrprog
PORTVERSION=	1.2.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	bsd

MAINTAINER=	bsd@FreeBSD.org

MAN1=		avrprog.1
MANCOMPRESSED=	no

.include <bsd.port.mk>
